objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>CMI</fullName>
        <active>true</active>
        <description>To be used for managing internal Core employees</description>
        <label>CMI</label>
    </recordTypes>
    <recordTypes>
        <fullName>CSS</fullName>
        <active>true</active>
        <label>CSS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_UserLocation__c.object
<CustomObject>
    <fields>
        <fullName>Location_code__c</fullName>
        <externalId>true</externalId>
        <label>Location_code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSS_UserLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isClaims__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for accessing claims based on location from LDAP</description>
        <label>isClaims</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isServiceJobs__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is for accessing jobs based on location from LDAP</description>
        <label>isServiceJobs</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS_UserLocation</label>
    <nameField>
        <label>CSS_UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_UserLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Location__c</fullName>
        <label>User Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CG_CL_MyAccount_Test.cls
@isTest
public class CG_CL_MyAccount_Test {
    Public static  TestMethod void MyAccountMethod1()
    {
        /*Account acc = new Account();
           acc.name='Rtest';
           acc.CSS_DistributorCode__c='562701';
           acc.IAM_Service_Provider_Code__c='562551';
            insert acc;*/
        UserRole empRole = [Select Id From UserRole Where Name = 'DFSE-CUMMINS CENTRAL' Limit 1];
        //UserRole empRole = [Select Id From UserRole Where Name = 'DFSE-CSSNA- Central Region' Limit 1];
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User objUser1 =[SELECT id, DefaultCurrencyIsoCode, CurrencyIsoCode From User Where id =: userInfo.getUserId() limit 1];
        /*new User(Alias = 'cmi-u1', Email='css-cmi1@cummins.com',
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId = empRole.id,isActive=true, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='css-cmi1@cummins.com', User_Location__c='123456',DefaultCurrencyIsoCode='USD',CurrencyIsoCode='USD');
       insert objUser1;*/
       List<CSS_UserLocation__c> JobLocations1 =new List<CSS_UserLocation__c>();
        CSS_UserLocation__c userLocation1 = new CSS_UserLocation__c(isActive__c=true,isServiceJobs__c=true,isPrimary__c=true,UserId__c=objUser1.Id,Location_code__c='LDAP');
        insert userLocation1;
        JobLocations1.add(userLocation1);
        List<CSS_UserLocation__c> ClaimLocations1=new List<CSS_UserLocation__c>();
        CSS_UserLocation__c userLocation2 = new CSS_UserLocation__c(isActive__c=true,isClaims__c = true,isPrimary__c=true,UserId__c=objUser1.Id,Location_code__c='ARF');
        insert userLocation2;
        ClaimLocations1.add(userLocation2);
        list<CurrencyType> Currencies1=new list<CurrencyType>();
        CurrencyType cur=new CurrencyType();
        cur.IsoCode='USD';
            cur.ConversionRate=10.0;
        cur.IsActive=true;
      //update cur;
      Currencies1.add(cur); 
        CG_CL_MyAccount myacc=new CG_CL_MyAccount();
        myacc.JobLocations=JobLocations1;
        myacc.ClaimLocations=ClaimLocations1;
        myacc.selectedValue='USD';
        myacc.selCurrency='USD';
        myacc.Currencies=Currencies1;
        List<SelectOption> opt= myacc.getOptions();
        myacc.OnChangeSelectedCurrency();
        myacc.SaveAndContinue();
        CG_CL_MyAccount.activeLocationsWrapper wrapclass = new CG_CL_MyAccount.activeLocationsWrapper('03520','Boyer truck',true);
        
        
        
    }
 Public static  TestMethod void CatchMethod1()
 {
       CurrencyType cur=null;
     CG_CL_MyAccount myacc=new CG_CL_MyAccount();
   
     myacc.Currencies=null;
     myacc.getOptions();
         }
}