objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DSID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DSID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>Account_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Code</label>
        <referenceTo>FSL_Account_Code__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <description>Action Selected by Technician during repair</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Replace</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CampaignPartsPercentage__c</fullName>
        <label>CampaignPartsPercentage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Description__c</fullName>
        <label>Campaign Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complete_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <description>Captures the Component or Failure ID for the Repair</description>
        <label>Component Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FailCode__c</fullName>
        <label>FailCode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failure_Date__c</fullName>
        <label>Failure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Failure_Point__c</fullName>
        <label>Failure Point</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Multiple_Times__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to map the attributes MultipleTimes</description>
        <label>Multiple Times</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Performed_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required to Perform</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Job for this Component</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A field to differentiate Camp,TRP &amp; ATCs from Solution Component</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_SRT__c.object
<CustomObject>
    <fields>
        <fullName>Access_Code_A__c</fullName>
        <label>Access Code A</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Access_Code_C__c</fullName>
        <label>Access Code C</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adjustment_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Justified Per Failure Code</fullName>
                </value>
                <value>
                    <fullName>Partial Re-Assembly</fullName>
                </value>
                <value>
                    <fullName>Penalty</fullName>
                </value>
                <value>
                    <fullName>Travel SRT’s Incorrectly Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Component ID for this Repair</description>
        <label>CSS Solution Component</label>
        <referenceTo>CSS_Solution_Component__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extended_Hours__c</fullName>
        <label>Extended Hours</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FailCode__c</fullName>
        <label>FailCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPopUpSRT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPopUpSRT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRT_AccessiblityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accessiblity CheckBox Option from the SRT Table</description>
        <label>SRT AccessiblityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRT_Category__c</fullName>
        <label>SRT Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Estimate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SRT Estimate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRT_ID__c</fullName>
        <label>SRT ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Notes__c</fullName>
        <label>SRT Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SRT_Order__c</fullName>
        <label>SRT_Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SRT_Select__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SRT_Select</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRT_Status_Message__c</fullName>
        <label>SRT Status Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SRT_Time__c</fullName>
        <label>SRT Time</label>
        <precision>13</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SRT_Title__c</fullName>
        <label>SRT Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Type__c</fullName>
        <label>SRT Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Warrantable__c</fullName>
        <label>SRT_%Warrantable</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution Number</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step_Id__c</fullName>
        <label>Step Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diagnosis</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Diag Access</fullName>
                </value>
                <value>
                    <fullName>Repair Access</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>99Time</fullName>
                </value>
                <value>
                    <fullName>Overlap</fullName>
                </value>
                <value>
                    <fullName>Field Action</fullName>
                </value>
                <value>
                    <fullName>Field Action Access</fullName>
                </value>
                <value>
                    <fullName>BMS SRT</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isPerformed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPerformed</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS SRT</label>
    <nameField>
        <label>CSS SRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS SRTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CG_CL_RJFieldActionSRTs_RO_Test.cls
@isTest
public class CG_CL_RJFieldActionSRTs_RO_Test {
    public static testMethod void Method1(){
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;

        test.startTest();
        CSS_Job_Order__c JO = new CSS_Job_Order__c();
        JO.Account__c = acc.id;
        JO.Customer_Name__c = 'wenchin';
        JO.Application__c = 'Recreational Vehicle';
        JO.Model__c = 'test';
        JO.Make__c = 'CSSTest';
        JO.Notes__c = 'CAMPCOMMENTS';
        JO.Failure_Point__c = 122;
        JO.Failure_Point_Measure__c = 'Miles';
        JO.VIN__c = '12345677890';
        JO.Failure_Date__c = date.today() - 20;
        JO.Warranty_Start_Date__c = date.today() - 365;
        JO.Location_Certification__c = 'abc';
        JO.jobLocation__c = 'abc';
        JO.Before_In_Service__c = True;
        JO.Status__c = 'Repair Complete';
        JO.Unit_Number__c = 'test123';
        Jo.Assigned_To__c = UserInfo.getUserId();
        Jo.esn__c = '79464646';
        JO.Unit_Type__c = 'type';
        Jo.Country__c = 'United States';
        Jo.CSS_State__c = 'Indiana';
        Jo.City__c = 'Columbus';
        Jo.Customer_Code__c = '23456';
        Jo.EditComplaint__c = 'complaint';
        Jo.EditCoverage__c = 'coverage';
        Jo.EditCause__c = 'cause';
        Jo.EditCorrection__c = 'correction';
        JO.chevron_page__c = 'prt';
        JO.CSS_Resolution__c = 'Test';
        JO.DSID__c = 'VFD23';
        insert JO;
        
        PageReference pref;
        pref = new PageReference('/'+JO.id);
        pref.getParameters().put('id',JO.id);
        Test.setCurrentPage(pref);
        CSS_Solution_Component__c solComp = new CSS_Solution_Component__c();
        solComp.Component_Id__c ='F0051000';
        solComp.Service_Job__c = Jo.id;
        solComp.Action__c = '';
        solComp.Type__c = 'Campaign';
        solComp.Campaign_Description__c = 'Hey Hai Man Camp';
        solComp.CampaignPartsPercentage__c = '20';
        solcomp.Performed_Review__c = True;
        solcomp.Status__c='Approved';
        solcomp.Complete_Indicator__c=true; 
        solcomp.Multiple_Times__c=true;
        insert solComp;
        
        CSS_Solution_Component__c solComptrp = new CSS_Solution_Component__c();
        solComptrp.Component_Id__c ='F0051000';
        solComptrp.Service_Job__c = Jo.id;
        solComptrp.Type__c = 'TRP';
        solComptrp.Campaign_Description__c = 'Hey Hai Man TRP';
        solComptrp.CampaignPartsPercentage__c = '10';
        solcomptrp.Performed_Review__c = True;
        solcomptrp.Status__c='Approved';
        solcomptrp.Complete_Indicator__c=true; 
        solcomptrp.Multiple_Times__c=true;
        insert solComptrp;
        
        CSS_Solution_Component__c solCompatc = new CSS_Solution_Component__c();
        solCompatc.Component_Id__c ='F0051000';
        solCompatc.Service_Job__c = Jo.id;
        solCompatc.Type__c = 'ATC';
        solCompatc.Campaign_Description__c = 'Hey Hai Man ATC';
        solCompatc.CampaignPartsPercentage__c = '10';
        solcompatc.Performed_Review__c = True;
        solcompatc.Status__c='Approved';
        solcompatc.Complete_Indicator__c=true; 
        solcompatc.Multiple_Times__c=true;
        insert solCompatc;
        system.debug('Solution Component:'+solCompatc);
        
        CSS_SRT__C srt = new CSS_SRT__C();
        srt.Access_Code_A__c=4;
        srt.SRT_ID__c = 'test';
        srt.Extended_Hours__c = 12323;
        srt.SRT_Estimate__c = true;
        srt.Adjustment_Reason__c = 'test';
        //srt.SRT_Warrantable__c = '124345';
        srt.Account_Code__c = 'test';
        srt.FailCode__c = 'test';
        srt.SRT_Time__c = 124235;
        srt.Step_Id__c = 'test';
        srt.SRT_AccessiblityCheck__c = true;
        srt.Type__c = 'test';
        srt.SRT_Type__c = 'test';
        srt.SRT_Title__c = 'test';
        srt.SRT_Notes__c = 'this i sthe test class';
        srt.SRT_Status_Message__c = 'This is the test class';
        //srt.SRT_Warrantable__c = 'test';
        srt.SRT_Order__c = 454747676;
        srt.Access_Code_C__c = 123;
        srt.SRT_Category__c = 'Campaign';
        srt.Job_Order__c=Jo.id;
        srt.SRT_Time__c=2.0;
        srt.Type__c='campaign';
        srt.SRT_Select__c=true;
        srt.SRT_Warrantable__c='12';
        srt.Component_Id__c=solComp.id;        
        insert srt;
        string percentageCov1 = '100';
        List<CSS_SRT__c> srtlst = new List<CSS_SRT__c>();
        CSS_SRT__C srt1 = new CSS_SRT__C();
        srt1.Access_Code_A__c=3;
        srt1.SRT_Time__c=2.0;
        srt1.Type__c='campaign';
        srt1.SRT_Select__c=true;
        //srt1.SRT_Warrantable__c=12;
        srt1.Component_Id__c=solCompatc.id;
        insert srt1;
        srtlst.add(srt1);
        CSS_SRT__C srt2 = new CSS_SRT__C();
        srt2.Access_Code_A__c=2;
        srt2.SRT_Time__c=2.0;
        srt2.Type__c='campaign';
        srt2.SRT_Select__c=true;
        srt2.SRT_Warrantable__c='12';
        srt2.Job_Order__c = solCompatc.Service_Job__c;
        srt2.Component_Id__c=solCompatc.id;
        insert srt2;
        
         CSS_SRT__C srt5 = new CSS_SRT__C();
        srt5.Access_Code_A__c=3;
        srt5.Job_Order__c=Jo.id;
        srt5.SRT_Time__c=2.0;
        srt5.srt_category__c='campaign';
        srt5.isPopupSRT__c=true;
        srt5.Solution_Number__c=null;
        srt5.Component_Id__c=null;
        srt5.isPerformed__c=true;
        insert srt5;
        
        
       CSS_srt__C srt6 = new CSS_srt__C();
        srt6.Access_Code_A__c=4;
        srt6.srt_ID__c = 'test';
        srt6.Extended_Hours__c = 12323;
        srt6.srt_Estimate__c = true;
        srt6.Adjustment_Reason__c = 'test';
        srt6.SRT_Warrantable__c = '12';
        srt6.Account_Code__c = 'test';
        srt6.FailCode__c = 'test';
        srt6.srt_Time__c = 124235;
        srt6.Step_Id__c = 'test';
        srt6.srt_AccessiblityCheck__c = true;
        srt6.Type__c = 'test';
        srt6.srt_Type__c = 'test';
        srt6.srt_Title__c = 'test';
        srt6.srt_Notes__c = 'this i sthe test class';
        srt6.srt_Status_Message__c = 'This is the test class';
        srt6.srt_Warrantable__c = 'test';
        srt6.srt_Order__c = 454747676;
        srt6.Access_Code_C__c = 123;
        srt6.srt_Category__c = 'TRP';
        srt6.Job_Order__c=Jo.id;
        srt6.srt_Time__c=2.0;
        srt6.Type__c='TRP';
        srt6.srt_Select__c=true;
        srt6.SRT_Warrantable__c='12';
        srt6.Component_Id__c=solComptrp.id;        
        insert srt6;
        
        CSS_SRT__C srtv = new CSS_SRT__C();
        srtv.Access_Code_A__c=3;
        srtv.Job_Order__c=Jo.id;
        srtv.SRT_Time__c=2.0;
        srtv.srt_category__c='TRP';
        srtv.isPopupSRT__c=true;
        srtv.Solution_Number__c=null;
        srtv.Component_Id__c=null;
        srtv.isPerformed__c=true;
        insert srtv;
        
        CSS_SRT__C srte = new CSS_SRT__C();
        srte.Access_Code_A__c=3;
        srte.Job_Order__c=Jo.id;
        srte.SRT_Time__c=2.0;
        srte.srt_category__c='ATC';
        srte.isPopupSRT__c=true;
        srte.Solution_Number__c=null;
        srte.Component_Id__c=null;
        srte.isPerformed__c=true;
        insert srte;
        
        CSS_SRT__C srt9 = new CSS_SRT__C();
        srt.Job_Order__c=Jo.id;
        srt.Solution_Number__c=null;
        srt.isPopupSRT__c=true;
        srt.SRT_Warrantable__c='12';
        srt.Component_Id__c=solComptrp.id;
        
        insert srt9;
        list<CG_CL_RJFieldActionSRTs_RO.srtWrapper> pwlist=new list<CG_CL_RJFieldActionSRTs_RO.srtWrapper>();
        CG_CL_RJFieldActionSRTs_RO.srtWrapper srtwrap = new  CG_CL_RJFieldActionSRTs_RO.srtWrapper(srt1.id,'SRTCode','SRTDescription',123.1,'ACCESSSRTTime',1.2,'AccessCode','SRTHours','AdjustmentReason',true,true,2,'100','type','extendedHours');
        pwlist.add(srtwrap);
        string fan;
        integer srtcount;
        List<CG_CL_RJFieldActionSRTs_RO.CompWrapper> lstcompwrap = new List<CG_CL_RJFieldActionSRTs_RO.CompWrapper>();
        CG_CL_RJFieldActionSRTs_RO.CompWrapper comwra = new CG_CL_RJFieldActionSRTs_RO.CompWrapper(solComptrp.id,fan,pwlist,2);
        lstcompwrap.add(comwra);
        system.debug('lstcompwrap--->'+lstcompwrap);
        
        List<CG_CL_RJFieldActionSRTs_RO.TRPsrtWrapper> lsttrpsrtwra = new List<CG_CL_RJFieldActionSRTs_RO.TRPsrtWrapper>();
        CG_CL_RJFieldActionSRTs_RO.TRPsrtWrapper trpsrtwra = new CG_CL_RJFieldActionSRTs_RO.TRPsrtWrapper(srt1.id,'SRTCode','SRTDescription',2,'ACCESSSRTTime',2,'AccessCode','SRTHours','AdjustmentReason',true,true,2,'23','campaign','3');    
        lsttrpsrtwra.add(trpsrtwra);
        
        CG_CL_RJFieldActionSRTs_RO.TRPCompWrapper trpWrap = new CG_CL_RJFieldActionSRTs_RO.TRPCompWrapper(solComptrp.id,'test',lsttrpsrtwra,2);
        
        List<CG_CL_RJFieldActionSRTs_RO.ATCsrtWrapper> lstatcsrtwra = new List<CG_CL_RJFieldActionSRTs_RO.ATCsrtWrapper>();
        CG_CL_RJFieldActionSRTs_RO.ATCsrtWrapper atcsrtwra = new CG_CL_RJFieldActionSRTs_RO.ATCsrtWrapper(srt2.id,'SRTCode','SRTDescription',2,'ACCESSSRTTime',2,'AccessCode','SRTHours','AdjustmentReason',true,true,2,'23','campaign','3');    
        lstatcsrtwra.add(atcsrtwra);
        
        
        CG_CL_RJFieldActionSRTs_RO.ATCCompWrapper atcwrap = new CG_CL_RJFieldActionSRTs_RO.ATCCompWrapper(solComptrp.id,'test',lstatcsrtwra,2);
        
        CG_CL_RJFieldActionSRTs_RO.srtWrapper Dh = new CG_CL_RJFieldActionSRTs_RO.srtWrapper(srt.Id,'RTCode','SRTDescription',2.0,'ACCESSSRTTime',2.0,'AccessCode','SRTHours','AdjustmentReason',true,true,2,'23','SRT','extendedHours');
        
        ApexPages.currentPage().getParameters().put('id',JO.id);
        
        
        CG_CL_RJFieldActionSRTs_RO campaign = new CG_CL_RJFieldActionSRTs_RO();
        campaign.addlistcompwrapper = lstcompwrap;
        campaign.additionalSRTList = srtlst;
        campaign.getAllCampSrtsData();
        campaign.getAllTRPSrtsData();
        campaign.getAllATCSrtsData();
        
        test.stopTest();
    }
    public static testMethod void Method2(){
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;

       CSS_Job_Order__c jo = CSS_TestData.createJobOrder(false);
        jo.Account__c = acc.id;
        //insert jo;
        List<CSS_SRT__c> srtlst = new List<CSS_SRT__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        //srt.Job_Order__c=4;
        srt.Job_Order__c=jo.id; 
        srt.Solution_Number__c=null;
        srt.component_id__c=null;
        srt.isPopupSRT__c=true;
        srt.SRT_Warrantable__c='12';
       
        insert srt;
        srtlst.add(srt);
        CG_CL_RJFieldActionSRTs_RO jobplanCamp = new CG_CL_RJFieldActionSRTs_RO();
        jobplanCamp.additionalSRTList = srtlst;
        jobplanCamp.getAllATCSrtsData();
        jobplanCamp.getAllCampSrtsData();
        jobplanCamp.getAllTRPSrtsData();
    }
}