objects/Account.object
<CustomObject>
    <fields>
        <fullName>IAM_ABO_Code_Formula__c</fullName>
        <formula>CASE(IAM_WWSPS_Regions__c,
&quot;US and Canada&quot;,&quot;1&quot;,
&quot;Europe&quot;,&quot;3&quot;,
&quot;Africa&quot;,&quot;4&quot;,
&quot;Middle East&quot;,&quot;5&quot;,
&quot;Latin America&quot;,&quot;6&quot;,
&quot;Mexico&quot;,&quot;8&quot;,
&quot;Southeast Asia&quot;,&quot;10&quot;,
&quot;South Pacific&quot;,&quot;11&quot;,
&quot;East Asia&quot;,&quot;12&quot;,
&quot;India&quot;,&quot;13&quot;,
&quot;CIS&quot;,&quot;15&quot;,
&quot;Japan&quot;,&quot;16&quot;,
&quot;Korea&quot;,&quot;17&quot;,
Null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ABO_Code</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <recordTypes>
        <fullName>IAM</fullName>
        <active>true</active>
        <description>Please use this only for creating non-WWSPS managed locations (Fleet, Individual, Business, etc.). For any Service Provider additions cancel this creation and please visit and use existing WWSPS process.</description>
        <label>IAM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CMI_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Application_Roles__c</fullName>
        <label>Application Roles</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Applications__c</fullName>
        <description>this field is used to store the default access of all the applications that user gets before creating a user.because of different approval levels.</description>
        <label>Application Groups</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IAM_Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reclaim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_DN_Value__c</fullName>
        <description>It stores DN Value of a user received from LDAP as well as for a Contact created in IAM</description>
        <label>DN Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Ext_Legacy_Uid__c</fullName>
        <label>Ext Legacy Uid</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IAM_Internal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for IDM Purpose and is used to know if the user is internal or external</description>
        <label>Internal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Legacy_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legacy User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_NpbuDiagExpire__c</fullName>
        <description>It stores subscription and its expiration date format for subscribed and admin managed NPBU Diagnostics app.</description>
        <label>NPBU Diagnostics Expiration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Person_Type__c</fullName>
        <label>LDAP PersonType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>CWK</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Ex-employee</fullName>
                </value>
                <value>
                    <fullName>Joint Venture</fullName>
                </value>
                <value>
                    <fullName>Non-North America Distributor</fullName>
                </value>
                <value>
                    <fullName>Non-Person</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Product_Group_Access__c</fullName>
        <description>this fields are used for IDM Purpose to update the user records</description>
        <label>Product Group Access</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Promotion__c</fullName>
        <externalId>true</externalId>
        <label>Service Training ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Qsolexpiration__c</fullName>
        <label>QSOL Expiration</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Qsolview__c</fullName>
        <label>Qsolview</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Reason__c</fullName>
        <label>De-Activate Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Reject_Reason__c</fullName>
        <label>De-Activate Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Longer at Location</fullName>
                </value>
                <value>
                    <fullName>Requested Removal</fullName>
                </value>
                <value>
                    <fullName>Cancellation Comments</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Subscription Cancelled</fullName>
                </value>
                <value>
                    <fullName>Subscription Expired</fullName>
                </value>
                <value>
                    <fullName>Subscription Request Rejected</fullName>
                </value>
                <value>
                    <fullName>Subscription Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Work_Group_Id__c</fullName>
        <label>Work Group Id</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IAM_is_Member_of__c</fullName>
        <label>is Member of</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IAM_swregexpire__c</fullName>
        <label>SW Reg Expiration</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>this is for IDM purpose and to store cummins LDAP ID of all the users having the WWID from LDAP</description>
        <externalId>true</externalId>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <recordTypes>
        <fullName>IAM</fullName>
        <active>true</active>
        <description>Please use this for creating external users, for creating Cummins users please follow WWIMS process. After creating user, please assign needed Application-Role&apos;s by clicking on &quot;Assign App/Feature&quot; to complete user setup without which user cannot access.</description>
        <label>IAM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IAM_Contact_Provisioning__c.object
<CustomObject>
    <fields>
        <fullName>IAM_Contact_Status__c</fullName>
        <formula>TEXT(IAM_Contact__r.IAM_Contact_Status__c)</formula>
        <label>Contact Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User_Features_And_ Access (Contact)</relationshipLabel>
        <relationshipName>Contact_Provisionings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IAM_NpbuDiagExpire__c</fullName>
        <description>It stores subscription and its expiration date format for subscribed and admin managed NPBU Diagnostics app.</description>
        <label>NPBU Diagnostics Expiration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Promotion__c</fullName>
        <label>Service Training ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Qsolexpiration__c</fullName>
        <label>QSOL Expiration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Reason__c</fullName>
        <label>User Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Reject_Reason__c</fullName>
        <label>IAM Reject Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription Revoked</fullName>
                </value>
                <value>
                    <fullName>Subscription Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cancellation Comments</fullName>
                </value>
                <value>
                    <fullName>Subscription Expired</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Subscription Request Rejected</fullName>
                </value>
                <value>
                    <fullName>Requested Removal</fullName>
                </value>
                <value>
                    <fullName>No Longer at Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Account Level</fullName>
                </value>
                <value>
                    <fullName>Pending Account Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Contact Approval</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_swregExpire__c</fullName>
        <label>SW Reg Expiration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>User Feature &amp; Access</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Rec Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Features_And_ Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>IAM_Application_Roles__c</fullName>
        <label>Application_Roles</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IAM_NpbuDiagExpire__c</fullName>
        <description>It stores subscription and its expiration date format for subscribed and admin managed NPBU Diagnostics app.</description>
        <label>NPBU Diagnostics Expiration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Promotion__c</fullName>
        <label>IAM_Promotion</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Qsolexpiration__c</fullName>
        <label>IAM_Qsolexpiration</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Qsolview__c</fullName>
        <label>IAM_Qsolview</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_is_Member_of__c</fullName>
        <label>is Member of</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IAM_swregexpire__c</fullName>
        <label>IAM_swregexpire</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/IAM_Reclaim_Contact_Update_Queueable.cls
/************************************************************
Name:  IAM_Reclaim_Contact_Update_Queueable
Copyright © 2020  Cummins
=============================================================
=============================================================
Purpose:                                                            
This is Class for Reclaim Process Contact Update.                          
=============================================================
=============================================================
History                                                            
-------                                                            
VERSION  AUTHOR                   DATE              DETAIL                                
1.0 -    Karthik Golakram       09/02/2020        INITIAL DEVELOPMENT 
1.1 -    Karthik Golakaram      10/19/2020        Made change to guidanz contact
                                                  account location is not IAM Default. 
1.2      Shubhangi Sardar       12/03/2020        Added NPBU Diagnostic Expration            
*****************************************************/
public class IAM_Reclaim_Contact_Update_Queueable Implements Queueable{
    
    Private Contact cn;
    Private String newUsername;
    Private String newEmail;
    Private Boolean isGuidanzUSer;
    Private Map<String,Boolean> reclaimTracker;
    Private Boolean isDuplicateUser;
    Private id guidanzContactId;
    Private user userCreated;

    public IAM_Reclaim_Contact_Update_Queueable(user userCreated,id guidanzContactId,Contact cn,String newUsername,String newEmail,Boolean isGuidanzUSer,Map<String,Boolean> reclaimTracker,Boolean isDuplicateUser) {
        this.userCreated=userCreated;
        this.guidanzContactId=guidanzContactId;
        this.cn=cn;
        this.newUsername=newUsername;
        this.newEmail=newEmail;
        this.isGuidanzUSer=isGuidanzUSer;
        this.reclaimTracker=reclaimTracker;
        this.isDuplicateUser=isDuplicateUser;
    }

    Public Void execute(QueueableContext Context){
        try{
            List<User> usr=[Select id,IAM_Application_Roles__c,IAM_Promotion__c from User where id=:userCreated.id];
            if(!String.isEmpty(newUsername)&&!String.isEmpty(cn.IAM_Ext_Legacy_UID__C)){
                IAM_Reclaim_Utility.UpdateNewUserName(cn.IAM_Ext_Legacy_UID__C,newUsername);
            }
            if(!reclaimTracker.isEmpty()){
                IAM_Reclaim_Utility.UpdateReclaimTracker(newUsername,reclaimTracker);
            }
            if(isGuidanzUSer){
                // Process if it is a guidanz User or contact does have  a User record.
                System.debug('Guidanz User is Present');
                //Chech the respective Contact of the Guidanz user and update the contact attributes of the Guidanz User.
                Contact gzCon= new Contact(id=guidanzContactId);
                if(gzCon.AccountId==Label.IAM_Default_Location_ID_1||gzCon.AccountId==Label.IAM_Default_Location_ID_2){
                    gzCon.AccountId=cn.AccountId;
                }
                gzCon.FirstName=(cn.FirstName!=null?cn.FirstName:'');
                gzCon.LastName=(cn.LastName!=null?cn.LastName:'');
                //email that user entered from the Reclaim page
                gzCon.email=(newEmail!=null?newEmail:'');
                gzCon.Username__c=(newUsername!=null?newUsername:'');
                //Username the user enterd in reclaim Page
                /*if(label.css_org=='.cso'){
                    gzCon.Username__c=(newUsername!=null?newUsername:'');
                }else{
                    gzCon.Username__c=(newUsername!=null?newUsername+Label.css_org:'');   
                }*/
                gzCon.CMI_Contact_Type__c=(cn.CMI_Contact_Type__c!=null?cn.CMI_Contact_Type__c:'');
                gzCon.IAM_Contact_Status__c='Active';//Making Contact status Active since there is user already present.
                gzCon.IAM_Applications__c=(cn.IAM_Applications__c!=null?cn.IAM_Applications__c:'');
                gzCon.IAM_Application_Roles__c=(usr[0].IAM_Application_Roles__c!=null?usr[0].IAM_Application_Roles__c:'');
                gzCon.IAM_is_Member_of__c=(cn.IAM_is_Member_of__c!=null?cn.IAM_is_Member_of__c:'');
                gzCon.IAM_Product_Group_Access__c=(cn.IAM_Product_Group_Access__c!=null?cn.IAM_Product_Group_Access__c:'');
                gzCon.IAM_Qsolexpiration__c=(cn.IAM_Qsolexpiration__c!=null?cn.IAM_Qsolexpiration__c:'');
                gzCon.IAM_Qsolview__c=(cn.IAM_Qsolview__c!=null?cn.IAM_Qsolview__c:'');
                /* 12/03/2020 - Added NPBU Diagnostic Expration */
                gzCon.IAM_NpbuDiagExpire__c=(cn.IAM_NpbuDiagExpire__c!=null?cn.IAM_NpbuDiagExpire__c:'');
                //Work group ID should be check While inserting the Contact.
                gzCon.IAM_Work_Group_Id__c=(cn.IAM_Work_Group_Id__c!=null?cn.IAM_Work_Group_Id__c:'');
                gzCon.IAM_swregexpire__c=(cn.IAM_swregexpire__c!=null?cn.IAM_swregexpire__c:'');
                //gzCon.IAM_ABO_Code_Formula__c=cn.IAM_ABO_Code_Formula__c;
                gzCon.RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('IAM').getRecordTypeId();
                gzCon.IAM_Ext_Legacy_Uid__c=(cn.IAM_Ext_Legacy_Uid__c!=null?cn.IAM_Ext_Legacy_Uid__c:'');
                gzCon.IAM_Legacy_User__c=false;
                gzCon.IAM_Promotion__c=(usr[0].IAM_Promotion__c!=null?usr[0].IAM_Promotion__c:'');
                //gzCon.IAM_DN_Value__c = IAM_Utility.getDNValue(newUsername, false, gzCon.IAM_Internal__c);
               gzCon.IAM_DN_Value__c = IAM_Utility.getDNValue(newUsername,gzCon.IAM_Person_Type__c);//added by vineet
   
        //Deleting the contact the is inserted as a part of data loading.
                Contact conRec = new Contact();
               if(cn.id!=gzCon.id){
                updateUserFeature(cn.Id);
                conRec = [Select IAM_Applications__c, IAM_is_Member_of__c, IAM_Promotion__c from Contact
                         where Id =: cn.Id];
                    // before deleting contact delete User access features frst.
                    List<IAM_Contact_Provisioning__c> conDel= [SELECT id,IAM_Reject_Reason__c,IAM_Reason__c FROM IAM_Contact_Provisioning__c WHERE IAM_Contact__C=:cn.id];
                    if(!conDel.isEmpty()){
                        for(IAM_Contact_Provisioning__c iamCP: conDel){
                            iamCp.IAM_Status__c='Inactive';
                            iamCP.IAM_Reject_Reason__c='Other';
                            iamCP.IAM_Reason__c='Deactivated because we already have a guidanz User.';
                        }
                        Update conDel;
                    }
                    cn.IAM_Ext_Legacy_UID__c='';
                    cn.IAM_Contact_Status__c='Inactive';
                    Update cn;
                }
                gzCon.IAM_Applications__c=(conRec.IAM_Applications__c!=null?conRec.IAM_Applications__c:'');
                gzCon.IAM_is_Member_of__c=(conRec.IAM_is_Member_of__c!=null?conRec.IAM_is_Member_of__c:'');
                Update gzCon;
                //Create User access and Features under new guidanz contact using Application groups attributre.
                ID jobID = System.enqueueJob(new IAM_Reclaim_Queable_API_Class(gzCon,isDuplicateUser));
            System.debug('Printing Secondary JOB ID'+jobID); 
            }else{
                //Case where Contact does not have any user record.
                System.debug('Updating Contact where wthere is no guidanz user record');
                /*if(label.css_org=='.cso'){
                    cn.Username__c=(newUsername!=null?newUsername:'');
                }else{
                    cn.Username__c=(newUsername!=null?newUsername+label.css_org:'');
                }*/
                //cn.IAM_DN_Value__c = IAM_Utility.getDNValue(newUsername, false, cn.IAM_Internal__c);
                cn.IAM_DN_Value__c = IAM_Utility.getDNValue(newUsername,cn.IAM_Person_Type__c);//added by vineet
                cn.Username__c=(newUsername!=null?newUsername:'');
                cn.email=(newEmail!=null?newEmail:'');
                cn.IAM_Contact_Status__c='Active';
                cn.IAM_Legacy_User__c=false;
                cn.IAM_Promotion__c=(userCreated.IAM_Promotion__c!=null?userCreated.IAM_Promotion__c:'');
                cn.IAM_Application_Roles__c=(usr[0].IAM_Application_Roles__c!=null?usr[0].IAM_Application_Roles__c:'');
                Update cn;
                //below method call to update any user feature record in Pending status to Active for this contact - @Anupam CHG0065797
                updateUserFeature(cn.Id);
                // Update User access and feature with respective new username and also create if any new has to be ceated.
                ID jobID = System.enqueueJob(new IAM_Reclaim_Queable_API_Class(cn,isDuplicateUser));
                System.debug('Printing Secondary JOB ID'+jobID); 
            }

            reclaimTracker.put('Is_Contact_Update',true);
            IAM_Reclaim_Utility.UpdateReclaimTracker(newUsername,reclaimTracker);
            
             
        }catch(exception e){
            System.debug('Printing exception'+e);
            System.debug('Prinitng Stack Trace String'+e.getStackTraceString());
            //Code write to error Object and Reclaim tracker status.
            String processedData = 'Method - execute, Contact Id - '
            + cn.Id + ', New Username User Choose - ' + newUsername;
            IAM_ErrorHandling.IAMerrorCapture(processedData, Label.IAM_Reclaim_Flow, 
            e.getStackTraceString() + ' - ' + e.getMessage(),
            IAM_Reclaim_Contact_Update_Queueable.class.getName());
        }
    }
    
    //CHG0065797 @Anupam - to update user feature status from Pending to active for reclaim contacts
    Public Static void updateUserFeature(Id conRecId){
        system.debug('Inside updateUserFeature method--->');
        List<IAM_Contact_Provisioning__c> updateListUserFeat = new List<IAM_Contact_Provisioning__c>();
        List<IAM_Contact_Provisioning__c> userFeatPendingList = [Select Id, IAM_Status__c,IAM_Application_Name__c,IAM_swregexpire__c,
                                                                 IAM_Qsolexpiration__c,IAM_Role__c,IAM_Contact__c,IAM_User__c,
                                                                 IAM_Cumpas_Modularity__c,IAM_Promotion__c,IAM_Subscription_Name__c,
                                                                 IAM_Remaining_Units__c,IAM_Remaining_Count_Formatted__c,IAM_NpbuDiagExpire__c
                                                                 from IAM_Contact_Provisioning__c
                                                                 where IAM_Contact__c =: conRecId AND IAM_Status__c =: System.Label.IAM_Status_Pending];
        
        if(userFeatPendingList.size() > 0){
            for(IAM_Contact_Provisioning__c conFeatRec : userFeatPendingList){
                conFeatRec.IAM_Status__c = 'Active';
                updateListUserFeat.add(conFeatRec);
            }
        }
        system.debug('updateListUserFeat--->'+updateListUserFeat);
        if(updateListUserFeat.size() > 0){
            update updateListUserFeat;
        }
		IAM_contactHelperClass.updateApplicationContact(updateListUserFeat);        
    }

}