objects/Account.object
<CustomObject>
    <fields>
        <fullName>ccrz__E_AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Invoice__c.object
<CustomObject>
    <description>Invoice main object.  The invoice represents object against which payments may be made.</description>
    <label>CC Invoice</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>CC Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_SW_InvoiceActions_Test.cls
@isTest 
public class OSM_SW_InvoiceActions_Test {

    static testMethod void testOSM_SW_InvoiceActions(){
        
        //Create User
        User objUser = TestingUtils.ADMIN_USER;
        
        //Create Account Group
        List<ccrz__E_AccountGroup__c> listAccountGrp = TestingUtils.createAccountGroup(5, 'TestDataAccountGroup', 'Best Price', true);
        
        //Create Account
        List<Account> listAccount = TestingUtils.createAccount(1, 'TestAccountData', listAccountGrp[0].Id, objUser.Id, true);
        
        //Create Contact
        List<Contact> listContact  = TestingUtils.createContact(1, listAccount[0].Id, null, true);
       
        // Create Order
        ccrz__E_Order__c objOrder = TestingUtils.createOrder(listContact[0].Id, 'TestDataOrder', true);
        
        // Create CC Invoices
        List<ccrz__E_Invoice__c> listCCInvoices = TestingUtils.createCCInvoices(1,objOrder.Id, listContact[0].Id,'Open','SoftwareStore', true);
        
        // Get List of Invoice Id's
        List<Id> listInvoiceIds = new List<Id>();
        if(!listCCInvoices.isEmpty()){
            for(ccrz__E_Invoice__c objInvoice: listCCInvoices){
            	listInvoiceIds.add(objInvoice.Id);
        	}
        }
        
        // Start Test
        Test.startTest();
        	
        	//OSM_SW_InvoiceActions.setARInvoiceOutboundWrapper(listInvoiceIds);
        
        // Stop Test
        Test.stopTest();
    }
}