objects/Account.object
<CustomObject>
    <fields>
        <fullName>OSM_Preferred_Payment_Method__c</fullName>
        <label>OSM Preferred Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>cc</fullName>
                </value>
                <value>
                    <fullName>po</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this order was placed for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Billing_Frequency__c</fullName>
        <formula>ccrz__SubProdTerm__r.Billing_Display_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Quantityperunit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of items that come in one order-able unit</description>
        <label>Quantityperunit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <label>Sequence</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>SoftwareStore</fullName>
                    <default>true</default>
                    <label>SoftwareStore</label>
                </value>
                <value>
                    <fullName>CSSNAStore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Subscription__c.object
<CustomObject>
    <description>This is a subscription, the record of purchased subscription</description>
    <fields>
        <fullName>OSM_Display_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OSM Display Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Subscriptions (OSM Display Product)</relationshipLabel>
        <relationshipName>CC_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OSM_Free_Trial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Free Trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OSM_Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account associated with this subscription.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items shipped for this subscriptions</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <description>Used for modifiers to determine order in which they are processed.</description>
        <label>Sequence</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront to which this subscription belongs.</description>
        <label>Storefront</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product that this subscription is for.  When recurring orders are used this is the product that will be ordered.</description>
        <label>Subscription Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionStartDate__c</fullName>
        <description>The start date of the subscription</description>
        <label>Subscription Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionStatus__c</fullName>
        <description>The status of the subscription</description>
        <label>Subscription Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CC Subscription</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>CC Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OSM_Order_Item_License__c.object
<CustomObject>
    <fields>
        <fullName>CC_Order_Item__c</fullName>
        <label>CC Order Item</label>
        <referenceTo>ccrz__E_OrderItem__c</referenceTo>
        <relationshipName>OSM_Oreder_Item_Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Revoked/ReIssue</fullName>
                </value>
                <value>
                    <fullName>ReIssued</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Revoke/ReIssue Pending</fullName>
                </value>
                <value>
                    <fullName>Create And Get Done</fullName>
                </value>
                <value>
                    <fullName>Create And Get Failed</fullName>
                </value>
                <value>
                    <fullName>Revoke Initiated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OSM Order Item License</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>OSM License Activation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Order Item Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OSM_Order_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Frequency__c</fullName>
        <label>Billing Frequency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>One Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Order_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Order Item</label>
        <referenceTo>ccrz__E_OrderItem__c</referenceTo>
        <relationshipLabel>OSM Order Subscriptions</relationshipLabel>
        <relationshipName>OSM_Order_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OSM_CCOrder__c</fullName>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>OSM Order Subscriptions</relationshipLabel>
        <relationshipName>OSM_Order_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OSM_CCSubscription__c</fullName>
        <label>CC Subscription</label>
        <referenceTo>ccrz__E_Subscription__c</referenceTo>
        <relationshipLabel>OSM Order Subscriptions</relationshipLabel>
        <relationshipName>OSM_Order_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OSM Order Subscription</label>
    <nameField>
        <displayFormat>OSM-{00000}</displayFormat>
        <label>OSM Order Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Order Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OSM_SW_CreateGetOrdr_ReIssueBatch_Test.cls
@isTest
public class OSM_SW_CreateGetOrdr_ReIssueBatch_Test {
    static testMethod void testBatchScript(){
        User usr=OSM_TestDataCreationUtility.getPortalUser();
        TestProductSetupReq testReq = new TestProductSetupReq();
        testReq.permissionSetName = 'OSM_Support_Admin';
        
        testReq.accountGroupName = 'TestingAccountGroup';
        testReq.accountName = 'TestingAccount';        
        
        testReq.compositeProductName = 'Guidanz';
        testReq.compositeProductSKU = '1234567-BUS';
        testReq.compositeProductGroupName = 'DA';
        testReq.compositeProductProductType = 'Aggregated';
        
        testReq.componentProductName = 'Guidanz 12';
        testReq.componentProductStatus = 'Released';
        testReq.componentProductSKU = '1301298-BUS';
        testReq.componentProductGroupName = 'DA';
        testReq.componentProductPackageName = 'Base';
        
        
        testReq.priceListName = 'TestPriceList';
        testReq.specName = 'TestName';
        
        
        TestCompletedTransactionSetUpRes transecRes = new TestCompletedTransactionSetUpRes();
        transecRes = OSM_TestDataCreationUtility.createProductSetUp(testReq);
        system.debug('transecRes---->>'+transecRes);
        
        Account acc = new Account();
        acc.name = 'OSM_Test_Acc';
        acc.OSM_Preferred_Payment_Method__c = 'PO';
        insert acc;
        
        set<string> prodid = new set<string>();
        ccrz__E_Product__c prod = new ccrz__E_Product__c();
        prod.name = 'Guidanz';
        prod.ccrz__SKU__c = '15458776';
        prod.ccrz__Quantityperunit__c = 3343;
        prod.ccrz__StartDate__c = system.today();
        prod.ccrz__EndDate__c = system.today()+1;
        prod.ccrz__ShortDesc__c = 'testing';
        prod.ccrz__ProductStatus__c='Released';
        insert prod;
        String prodidstring = String.valueof(prod.id);
        prodid.add(prodidstring); 
        
        List<ccrz__E_Subscription__c> subList = new List<ccrz__E_Subscription__c>();
        ccrz__E_Subscription__c sub = new ccrz__E_Subscription__c();
        sub.OSM_Display_Product__c = prod.id;
        sub.ccrz__Quantity__c = 10;
        sub.ccrz__Sequence__c = 2;
        sub.ccrz__Account__c = transecRes.objSetupDate.account.Id;
        sub.ccrz__Storefront__c ='SoftwareStore';
        sub.ccrz__SubscriptionStartDate__c  = system.today();
        sub.OSM_Subscription_End_Date__c  = System.today()+50;
        sub.ccrz__SubscriptionStatus__c = 'Active';
        sub.ccrz__SubscriptionProduct__c = prod.id;
        sub.OSM_Free_Trial__c =false;
        //sub.OSM_Display_Product__r.ccrz__ShortDesc__c = 'test description';
        subList.add(sub);
        insert subList;
        
        OSM_Order_Subscription__c objSubsc = new OSM_Order_Subscription__c();
        objSubsc.CC_Order_Item__c = transecRes.orderItem.Id;
        objSubsc.OSM_CCSubscription__c = subList[0].id;
        objSubsc.OSM_CCOrder__c = transecRes.order.Id;
        objSubsc.Billing_Frequency__c = 'Monthly';
        insert objSubsc;
        System.debug('transecRes.orderSubscriptionjunction: '+objSubsc);
        
        
        ccrz__E_Order__c objOrdr = new ccrz__E_Order__c();
        objOrdr.ccrz__OrderStatus__c = 'Order Submitted';
        objOrdr.Id = transecRes.order.Id;
        objOrdr.ByPassFlow__c = true;
        objOrdr.ccrz__OrderDate__c = system.today();
        update objOrdr;
        
        
        ccrz__E_OrderItem__c objItem = new ccrz__E_OrderItem__c();
        objItem.IsRevokeLicenseSucess__c = false;
        objItem.Revocation_Status__c = '';
        objItem.Id = transecRes.orderItem.Id;
        update objItem;
        
        
        OSM_Order_Item_License__c objLsc1 = new OSM_Order_Item_License__c();
        objLsc1.CC_Order_Item__c = transecRes.orderItem.Id;
        objLsc1.Activation_Key__c = 'ABCDEF';
        objLsc1.Status__c = 'New';
        objLsc1.Type__c = 'Basic';
        insert objLsc1;
        
        OSM_Order_Item_License__c objLsc2 = new OSM_Order_Item_License__c();
        objLsc2.Status__c = 'New';
        objLsc2.CC_Order_Item__c = transecRes.orderItem.Id;
        objLsc2.Tool_Instance_Key__c = 'test2';
        objLsc2.Parent_Activation_Key__c = objLsc1.Id;
        insert objLsc2;
        
        
        OSM_Order_Item_License__c objLsc12 = new OSM_Order_Item_License__c();
        objLsc12.CC_Order_Item__c = transecRes.orderItem.Id;
        objLsc12.Activation_Key__c = 'ABCDEF';
        objLsc12.Status__c = 'New';
        objLsc12.Type__c = 'Functional';
        insert objLsc12;
        
        OSM_Order_Item_License__c objLsc21 = new OSM_Order_Item_License__c();
        objLsc21.Status__c = 'Revoked/ReIssue';
        objLsc21.CC_Order_Item__c = transecRes.orderItem.Id;
        objLsc21.Tool_Instance_Key__c = 'test2';
        objLsc21.Parent_Activation_Key__c = objLsc12.Id;
        insert objLsc21;
        
        Test.startTest();
        Database.executeBatch(new OSM_SW_CreateGetOrder_ON_ReIssueBatch(), 1);
        Test.stopTest();
    }
}