objects/Account.object
<CustomObject>
    <fields>
        <fullName>BMS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BMS Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <formula>IF(AND(ISBLANK(CSS_DealerCode__c), ISBLANK(CSS_DBCode__c), ISBLANK(CSS_DBCode__c), ISBLANK(IAM_Service_Provider_Code__c)), &apos;&apos;, IF(CSS_DistributorCode__c=&apos;50000&apos;, CSS_DBCode__c+&apos;-&apos;+IAM_Service_Provider_Code__c, CSS_DistributorCode__c+&apos;-&apos;+IAM_Service_Provider_Code__c))</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to Store Region Value based on SP code</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_UserLocation__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS_UserLocations</relationshipLabel>
        <relationshipName>CSS_UserLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMS_Enabled__c</fullName>
        <formula>AccountId__r.BMS_Enabled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BMS Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_code__c</fullName>
        <externalId>true</externalId>
        <label>Location_code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSS_UserLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPrimary</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS_UserLocation</label>
    <nameField>
        <label>CSS_UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_UserLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EVL_LookupCompController_Test.cls
/**********************************************************************
Name:EVL_LookupCompController_Test
Copyright © 2020  Cummins
======================================================
======================================================
Purpose: Test Class for EVL_LookupCompController.                                                          
======================================================
======================================================
History                                                            
VERSION  	AUTHOR            			DATE                DETAIL                                 
1.0 	 	Krishnamoorthi N			06/26/2020			INITIAL DEVELOPMENT 
2.0         Diksha Rajpurohit           08/25/2022        	SOQL INJECTION SAFE
***********************************************************************/
@isTest
public class EVL_LookupCompController_Test {
    static testMethod void myTest() {
    	
        Account a=new Account();
        a.name='name';
        a.CSS_DistributorCode__c='test';
        a.IAM_Service_Provider_Code__c='P12345';
        a.Type='Dealer Account';
        a.Region__c = 'US and Canada';
        a.CMI_Account_Status__c = 'Active';
        a.IAM_Service_Provider_Code__c = '562551';
		a.BMS_Enabled__c = true;
        insert a;
        
        CSS_UserLocation__c  usloc = new CSS_UserLocation__c();
        usloc.UserId__c=userInfo.getUserId();
        usloc.Location_code__c=a.Location__c;
        usloc.isActive__c=true;
        usloc.AccountId__c = a.Id;
        usloc.isPrimary__c = true;
        usloc.Name = 'krishna';
        insert usloc ;
        
        Asset AssRec = new Asset();
        
        AssRec.Name = '79464646';
        insert AssRec;
        
        test.startTest();
        EVL_LookupCompController.fetchLookUpValues('AssetNumber','name', 'Account'); 
        EVL_LookupCompController.fetchLookUpValues('UnitNumber','krishna', 'Asset');
        EVL_LookupCompController.fetchUser();
        EVL_LookupCompController.saveServiceOrder(a.Id,'testCon',AssRec.Id,'test','testing','te','12','555','km');
        test.stopTest();
        
    }
}