objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSS_DBCode__c</fullName>
        <description>DistributorBranchCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Branch Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_DE_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS_DE_Parent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>WWSPS</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>IAM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS_DE_Parent</relationshipLabel>
        <relationshipName>CSS_DE_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Data_Receive_from_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Data Receive from CSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Data_Send_to_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Data Send to CSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DSID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DSID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Exchange_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Exchange Enabled?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ESN_Service_History_Send_to_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ESN Service History Send to CSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fault_Code_Data_Receive_from_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fault Code Data Receive from CSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <formula>IF(AND(ISBLANK(CSS_DealerCode__c), ISBLANK(CSS_DBCode__c), ISBLANK(CSS_DBCode__c), ISBLANK(IAM_Service_Provider_Code__c)), &apos;&apos;, IF(CSS_DistributorCode__c=&apos;50000&apos;, CSS_DBCode__c+&apos;-&apos;+IAM_Service_Provider_Code__c, CSS_DistributorCode__c+&apos;-&apos;+IAM_Service_Provider_Code__c))</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repair_Data_Receive_from_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Repair Data Receive from CSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solution_Data_Receive_from_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solution Data Receive from CSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Unit_Data_Receive_from_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vehicle/Unit Data Receive from CSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Unit_Data_Send_to_CSS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vehicle/Unit Data Send to CSS</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>CSS</fullName>
        <active>true</active>
        <label>CSS</label>
    </recordTypes>
    <recordTypes>
        <fullName>WWSPS</fullName>
        <active>true</active>
        <description>Record type for all WWSPS records</description>
        <label>WWSPS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Cummins_login_ID__c</fullName>
        <description>this is for IDM purpose and to store cummins LDAP ID of all the users having the WWID from LDAP</description>
        <externalId>true</externalId>
        <label>User Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSS_DataExchange_Child__c.object
<CustomObject>
    <fields>
        <fullName>CSS_DataExchange_Parent__c</fullName>
        <label>CSS_DataExchange_Parent</label>
        <referenceTo>CSS_DataExchange_Parent__c</referenceTo>
        <relationshipLabel>CSS_DataExchange_Child</relationshipLabel>
        <relationshipName>CSS_DataExchange_Child</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DataExchangeChildType__c</fullName>
        <label>DataExchangeChildType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataExchangeChild_Status__c</fullName>
        <label>DataExchangeChild Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UnProcessed</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN__c</fullName>
        <label>ESN</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repair_Fault_Code__c</fullName>
        <label>Repair Fault Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repair_Related_Fault_Code__c</fullName>
        <label>Repair Related Fault Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repair_Symptom__c</fullName>
        <label>Repair Symptom</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Component__c</fullName>
        <label>Selected Component</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSS_DataExchange_Child</label>
    <nameField>
        <label>CSS_DataExchange_Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_DataExchange_Child</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSS_DataExchange_Parent__c.object
<CustomObject>
    <description>This is used for storing Request &amp; Response values from Triage mobile app or external data system</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Fire Truck</fullName>
                </value>
                <value>
                    <fullName>Generator Drive (Other Than Standby)</fullName>
                </value>
                <value>
                    <fullName>Generator Drive (Standby Power)</fullName>
                </value>
                <value>
                    <fullName>Marine (Continuous Duty)</fullName>
                </value>
                <value>
                    <fullName>Marine (Heavy Duty)</fullName>
                </value>
                <value>
                    <fullName>Marine (Intermittent Duty)</fullName>
                </value>
                <value>
                    <fullName>Marine(Medium Continuous Duty)</fullName>
                </value>
                <value>
                    <fullName>Marine (Prime Or Continuous Power)</fullName>
                </value>
                <value>
                    <fullName>Marine - Recreational(All Eng)</fullName>
                </value>
                <value>
                    <fullName>Recreational Vehicle</fullName>
                </value>
                <value>
                    <fullName>Recreational Vehicle Ad</fullName>
                </value>
                <value>
                    <fullName>School Bus (Us &amp; Canada)</fullName>
                </value>
                <value>
                    <fullName>Worldwide Bus (Exc Us &amp; Can School Bus)</fullName>
                </value>
                <value>
                    <fullName>Worldwide Off-Highway</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_Job_Number__c</fullName>
        <label>CSS Job Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerID__c</fullName>
        <label>CustomerID</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DataExchange_Status__c</fullName>
        <label>DataExchange Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UnProcessed</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ESN__c</fullName>
        <label>ESN</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failure_Date__c</fullName>
        <label>Failure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Failure_Point__c</fullName>
        <label>Failure Point</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MAKE__c</fullName>
        <label>MAKE</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MODEL__c</fullName>
        <label>MODEL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage_Measure__c</fullName>
        <label>Mileage_Measure</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SERVICEMODELNAME__c</fullName>
        <label>SERVICEMODELNAME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shop_Work_Order__c</fullName>
        <label>Shop Work Order</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warranty_Start_Date__c</fullName>
        <label>Warranty_Start_Date</label>
        <type>Date</type>
    </fields>
    <label>CSS_DataExchange_Parent</label>
    <nameField>
        <displayFormat>IAS-{0000000000}</displayFormat>
        <label>IAS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSS_DataExchange_Parent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CSS_GetJobInfo_Test.cls
@isTest
public class CSS_GetJobInfo_Test {
    

    Static String recordType_Id = Schema.SObjectType.Account.getRecordTypeInfosByName().get('WWSPS').getRecordTypeId();  
    
    static testmethod void AccountMethod(){
        
         Id p = [select id from profile where name='CSS_Dealer_Data_ExChange_Admin'].id;
         
         Account A = new Account();
         A.Name = 'OEM-DTNA HQ';
         A.BillingCity = 'City';
         A.BillingStreet = 'Street';
         A.BillingCountry = 'Canada';
         A.Data_Exchange_Enabled__c = true;
         insert A;
          
        Contact con = new Contact(LastName ='testCon',firstname = 'testing', IAM_Cummins_login_ID__c = 'test@cummins.com', AccountId = A.Id);
        insert con;
        
                  
        User user = new User(alias = 'test123', email='test123@noemail.com',
                    emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                    localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                    ContactId = con.Id, timezonesidkey='America/Los_Angeles', username='iiiioooo@noemail.com');
        insert user;
        
        User U = [ SELECT id, accountid, ContactId, profileid, IsActive from user where username='iiiioooo@noemail.com'];
        system.debug('user'+U);
        
        system.runAs(User){
            
           Test.startTest(); 
            
            Account acc1 = new Account();
            Acc1.Name = 'test';
            acc1.css_de_parent__c = A.id;
            Acc1.BillingCity = 'City';
            Acc1.BillingStreet = 'Street';
            Acc1.BillingCountry = 'Canada';
            Acc1.BillingPostalCode = '90001';
            acc1.RecordTypeId=recordType_Id;
            acc1.IAM_Service_Provider_Code__c = '56255';
            acc1.CSS_DistributorCode__c = '56270';
            acc1.CSS_DBCode__c = '56255';
            acc1.Data_Exchange_Enabled__c = true;
            acc1.Customer_Data_Send_to_CSS__c = true;
            acc1.Vehicle_Unit_Data_Send_to_CSS__c = true;
            acc1.Vehicle_Unit_Data_Receive_from_CSS__c = true;
            acc1.ESN_Service_History_Send_to_CSS__c = true;
            acc1.Customer_Data_Receive_from_CSS__c = true;
            acc1.Solution_Data_Receive_from_CSS__c = true;
            acc1.Repair_Data_Receive_from_CSS__c = true;
            acc1.Fault_Code_Data_Receive_from_CSS__c = true;
            insert acc1;
            System.debug('acc1------->'+acc1); 
             
            list<account> acctlist1=[select id,name,css_de_parent__c,Location__c from account];
            system.debug('acctlist1>>'+acctlist1);
            
            Contact con1 = new Contact(LastName ='testCon',AccountId = acc1.Id);
            insert con1;
            
            CSS_Job_Order__c SerRec = new CSS_Job_Order__c();
            SerRec.Shop_Work_Order__c = 'WO12345';
            Date d = Date.Today();
            SerRec.DSID__c='12345';
            SerRec.DSID_Status__c='open';
            SerRec.ESN__c ='79464646';
            SerRec.Customer_Name__c='Oliver';
            SerRec.Failure_Date__c =d;
            SerRec.Warranty_Start_Date__c=d;
            SerREc.CSS_Job_Location_Code__c = '56270-56255';
            insert SerRec;
    
            list<CSS_Job_Order__c> SerRec1 = [select id, name,Creator_Location__c from CSS_Job_Order__c 
                                              where Customer_Name__c = 'Oliver'];
            system.debug('SerRec1'+SerRec1);
            
            CSS_DataExchange_Parent__c  DataParent = new CSS_DataExchange_Parent__c();
            DataParent.CSS_Job_Number__c = SerRec1[0].Name;
            DataParent.Failure_Point__c =5.9;
            DataParent.Customer_Name__c='testAs';
            DataParent.CustomerID__c='123';
            DataParent.Hours__c=2;
            DataParent.ESN__c='testTs'; 
            DataParent.Unit_Number__c='testRa';
            DataParent.MAKE__c='testRe';
            DataParent.VIN__c='testWr';
            DataParent.Mileage_Measure__c='<Miles/KM>';
            DataParent.MODEL__c='testQr';
            DataParent.Application__c='Automotive';
            DataParent.Address__c='testSh';
            DataParent.SERVICEMODELNAME__c='testRa';
            DataParent.Contact_Name__c='testJe';
            DataParent.City__c='COLUMBUS';
            DataParent.State__c='IN';
            DataParent.Country__c='AP';
            DataParent.DataExchange_Status__c='UnProcessed';
            insert DataParent;
            
            list<CSS_DataExchange_Parent__c> DP1 = [select id, CSS_Job_Number__c,DataExchange_Status__c from CSS_DataExchange_Parent__c 
                                              where Customer_Name__c = 'testAs'];
            system.debug('DP1'+DP1); 
        
            list<CSS_DataExchange_Child__c> DEChildList = new list<CSS_DataExchange_Child__c>();
            CSS_DataExchange_Child__c chilRec1= new CSS_DataExchange_Child__c();
            chilRec1.DataExchangeChild_Status__c='UnProcessed';
            chilRec1.CSS_DataExchange_Parent__c = DataParent.id;
            chilRec1.DataExchangeChildType__c='RepairData';        
            chilRec1.Selected_Component__c='{"ComponentID":"F20000","ComponentName":"PressureSensor","Action":"Repaired"}';
            chilRec1.Repair_Symptom__c='123';
            chilRec1.Repair_Fault_Code__c='123';
            chilRec1.Repair_Related_Fault_Code__c='123456';
            DEChildList.add(chilRec1);
            
            CSS_DataExchange_Child__c chilRec2= new CSS_DataExchange_Child__c();
            chilRec2.DataExchangeChild_Status__c='UnProcessed';
            chilRec2.CSS_DataExchange_Parent__c = DataParent.id;
            chilRec2.DataExchangeChildType__c='FaultCode';        
            chilRec2.Selected_Component__c='{"ComponentID":"F20000","ComponentName":"PressureSensor","Action":"Repaired"}';
            chilRec2.Repair_Symptom__c='123';
            chilRec2.Repair_Fault_Code__c='123';
            chilRec2.Repair_Related_Fault_Code__c='123456';
            DEChildList.add(chilRec2);
            
            CSS_DataExchange_Child__c chilRec3= new CSS_DataExchange_Child__c();
            chilRec3.DataExchangeChild_Status__c='UnProcessed';
            chilRec3.CSS_DataExchange_Parent__c = DataParent.id;
            chilRec3.DataExchangeChildType__c='SolutionData';        
            chilRec3.Selected_Component__c='{"ComponentID":"F20000","ComponentName":"PressureSensor","Action":"Repaired"}';
            chilRec3.Repair_Symptom__c='123';
            chilRec3.Repair_Fault_Code__c='123';
            chilRec3.Repair_Related_Fault_Code__c='123456';
            DEChildList.add(chilRec3);
            insert DEChildList;
                                    
            
            
        CSS_GetJobInfo.WrapperInput wrap=new CSS_GetJobInfo.WrapperInput();
        CSS_GetJobInfo.ComponentWrapper comp=new CSS_GetJobInfo.ComponentWrapper();
            
        
            RestRequest request = new RestRequest();
            request.addHeader('Content-Type', 'application/json');
            request.requestUri ='https://cumminscss--cssbrkfx.cs54.my.salesforce.com/services/apexrest/GetJobInfo/';
            request.httpMethod = 'POST'; 
            
            string requestRes1 =  '{'+
                ' "Header": {'+       
                ' "ServiceName":"GetJobInfo",'+
                ' "ServiceVersion":"1.0", '+
                ' "ToolID":"<Name of Dealer System>" ,'+
                ' "SPCode":"56255" ,'+
                ' "SenderID":"<User Id / System User>",'+
                ' "TargetID":"CSS" '+        
                '  },'+                  
                ' "DataArea":{'+         
                ' "CSSJobID":"'+SerRec1[0].Name+'",'+
                ' "ShopWO":"WO12345" '+
                '}'+
                ' }';   
                
            request.requestBody = Blob.valueOf(requestRes1);
            RestContext.request = request;
            CSS_GetJobInfoResWrapper getJobW=CSS_GetJobInfo.GetJobInfomration(); 
          
            string requestRes2 =  '{'+
                ' "Header": {'+       
                '  "ServiceName_Test":"GetJobInfo",'+
                '  "ServiceVersion":"1.0", '+
                '  "ToolID":"<Name of Dealer System>" ,'+
                '  "SPCode":"56255" ,'+
                '  "SenderID":"<User Id / System User>",'+
                '  "TargetID":"CSS" '+        
                '  },'+                  
                '  "DataArea":{'+         
                '  "CSSJobID":"'+SerRec1[0].Name+'",'+
                '  "ShopWO":"1234" '+
                '}'+
                ' }';      
            request.requestBody = Blob.valueOf(requestRes2);
            RestContext.request = request;                
            CSS_GetJobInfoResWrapper getJobW1=CSS_GetJobInfo.GetJobInfomration();
            
            
            string requestRes3 =  '{'+
                ' "Header": {'+       
                '  "ServiceName":"GetJobInfo_Test",'+
                '  "ServiceVersion":"1.0", '+
                '  "ToolID":"<Name of Dealer System>" ,'+
                '  "SPCode":"56255" ,'+
                '  "SenderID":"<User Id / System User>",'+
                '  "TargetID":"CSS" '+        
                '  },'+                  
                '  "DataArea":{'+         
                '  "CSSJobID":"'+SerRec1[0].Name+'",'+
                '  "ShopWO":"1234" '+
                '}'+
                ' }';      
            request.requestBody = Blob.valueOf(requestRes3);
            RestContext.request = request;
            CSS_GetJobInfoResWrapper getJobW2=CSS_GetJobInfo.GetJobInfomration();
           
            
            string requestRes4 =  '{'+
                ' "Header": {'+       
                '  "ServiceName":"GetJobInfo",'+
                '  "ServiceVersion":"1.0", '+
                '  "ToolID":"" ,'+
                '  "SPCode":"56255" ,'+
                '  "SenderID":"<User Id / System User>",'+
                '  "TargetID":"CSS" '+        
                '  },'+                  
                '  "DataArea":{'+         
                '  "CSSJobID":"'+SerRec1[0].Name+'",'+
                '  "ShopWO":"123" '+
                '}'+
                ' }';      
            request.requestBody = Blob.valueOf(requestRes4);
            RestContext.request = request;
            CSS_GetJobInfoResWrapper getJobW3=CSS_GetJobInfo.GetJobInfomration();
           
            
            string requestRes5 =  '{'+
                ' "Header": {'+       
                '  "ServiceName":"GetJobInfo",'+
                '  "ServiceVersion":"1.0", '+
                '  "ToolID":"<Name of Dealer System>" ,'+
                '  "SPCode":"56255" ,'+
                '  "SenderID":"<User Id / System User>",'+
                '  "TargetID":"CSS" '+        
                '  },'+                  
                '  "DataArea":{'+         
                '  "CSSJobID":"'+SerRec1[0].Name+'",'+
                '  "ShopWO":"123" '+
                '}'+
                ' }';      
            request.requestBody = Blob.valueOf(requestRes5);
            RestContext.request = request;
            CSS_GetJobInfoResWrapper getJobW4=CSS_GetJobInfo.GetJobInfomration();
          
        
            string requestRes6 =  '{'+
                ' "Header": {'+       
                '  "ServiceName":"GetJobInfo",'+
                '  "ServiceVersion":"1.0", '+
                '  "ToolID":"<Name of Dealer System>" ,'+
                '  "SPCode":"56255" ,'+
                '  "SenderID":"<User Id / System User>",'+
                '  "TargetID":"CSS" '+        
                '  },'+                  
                '  "DataArea":{'+         
                '  "CSSJobID":"'+SerRec1[0].Name+'",'+
                '  "ShopWO":"'+SerRec.Shop_Work_Order__c+'" '+
                '}'+
                ' }';      
            request.requestBody = Blob.valueOf(requestRes6);
            RestContext.request = request;
            CSS_GetJobInfoResWrapper getJobW5=CSS_GetJobInfo.GetJobInfomration();
          
            Test.stopTest(); 
            
        }
      }
}