objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_JobEventTemporary__c.object
<CustomObject>
    <fields>
        <fullName>Attribute1__c</fullName>
        <label>Attribute1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute2__c</fullName>
        <label>Attribute2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute3__c</fullName>
        <label>Attribute3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>TRPs</fullName>
                </value>
                <value>
                    <fullName>TSBs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS_JobEventTemporary</label>
    <nameField>
        <label>CSS_JobEventTemporary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_JobEventTemporaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_PSN__c.object
<CustomObject>
    <description>To handle multiple ESN scenarios with respect to Claims</description>
    <fields>
        <fullName>AccessCode__c</fullName>
        <label>AccessCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS PSNs</relationshipLabel>
        <relationshipName>CSS_PSNs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Equipment_ID__c</fullName>
        <label>Equipment ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSS PSN</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS PSNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>AccountCodeEdit__c</fullName>
        <label>AccountCodeEdit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountCodeType__c</fullName>
        <label>AccountCodeType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountCode__c</fullName>
        <label>AccountCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Description__c</fullName>
        <label>Campaign Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Code__c</fullName>
        <label>Component Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <description>Captures the Component or Failure ID for the Repair</description>
        <label>Component Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fail_Code__c</fullName>
        <formula>IF(BEGINS (System_Code__c, &quot;W&quot;), TRIM(LEFT(System_Code__c, 2)) + TRIM(LEFT(Component_Code__c, 2))+ TRIM(LEFT(Failure_Mode__c, 2)), TRIM(LEFT(System_Code__c, 2)) + TRIM(LEFT(Component_Code__c, 2)) )</formula>
        <label>Fail Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failure_Mode__c</fullName>
        <label>Failure Mode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ODM_Penalty__c</fullName>
        <label>ODM Penalty</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Job for this Component</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Code__c</fullName>
        <label>System Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A field to differentiate Camp,TRP &amp; ATCs from Solution Component</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <description>This field is the case Id from EDS.</description>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Response__c</fullName>
        <description>Values for Verification</description>
        <label>Diagnostic Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not the solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Repair_Response__c</fullName>
        <label>Repair Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair Successful.</fullName>
                </value>
                <value>
                    <fullName>Repair Successful with additional parts/procedures.</fullName>
                </value>
                <value>
                    <fullName>Repair performed but didnot resolve the root cause.</fullName>
                </value>
                <value>
                    <fullName>Repair not performed.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup for Service Job object that stores the  Job order number associated with it.</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <description>It’s a solution Id obtained from EDS.</description>
        <label>Solution Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_SRT__c.object
<CustomObject>
    <fields>
        <fullName>Access_Code__c</fullName>
        <label>Access Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Component ID for this Repair</description>
        <label>CSS Solution Component</label>
        <referenceTo>CSS_Solution_Component__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extended_Hours__c</fullName>
        <label>Extended Hours</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRT_Access_Code__c</fullName>
        <label>SRT Access Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_AccessiblityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accessiblity CheckBox Option from the SRT Table</description>
        <label>SRT AccessiblityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRT_Category__c</fullName>
        <label>SRT Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_ID__c</fullName>
        <label>SRT ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Quantity__c</fullName>
        <label>SRT Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SRT_Time__c</fullName>
        <label>SRT Time</label>
        <precision>13</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SRT_Title__c</fullName>
        <label>SRT Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution Number</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <formula>Solution_Number__r.Solution_Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diagnosis</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Diag Access</fullName>
                </value>
                <value>
                    <fullName>Repair Access</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>99Time</fullName>
                </value>
                <value>
                    <fullName>Overlap</fullName>
                </value>
                <value>
                    <fullName>Field Action</fullName>
                </value>
                <value>
                    <fullName>Field Action Access</fullName>
                </value>
                <value>
                    <fullName>BMS SRT</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isPerformed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPerformed</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS SRT</label>
    <nameField>
        <label>CSS SRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS SRTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CG_CL_ClaimsSRTRepController_Test.cls
@istest
public class CG_CL_ClaimsSRTRepController_Test 
{          
    public static testmethod void CG_CL_ClaimsSRTRepController_method(){
        
        CSS_JobEventTemporary__c Tempkal = new CSS_JobEventTemporary__c();
        Tempkal.Attribute1__c = 'POL';
        Tempkal.Attribute2__c = 'New Engine Warranty';
        Tempkal.Attribute3__c = '67';
        Tempkal.Key__c = 'AccountCodes';
        Insert Tempkal;
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02650';
        acc.IAM_Service_Provider_Code__c='97895';
        acc.type='Dealer Account';
        insert acc;
        CSS_Claims__c claim = new CSS_Claims__C();
        claim.ODM_Penalty__c = '50';
        claim.AccessCode__c='test';
        claim.Account__c=acc.Id;
        claim.Assigned_To__c = null;
        insert claim;
        CSS_PSN__c objPsn = new CSS_PSN__c();
        objPsn.Equipment_ID__c = 'cdrtfvbgyunhjmik';
        objPsn.CSS_Claims__c = claim.id;
        insert objPsn;
        CSS_Job_Order__c JO = CSS_TestData.createJobOrder(true);
        CSS_Solution_Component__c solComp = new CSS_Solution_Component__c();
        solComp.Type__c = 'TRP';
        solComp.Campaign_Description__c='test';
        solComp.System_Code__c ='TH';
        solComp.Component_Code__c = 'AC';
        solComp.AccountCodeEdit__c ='New Parts Warranty 62';
        insert solComp;
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        List<CSS_Srt__c> additionalSRTList = new List<CSS_Srt__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_ID__c = '100';
        srt.Type__c = 'Repair';
        srt.SRT_Category__c = null;
        srt.isPerformed__c = true;
        srt.Extended_Hours__c = 12.00;
        srt.Component_Id__c = null;
        srt.CSS_Claims__c = claim.id;
        insert srt;    
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Solution_Number__c = sol.id;
        srt1.SRT_Title__c='test';
        srt1.SRT_Quantity__c=123;
        srt1.SRT_Time__c=123;
        srt1.SRT_Access_Code__c='test';
        srt1.SRT_ID__c = '100';
        srt1.Type__c = 'Repair Access';
        srt1.Extended_Hours__c = 12.00;
        srt1.SRT_Category__c = 'AdditionalRep';
        srt1.isPerformed__c = true;
        srt1.Component_Id__c = null;
        srt1.CSS_Claims__c = claim.id;
        insert srt1;
        
        additionalSRTList.add(srt);
        additionalSRTList.add(srt1);
        //additionalSRTList.add(srt2);
        ApexPages.currentPage().getParameters().put('id', claim.Id);
        Test.startTest();
        CG_CL_ClaimsSRTRepController obj = new CG_CL_ClaimsSRTRepController();
        obj.totalDecimalTimeRep = 123.0;
        obj.totalDecimalTimeAccRep = 234.99;
        obj.isCatastrophic = true;
        obj.isAutomatedClaim = true;
        obj.checklaborrate = true;
        obj.selSRTID = 'selSRTID';
        obj.selCoveredVal = 'selCoveredVal';
        obj.PenaltyExists = true;
        obj.isDiagRepSRTCovered = true;
        obj.CID = claim.id;
        obj.calculateExtendedHours();
        Test.stopTest();
    }
    public static testmethod void CG_CL_ClaimsSRTRepController_method1(){
        
        CSS_JobEventTemporary__c Tempkal = new CSS_JobEventTemporary__c();
        Tempkal.Attribute1__c = 'POL';
        Tempkal.Attribute2__c = 'New Engine Warranty';
        Tempkal.Attribute3__c = '67';
        Tempkal.Key__c = 'AccountCodes';
        Insert Tempkal;
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02650';
        acc.IAM_Service_Provider_Code__c='97895';
        acc.type='Dealer Account';
        insert acc;
        CSS_Claims__c claim = new CSS_Claims__C();
        claim.ODM_Penalty__c = '50';
        claim.AccessCode__c='test';
        claim.Account__c=acc.Id;
        claim.Assigned_To__c = null;
        insert claim;
        CSS_PSN__c objPsn = new CSS_PSN__c();
        objPsn.Equipment_ID__c = 'cdrtfvbgyunhjmik';
        objPsn.CSS_Claims__c = claim.id;
        insert objPsn;
        CSS_Job_Order__c JO = CSS_TestData.createJobOrder(true);
        CSS_Solution_Component__c solComp = new CSS_Solution_Component__c();
        solComp.Type__c = 'TRP';
        solComp.Campaign_Description__c='test';
        solComp.System_Code__c ='TH';
        solComp.Component_Code__c = 'AC';
        solComp.AccountCodeEdit__c ='New Parts Warranty 62';
        solComp.CSS_Claims__c = claim.id;
     //   solComp.Fail_Code__c = 'TestData';
        solComp.AccountCode__c = 'Troy';
        solComp.AccountCodeType__c = 'data';
        solComp.AccountCodeEdit__c = 'Type3';
        solComp.System_Code__c = 'Star';
        solComp.Failure_Mode__c = 'Wars';
        solComp.Component_Code__c = 'Avengers';
        insert solComp;
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        
        insert sol;
        List<CSS_Srt__c> additionalSRTList = new List<CSS_Srt__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = null;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_ID__c = '100';
       srt.Type__c = 'Repair Access';
      
        srt.SRT_Category__c = null;
        srt.isPerformed__c = true;
        srt.Extended_Hours__c = 12.00;
        srt.Component_Id__c = solComp.id;
        srt.CSS_Claims__c = claim.id;
        srt.SRT_AccessiblityCheck__c = true;
        insert srt;    
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Solution_Number__c = sol.id;
        srt1.SRT_Title__c='test';
        srt1.SRT_Quantity__c=123;
        srt1.SRT_Time__c=123;
        srt1.SRT_Access_Code__c='test';
        srt1.SRT_ID__c = '100';
        srt1.Type__c = 'Repair Access';
        srt1.Extended_Hours__c = 12.00;
        srt1.SRT_Category__c = null;
        srt1.isPerformed__c = true;
        srt1.Component_Id__c = solComp.id;
        srt1.CSS_Claims__c = claim.id;
        srt1.SRT_AccessiblityCheck__c = true;
        insert srt1;
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Solution_Number__c = sol.id;
        srt2.SRT_Title__c='test';
        srt2.SRT_Quantity__c=123;
        srt2.SRT_Time__c=123;
        srt2.SRT_Access_Code__c='test';
        srt2.SRT_ID__c = '100';
        srt2.Type__c = 'Access';
        srt2.Extended_Hours__c = 12.00;
        srt2.SRT_Category__c = null;
        srt2.isPerformed__c = true;
        srt2.Component_Id__c = solComp.id;
        srt2.CSS_Claims__c = claim.id;
        insert srt2;
        
        additionalSRTList.add(srt);
        additionalSRTList.add(srt1);
        additionalSRTList.add(srt2);
        
        ApexPages.currentPage().getParameters().put('id', claim.Id);
        Test.startTest();
        CG_CL_ClaimsSRTRepController obj = new CG_CL_ClaimsSRTRepController();
        obj.totalDecimalTimeRep = 123.0;
        obj.totalDecimalTimeAccRep = 234.99;
        obj.isCatastrophic = true;
        obj.isAutomatedClaim = true;
        obj.checklaborrate = true;
        obj.selSRTID = 'selSRTID';
        obj.selCoveredVal = 'selCoveredVal';
        obj.PenaltyExists = true;
        obj.isDiagRepSRTCovered = true;
        obj.CID = claim.id;
        Test.stopTest();
    }
     public static testmethod void CG_CL_ClaimsSRTRepController_method2(){
        
        CSS_JobEventTemporary__c Tempkal = new CSS_JobEventTemporary__c();
        Tempkal.Attribute1__c = 'NPW';
        Tempkal.Attribute2__c = 'New Engine Warranty';
        Tempkal.Attribute3__c = '67';
        Tempkal.Key__c = 'AccountCodes';
        Insert Tempkal;
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02650';
        acc.IAM_Service_Provider_Code__c='97895';
        acc.type='Dealer Account';
        insert acc;
        CSS_Job_Order__c JO = CSS_TestData.createJobOrder(true);
        CSS_Claims__c claim = new CSS_Claims__C();
        claim.ODM_Penalty__c = '50';
        claim.AccessCode__c='test';
        claim.Account__c=acc.Id;
        claim.Assigned_To__c = null;
        claim.CSS_Job__c = JO.id;
        insert claim;
        CSS_PSN__c objPsn = new CSS_PSN__c();
        objPsn.Equipment_ID__c = 'cdrtfvbgyunhjmik';
        objPsn.CSS_Claims__c = claim.id;
        insert objPsn;
        
        List<CSS_Solution_Component__c> solComplist = new List<CSS_Solution_Component__c>();
        CSS_Solution_Component__c solComp = new CSS_Solution_Component__c();
        solComp.Type__c = 'TRP';
        solComp.Campaign_Description__c='test';
        solComp.System_Code__c ='TH';
        solComp.Component_Code__c = 'AC';
        solComp.AccountCodeEdit__c ='New Parts Warranty 62';
        
        solComplist.add(solComp);
        insert solComplist;
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        List<CSS_Srt__c> additionalSRTList = new List<CSS_Srt__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = null;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_ID__c = '100';
        srt.Type__c = 'Repair';
        srt.SRT_Category__c = null;
        srt.isPerformed__c = true;
        srt.Extended_Hours__c = 12.00;
        srt.Component_Id__c = solComp.id;
        srt.CSS_Claims__c = claim.id;
        srt.SRT_AccessiblityCheck__c = true;
        insert srt;    
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Solution_Number__c = sol.id;
        srt1.SRT_Title__c='test';
        srt1.SRT_Quantity__c=123;
        srt1.SRT_Time__c=123;
        srt1.SRT_Access_Code__c='test';
        srt1.SRT_ID__c = '100';
        srt1.Type__c = 'Repair';
        srt1.Extended_Hours__c = 12.00;
        srt1.SRT_Category__c = null;
        srt1.isPerformed__c = true;
        srt1.Component_Id__c = solComp.id;
        srt1.CSS_Claims__c = claim.id;
        srt1.SRT_AccessiblityCheck__c = true;
        insert srt1;
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Solution_Number__c = sol.id;
        srt2.SRT_Title__c='test';
        srt2.SRT_Quantity__c=123;
        srt2.SRT_Time__c=123;
        srt2.SRT_Access_Code__c='test';
        srt2.SRT_ID__c = '100';
        srt2.Type__c = 'Repair';
        srt2.Extended_Hours__c = 12.00;
        srt2.SRT_Category__c = null;
        srt2.isPerformed__c = true;
        srt2.Component_Id__c = solComp.id;
        srt2.CSS_Claims__c = claim.id;
        srt2.SRT_AccessiblityCheck__c = true;
        insert srt2;
        
        additionalSRTList.add(srt);
        additionalSRTList.add(srt1);
        additionalSRTList.add(srt2);
        
        ApexPages.currentPage().getParameters().put('id', claim.Id);
        Test.startTest();
        CG_CL_ClaimsSRTRepController obj = new CG_CL_ClaimsSRTRepController();
        obj.totalDecimalTimeRep = 123.0;
        obj.totalDecimalTimeAccRep = 234.99;
        obj.isCatastrophic = true;
        obj.isAutomatedClaim = true;
        obj.checklaborrate = true;
        obj.selSRTID = 'selSRTID';
        obj.selCoveredVal = 'selCoveredVal';
        obj.PenaltyExists = true;
        obj.isDiagRepSRTCovered = true;
        obj.CID = claim.id;
        Test.stopTest();
    }
    public static testmethod void SRTPercReqRepMethod(){
        Test.startTest();
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        List <CSS_Job_Order__c> lstjo = new List <CSS_Job_Order__c>();
        CSS_Job_Order__c jo = new CSS_Job_Order__c();
        jo.createdDate=dateTime.now();
        jo.ESN__c = '79464646';
        jo.Customer_Name__c='test';
        jo.Shop_Work_Order__c='uiafh';
        jo.Mileage__c=123;
        jo.Complaint_Type_Desc__c = 'CRUISE CONTROL';
        jo.Category_Desc__c = 'Fuel - Oil - Coolant';
        jo.Status__c = 'closed';
        jo.Service_Model__c = 'model';
        jo.Customer_Name__c = 'CumminsTnD';
        jo.Equipment_ID__c = 'EQ7667';
        jo.Qsol_Engine_Family_Code__c ='56';
        jo.AccessCode__c = 'A';
        jo.Account__c = acc.id;
        insert jo;
        lstjo.add(jo);
        
        list<CSS_Claims__c> clist = new list<CSS_Claims__c>();
        CSS_Claims__c c1 = new CSS_Claims__c();
        c1.CSS_Job__c=jo.id;
        insert c1;
        clist.add(c1);
        
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        
        List<String> additionalSRTList = new List<String>();
        
        List<CSS_SRT__c> additionalSRTList1 = new List<CSS_SRT__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_Category__c='Campaign';
        srt.Type__c= '';
        additionalSRTList1.add(srt);
        
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Job_Order__c = JO.id;
        srt1.SRT_AccessiblityCheck__c=True;
        srt1.Access_Code_A__c = 65;
        srt1.name = 'TestClassName';
        srt1.type__c = 'Repair';
        srt1.Assignment__c = 'PRIMARY';
        srt1.srt_time__c = 1;
        srt1.SRT_ID__c = '100';
        srt1.isPerformed__c = true;
        srt1.ODM_Status__c = '';
        srt1.Access_Code__c = 'A';
        srt1.Account_Code__c = 'Select One';
        additionalSRTList1.add(srt1);
        
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Job_Order__c = JO.id;
        srt2.SRT_AccessiblityCheck__c=True;
        srt2.Access_Code_A__c = 65;
        srt2.name = 'TestClassName';
        srt2.type__c = 'Repair';
        srt2.Assignment__c = 'PRIMARY';
        srt2.srt_time__c = 1;
        srt2.SRT_ID__c = '100';
        srt2.isPerformed__c = true;
        srt2.ODM_Status__c = '';
        srt2.Access_Code__c = 'A';
        srt2.Account_Code__c = '';
        srt2.SRT_Category__c='';
        additionalSRTList1.add(srt2);
        insert additionalSRTList1;
        
        List<String> sid=new List<String>();
        for(CSS_SRT__c ss:additionalSRTList1){
            sid.add(ss.id);
        }
        List<CSS_Claims__c> cc=new List<CSS_Claims__c>();
        CSS_Claims__c claim = new CSS_Claims__c();
        claim.Customer_Name__c='Gopal';
        claim.Customer_Code__c='123';
        claim.Status__c='Draft';
        claim.Actual_Technician_Time__c=1.2;
        claim.Account__c = acc.id;
        cc.add(claim);
        insert cc;
        
        apexpages.currentPage().getparameters().put('id',Claim.id); 
        id cid=apexpages.currentPage().getparameters().get('id');
        system.assert(cid!=null);
        CG_CL_ClaimsSRTRepController p = new CG_CL_ClaimsSRTRepController();
        CG_CL_ClaimsSRTRepController.srtWrapper cmp =new  CG_CL_ClaimsSRTRepController.srtWrapper();
        List<CG_CL_ClaimsSRTRepController.srtWrapper> lstcmp = new List<CG_CL_ClaimsSRTRepController.srtWrapper>();
        
        CG_CL_ClaimsSRTRepController.sortWrapper srtdata=new CG_CL_ClaimsSRTRepController.sortWrapper(cmp);
        List<CG_CL_ClaimsSRTRepController.sortWrapper> ss=new List<CG_CL_ClaimsSRTRepController.sortWrapper>();
        ss.add(srtdata);
        p.repListWrap=ss;
        srtdata.compareTo(srtdata);
        cmp.solTitle='Test';
        cmp.solNum='1234';
        cmp.srtCheckBox=True;
        cmp.accessSrtCheckBox=True;
        cmp.sId=null;
        
        cmp.failcode='';
        cmp.srtType='';
        cmp.fautCodeName='';
        cmp.symptomName='';
        cmp.AccessCodeSaved='';
        cmp.SRTAccessCode='';
        
        cmp.AccessCode='';
        cmp.accountcode='';
        cmp.srtID='';
        cmp.srtDescription='';
        cmp.quantity=null;
        
        cmp.srtTime=null;
        cmp.srtAccessTime=null;
        cmp.srtWarrantable='';
        cmp.selectedRecord=true;
        cmp.accTime='';
        
        cmp.accTimeDec=null;
        cmp.ClaimedHrs=null;
        cmp.IsPopUpSRT=True;
        cmp.sortOrder=null; 
        p.CID=cc[0].id;
        lstcmp.add(cmp);
        //p.selSRTID = '100';
        p.SRTPercReqRep();
        Test.stopTest();
    }
    public static testmethod void getRepairTimeMethod(){
        Test.startTest();
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        List <CSS_Job_Order__c> lstjo = new List <CSS_Job_Order__c>();
        CSS_Job_Order__c jo = new CSS_Job_Order__c();
        jo.createdDate=dateTime.now();
        jo.ESN__c = '79464646';
        jo.Customer_Name__c='test';
        jo.Shop_Work_Order__c='uiafh';
        jo.Mileage__c=123;
        jo.Complaint_Type_Desc__c = 'CRUISE CONTROL';
        jo.Category_Desc__c = 'Fuel - Oil - Coolant';
        jo.Status__c = 'closed';
        jo.Service_Model__c = 'model';
        jo.Customer_Name__c = 'CumminsTnD';
        jo.Equipment_ID__c = 'EQ7667';
        jo.Qsol_Engine_Family_Code__c ='56';
        jo.AccessCode__c = 'A';
        jo.Account__c = acc.id;
        insert jo;
        lstjo.add(jo);
        
        list<CSS_Claims__c> clist = new list<CSS_Claims__c>();
        CSS_Claims__c c1 = new CSS_Claims__c();
        c1.CSS_Job__c=jo.id;
        insert c1;
        clist.add(c1);
        
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        
        List<String> additionalSRTList = new List<String>();
        
        List<CSS_SRT__c> additionalSRTList1 = new List<CSS_SRT__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_Category__c='Campaign';
        srt.Type__c= '';
        additionalSRTList1.add(srt);
        
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Job_Order__c = JO.id;
        srt1.SRT_AccessiblityCheck__c=True;
        srt1.Access_Code_A__c = 65;
        srt1.name = 'TestClassName';
        srt1.type__c = 'Repair';
        srt1.Assignment__c = 'PRIMARY';
        srt1.srt_time__c = 1;
        srt1.SRT_ID__c = '00-901-10';
        srt1.isPerformed__c = true;
        srt1.ODM_Status__c = '';
        srt1.Access_Code__c = 'A';
        srt1.Account_Code__c = 'Select One';
        additionalSRTList1.add(srt1);
        
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Job_Order__c = JO.id;
        srt2.SRT_AccessiblityCheck__c=True;
        srt2.Access_Code_A__c = 65;
        srt2.name = 'TestClassName';
        srt2.type__c = 'Repair';
        srt2.Assignment__c = 'PRIMARY';
        srt2.srt_time__c = 1;
        srt2.SRT_ID__c = '00-901-10';
        srt2.isPerformed__c = true;
        srt2.ODM_Status__c = '';
        srt2.Access_Code__c = 'A';
        srt2.Account_Code__c = '';
        srt2.SRT_Category__c='';
        additionalSRTList1.add(srt2);
        insert additionalSRTList1;
        
        List<String> sid=new List<String>();
        for(CSS_SRT__c ss:additionalSRTList1){
            sid.add(ss.id);
        }
        List<CSS_Claims__c> cc=new List<CSS_Claims__c>();
        CSS_Claims__c claim = new CSS_Claims__c();
        claim.Customer_Name__c='Gopal';
        claim.Customer_Code__c='123';
        claim.Status__c='Draft';
        claim.Actual_Technician_Time__c=1.2;
        claim.Account__c = acc.id;
        cc.add(claim);
        insert cc;
        
        apexpages.currentPage().getparameters().put('id',Claim.id); 
        id cid=apexpages.currentPage().getparameters().get('id');
        system.assert(cid!=null);
        CG_CL_ClaimsSRTRepController p = new CG_CL_ClaimsSRTRepController();
        CG_CL_ClaimsSRTRepController.srtWrapper cmp =new  CG_CL_ClaimsSRTRepController.srtWrapper();
        List<CG_CL_ClaimsSRTRepController.srtWrapper> lstcmp = new List<CG_CL_ClaimsSRTRepController.srtWrapper>();
        
        CG_CL_ClaimsSRTRepController.sortWrapper srtdata=new CG_CL_ClaimsSRTRepController.sortWrapper(cmp);
        List<CG_CL_ClaimsSRTRepController.sortWrapper> ss=new List<CG_CL_ClaimsSRTRepController.sortWrapper>();
        ss.add(srtdata);
        p.repListWrap=ss;
        srtdata.compareTo(srtdata);
        cmp.solTitle='Test';
        cmp.solNum='1234';
        cmp.srtCheckBox=True;
        cmp.accessSrtCheckBox=True;
        cmp.sId=null;
        
        cmp.failcode='';
        cmp.srtType='';
        cmp.fautCodeName='';
        cmp.symptomName='';
        cmp.AccessCodeSaved='';
        cmp.SRTAccessCode='';
        
        cmp.AccessCode='';
        cmp.accountcode='';
        cmp.srtID='';
        cmp.srtDescription='';
        cmp.quantity=null;
        
        cmp.srtTime=null;
        cmp.srtAccessTime=null;
        cmp.srtWarrantable='';
        cmp.selectedRecord=true;
        cmp.accTime='';
        
        cmp.accTimeDec=null;
        cmp.ClaimedHrs=null;
        cmp.IsPopUpSRT=True;
        cmp.sortOrder=null; 
        p.CID=cc[0].id;
        lstcmp.add(cmp);
        p.getRepairTime();
        Test.stopTest();
    }
    public static testmethod void overlapSRTCalloutMethod(){
        CSS_JobEventTemporary__c Tempkal = new CSS_JobEventTemporary__c();
        Tempkal.Attribute1__c = 'POL';
        Tempkal.Attribute2__c = 'New Engine Warranty';
        Tempkal.Attribute3__c = '67';
        Tempkal.Key__c = 'AccountCodes';
        Insert Tempkal;
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02650';
        acc.IAM_Service_Provider_Code__c='97895';
        acc.type='Dealer Account';
        insert acc;
        CSS_Claims__c claim = new CSS_Claims__C();
        claim.ODM_Penalty__c = '50';
        claim.AccessCode__c='test';
        claim.Account__c=acc.Id;
        claim.Assigned_To__c = null;
        insert claim;
        CSS_PSN__c objPsn = new CSS_PSN__c();
        objPsn.Equipment_ID__c = 'cdrtfvbgyunhjmik';
        objPsn.CSS_Claims__c = claim.id;
        insert objPsn;
        CSS_Job_Order__c JO = CSS_TestData.createJobOrder(true);
        CSS_Solution_Component__c solComp = new CSS_Solution_Component__c();
        solComp.Type__c = 'TRP';
        solComp.Campaign_Description__c='test';
        solComp.System_Code__c ='TH';
        solComp.Component_Code__c = 'AC';
        solComp.AccountCodeEdit__c ='New Parts Warranty 62';
        insert solComp;
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        List<CSS_Srt__c> additionalSRTList = new List<CSS_Srt__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_ID__c = '100';
     //   srt.Type__c = 'Repair';
     srt.Type__c = 'Access';
     srt.SRT_AccessiblityCheck__c = true;
        srt.SRT_Category__c = null;
        srt.isPerformed__c = true;
        srt.Extended_Hours__c = 12.00;
        srt.Component_Id__c = solComp.id;
        srt.CSS_Claims__c = claim.id;
        //srt.Step_Id__c = 'Test';
        srt.Access_Code_A__c =0;
        srt.Access_Code_B__c = 0;
        srt.Access_Code_C__c = 0;
        srt.Access_Code_D__c = 0;
        srt.Access_Code_R__c = 2;
        srt.FailCode__c = 'TestData';
        insert srt;    
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Solution_Number__c = sol.id;
        srt1.SRT_Title__c='test';
        srt1.SRT_Quantity__c=123;
        srt1.SRT_Time__c=123;
        srt1.SRT_Access_Code__c='test';
        srt1.SRT_ID__c = '100';
        srt1.Type__c = 'Access';
        srt1.Extended_Hours__c = 12.00;
        srt1.SRT_Category__c = 'AdditionalRep';
        srt1.isPerformed__c = true;
        srt1.Component_Id__c = solComp.id;
        srt1.CSS_Claims__c = claim.id;
        srt1.SRT_AccessiblityCheck__c = true;
        //srt1.Step_Id__c = 'Test';
        srt1.Access_Code_A__c =0;
        srt1.Access_Code_B__c = 0;
        srt1.Access_Code_C__c = 0;
        srt1.Access_Code_D__c = 0;
        srt1.Access_Code_R__c = 2;
        srt1.FailCode__c = 'TestData';
        insert srt1;
        additionalSRTList.add(srt);
        additionalSRTList.add(srt1);
        ApexPages.currentPage().getParameters().put('id', claim.Id);
        
       
        
        Test.startTest();
        CG_CL_ClaimsSRTRepController obj = new CG_CL_ClaimsSRTRepController();
         Set<String> overlapSRTIds = new Set<String>();
        overlapSRTIds.add('element');
        
        obj.overlapSRTCallout('accCode',additionalSRTList);
        Test.stopTest();
    }
    public static testmethod void calculateExtendedHoursMethod(){
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        List <CSS_Job_Order__c> lstjo = new List <CSS_Job_Order__c>();
        CSS_Job_Order__c jo = new CSS_Job_Order__c();
        jo.createdDate=dateTime.now();
        jo.ESN__c = '79464646';
        jo.Customer_Name__c='test';
        jo.Shop_Work_Order__c='uiafh';
        jo.Mileage__c=123;
        jo.Complaint_Type_Desc__c = 'CRUISE CONTROL';
        jo.Category_Desc__c = 'Fuel - Oil - Coolant';
        jo.Status__c = 'closed';
        jo.Service_Model__c = 'model';
        jo.Customer_Name__c = 'CumminsTnD';
        jo.Equipment_ID__c = 'EQ7667';
        jo.Qsol_Engine_Family_Code__c ='56';
        jo.AccessCode__c = 'A';
        jo.Account__c = acc.id;
        insert jo;
        lstjo.add(jo);
        
        list<CSS_Claims__c> clist = new list<CSS_Claims__c>();
        CSS_Claims__c c1 = new CSS_Claims__c();
        c1.CSS_Job__c=jo.id;
        insert c1;
        clist.add(c1);
        
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        
        List<String> additionalSRTList = new List<String>();
        
        List<CSS_SRT__c> additionalSRTList1 = new List<CSS_SRT__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_Category__c='Campaign';
        srt.Type__c= '';
        additionalSRTList1.add(srt);
        
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Job_Order__c = JO.id;
        srt1.SRT_AccessiblityCheck__c=True;
        srt1.Access_Code_A__c = 65;
        srt1.name = 'TestClassName';
        srt1.type__c = 'Repair';
        srt1.Assignment__c = 'PRIMARY';
        srt1.srt_time__c = 1;
        srt1.SRT_ID__c = '00-901-10';
        srt1.isPerformed__c = true;
        srt1.ODM_Status__c = '';
        srt1.Access_Code__c = 'A';
        srt1.Account_Code__c = 'Select One';
        additionalSRTList1.add(srt1);
        
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Job_Order__c = JO.id;
        srt2.SRT_AccessiblityCheck__c=True;
        srt2.Access_Code_A__c = 65;
        srt2.name = 'TestClassName';
        srt2.type__c = 'Repair';
        srt2.Assignment__c = 'PRIMARY';
        srt2.srt_time__c = 1;
        srt2.SRT_ID__c = '00-901-10';
        srt2.isPerformed__c = true;
        srt2.ODM_Status__c = '';
        srt2.Access_Code__c = 'A';
        srt2.Account_Code__c = '';
        srt2.SRT_Category__c='';
        additionalSRTList1.add(srt2);
        
        insert additionalSRTList1;
        Test.startTest();
        CG_CL_ClaimsSRTRepController p = new CG_CL_ClaimsSRTRepController();
        p.calculateExtendedHours();
        Test.stopTest();
    }
    public static testmethod void changeUpOrderMethod(){
        Test.startTest();
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        List <CSS_Job_Order__c> lstjo = new List <CSS_Job_Order__c>();
        CSS_Job_Order__c jo = new CSS_Job_Order__c();
        jo.createdDate=dateTime.now();
        jo.ESN__c = '79464646';
        jo.Customer_Name__c='test';
        jo.Shop_Work_Order__c='uiafh';
        jo.Mileage__c=123;
        jo.Complaint_Type_Desc__c = 'CRUISE CONTROL';
        jo.Category_Desc__c = 'Fuel - Oil - Coolant';
        jo.Status__c = 'closed';
        jo.Service_Model__c = 'model';
        jo.Customer_Name__c = 'CumminsTnD';
        jo.Equipment_ID__c = 'EQ7667';
        jo.Qsol_Engine_Family_Code__c ='56';
        jo.AccessCode__c = 'A';
        jo.Account__c = acc.id;
        insert jo;
        lstjo.add(jo);
        
        list<CSS_Claims__c> clist = new list<CSS_Claims__c>();
        CSS_Claims__c c1 = new CSS_Claims__c();
        c1.CSS_Job__c=jo.id;
        insert c1;
        clist.add(c1);
        
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        
        List<String> additionalSRTList = new List<String>();
        
        List<CSS_SRT__c> additionalSRTList1 = new List<CSS_SRT__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_Category__c='Campaign';
        srt.Type__c= '';
        additionalSRTList1.add(srt);
        
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Job_Order__c = JO.id;
        srt1.SRT_AccessiblityCheck__c=True;
        srt1.Access_Code_A__c = 65;
        srt1.name = 'TestClassName';
        srt1.type__c = 'Repair';
        srt1.Assignment__c = 'PRIMARY';
        srt1.srt_time__c = 1;
        srt1.SRT_ID__c = '00-901-10';
        srt1.isPerformed__c = true;
        srt1.ODM_Status__c = '';
        srt1.Access_Code__c = 'A';
        srt1.Account_Code__c = 'Select One';
        additionalSRTList1.add(srt1);
        
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Job_Order__c = JO.id;
        srt2.SRT_AccessiblityCheck__c=True;
        srt2.Access_Code_A__c = 65;
        srt2.name = 'TestClassName';
        srt2.type__c = 'Repair';
        srt2.Assignment__c = 'PRIMARY';
        srt2.srt_time__c = 1;
        srt2.SRT_ID__c = '00-901-10';
        srt2.isPerformed__c = true;
        srt2.ODM_Status__c = '';
        srt2.Access_Code__c = 'A';
        srt2.Account_Code__c = '';
        srt2.SRT_Category__c='';
        additionalSRTList1.add(srt2);
        insert additionalSRTList1;
        
        List<String> sid=new List<String>();
        for(CSS_SRT__c ss:additionalSRTList1){
            sid.add(ss.id);
        }
        List<CSS_Claims__c> cc=new List<CSS_Claims__c>();
        CSS_Claims__c claim = new CSS_Claims__c();
        claim.Customer_Name__c='Gopal';
        claim.Customer_Code__c='123';
        claim.Status__c='Draft';
        claim.Actual_Technician_Time__c=1.2;
        claim.Account__c = acc.id;
        cc.add(claim);
        insert cc;
        
        apexpages.currentPage().getparameters().put('id',Claim.id); 
        id cid=apexpages.currentPage().getparameters().get('id');
        system.assert(cid!=null);
        CG_CL_ClaimsSRTRepController p = new CG_CL_ClaimsSRTRepController();
        CG_CL_ClaimsSRTRepController.srtWrapper cmp =new  CG_CL_ClaimsSRTRepController.srtWrapper();
        List<CG_CL_ClaimsSRTRepController.srtWrapper> lstcmp = new List<CG_CL_ClaimsSRTRepController.srtWrapper>();
        
        CG_CL_ClaimsSRTRepController.sortWrapper srtdata=new CG_CL_ClaimsSRTRepController.sortWrapper(cmp);
        List<CG_CL_ClaimsSRTRepController.sortWrapper> ss=new List<CG_CL_ClaimsSRTRepController.sortWrapper>();
        ss.add(srtdata);
        p.repListWrap=ss;
        srtdata.compareTo(srtdata);
        cmp.solTitle='Test';
        cmp.solNum='1234';
        cmp.srtCheckBox=True;
        cmp.accessSrtCheckBox=True;
        cmp.sId=null;
        
        cmp.failcode='';
        cmp.srtType='';
        cmp.fautCodeName='';
        cmp.symptomName='';
        cmp.AccessCodeSaved='';
        cmp.SRTAccessCode='';
        
        cmp.AccessCode='';
        cmp.accountcode='';
        cmp.srtID='';
        cmp.srtDescription='';
        cmp.quantity=null;
        
        cmp.srtTime=null;
        cmp.srtAccessTime=null;
        cmp.srtWarrantable='';
        cmp.selectedRecord=true;
        cmp.accTime='';
        
        cmp.accTimeDec=null;
        cmp.ClaimedHrs=null;
        cmp.IsPopUpSRT=True;
        cmp.sortOrder=null; 
        p.CID=cc[0].id;
        lstcmp.add(cmp);
        p.changeUpOrder();
        Test.stopTest();
    }
    public static testmethod void changeDownOrderMethod(){
        Test.startTest();
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        List <CSS_Job_Order__c> lstjo = new List <CSS_Job_Order__c>();
        CSS_Job_Order__c jo = new CSS_Job_Order__c();
        jo.createdDate=dateTime.now();
        jo.ESN__c = '79464646';
        jo.Customer_Name__c='test';
        jo.Shop_Work_Order__c='uiafh';
        jo.Mileage__c=123;
        jo.Complaint_Type_Desc__c = 'CRUISE CONTROL';
        jo.Category_Desc__c = 'Fuel - Oil - Coolant';
        jo.Status__c = 'closed';
        jo.Service_Model__c = 'model';
        jo.Customer_Name__c = 'CumminsTnD';
        jo.Equipment_ID__c = 'EQ7667';
        jo.Qsol_Engine_Family_Code__c ='56';
        jo.AccessCode__c = 'A';
        jo.Account__c = acc.id;
        insert jo;
        lstjo.add(jo);
        
        list<CSS_Claims__c> clist = new list<CSS_Claims__c>();
        CSS_Claims__c c1 = new CSS_Claims__c();
        c1.CSS_Job__c=jo.id;
        insert c1;
        clist.add(c1);
        
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        
        List<String> additionalSRTList = new List<String>();
        
        List<CSS_SRT__c> additionalSRTList1 = new List<CSS_SRT__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_Category__c='Campaign';
        srt.Type__c= '';
        additionalSRTList1.add(srt);
        
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Job_Order__c = JO.id;
        srt1.SRT_AccessiblityCheck__c=True;
        srt1.Access_Code_A__c = 65;
        srt1.name = 'TestClassName';
        srt1.type__c = 'Repair';
        srt1.Assignment__c = 'PRIMARY';
        srt1.srt_time__c = 1;
        srt1.SRT_ID__c = '00-901-10';
        srt1.isPerformed__c = true;
        srt1.ODM_Status__c = '';
        srt1.Access_Code__c = 'A';
        srt1.Account_Code__c = 'Select One';
        additionalSRTList1.add(srt1);
        
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Job_Order__c = JO.id;
        srt2.SRT_AccessiblityCheck__c=True;
        srt2.Access_Code_A__c = 65;
        srt2.name = 'TestClassName';
        srt2.type__c = 'Repair';
        srt2.Assignment__c = 'PRIMARY';
        srt2.srt_time__c = 1;
        srt2.SRT_ID__c = '00-901-10';
        srt2.isPerformed__c = true;
        srt2.ODM_Status__c = '';
        srt2.Access_Code__c = 'A';
        srt2.Account_Code__c = '';
        srt2.SRT_Category__c='';
        additionalSRTList1.add(srt2);
        insert additionalSRTList1;
        
        List<String> sid=new List<String>();
        for(CSS_SRT__c ss:additionalSRTList1){
            sid.add(ss.id);
        }
        List<CSS_Claims__c> cc=new List<CSS_Claims__c>();
        CSS_Claims__c claim = new CSS_Claims__c();
        claim.Customer_Name__c='Gopal';
        claim.Customer_Code__c='123';
        claim.Status__c='Draft';
        claim.Actual_Technician_Time__c=1.2;
        claim.Account__c = acc.id;
        cc.add(claim);
        insert cc;
        
        apexpages.currentPage().getparameters().put('id',Claim.id); 
        id cid=apexpages.currentPage().getparameters().get('id');
        system.assert(cid!=null);
        CG_CL_ClaimsSRTRepController p = new CG_CL_ClaimsSRTRepController();
        CG_CL_ClaimsSRTRepController.srtWrapper cmp =new  CG_CL_ClaimsSRTRepController.srtWrapper();
        List<CG_CL_ClaimsSRTRepController.srtWrapper> lstcmp = new List<CG_CL_ClaimsSRTRepController.srtWrapper>();
        
        CG_CL_ClaimsSRTRepController.sortWrapper srtdata=new CG_CL_ClaimsSRTRepController.sortWrapper(cmp);
        List<CG_CL_ClaimsSRTRepController.sortWrapper> ss=new List<CG_CL_ClaimsSRTRepController.sortWrapper>();
        ss.add(srtdata);
        p.repListWrap=ss;
        srtdata.compareTo(srtdata);
        cmp.solTitle='Test';
        cmp.solNum='1234';
        cmp.srtCheckBox=True;
        cmp.accessSrtCheckBox=True;
        cmp.sId=null;
        
        cmp.failcode='';
        cmp.srtType='';
        cmp.fautCodeName='';
        cmp.symptomName='';
        cmp.AccessCodeSaved='';
        cmp.SRTAccessCode='';
        
        cmp.AccessCode='';
        cmp.accountcode='';
        cmp.srtID='';
        cmp.srtDescription='';
        cmp.quantity=null;
        
        cmp.srtTime=null;
        cmp.srtAccessTime=null;
        cmp.srtWarrantable='';
        cmp.selectedRecord=true;
        cmp.accTime='';
        
        cmp.accTimeDec=null;
        cmp.ClaimedHrs=null;
        cmp.IsPopUpSRT=True;
        cmp.sortOrder=null; 
        p.CID=cc[0].id;
        lstcmp.add(cmp);
        p.changeDownOrder();
        Test.stopTest();
    }
    public static testmethod void callClaimsAccessStepDetailsRepairMethod(){
        Test.startTest();
        CG_CL_ClaimsSRTRepController obj = new CG_CL_ClaimsSRTRepController();
        obj.callClaimsAccessStepDetailsRepair();
        Test.stopTest();
    }
    public static testmethod void ClaimsRepairNotesPopupOkMethod(){
        Test.startTest();
        CG_CL_ClaimsSRTRepController obj = new CG_CL_ClaimsSRTRepController();
        obj.ClaimsRepairNotesPopupOk();
        Test.stopTest();
    }
    public static testmethod void saveRepDataMethod(){
        Test.startTest();
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        List <CSS_Job_Order__c> lstjo = new List <CSS_Job_Order__c>();
        CSS_Job_Order__c jo = new CSS_Job_Order__c();
        jo.createdDate=dateTime.now();
        jo.ESN__c = '79464646';
        jo.Customer_Name__c='test';
        jo.Shop_Work_Order__c='uiafh';
        jo.Mileage__c=123;
        jo.Complaint_Type_Desc__c = 'CRUISE CONTROL';
        jo.Category_Desc__c = 'Fuel - Oil - Coolant';
        jo.Status__c = 'closed';
        jo.Service_Model__c = 'model';
        jo.Customer_Name__c = 'CumminsTnD';
        jo.Equipment_ID__c = 'EQ7667';
        jo.Qsol_Engine_Family_Code__c ='56';
        jo.AccessCode__c = 'A';
        jo.Account__c = acc.id;
        insert jo;
        lstjo.add(jo);
        
        list<CSS_Claims__c> clist = new list<CSS_Claims__c>();
        CSS_Claims__c c1 = new CSS_Claims__c();
        c1.CSS_Job__c=jo.id;
        insert c1;
        clist.add(c1);
        
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.Service_Job__c = JO.ID;
        sol.Case_Name__c = 'ABC';
        sol.Solution_Title__c='CDE';
        sol.Name='ABC';
        sol.Diagnostic_Response__c ='Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        insert sol;
        
        List<String> additionalSRTList = new List<String>();
        
        List<CSS_SRT__c> additionalSRTList1 = new List<CSS_SRT__c>();
        CSS_SRT__c srt = new CSS_SRT__c();
        srt.Solution_Number__c = sol.id;
        srt.SRT_Title__c='test';
        srt.SRT_Quantity__c=123;
        srt.SRT_Time__c=123;
        srt.SRT_Access_Code__c='test';
        srt.SRT_Category__c='Campaign';
        srt.Type__c= 'Admin';
        srt.isPerformed__c = false;
        additionalSRTList1.add(srt);
        
        CSS_SRT__c srt1 = new CSS_SRT__c();
        srt1.Job_Order__c = JO.id;
        srt1.SRT_AccessiblityCheck__c=True;
        srt1.Access_Code_A__c = 65;
        srt1.name = 'TestClassName';
        srt1.type__c = 'Repair';
        srt1.Assignment__c = 'PRIMARY';
        srt1.srt_time__c = 1;
        srt1.SRT_ID__c = '00-901-10';
        srt1.isPerformed__c = false;
        srt1.ODM_Status__c = '';
        srt1.Access_Code__c = 'A';
        srt1.Account_Code__c = 'Not 2';
        srt1.FailCode__c = 'Select One';
       additionalSRTList1.add(srt1);
        
        CSS_SRT__c srt2 = new CSS_SRT__c();
        srt2.Job_Order__c = JO.id;
        srt2.SRT_AccessiblityCheck__c=True;
        srt2.Access_Code_A__c = 65;
        srt2.name = 'TestClassName';
        srt2.type__c = 'Repair';
        srt2.Assignment__c = 'PRIMARY';
        srt2.srt_time__c = 1;
        srt2.SRT_ID__c = '00-901-10';
        srt2.isPerformed__c = false;
        srt2.ODM_Status__c = '';
        srt2.Access_Code__c = 'A';
        srt2.Account_Code__c = '';
        srt2.SRT_Category__c='';
        srt2.FailCode__c = 'Select One';
        additionalSRTList1.add(srt2);
        insert additionalSRTList1;
        
        List<String> sid=new List<String>();
        for(CSS_SRT__c ss:additionalSRTList1){
            sid.add(ss.id);
        }
        List<CSS_Claims__c> cc=new List<CSS_Claims__c>();
        CSS_Claims__c claim = new CSS_Claims__c();
        claim.Customer_Name__c='Gopal';
        claim.Customer_Code__c='123';
        claim.Status__c='Draft';
        claim.Actual_Technician_Time__c=1.2;
        claim.Account__c = acc.id;
        cc.add(claim);
        insert cc;
        
        apexpages.currentPage().getparameters().put('id',Claim.id); 
        id cid=apexpages.currentPage().getparameters().get('id');
        system.assert(cid!=null);
        CG_CL_ClaimsSRTRepController p = new CG_CL_ClaimsSRTRepController();
        CG_CL_ClaimsSRTRepController.srtWrapper cmp =new  CG_CL_ClaimsSRTRepController.srtWrapper();
        List<CG_CL_ClaimsSRTRepController.srtWrapper> lstcmp = new List<CG_CL_ClaimsSRTRepController.srtWrapper>();
        
        CG_CL_ClaimsSRTRepController.sortWrapper srtdata=new CG_CL_ClaimsSRTRepController.sortWrapper(cmp);
        List<CG_CL_ClaimsSRTRepController.sortWrapper> ss=new List<CG_CL_ClaimsSRTRepController.sortWrapper>();
        ss.add(srtdata);
        p.repListWrap=ss;
        srtdata.compareTo(srtdata);
        cmp.solTitle='Test';
        cmp.solNum='1234';
        cmp.srtCheckBox=True;
        cmp.accessSrtCheckBox=True;
        cmp.sId=null;
        
        cmp.failcode='';
        cmp.srtType='';
        cmp.fautCodeName='';
        cmp.symptomName='';
        cmp.AccessCodeSaved='';
        cmp.SRTAccessCode='';
        
        
        cmp.AccessCode='testData';
        cmp.accountcode='';
        cmp.srtID= '00-901-10';
        
        cmp.srtDescription='';
        cmp.quantity=10;
        
        cmp.srtTime=null;
        cmp.srtAccessTime=null;
        cmp.srtWarrantable='';
        cmp.selectedRecord=true;
        cmp.accTime='';
        
        cmp.accTimeDec=null;
        cmp.ClaimedHrs=null;
        cmp.IsPopUpSRT=True;
        cmp.sortOrder=null; 
        p.CID=cc[0].id;
        lstcmp.add(cmp);
        p.saveRepData();
        Test.stopTest();
    }
    
}