objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to Store Region Value based on SP code</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Used to store Territory value based on SP code</description>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/css_header_nav__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting for determining header Navigation</description>
    <fields>
        <fullName>RSWButtonEnable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To Enable RSW Button in Repair Review and Warranty Control Number in Job Overview section.</description>
        <label>RSWButtonEnable</label>
        <type>Checkbox</type>
    </fields>
    <label>css header nav</label>
</CustomObject>

objects/CSS_PSN__c.object
<CustomObject>
    <description>To handle multiple ESN scenarios with respect to Claims</description>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS PSNs</relationshipLabel>
        <relationshipName>CSS_PSNs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Multi_PSN_Claim__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Multi PSN Claim for manual claim</description>
        <label>Multi - PSN Claim</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS PSN</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS PSNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>AccountCodeEdit__c</fullName>
        <label>AccountCodeEdit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountCodeType__c</fullName>
        <label>AccountCodeType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountCode__c</fullName>
        <label>AccountCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <description>Action Selected by Technician during repair</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Replace</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charlength__c</fullName>
        <defaultValue>false</defaultValue>
        <description>turns true if the length of the component name is more than 80 characters</description>
        <label>Charlength</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Claim_FailCode__c</fullName>
        <description>Created field to hold failcode for claims from failure popup</description>
        <formula>TRIM(LEFT(System_Code__c, 2)) + TRIM(LEFT(Component_Code__c, 2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClaimFailCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <description>Captures the Component or Failure ID for the Repair</description>
        <label>Component Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveredPartsQty__c</fullName>
        <label>CoveredPartsQty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of Parts used in Repair</description>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected_Component__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected Component</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solutions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Solutions linked to the Component</description>
        <label>CSS Solutions</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>Failure Selected By Technician</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A field to differentiate Camp,TRP &amp; ATCs from Solution Component</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <description>This field is the case Id from EDS.</description>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Notes__c</fullName>
        <label>Diagnostic Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Response__c</fullName>
        <description>Values for Verification</description>
        <label>Diagnostic Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not the solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Repair_Notes__c</fullName>
        <label>Repair Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Repair_Response__c</fullName>
        <label>Repair Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair Successful.</fullName>
                </value>
                <value>
                    <fullName>Repair Successful with additional parts/procedures.</fullName>
                </value>
                <value>
                    <fullName>Repair performed but didnot resolve the root cause.</fullName>
                </value>
                <value>
                    <fullName>Repair not performed.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <description>It’s a solution Id obtained from EDS.</description>
        <label>Solution Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CG_CL_ClaimsWarranty_Test.cls
/**********************************************************************
Name:CG_CL_ClaimsWarranty_Test
Copyright Â© 2018  Cummins
===============================================================
===============================================================
Purpose:                                                            
-------  
this is test class for CG_CL_ClaimsWarranty Controller.
===============================================================
===============================================================
History                                                            
-------                                                            
VERSION    AUTHOR                      DATE                DETAIL                                 
1.0 -      Rajasekhar Hindupur      02/14/2018           INITIAL DEVELOPMENT                    
***********************************************************************/
@isTest(seealldata=true)
public class CG_CL_ClaimsWarranty_Test{
    public static Testmethod void CG_CL_ClaimsWarranty_Method(){
        test.startTest();
        
        String grpName = 'CQ'+'-'+'12345-12345';
        Group testQue = new Group(Name=grpName, type='Queue');
        insert testQue;
        system.runas(new User(Id=UserInfo.getUserId()))
        { 
            QueueSObject tq = new QueueSObject(SobjectType='CSS_Claims__c', QueueId=testQue.Id);
            insert tq;
        
        string cId;
        //css_job_order__c jo = css_testdata.createJobOrder(true);
        //CSS_claims__c claims = css_testdata.createclaims(true,jo.id);
        Account Acc = new Account();
        Acc.Name = 'Test Account';
        Acc.Region__c = 'NORTH AMERICA';
        Acc.Territory__c = 'UNITED STATES';
        Acc.IAM_Service_Provider_Code__c = '12345';
        Acc.CSS_DistributorCode__c = '12345';
        
        insert Acc;
        css_header_nav__c ch = new css_header_nav__c(SetupOwnerId = UserInfo.getUserId(), Name = 'Ritesh');
            ch.RSWButtonEnable__c = true;
            insert ch;
        CSS_Claims__c claims = new CSS_Claims__c();
        claims.Status__c='Submitted';
        claims.ESN__c='79462880';
        claims.Customer_Name__c='BRITESTONE COLONY';
        claims.Customer_Code__c='123';
        claims.Location_Code__c='12345-12345';
        claims.Multi_PSN_Claim__c=true;
            claims.FieldActionWebServiceResult__c='Error';
        insert claims;
      /*  CSS_Solutions__c solAdd = new CSS_Solutions__c();
        solAdd.Case_Name__c = 'Additional SRTS';
        solAdd.Solution_Title__c='Additional SRTS';
        solAdd.Name='TestSRTS'+Math.random();
        solAdd.Diagnostic_Response__c ='Most likely the solution';
        solAdd.Diagnostic_notes__c = 'solutions diagnostic notes';
        solAdd.Repair_Notes__c = 'Repair Notes';
        solAdd.Repair_Response__c = 'Repair Successful.';
        solAdd.Rank__c = 3;
        insert soladd;*/
        List<CSS_Solution_Component__c> solComps=new List<CSS_Solution_Component__c>();
        CSS_Solution_Component__c AddsolComp = new CSS_Solution_Component__c();
        AddsolComp.Component_Id__c ='F0051000';
        AddsolComp.Action__c = 'Repair';
        //AddsolComp.Solutions__c = solAdd;
        AddsolComp.Quantity__c = 4;
        AddsolComp.type__c='CAM';
        AddsolComp.CSS_Claims__c=claims.id;
        AddsolComp.Selected_Component__c = True;
        AddsolComp.AccountCode__c = 'Test-AccountCode';
        AddsolComp.AccountCodeEdit__c = 'Test-ACEdit';
        AddsolComp.CoveredPartsQty__c = null;
        AddsolComp.AccountCodeType__c='ASAS';
        AddsolComp.Charlength__c = true;
        AddsolComp.Name = 'Test'+Math.random();
        AddsolComp.Type__c='ATC';
        AddsolComp.Status__c = 'Approved';
        // solcomp.Claim_FailCode__c=
        AddsolComp.Selected_Component__c=true;
        AddsolComp.AccountCodeType__c='Test-AccountCode2';
        AddsolComp.AccountCodeEdit__c = 'Test-AccountCode';
        AddsolComp.AccountCode__c = 'Test-AccountCode1';
        upsert AddsolComp;
        solComps.add(AddsolComp);
        //insert solComps;
        CSS_PSN__c psn=css_testdata.createpsn(true,claims.id);
        //system.debug('JO ID---'+JO.ID);
        //cId=ApexPages.CurrentPage().getParameters().get('id');
        //PageReference pageRef = new PageReference('/apex/CG_ClaimsWarranty?id=');
        PageReference pageRef = Page.CG_ClaimsWarranty;
        pageRef.getParameters().put('id', claims.Id);
        Test.setCurrentPage(pageRef); 
        
        //String id = ApexPages.currentPage().getParameters().get('id');
        CG_CL_ClaimsWarranty claimsWar = new CG_CL_ClaimsWarranty();
        css_utility.getRegionTerritory('12345-12345');
        PageReference pageRef1=claimsWar.nvClaimsIntake();
        PageReference pageRef2=claimsWar.nvClaimsVH();
        PageReference pageRef3=claimsWar.nvClaimsCC();
        PageReference pageRef4=claimsWar.nvClaimsFC();
        PageReference pageRef5=claimsWar.nvClaimsPOC();
        PageReference pageRef6=claimsWar.nvClaimsSRTs();
        PageReference pageRef7=claimsWar.nvClaimsJobNotes();
        PageReference pageRef8=claimsWar.nvClaimsVS();
        PageReference pageRef9=claimsWar.nvClaimsPSN();
        claimsWar.pgSave();
        claimsWar.nvClaimsMulti_PSN();
        test.stopTest();
    }
    }
    }