objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to Store Region Value based on SP code</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Used to store Territory value based on SP code</description>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Model__c</fullName>
        <defaultValue>&quot;NONCUMMINS&quot;</defaultValue>
        <label>Service Model</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_PSN__c</fullName>
        <externalId>true</externalId>
        <label>Type-PSN</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engines</fullName>
                    <default>true</default>
                    <label>Engines</label>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>FIREPUMP</fullName>
                </value>
                <value>
                    <fullName>ENGINE</fullName>
                </value>
                <value>
                    <fullName>GENSET</fullName>
                </value>
                <value>
                    <fullName>ENGINE CORE</fullName>
                </value>
                <value>
                    <fullName>SWITCH GEAR</fullName>
                </value>
                <value>
                    <fullName>TRANSFER SWITCH</fullName>
                </value>
                <value>
                    <fullName>TRANSMISSIONS</fullName>
                </value>
                <value>
                    <fullName>BATTERY</fullName>
                </value>
                <value>
                    <fullName>PARSYS</fullName>
                </value>
                <value>
                    <fullName>MARINE GEAR</fullName>
                </value>
                <value>
                    <fullName>ONAN</fullName>
                </value>
                <value>
                    <fullName>REFRIG</fullName>
                </value>
                <value>
                    <fullName>KOMATSU EQUIPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Integration_Details__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting used to store Integration Connection details</description>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Type__c</fullName>
        <label>Method Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passcode__c</fullName>
        <label>Passcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSS_Integration_Details</label>
</CustomObject>

objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>AccountCodeEdit__c</fullName>
        <label>AccountCodeEdit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountCodeType__c</fullName>
        <label>AccountCodeType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountCode__c</fullName>
        <label>AccountCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <description>Action Selected by Technician during repair</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Replace</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charlength__c</fullName>
        <defaultValue>false</defaultValue>
        <description>turns true if the length of the component name is more than 80 characters</description>
        <label>Charlength</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <description>Captures the Component or Failure ID for the Repair</description>
        <label>Component Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoveredPartsQty__c</fullName>
        <label>CoveredPartsQty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FSL Service Job</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Failures Added</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FailCode_Formula__c</fullName>
        <formula>IF( Fail_Code__c != null , ( Name +&quot;-&quot; +Fail_Code__c) , Fail_Code_Editable__c)</formula>
        <label>FailCode Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fail_Code_Editable__c</fullName>
        <description>Fail code formula field is empty, user can enter and save the fail code that code saved into this field.</description>
        <label>Fail Code Editable</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fail_Code__c</fullName>
        <formula>IF(BEGINS (System_Code__c, &quot;W&quot;), TRIM(LEFT(System_Code__c, 2)) + TRIM(LEFT(Component_Code__c, 2))+ TRIM(LEFT(Failure_Mode__c, 2)), TRIM(LEFT(System_Code__c, 2)) + TRIM(LEFT(Component_Code__c, 2)) )</formula>
        <label>Fail Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of Parts used in Repair</description>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected_Component__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected Component</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Model__c</fullName>
        <formula>IF( Service_Job__c&lt;&gt; null , Service_Job__r.Service_Model__c,  CSS_Claims__r.Service_Model__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solutions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Solutions linked to the Component</description>
        <label>CSS Solutions</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>Failure Selected By Technician</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A field to differentiate Camp,TRP &amp; ATCs from Solution Component</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <description>This field is the case Id from EDS.</description>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Notes__c</fullName>
        <label>Diagnostic Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Response__c</fullName>
        <description>Values for Verification</description>
        <label>Diagnostic Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not the solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FSL Service Job</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Solutions History</relationshipLabel>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FaultCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Fault Code</label>
        <referenceTo>CSS_Fault_Code__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Repair_Notes__c</fullName>
        <label>Repair Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Repair_Response__c</fullName>
        <label>Repair Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair Successful.</fullName>
                </value>
                <value>
                    <fullName>Repair Successful with additional parts/procedures.</fullName>
                </value>
                <value>
                    <fullName>Repair performed but didnot resolve the root cause.</fullName>
                </value>
                <value>
                    <fullName>Repair not performed.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Model__c</fullName>
        <formula>Service_Job__r.Service_Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <description>It’s a solution Id obtained from EDS.</description>
        <label>Solution Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>FSL_Service_Territory_Code__c</fullName>
        <description>Territory Code of the Service Location</description>
        <inlineHelpText>Territory Code of the Service Location</inlineHelpText>
        <label>Service Territory Code</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <label>Location Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DEALER</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-BRANCH</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-HEADQUARTERS</fullName>
                </value>
                <value>
                    <fullName>GROUP</fullName>
                </value>
                <value>
                    <fullName>HOLSET - DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>INDUSTRIAL/VOCATIONAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FSLTestDataSetupCls.cls
public class FSLTestDataSetupCls { 
    public static Account createAccountData()
    {
        Id accRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
        Account a = new Account(name='testFSL');
        a.RecordTypeId = accRecId;
        a.BillingStreet = 'test billing Street';
		a.BillingPostalCode = '47201';
		a.BillingCity = 'test city';
		a.BillingState = 'Texas';
		a.BillingCountry = 'United States';
        insert a;
        return a;
    }
    public static Asset createAssetRecord()
    {
        Asset ast = new Asset(name='Assst1',Type_PSN__c='aset1223',Service_Model__c='testmodel');
        insert ast;
        return ast;
    }
    public static WorkOrder createWorkOrder(asset ast, account a)
    {
        WorkOrder wo=new WorkOrder(accountid=a.id, assetid=ast.id);
        insert wo;
        return wo;
    }
    public static string returnAppCode(asset ast, account a)
    {
        WorkOrder wo=new WorkOrder(accountid=a.id, assetid=ast.id);
        insert wo;
        return wo.Application__c;
    }
   
    public static WorkOrder createWorkOrder(asset ast, account a, ServiceTerritory st)
    {
        WorkOrder wo=new WorkOrder(AccountId=a.id, assetid=ast.id, serviceterritoryId=st.Id);
        wo.Application__c = '130 - AUTOMOTIVE';
        wo.FSL_Application_Error_Message__c = '';
        insert wo;
        return wo;
    }
    
   
    
    
    //Method to create CSS_Solutions__c 
    public static CSS_Solutions__c createSolutions(boolean isInsert,Id woId){
        CSS_Solutions__c solAdd = new CSS_Solutions__c();
        solAdd.FSL_Service_Job__c = woId;
        solAdd.Case_Name__c = 'Additional SRTS';
        solAdd.Solution_Title__c='Additional SRTS';
        
        solAdd.Name='TestSRTS'+Math.random();
        solAdd.Diagnostic_Response__c ='Most likely the solution';
        solAdd.Diagnostic_notes__c = 'solutions diagnostic notes';
        solAdd.Repair_Notes__c = 'Repair Notes';
        //solAdd.FaultCode__c = 'solution faultcode';
        //solAdd.Repair_Response__c = 'Most likely ';
        solAdd.Repair_Response__c = 'Repair Successful.';
        solAdd.Rank__c = 3;
        if(isInsert){
            insert solAdd;
        }
        return solAdd;
    }
    //Method to create  
    public static  CSS_Solution_Component__c createSRT(boolean isInsert,Id jobId,Id solAdd){
        
        CSS_Solution_Component__c AddsolComp = new CSS_Solution_Component__c();
        AddsolComp.Component_Id__c ='F0051000';
        AddsolComp.FSL_Service_Job__c = jobId;
        AddsolComp.Action__c = 'Repair';
        AddsolComp.Solutions__c = solAdd;
        AddsolComp.Quantity__c = 4;
        AddsolComp.type__c='CAM';
        //AddsolComp.
        AddsolComp.Selected_Component__c = True;
        AddsolComp.AccountCode__c = 'Test-AccountCode';
        AddsolComp.AccountCodeEdit__c = 'Test-ACEdit';
        AddsolComp.CoveredPartsQty__c = null;
        AddsolComp.AccountCodeType__c='ASAS';
        AddsolComp.Fail_Code_Editable__c='CAM-campaign';
        //Addsolcomp.Part_Assignment__c ='Primary';
        //AddsolComp.Fail_Code__c ='Test-FAilcode';
        //  AddsolComp.FailCode_Formula__c = 'Test-FailCode';   Field is not writeable
        AddsolComp.Charlength__c = true;
        AddsolComp.Name = 'Test'+Math.random();
        if(isInsert)
        {
            insert AddsolComp;
        }
        return AddsolComp;
    }
    
    public static ServiceTerritory createServiceTerritory()
    {
        Operatinghours oh=new operatinghours(name='test');
        insert oh;
        ServiceTerritory st = new ServiceTerritory();
        st.City='Test City Mobile';
        //st.Country='United States';
        st.CountryCode='US';
        st.PostalCode='12345';
        st.State='Alabama';
        st.Name='Test Territory1 Mobile';
        st.Location_Code__c='abacc';
        st.OperatingHoursId=oh.id;
        st.IsActive=true;
        st.FSL_Service_Territory_Code__c='ABCX';
        st.Region__c = 'AUSTRALIA/ NEW ZEALAND';
        st.Territory__c = 'AUSTRALIA';
        insert st;
        return st;
    }
    public static list<CSS_Integration_Details__c> createIntegrationConfigs()
    {
        List<CSS_Integration_Details__c> cssIntDets = new List<CSS_Integration_Details__c>();
        CSS_Integration_Details__c conDetails = new CSS_Integration_Details__c();
        conDetails.End_Point__c = 'https//test.com/getTokenQSOL';
        conDetails.Passcode__c = 'Admin';
        conDetails.Username__c = 'Admin';
        conDetails.Name = 'FSL_GetApiToken_QSOL';
        cssIntDets.add(conDetails);
        
        CSS_Integration_Details__c conDetails1 = new CSS_Integration_Details__c();
        conDetails1.End_Point__c = 'https//test.com/getProcedureLink';
        conDetails1.Passcode__c = 'Admin';
        conDetails1.Username__c = 'Admin';
        conDetails1.Name = 'FSL_QSOL_ProcedureLink'; 
        cssIntDets.add(conDetails1);
        
        CSS_Integration_Details__c conDetails2 = new CSS_Integration_Details__c();
        conDetails2.End_Point__c = 'https//test.com/getFCOverview';
        conDetails2.Passcode__c = 'Admin';
        conDetails2.Username__c = 'Admin';
        conDetails2.Name = 'FSL_QSOL_FCOverview'; 
        cssIntDets.add(conDetails2);
        
        CSS_Integration_Details__c conDetails3 = new CSS_Integration_Details__c();
        conDetails3.End_Point__c = 'https//test.com/getServiceHistory';
        conDetails3.Passcode__c = 'Admin';
        conDetails3.Username__c = 'Admin';
        conDetails3.Name = 'FSL_MoveX_ServiceHistory'; 
        cssIntDets.add(conDetails3);
        
        CSS_Integration_Details__c conDetails4 = new CSS_Integration_Details__c();
        conDetails4.End_Point__c = 'https//test.com/getRetrieveOptionList';
        conDetails4.Passcode__c = 'Admin';
        conDetails4.Username__c = 'Admin';
        conDetails4.Name = 'FSL_QSOL_RetrieveOptionList'; 
        cssIntDets.add(conDetails4);
        conDetails = new CSS_Integration_Details__c();
        conDetails.End_Point__c = 'https//test.com/getTokenQSOL';
        conDetails.Passcode__c = 'Admin';
        conDetails.Username__c = 'Admin';
        conDetails.Name = 'FSL_QSOL_Getwarrantydocs';
        cssIntDets.add(conDetails); 
        conDetails = new CSS_Integration_Details__c();
        conDetails.End_Point__c = 'https//test.com/getTokenQSOL';
        conDetails.Passcode__c = 'Admin';
        conDetails.Username__c = 'Admin';
        conDetails.Name = 'GetPartsListSRT';
        cssIntDets.add(conDetails); 
        conDetails = new CSS_Integration_Details__c();
        conDetails.End_Point__c = 'https//test.com/getTokenQSOL';
        conDetails.Passcode__c = 'Admin';
        conDetails.Username__c = 'Admin';
        conDetails.Name = 'FSLAccessibilityChecklistToken';
        cssIntDets.add(conDetails); 
        conDetails = new CSS_Integration_Details__c();
        conDetails.End_Point__c = 'https//test.com/getTokenQSOL';
        conDetails.Passcode__c = 'Admin';
        conDetails.Username__c = 'Admin';
        conDetails.Name = 'CG_GETDiagnosticSRT';
        conDetails.Method_Type__c='Get';
        conDetails.IsActive__c=true;
        conDetails.Key__c='test key1';
        cssIntDets.add(conDetails); 
        conDetails = new CSS_Integration_Details__c();
        conDetails.End_Point__c = 'https//test.com/getTokenQSOL';
        conDetails.Name = 'OAGOAuth';
        conDetails.Method_Type__c='Get';
        conDetails.IsActive__c=true;
        conDetails.Key__c='Kl2WdTIi8i4N55jezpTYGOi5gZ6vXRk/EDxzdcIj47g=';
        conDetails.Passcode__c='STbLSzIQhyVioY0Nt0j8fxsjsdBNjq2NyZLSOtfzgfgMjP5aCKnVK1kCmvl/d0unQKi0DMYXf92Mx5C20l6SVA=='; 
        conDetails.Username__c='wiYlq3UEFXo5AdO/D4p5II75P/I83y1hKcDoPHmCt0Mg0lbS9S1/LFCJenCA6qa2xIvQq9N7VfFPQKt6Vi9XiA==';
        cssIntDets.add(conDetails); 
        conDetails = new CSS_Integration_Details__c();
        conDetails.End_Point__c = 'https//test.com/getTokenQSOL';
        conDetails.Name = 'CSS_SBL_WarrantyDetailCoverage';
        conDetails.Method_Type__c='Get';
        conDetails.IsActive__c=true;
        conDetails.Key__c='Kl2WdTIi8i4N55jezpTYGOi5gZ6vXRk/EDxzdcIj47g=';
        conDetails.Passcode__c='STbLSzIQhyVioY0Nt0j8fxsjsdBNjq2NyZLSOtfzgfgMjP5aCKnVK1kCmvl/d0unQKi0DMYXf92Mx5C20l6SVA=='; 
        conDetails.Username__c='wiYlq3UEFXo5AdO/D4p5II75P/I83y1hKcDoPHmCt0Mg0lbS9S1/LFCJenCA6qa2xIvQq9N7VfFPQKt6Vi9XiA==';
        cssIntDets.add(conDetails); 
        
        cssIntDets.add(new CSS_Integration_Details__c(name='CG_GETAllSRT',End_Point__c='https://test.url.com',Method_Type__c='Get',Timeout__c=1200));
        insert cssintdets;
        return cssintdets;
    }
    
    public static IAM_CDH_Cross_references__c createSite(Id accId)
    {
        IAM_CDH_Cross_references__c site = new IAM_CDH_Cross_references__c(IAM_Account__c=accId,
                                                                           FSL_City__c='Test City',
                                                                           FSL_Country__c='Australia',
                                                                           FSL_State__c='Queensland',
                                                                           FSL_Site_Status__c='Active'
                                                                          );
        insert site;
        return site;
    }
}