objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_Parts_Options__c.object
<CustomObject>
    <description>To store Parts and Options. Created Record type</description>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS Parts Options</relationshipLabel>
        <relationshipName>CSS_Parts_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fail_Code__c</fullName>
        <label>Fail Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnToFactory__c</fullName>
        <label>ReturnToFactory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReturnWaiver__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ReturnWaiver</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Parts Options</relationshipLabel>
        <relationshipName>CSS_Parts_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Select One</fullName>
                    <default>true</default>
                    <label>Select One</label>
                </value>
                <value>
                    <fullName>Lodging</fullName>
                </value>
                <value>
                    <fullName>Meals</fullName>
                </value>
                <value>
                    <fullName>Non Commercial-Travel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS Parts Options</label>
    <nameField>
        <label>CSS Parts Options Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Parts Options</pluralLabel>
    <recordTypes>
        <fullName>Options</fullName>
        <active>true</active>
        <description>Store Options</description>
        <label>Options</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parts</fullName>
        <active>true</active>
        <description>To store Parts</description>
        <label>Parts</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>AccountCodeEdit__c</fullName>
        <label>AccountCodeEdit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Code</label>
        <referenceTo>FSL_Account_Code__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CampaignLaborPercentage__c</fullName>
        <label>CampaignLaborPercentage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fail_Code_Editable__c</fullName>
        <description>Fail code formula field is empty, user can enter and save the fail code that code saved into this field.</description>
        <label>Fail Code Editable</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fail_Code__c</fullName>
        <formula>IF(BEGINS (System_Code__c, &quot;W&quot;), TRIM(LEFT(System_Code__c, 2)) + TRIM(LEFT(Component_Code__c, 2))+ TRIM(LEFT(Failure_Mode__c, 2)), TRIM(LEFT(System_Code__c, 2)) + TRIM(LEFT(Component_Code__c, 2)) )</formula>
        <label>Fail Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Job for this Component</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A field to differentiate Camp,TRP &amp; ATCs from Solution Component</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup for Service Job object that stores the  Job order number associated with it.</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_SRT__c.object
<CustomObject>
    <fields>
        <fullName>Account_Code__c</fullName>
        <label>Account Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRT_Category__c</fullName>
        <label>SRT Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_ID__c</fullName>
        <label>SRT ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diagnosis</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Diag Access</fullName>
                </value>
                <value>
                    <fullName>Repair Access</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>99Time</fullName>
                </value>
                <value>
                    <fullName>Overlap</fullName>
                </value>
                <value>
                    <fullName>Field Action</fullName>
                </value>
                <value>
                    <fullName>Field Action Access</fullName>
                </value>
                <value>
                    <fullName>BMS SRT</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS SRT</label>
    <nameField>
        <label>CSS SRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS SRTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CG_CL_UpdatePartReturnFlagJobs_Test.cls
@istest
public class CG_CL_UpdatePartReturnFlagJobs_Test 
{
  
    CG_CL_UpdatePartReturnToCenterFlagJobs updjobs = new CG_CL_UpdatePartReturnToCenterFlagJobs();
    
    static testmethod void M1()
    {
        
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466'; 
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        //SRT LIST
        List<CSS_SRT__c> srtlist = new List<CSS_SRT__c>();
        
        //Create Job
        CSS_Job_Order__c testjob=CSS_TestData.createJobOrder(false);
        testjob.Account__c=acc.id;
        insert testjob;
        String stestjobid=String.valueOf(testjob.id);
       
        //Create Sol Data
        CSS_Solutions__c sol=CSS_TestData.createSolutions(true,testjob.id);
        
        //Create Sol Comp Data       
        CSS_Solution_Component__c solcom1= CSS_TestData.createSRT(false,null,sol.id);

        CSS_Solution_Component__c solcom2= CSS_TestData.createSRT(false,null,sol.id);  

        list<CSS_Solution_Component__c> solcomplist=new list<CSS_Solution_Component__c>();
        solcomplist.add(solcom1);
        solcomplist.add(solcom2);
        insert solcomplist;
        
        //Create Parts options list
        CSS_Parts_Options__c parts1= CSS_TestData.createParts(false,testjob.id,solcomplist[0].id,sol.id);
        parts1.ReturnToFactory__c = 'Y';
        parts1.ReturnWaiver__c=false;
        parts1.Service_Job__c=testjob.id;
        parts1.Fail_Code__c='ABBC-ASD';
        parts1.Account_Code__c='CAMPAIGN 65';
        CSS_Parts_Options__c parts2= CSS_TestData.createParts(false,testjob.id,solcomplist[1].id,sol.id);
        parts2.ReturnWaiver__c=true;
        parts2.ReturnToFactory__c = 'Y';
        parts2.Service_Job__c=testjob.id;
        parts2.Fail_Code__c='ABC-ASD';
        parts2.Account_Code__c='CHINA JV POLICY JV';
        list<CSS_Parts_Options__c> polist=new list<CSS_Parts_Options__c>();
        polist.add(parts1);
        polist.add(parts2);
        insert polist;
        
        //Create SRT Object (RTF=Y AND EXCEPTION)
        CSS_SRT__c SrtRec1=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec1.SRT_ID__c = '00-10S-00';
        SrtRec1.Type__c = 'Admins';
        SrtRec1.CSS_Claims__c=null;
        SrtRec1.Job_Order__c=testjob.id;
        insert SrtRec1;
        
        CSS_SRT__c SrtRec2=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec2.SRT_Category__c = 'AdditionalDiag';
        SrtRec2.SRT_ID__c = '00-10S-00';
        SrtRec2.Type__c = 'Admins';
        SrtRec2.Job_Order__c=testjob.id;
        insert SrtRec2;

        CSS_SRT__c SrtRec3=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec3.SRT_Category__c = 'AdditionalDiag';
        SrtRec3.Type__c = 'Admins';
        SrtRec3.SRT_ID__c = '00-10S-00';
        SrtRec3.Job_Order__c=testjob.id;
        insert SrtRec3;
        
        CSS_SRT__c SrtRec4=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec4.SRT_ID__c = '00-10S-00';
        SrtRec4.Type__c = 'Admins';
        SrtRec4.CSS_Claims__c=null;
        SrtRec4.Job_Order__c=testjob.id;
        insert SrtRec4;
       
        //Create SRT List
        srtlist.add(SrtRec1); 
        srtlist.add(SrtRec2);
        srtlist.add(SrtRec3);
        srtlist.add(SrtRec4);
        
        //Dummy string
        list<String> stringList1 = new list<String>();
        string s='Y;;'+'true;;'+stestjobid+';;True';
        stringList1.add(s);
        system.debug('The Dummy string is'+stringList1);
         
        //Call the method to verify
        srtlist = CSS_WS_SRT.getAllClaimsDigRepSRTs(testjob.id,'Admin');
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
    CG_CL_UpdatePartReturnToCenterFlagJobs.CreateAdminSRTforJobs(stringList1);
        
        //Call the method to verify 
        list<String> stringList2 = new list<String>();
        string s1='N;;'+'false;;'+stestjobid+';;True';
        stringList2.add(s1);
        system.debug('The Dummy string is'+stringList2);
       
    //Call the method to verify
        srtlist = CSS_WS_SRT.getAllClaimsDigRepSRTs(testjob.id,'Admin');
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
    CG_CL_UpdatePartReturnToCenterFlagJobs.CreateAdminSRTforJobs(stringList1);
    }    
    static testmethod void M2()
        
    {
        
        
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466'; 
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;//SRT LIST
        List<CSS_SRT__c> srtlist = new List<CSS_SRT__c>();
        
        //Create Job
        CSS_Job_Order__c testjob=CSS_TestData.createJobOrder(false);
        testjob.Account__c=acc.id;
        insert testjob;
        String stestjobid=String.valueOf(testjob.id);
       
        //Create Sol Data
        CSS_Solutions__c sol=CSS_TestData.createSolutions(true,testjob.id);
        
        list<CSS_Solution_Component__c> solcomplist=new list<CSS_Solution_Component__c>();
        
        //Create Sol Comp Data       
        CSS_Solution_Component__c solcom1= CSS_TestData.createSRT(false,null,sol.id);
		solcom1.Type__c='CAM';
        solcom1.CampaignLaborPercentage__c = '9000099';
        solcom1.AccountCodeEdit__c = 'AccountEdit';
        solcom1.Fail_Code_Editable__c = 'FailEdit';
        //insert solcom1;
        CSS_Solution_Component__c solcom2= CSS_TestData.createSRT(false,null,sol.id);  
          solcom1.Type__c='CAM';
        solcom1.CampaignLaborPercentage__c = '900009';
        solcom1.AccountCodeEdit__c = 'Account';
        solcom1.Fail_Code_Editable__c = 'Fail';

        solcomplist.add(solcom1);
        solcomplist.add(solcom2);
        insert solcomplist;
        
        //Create Parts options list
        CSS_Parts_Options__c parts1= CSS_TestData.createParts(false,testjob.id,solcomplist[0].id,sol.id);
        parts1.ReturnToFactory__c = 'Y';
        parts1.ReturnWaiver__c=false;
        parts1.Service_Job__c=testjob.id;
        parts1.Fail_Code__c='ABBC-ASD';
        parts1.Account_Code__c='CAMPAIGN 65';
        CSS_Parts_Options__c parts2= CSS_TestData.createParts(false,testjob.id,solcomplist[1].id,sol.id);
        parts2.ReturnWaiver__c=true;
        parts2.ReturnToFactory__c = 'Y';
        parts2.Service_Job__c=testjob.id;
        parts2.Fail_Code__c='ABC-ASD';
        parts2.Account_Code__c='CHINA JV POLICY JV';
        list<CSS_Parts_Options__c> polist=new list<CSS_Parts_Options__c>();
        polist.add(parts1);
        polist.add(parts2);
        insert polist;
        
        //Create SRT Object (RTF=Y AND EXCEPTION)
        CSS_SRT__c SrtRec1=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec1.SRT_ID__c = '00-10S-00';
        SrtRec1.Type__c = 'Admins';
        SrtRec1.CSS_Claims__c=null;
        SrtRec1.Job_Order__c=testjob.id;
        insert SrtRec1;
        
        CSS_SRT__c SrtRec2=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec2.SRT_Category__c = 'AdditionalDiag';
        SrtRec2.SRT_ID__c = '00-10S-00';
        SrtRec2.Type__c = 'Admins';
        SrtRec2.Job_Order__c=testjob.id;
        insert SrtRec2;

        CSS_SRT__c SrtRec3=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec3.SRT_Category__c = 'AdditionalDiag';
        SrtRec3.Type__c = 'Admins';
        SrtRec3.SRT_ID__c = '00-10S-00';
        SrtRec3.Job_Order__c=testjob.id;
        insert SrtRec3;
        
        CSS_SRT__c SrtRec4=CSS_TestData.createSRT_New(false,'string typ',sol.Id,testjob.Id,null);
        SrtRec4.SRT_ID__c = '00-10S-00';
        SrtRec4.Type__c = 'Admins';
        SrtRec4.CSS_Claims__c=null;
        SrtRec4.Job_Order__c=testjob.id;
        insert SrtRec4;
       
        //Create SRT List
        srtlist.add(SrtRec1); 
        srtlist.add(SrtRec2);
        srtlist.add(SrtRec3);
        srtlist.add(SrtRec4);
        
        //Dummy string
        list<String> stringList1 = new list<String>();
        string s='N;;'+'true;;'+stestjobid+';;True';
        stringList1.add(s);
        system.debug('The Dummy string is'+stringList1);
         
        //Call the method to verify
        srtlist = CSS_WS_SRT.getAllClaimsDigRepSRTs(testjob.id,'Admin');
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        CG_CL_UpdatePartReturnToCenterFlagJobs.CreateAdminSRTforJobs(stringList1);
        delete polist;
        CG_CL_UpdatePartReturnToCenterFlagJobs.CreateAdminSRTforJobs(stringList1);
        CG_CL_UpdatePartReturnToCenterFlagJobs.callAdminSRT(testjob.id,'Admin','ABC-ASD','CHINA JV POLICY JV','test',solcom1.id);
        
        
    }
 }