objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bolt_Acc_Site_Reference__c</fullName>
        <label>Bolt Acc Site Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bolt_BC_Code__c</fullName>
        <label>Bolt_BC_Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertex_Customer_Class_Code__c</fullName>
        <label>Vertex Customer Class Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_Invoice__c.object
<CustomObject>
    <description>Invoice main object.  The invoice represents object against which payments may be made.</description>
    <fields>
        <fullName>ccrz__CCOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order to which this invoice applies (optional).</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Invoices</relationshipLabel>
        <relationshipName>CCInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__CurrencyCode__c</fullName>
        <description>B2B Commerce currency code.</description>
        <label>Currency Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__OriginalAmount__c</fullName>
        <description>The original amount of the invoice. Once set this should not be changed. Could be negative or positive.</description>
        <label>Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Terms__c</fullName>
        <description>The payment terms of the invoice, e.g. Net 15.</description>
        <label>Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Invoice</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>CC Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this order was placed for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderDate__c</fullName>
        <description>The date of the order.</description>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderNumber__c</fullName>
        <description>Derived from the SFDC Name field as the digit portion of the order Name + 1000000.</description>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
    <description>Transaction payments represent payments made to the system.</description>
    <fields>
        <fullName>Bolt_AR_Call_Status__c</fullName>
        <label>Bolt AR Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bolt_JE_Call_Status__c</fullName>
        <label>Bolt JE Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account of the user that created this transaction payment.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Transaction Payments</relationshipLabel>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__CCOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the order this payment was applied to (optional).</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Transaction Payments</relationshipLabel>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__InvoiceAppliedFor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Invoice this payment was made for (optional).  In a summary invoice case this is the summary invoice.  For non-summary invoices this will be the same as the InvoiceAppliedTo field.</description>
        <label>Invoice Applied For</label>
        <referenceTo>ccrz__E_Invoice__c</referenceTo>
        <relationshipLabel>CC Transaction Payments For</relationshipLabel>
        <relationshipName>TransactionPaymentsFor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__InvoiceAppliedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Invoice this payment was applied to (optional).  This is the invoice that the payment was applied to.  In a summary invoice case this will be the child invoice the sub-payment was applied to.  For a non-summary case this will be the same as the applied for field.</description>
        <label>Invoice Applied To</label>
        <referenceTo>ccrz__E_Invoice__c</referenceTo>
        <relationshipLabel>CC Transaction Payments To</relationshipLabel>
        <relationshipName>TransactionPaymentsTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{0000000000}</displayFormat>
        <label>CC Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Transaction Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OSM_BOLT_SW_BusinessLayerUtility_Test.cls
/************************************************
 History
 --------
 VERSION    AUTHOR          DATE            DETAILS
 1.0        Ashish          03/03/2021      Test Class Fixes
 2.0        Ashish          05/03/2021      Test Class Fixes
 3.0        Ashish          05/03/2021      Test Class Fixes
 4.0        Ashish          05/03/2021      Test Class Fixes
 5.0        Ashish          06/03/2021      Test Class Fixes
 6.0        Ashish          12/03/2021      Test Class Fixes
 7.0        Ashish          17/03/2021      Test Class Fixes
 8.0        Ashish          24/06/2021      Test Class Fixes
 9.0        Ashish          25/06/2021      Test Class Fixes
 */
@isTest
   Public class OSM_BOLT_SW_BusinessLayerUtility_Test{
   static testmethod void testBusinessLayerUtility(){
   List<Id> id1 = new List<Id>();
   Map<Id, Id> Mapid = new Map<Id,Id>();
   Test.starttest();
   string state = 'Order Placed';
   OSM_BOLT_SW_BusinessLayerUtility.getARInvoiceServices(id1, Mapid,state);
   OSM_BOLT_SW_BusinessLayerUtility.getJournalEntryServices(id1, Mapid,state);
   Test.stoptest();
   
   } 
   
   static testmethod void testBusinessLayerUtility1(){  
       
   List<Id> id1 = new List<Id>();
   List<Id>OSMId = new List<Id>();
   Account acc = new Account();
   acc.Name = 'testName';
   acc.AccountNumber = '5555555';
   acc.Vertex_Customer_Class_Code__c = '65941515';
   acc.Bolt_BC_Code__c = 'testingcode';
   acc.Bolt_Acc_Site_Reference__c='testingcodeqq';
   insert acc;
   
   ccrz__E_Order__c ord = new ccrz__E_Order__c();
   ord.ccrz__Account__c = acc.id;
   ord.ccrz__OrderDate__c= system.today();
   ord.ccrz__OrderNumber__c = 00006;
   insert ord;
   
   list<ccrz__E_Invoice__c>incList = new list<ccrz__E_Invoice__c>();
   Map<Id, Id> Mapid = new Map<Id,Id>();   
   
   ccrz__E_Invoice__c inc = new ccrz__E_Invoice__c();
  inc.ccrz__OriginalAmount__c=52.00;
  inc.ccrz__Terms__c='testing22222';
  inc.ccrz__CurrencyCode__c='USD';
  inc.ccrz__CCOrder__c=ord.id;
  incList.add(inc);
  insert incList;
 
   incList = new list<ccrz__E_Invoice__c>();
   incList = [Select Id from ccrz__E_Invoice__c];
   
   for(ccrz__E_Invoice__c obj : incList){
       id1.add(obj.Id);
   }
   
   system.assertEquals(1,incList.size());
     
   ccrz__E_TransactionPayment__c tran = new ccrz__E_TransactionPayment__c();
   tran.ccrz__InvoiceAppliedFor__c = id1[0];
   tran.ccrz__InvoiceAppliedTo__c = id1[0];
   tran.Bolt_AR_Call_Status__c = 'Pending';
   tran.Bolt_JE_Call_Status__c = 'Pending';
   insert tran;
   
   Mapid.put(id1[0],tran.Id);
   
   Test.starttest();
   string state = 'Order Placed';
   OSM_BOLT_SW_BusinessLayerUtility.getARInvoiceServices(id1, Mapid,state);
   OSM_BOLT_SW_BusinessLayerUtility.getJournalEntryServices(id1, Mapid,state);
   Test.stoptest();
   
   }       
      static testmethod void testBusinessLayerUtility2(){
       
   List<Id> id1 = new List<Id>();
   List<Id>OSMId = new List<Id>();
   
   Account acc = new Account();
   acc.Name = 'testName';
   acc.AccountNumber = '5555555';
   acc.Vertex_Customer_Class_Code__c = '65941515';
   acc.Bolt_BC_Code__c = 'testingcode';
   acc.Bolt_Acc_Site_Reference__c='testingcodeqq';
   insert acc;
   
   ccrz__E_Order__c ord = new ccrz__E_Order__c();
   ord.ccrz__Account__c = acc.id;
   ord.ccrz__OrderDate__c= system.today();
   ord.ccrz__OrderNumber__c = 00006;
   insert ord;
   
   list<ccrz__E_Invoice__c>incList = new list<ccrz__E_Invoice__c>();
   Map<Id, Id> Mapid = new Map<Id,Id>();   
   
   ccrz__E_Invoice__c inc = new ccrz__E_Invoice__c();
  inc.ccrz__OriginalAmount__c=52.00;
  inc.ccrz__Terms__c='testing22222';
  inc.ccrz__CurrencyCode__c='MZN';
  inc.ccrz__CCOrder__c=ord.id;
  incList.add(inc);
  insert incList;
 
   incList = new list<ccrz__E_Invoice__c>();
   incList = [Select Id from ccrz__E_Invoice__c];
   
   for(ccrz__E_Invoice__c obj : incList){
       id1.add(obj.Id);
   }
   
   system.assertEquals(1,incList.size());
   
   ccrz__E_TransactionPayment__c tran = new ccrz__E_TransactionPayment__c();
   tran.ccrz__InvoiceAppliedFor__c = id1[0];
   tran.ccrz__InvoiceAppliedTo__c = id1[0];
   tran.Bolt_AR_Call_Status__c = 'Pending';
   tran.Bolt_JE_Call_Status__c = 'Pending';
   insert tran;
   
   Mapid.put(id1[0],tran.Id);
   
   Test.starttest();
   string state = 'Order Placed';
   OSM_BOLT_SW_BusinessLayerUtility.getARInvoiceServices(id1, Mapid,state);
   OSM_BOLT_SW_BusinessLayerUtility.getJournalEntryServices(id1, Mapid,state);
   OSM_BOLT_SW_BusinessLayerHandler.setARInvoiceOutboundWrapper(id1,Mapid,state,null);
   Test.stoptest();
   
   }       
}