objects/Account.object
<CustomObject>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/IAM_Application__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>Text(IAM_Account_Name__r.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is for Sharing purpose</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Features &amp; Access</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IAM_Application_Name__c</fullName>
        <label>Application Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Guidanz</fullName>
                </value>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>INSITE</fullName>
                </value>
                <value>
                    <fullName>Cummins Service Training</fullName>
                </value>
                <value>
                    <fullName>QuickServe Online</fullName>
                </value>
                <value>
                    <fullName>India ABO</fullName>
                </value>
                <value>
                    <fullName>Repair logistics and Service</fullName>
                </value>
                <value>
                    <fullName>CUMPAS 2.0</fullName>
                </value>
                <value>
                    <fullName>Marketplace</fullName>
                </value>
                <value>
                    <fullName>Connected Solutions</fullName>
                </value>
                <value>
                    <fullName>WWSPS</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Fleetguard FIT</fullName>
                </value>
                <value>
                    <fullName>NextGen</fullName>
                </value>
                <value>
                    <fullName>Rapid Serve Web</fullName>
                </value>
                <value>
                    <fullName>DBU EFSR</fullName>
                </value>
                <value>
                    <fullName>BOX External Partners</fullName>
                </value>
                <value>
                    <fullName>Mexico Warranty</fullName>
                </value>
                <value>
                    <fullName>Archer</fullName>
                </value>
                <value>
                    <fullName>Electrified Powertrain Specification Tool</fullName>
                </value>
                <value>
                    <fullName>PowerSpec</fullName>
                </value>
                <value>
                    <fullName>Field Test Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Fluids Registration</fullName>
                </value>
                <value>
                    <fullName>FluidWatch</fullName>
                </value>
                <value>
                    <fullName>HighRadius</fullName>
                </value>
                <value>
                    <fullName>My Fleetguard Customer Portal</fullName>
                </value>
                <value>
                    <fullName>Shop Cummins Online Store</fullName>
                </value>
                <value>
                    <fullName>FT - NPBU Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Global Dealer Portal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Role__c</fullName>
        <label>Role/Feature</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>IAM_Application_Name__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AccountExecutive</fullName>
                </value>
                <value>
                    <fullName>AccountManager</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Advance</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>API Developer</fullName>
                </value>
                <value>
                    <fullName>API Owner</fullName>
                </value>
                <value>
                    <fullName>Application Manager</fullName>
                </value>
                <value>
                    <fullName>Applications Developer</fullName>
                </value>
                <value>
                    <fullName>BASIC</fullName>
                </value>
                <value>
                    <fullName>Beta Testing Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Channel Admin</fullName>
                </value>
                <value>
                    <fullName>CLAIMFILER</fullName>
                </value>
                <value>
                    <fullName>CUMMINS</fullName>
                </value>
                <value>
                    <fullName>CUMMINSBASIC</fullName>
                </value>
                <value>
                    <fullName>CumminsCare</fullName>
                </value>
                <value>
                    <fullName>CumminsTechnician</fullName>
                </value>
                <value>
                    <fullName>Customer Admin</fullName>
                </value>
                <value>
                    <fullName>Customer View and Pay</fullName>
                </value>
                <value>
                    <fullName>Dealer Admin</fullName>
                </value>
                <value>
                    <fullName>Dealer User</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Distributor Admin</fullName>
                </value>
                <value>
                    <fullName>Distributor Customer Support Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor Customer Support Rep</fullName>
                </value>
                <value>
                    <fullName>Distributor DFSE</fullName>
                </value>
                <value>
                    <fullName>Distributor Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor Sales Representative</fullName>
                </value>
                <value>
                    <fullName>Enabler</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>QSOL LOP</fullName>
                </value>
                <value>
                    <fullName>QSOL SIR Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Contact Approval</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Subscription_End_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName = &quot;IAM_EDS_Application&quot;  || $RecordType.DeveloperName = &quot;IAM_ProMotion_application&quot; || $RecordType.DeveloperName = &quot;IAM_Guidanz_Mobile&quot; ||
$RecordType.DeveloperName = &quot;IAM_Quick_Serve_Online&quot; || 
$RecordType.DeveloperName = &quot;INSITE&quot; , null, DATE(2100,12,31))</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Account Features &amp; Access</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Access Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Features &amp; Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IAM_Contact_Provisioning__c.object
<CustomObject>
    <fields>
        <fullName>IAM_Account_Name__c</fullName>
        <formula>IAM_Contact__r.Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Application_Name__c</fullName>
        <label>Application Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>Cummins Service Training</fullName>
                </value>
                <value>
                    <fullName>QuickServe Online</fullName>
                </value>
                <value>
                    <fullName>India ABO</fullName>
                </value>
                <value>
                    <fullName>Repair logistics and Service</fullName>
                </value>
                <value>
                    <fullName>Connected Solutions</fullName>
                </value>
                <value>
                    <fullName>CUMPAS 2.0</fullName>
                </value>
                <value>
                    <fullName>Guidanz</fullName>
                </value>
                <value>
                    <fullName>Marketplace</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>WWSPS</fullName>
                </value>
                <value>
                    <fullName>BOX External Partners</fullName>
                </value>
                <value>
                    <fullName>Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Fleetguard FIT</fullName>
                </value>
                <value>
                    <fullName>NextGen</fullName>
                </value>
                <value>
                    <fullName>Rapid Serve Web</fullName>
                </value>
                <value>
                    <fullName>Mexico Warranty</fullName>
                </value>
                <value>
                    <fullName>Archer</fullName>
                </value>
                <value>
                    <fullName>BOX</fullName>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>CSS</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Campaigns</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Free Registration</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - ImmediateAssessment</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Service</fullName>
                </value>
                <value>
                    <fullName>INSITE</fullName>
                </value>
                <value>
                    <fullName>Product Connectivity</fullName>
                </value>
                <value>
                    <fullName>DBU India - Field Service Lightning</fullName>
                </value>
                <value>
                    <fullName>Electrified Powertrain Specification Tool</fullName>
                </value>
                <value>
                    <fullName>PowerSpec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Account Level</fullName>
                </value>
                <value>
                    <fullName>Pending Account Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Contact Approval</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Feature &amp; Access</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Rec Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Features_And_ Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IAM_Remove_Subscritions.cls
/************************************************************
Name:  IAM_Remove_Subscritions
Copyright © 2018  Cummins
=============================================================
=============================================================
Purpose:                                                            
This is a queable class to update the Contact record Updates.                        
=============================================================
=============================================================
History                                                            
-------                                                            
VERSION         AUTHOR                   DATE              DETAIL                                
1.0 -        Amarnath Mishra          05/27/2019        INITIAL DEVELOPMENT 
1.1 -    Karthik Raj Golakaram        01/03/2021      Made changes to make sure that we are calling LDAP API to remove changes
                                                        Also made changes to update Contact and User record.changes
1.2 -      Ganesh K M                 16/05/2022      Made changes to pull only records having subscription end date less than today's date.
1.3 -	 Chetan Gaikwad				  10/08/2022	  EDS/CST deactivation if QSOL Deactivated
*****************************************************/
/********************************************************************************
***********************************************************************************/


global class IAM_Remove_Subscritions implements Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful {
    global integer numberofConProvProcessed = 0;
 
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date todayDate =  date.today();
        //string Inactive = System.label.IAM_Inactive_Label;
        string sActive = 'Active';
        String appGM = Label.IAM_AppName_guidanzmobile;
        String appFieldTestGM = Label.IAM_App_GuidanzMobileFieldTest;
        string query;
        
         if(Test.isRunningTest()){
            query = 'SELECT Id,IAM_Account_Name__r.Name,IAM_Account_Name__r.IAM_Service_Provider_Code__c,IAM_Application_Name__c,IAM_Status__c,IAM_Subscription_End_Date__c,IAM_Account_Name__c,Account_Type__c,IAM_Role__c FROM IAM_Application__c LIMIT 10';
        }
        else{
              query = 'Select Id,IAM_Account_Name__r.Name,IAM_Account_Name__r.IAM_Service_Provider_Code__c,IAM_Application_Name__c,IAM_Status__c,IAM_Subscription_End_Date__c,IAM_Account_Name__c,Account_Type__c,IAM_Role__c From IAM_Application__c WHERE IAM_Status__c =: sActive AND IAM_Subscription_End_Date__c <: todayDate';
        }    
        system.debug('query--->'+query);
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<IAM_Application__c> appAccess) {
        system.debug('appAccess--->'+appAccess);
        Set<id> idsToDeactivate= new Set<id>();
        Set<id> idsACCDeactivate= new Set<id>();//QSOL EDS CST deactivation
        Set<id> idsEDSCSTDeactivate= new Set<id>();//QSOL EDS CST deactivation
        Map<id,String> rolesToDelete=new Map<id,String>();
        Set<id> conIds = new Set<Id>();
        Set<id> deactiatedConProvs= new Set<id>();
        string Inactive = System.label.IAM_Inactive_Label;
        for(IAM_Application__c a:appAccess){
            idsToDeactivate.add(a.id);
            //QSOL EDS CST deactivation
            if(a.IAM_Application_Name__c == system.label.IAM_AppName_QSOL && a.Account_Type__c !='LOP Customer' && a.Account_Type__c !='SIR' && a.IAM_Role__c != 'QSOL LOP' && a.IAM_Role__c != 'QSOL SIR Customer'){
                idsACCDeactivate.add(a.IAM_Account_Name__c);
            }
            //QSOL EDS CST deactivation
        }
        system.debug('### idsToDeactivate'+idsToDeactivate);
        //QSOL EDS CST deactivation
        system.debug('### idsACCDeactivate'+idsACCDeactivate);
        if(!idsACCDeactivate.isEmpty()){
            for(IAM_Application__c app:[Select Id,IAM_Account_Name__r.Name,IAM_Account_Name__r.IAM_Service_Provider_Code__c,IAM_Application_Name__c,IAM_Status__c,IAM_Subscription_End_Date__c, IAM_Account_Name__c From IAM_Application__c WHERE IAM_Account_Name__c=:idsACCDeactivate and Id!=:idsToDeactivate and IAM_Status__c = 'Active' and IAM_Application_Name__c IN ('QuickServe Online')]){
            	idsACCDeactivate.remove(app.IAM_Account_Name__c);
            }
        }
        
        if(!idsACCDeactivate.isEmpty()){
            for(IAM_Application__c app:[Select Id,IAM_Account_Name__r.Name,IAM_Account_Name__r.IAM_Service_Provider_Code__c,IAM_Application_Name__c,IAM_Status__c,IAM_Subscription_End_Date__c, IAM_Account_Name__c From IAM_Application__c WHERE IAM_Account_Name__c=:idsACCDeactivate and IAM_Status__c = 'Active' and IAM_Application_Name__c IN ('Cummins Service Training','EDS')]){
            	idsEDSCSTDeactivate.add(app.Id);
            }
        }
        
        system.debug('### idsEDSCSTDeactivate'+idsEDSCSTDeactivate);
        if(!idsEDSCSTDeactivate.isEmpty()){
            idsToDeactivate.addAll(idsEDSCSTDeactivate);
        }
        system.debug('### idsToDeactivate'+idsToDeactivate);
        //QSOL EDS CST deactivation
        
        Set<id> conProvIdsToDeactive= new Set<id>();
        for(IAM_Contact_Provisioning__c c:[select id,IAM_Status__c,IAM_Reject_Reason__c,IAM_Contact__c from IAM_Contact_Provisioning__c  where IAM_Account_Application__c=:idsToDeactivate AND IAM_Status__c =: 'Active']){
            deactiatedConProvs.add(c.id);
            conIds.add(c.IAM_Contact__c);
            
        }
        system.debug('### deactiatedConProvs'+deactiatedConProvs);
        System.debug('numberofConProvProcessed.....'+numberofConProvProcessed);
        
        
        if(!deactiatedConProvs.isEmpty() || !idsToDeactivate.isEmpty() ){
            System.debug('### Inside If.....');
             IAM_RC_DeleteUserFromGroup.basicAuthCalloutExtention(deactiatedConProvs,rolesToDelete,false);
             if(Limits.getLimitQueueableJobs()>Limits.getQueueableJobs()){
                 System.debug('### Inside If 1.....');
                 id jobId= System.enqueueJob(new IAM_Remove_Sub_Features_Queueable(idsToDeactivate,deactiatedConProvs,conIds,'Since Subscription got inactive, changed Status to Inactive'));
             }
        }  
    }
     
    global void finish(Database.BatchableContext BC) {
      
      System.debug('Printing total number of records'+numberofConProvProcessed);
      
      AsyncApexJob job=[SELECT id,Status,NumberOfErrors,JobItemsProcessed,TotalJobItems FROM AsyncApexJob WHERE id=:BC.getJobId()];
      
      System.debug('Prinitng all the Job '+ job.JobItemsProcessed);
      //Insert records into Identity and Access Error Object;
      
      
        
    }
}