objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_Accreditation__c.object
<CustomObject>
    <description>Object to capture information related to Technician and Account Accreditations</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS Accreditations</relationshipLabel>
        <relationshipName>CSS_Accreditations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MARKET_APPLICATION__c</fullName>
        <label>MARKET_APPLICATION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRODUCT_RANGE__c</fullName>
        <label>PRODUCT_RANGE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Details__c</fullName>
        <label>Product Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SP_CODE__c</fullName>
        <label>SP_CODE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSS Accreditation</label>
    <nameField>
        <label>CSS_Accreditation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Accreditations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_UpdateAccSerLevel_HelperDataloader.cls
public class OSM_UpdateAccSerLevel_HelperDataloader {
    
       public static void dobeforeinsertOpertions(List<CSS_Accreditation__c> triggerNewList)
       {
           List<String> intList = new List<String>();
           Map<String,Id> strVsIdMap = new Map<String,Id>(); 
           for(CSS_Accreditation__c cssa : triggerNewList)
           {    system.debug('cssa.SP_CODE__c--->'+cssa.SP_CODE__c);
               if(cssa.SP_CODE__c != null )
               {
                   intList.add(cssa.SP_CODE__c+'');
               }
           }
           if(intList != null && intList.size()>0)
           {   
               for(Account a : [SELECT Id,IAM_Service_Provider_Code__c FROM Account WHERE IAM_Service_Provider_Code__c IN:intList ])
               {
                   strVsIdMap.put(a.IAM_Service_Provider_Code__c,a.Id);
               }
           }
           for(CSS_Accreditation__c cssa : triggerNewList)
           {
               if(cssa.SP_CODE__c != null  && !strVsIdMap.isEmpty() && strVsIdMap.containsKey(cssa.SP_CODE__c+'') )
               {
                   cssa.Account__c = strVsIdMap.get(cssa.SP_CODE__c+'');
                   cssa.Product_Details__c = '[{"PRODUCT_TYPE":"Electronics","PRODUCT_RANGE":"'+cssa.PRODUCT_RANGE__c+'","MARKET_APPLICATION":"'+cssa.MARKET_APPLICATION__c+'"}]';
               }
           }
           try{
              // insert triggerNewList;
              update triggerNewList;
           }
           catch (Exception e)
           {
               System.debug('Something went wrong ' + e.getMessage());
           }
       }
}