objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTNA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DTNA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__E_AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OSM_Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OSM Integration Logs</relationshipLabel>
        <relationshipName>OSM_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Batch_Failure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Batch Failure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Batch_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Batch Log</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_of_Jobs_Failed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Jobs Failed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OSM Integration Log</label>
    <nameField>
        <displayFormat>OSM- {0000000000}</displayFormat>
        <label>OSM Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_SubscriptionMigrationBatch.cls
/************************************************************
Name:  OSM_SubscriptionMigrationBatch
Copyright © 2018  Cummins
=============================================================
=============================================================
Purpose:                                                            
This batch is written to match coupons codes for all accounts
for which id will be passed
=============================================================
=============================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE              DETAIL                                
1.0 -   Sangeeta            3/06/2019    INITIAL DEVELOPMENT          


*************************************************************/

global class OSM_SubscriptionMigrationBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful{
    
    String query;
    global String AccountId;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        query='select id,Name,type,DTNA__c,IAM_Service_Provider_Code__c,ccrz__E_AccountGroup__r.name from Account where type=\'Dealer Account\' or type=\'Distributor Account\' or type=\'Distributor Branch Account\'' ;
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope){               
        //Set<Id> dealerAccountIdSet=new Set<Id>();
        //Set<Id> disAccountIdSet=new Set<Id>();
        Map<id,Account> dealerAccountsDataMap=new Map<id,Account>();
        Map<id,Account> disAccountsDataMap=new Map<id,Account>();
        for(Account a :scope)
        {
            if(a.type=='Dealer Account' && a.DTNA__c==false)
            {
                AccountId = a.id;// Added By Dhiraj
                //dealerAccountIdSet.add(a.id);
                dealerAccountsDataMap.put(a.id,a);
            }
            else if(a.type=='Distributor Account' || a.type=='Distributor Branch Account')
            {
                AccountId = a.id;// Added By Dhiraj
                //disAccountIdSet.add(a.id);
                disAccountsDataMap.put(a.id,a);
            }
            
        }                                                                          
        
        //OSM_SW_SubscriptionMigrationLogic.getCouponCodeforDealer(dealerAccountIdSet);    
        //OSM_SW_SubscriptionMigrationLogic.getCouponCodeforDistributors(disAccountIdSet); 
        if(dealerAccountsDataMap != null){
            OSM_SW_SubscriptionMigrationLogic.getCouponCodeforDealer(dealerAccountsDataMap);    
        }
        if(disAccountsDataMap != null){
            OSM_SW_SubscriptionMigrationLogic.getCouponCodeforDistributors(disAccountsDataMap);                                                                                              
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
        
        OSM_Integration_Log__c log = new OSM_Integration_Log__c();
        log.Service_Name__c='OSM_SubscriptionMigrationBatch';
        log.Internal_Batch_Log__c=true;
        AsyncApexJob jobstatus = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        log.Status__c = jobstatus.Status;
        if(jobstatus.Status=='Completed'){
            log.Status__c = 'Processed'; 
        }else if(jobstatus.Status=='Failed'){
            log.Internal_Batch_Failure__c=true;
            log.No_of_Jobs_Failed__c=jobstatus.NumberOfErrors;
        }
        log.Account__c = AccountId;  // Added By Dhiraj 
        insert log;
        
    }
}