objects/Account.object
<CustomObject>
    <fields>
        <fullName>BMSApplicationURL__c</fullName>
        <description>To store location specific BMS URL..</description>
        <label>BMSApplicationURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>BMS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BMS Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERP_System__c</fullName>
        <label>ERP System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BMS Legacy</fullName>
                </value>
                <value>
                    <fullName>MoveX</fullName>
                </value>
                <value>
                    <fullName>No ERP System</fullName>
                    <default>true</default>
                    <label>No ERP System</label>
                </value>
                <value>
                    <fullName>One BMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_UserLocation__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS_UserLocations</relationshipLabel>
        <relationshipName>CSS_UserLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMSApplicationURL__c</fullName>
        <formula>AccountId__r.BMSApplicationURL__c</formula>
        <label>BMSApplicationURL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BMS_Enabled__c</fullName>
        <formula>AccountId__r.BMS_Enabled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BMS Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Claim__c</fullName>
        <formula>AccountId__r.Enable_Claims__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enable Claim</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>AccountId__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_code__c</fullName>
        <externalId>true</externalId>
        <label>Location_code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSS_UserLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPrimary</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS_UserLocation</label>
    <nameField>
        <label>CSS_UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_UserLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Location__c</fullName>
        <label>User Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CG_CL_ClaimsOverview.cls
/*
* Block comments with details of changes
*/
/*VERSION    
AUTHOR                          DATE                  DETAIL
1.0         Kalpana Vemula                  07-02-2018          Initial Development
2.0         Rupesh Pande                    28-03-2018          Modified for the location code
*/
public class CG_CL_ClaimsOverview
{
    
    public String LocationCode {get;set;}
    public CG_CL_ClaimsIntake mainContr{set; get;}
    
    public String modifyDT{get;set;}
    public string createdDT{get;set;}
    public string jobCreatedDT{get;set;}
    
    
    
    public CSS_Claims__c claimsRec{get;  
                                   set
                                   {    
                                       String CreatorLocation;
                                       String LocationOverviewSection;
                                       claimsRec = value;
                                       system.debug('Claim Record1:'+value);
                                       if(claimsRec != null && claimsRec.Id != null ) 
                                       {
                                           system.debug('Claim Record2:'+claimsRec);
                                           createdDT = css_utility.getFormattedDate(claimsRec.CreatedDate); 
                                           createdDT=createdDT.touppercase();
                                           modifyDT = css_utility.getFormattedDate(claimsRec.LastModifiedDate);
                                           modifyDT=modifyDT.touppercase();
                                           
                                        system.debug('CreatorLocation in if' + ' ' + claimsRec.Location_Code__c);
                                           if(claimsRec.Location_Code__c!=null)
                                           {
                                               CreatorLocation = claimsRec.Location_Code__c;  
                                               system.debug('CreatorLocation in if' + ' ' + CreatorLocation);
                                           }
                                           else
                                           {
                                               LocationOverviewSection = (String)Cache.Session.get('ManualClaimsSelectedLocation');
                                               CreatorLocation = LocationOverviewSection;
                                                system.debug('CreatorLocation inside if else' + ' ' + CreatorLocation);
                                               
                                              /* User user = css_utility.getUserAttributes(userInfo.getUserId());
                                               CreatorLocation = user.User_Location__c;  */                             
                                           }
                                           
                                           //System.debug('modifyDTTemp'+ modifyDT);  
                                           if(claimsRec.css_job__r<>null)
                                           {
                                               jobCreatedDT=css_utility.getFormattedDate(claimsRec.css_job__r.createddate);
                                               jobCreatedDT=jobCreatedDT.touppercase();
                                               //system.debug('The formatted job created date is'+jobCreatedDT);
                                           }
                                       } 
                                       else
                                       {
                                           //User user = css_utility.getUserAttributes(userInfo.getUserId());
                                          /* list<CSS_UserLocation__c> userLocationList = new List<CSS_UserLocation__c>();
                                           userLocationList = [SELECT AccountId__c,isActive__c,isPrimary__c,Location_Name__c,BMSApplicationURL__c,
                                                               UserId__c,BMS_Enabled__c,Location_code__c
                                                               FROM CSS_UserLocation__c
                                                               WHERE UserId__c = : userInfo.getUserId() AND isActive__c = true AND Enable_Claim__c = true 
                                                               AND AccountId__r.ERP_System__c = 'One BMS' AND isPrimary__c = true LIMIT 1];
                                           // ORDER BY Location_Name__c asc];
                                           system.debug('userInfo.getUserId:'+userInfo.getUserId());
                                           system.debug('userLocationList'+userLocationList);
                                           
                                           if(userLocationList!=null && userLocationList.size()>0)
                                            CreatorLocation = userLocationList[0].Location_code__c;
                                           system.debug('CreatorLocation else'+CreatorLocation);
                                        */   
                                           
                                           LocationOverviewSection = (String)Cache.Session.get('ManualClaimsSelectedLocation');
                                               CreatorLocation = LocationOverviewSection;
                                                system.debug('CreatorLocation in main else' + ' ' + CreatorLocation);
                                       }
                                       
                                       if(CreatorLocation!=null && CreatorLocation != ''){
                                       Integer JobLocLength = CreatorLocation.Length();
                                       Integer Index = JobLocLength-5;
                                       
                                       LocationCode = CreatorLocation.substring(Index,CreatorLocation.Length());
                                       }
                                       system.debug('LocationCode End' + ' ' + LocationCode);
                                       
                                   }   
                                  }
    
    
}