objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DBCode__c</fullName>
        <description>DistributorBranchCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Branch Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Claim_Allow_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SP MX Claim Allow Days</description>
        <label>Claim Allow Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Max_Claim_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Max Claim Amount Flag</description>
        <label>Max Claim Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Region_Code__c</fullName>
        <description>SP MX Region Code</description>
        <label>Region Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Warranty_Training_Certification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to store true or false from Siebel Tech Info WebService</description>
        <label>Warranty Training Certification</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_WS_Failure__c.object
<CustomObject>
    <fields>
        <fullName>CSS_WS_ComponentCode__c</fullName>
        <label>Engine Component Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_EngineSystemCode__c</fullName>
        <label>Engine System Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_FailureModeCode__c</fullName>
        <label>Failure Mode Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_FailureModeName__c</fullName>
        <label>Failure Mode</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Warranty__c</fullName>
        <label>CSS_WS_Warranty</label>
        <referenceTo>CSS_WS_Warranty__c</referenceTo>
        <relationshipLabel>CSS WS Failures</relationshipLabel>
        <relationshipName>CSS_WS_FailureW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CSS WS Failure</label>
    <nameField>
        <label>SF Failure ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS WS Failures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSS_WS_US_Details__c.object
<CustomObject>
    <fields>
        <fullName>CSS_WS_Claim__c</fullName>
        <label>CSS WS Claim</label>
        <referenceTo>CSS_WS_Warranty__c</referenceTo>
        <relationshipLabel>CSS WS US Details</relationshipLabel>
        <relationshipName>CSS_WS_US_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Part_Number__c</fullName>
        <label>Part Number US</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Type_Section__c</fullName>
        <label>Type Section</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parts</fullName>
                </value>
                <value>
                    <fullName>SRTs</fullName>
                </value>
                <value>
                    <fullName>Other Claimables</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS WS US Details</label>
    <nameField>
        <label>CSS_WS_US_Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS WS US Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSS_WS_Warranty__c.object
<CustomObject>
    <description>Mexico Warranty Claims Object</description>
    <fields>
        <fullName>CSS_WS_Account_Code__c</fullName>
        <label>Account Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Engine_Family_Code__c</fullName>
        <label>Engine Family Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Engine_Serial_Number__c</fullName>
        <label>Engine Serial No.</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Failure_Date_Time__c</fullName>
        <label>Failure Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Failure_Point_Quantity__c</fullName>
        <label>Failure Point Qty</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Model_Series__c</fullName>
        <label>Model Series</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Policy_Flag__c</fullName>
        <description>This dropdown will allow the user to select whether the claim is for Warranty or Policy.</description>
        <label>Warranty / Policy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty</fullName>
                    <default>true</default>
                    <label>Warranty</label>
                </value>
                <value>
                    <fullName>Policy</fullName>
                </value>
                <value>
                    <fullName>Policy WW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_DR__c</fullName>
        <description>Service provider code - Service provider Name format of the distributor to which the logged in dealer belongs to</description>
        <label>Service Provider (DR)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_Dealer__c</fullName>
        <description>Service provider code - Service provider Name format</description>
        <label>Service Provider (Dealer)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Total_Amount_Other_Claimables__c</fullName>
        <label>Total Amount Other Claimables ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Total_Amount_Part__c</fullName>
        <label>Total Amount Part ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Total_Amount_SRT__c</fullName>
        <label>Total Amount SRT ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Total_Amount_Travel__c</fullName>
        <label>Total Amount Travel USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_US_Details_Status__c</fullName>
        <label>US Details Status</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_WarrantyId__c</fullName>
        <label>WarrantyId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Warranty_Start_Date__c</fullName>
        <label>Warranty Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Clone__c</fullName>
        <label>Is a clone</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CSS WS Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS WS Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_WS_Warranty_Parts__c.object
<CustomObject>
    <description>Object to store related parts registered on a Warranty</description>
    <fields>
        <fullName>CSS_WS_Description__c</fullName>
        <description>The part description will auto-populate based on the part number and will be non editable. </description>
        <label>Description</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_PartNumber__c</fullName>
        <description>This field will be editable for part number to be entered for the claim. Validation of the part number will take place. If the part number is valid, then it will be added to the claim, else,  the user will be asked to enter correct part number. </description>
        <label>Part Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Siebel_Unit_Part_Price__c</fullName>
        <label>Siebel Unit Part Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Unit_Part_Price__c</fullName>
        <description>The Unit Part Price will auto-populate based on the part number and will be non editable. It will be displayed in USD. (Based on Price List from Corporate list) (To get this value, it is necessary to send Pricing region, channel code, goms instance and failure date). This will be displayed only for Warranty admins from Planta. (It is needed to pull the promotion prices that Monica Jared uses in Oracle, needs to be defined)</description>
        <label>Unitary Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CSS_WS_WarrantyID__c</fullName>
        <description>master related ID</description>
        <label>Warranty</label>
        <referenceTo>CSS_WS_Warranty__c</referenceTo>
        <relationshipName>CSS_WS_Warranty_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CSS WS Warranty Part</label>
    <nameField>
        <label>SF Part ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS WS Warranty Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CSS_WS_PartsGridUSDetailsController_Test.cls
@IsTest
Public Class CSS_WS_PartsGridUSDetailsController_Test{
    Public Static TestMethod Void methodDistributor(){
        CSS_WS_Warranty__c claim = new CSS_WS_Warranty__c(
            CSS_WS_Warranty_Start_Date__c = system.today(),
            CSS_WS_Engine_Serial_Number__c = '10000000',
            CSS_WS_Service_Provider_DR__c = '54321',
            CSS_WS_Service_Provider_Dealer__c = '54321',
            CSS_WS_Policy_Flag__c = 'Warranty',
            CSS_WS_Account_Code__c = null,
            CSS_WS_Failure_Date_Time__c = system.today(),
            CSS_WS_Engine_Family_Code__c = '12',
            CSS_WS_Model_Series__c = 'XLF-124',
            Is_Clone__c = 1,
            CSS_WS_Total_Amount_Other_Claimables__c = 100, 
            CSS_WS_Total_Amount_Part__c = 100, 
            CSS_WS_Total_Amount_SRT__c = 100, 
            CSS_WS_Total_Amount_Travel__c = 100,
            CSS_WS_US_Details_Status__c = 'Success Response',
            CSS_WS_Failure_Point_Quantity__c = '1200');
        insert claim; 
        
        CSS_WS_Warranty_Parts__c partsWarranty = new CSS_WS_Warranty_Parts__c(
            CSS_WS_PartNumber__c = '90001', 
            CSS_WS_Quantity__c = 2, 
            CSS_WS_Description__c = 'Example', 
            CSS_WS_Siebel_Unit_Part_Price__c = 1, 
            CSS_WS_Unit_Part_Price__c = 1.2,
            CSS_WS_WarrantyID__c = claim.id);
        insert partsWarranty;
        
        CSS_WS_Failure__c Failures = new CSS_WS_Failure__c( 
            CSS_WS_ComponentCode__c = '12',
            CSS_WS_EngineSystemCode__c = '13',
            CSS_WS_FailureModeName__c = '14',
            CSS_WS_FailureModeCode__c = '15',
            CSS_WS_Warranty__c = claim.Id);
        insert Failures;
        
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '54321',
            CSS_DBCode__c = '54321',
            Type = 'Distributor Account',
            Name = 'DUMMY DEALER',
            CMI_Account_Status__c = 'Active',
            CSS_WS_Region_Code__c = 'USCA',
            BillingCountry = 'MEXICO',
            CSS_WS_Claim_Allow_Days__c = 10,
            Warranty_Training_Certification__c = true,
            CSS_WS_Max_Claim_Amount__c = 9999);
        insert SPDLTest;
        
        system.debug(SPDLTest);
        
        CSS_WS_US_Details__c detail1 =  new CSS_WS_US_Details__c(
            CSS_WS_Type_Section__c = 'Parts',
            CSS_WS_Part_Number__c = '90001',
            CSS_WS_Claim__c = claim.id);
        insert detail1; 
        
        CSS_WS_US_Details__c detail2 =  new CSS_WS_US_Details__c(
            CSS_WS_Type_Section__c = 'Parts',
            CSS_WS_Part_Number__c = '90002',
            CSS_WS_Claim__c = claim.id);
        insert detail2; 
           
        Test.StartTest();
        CSS_WS_PartsGridUSDetailsController jobUSDetailsParts = new CSS_WS_PartsGridUSDetailsController();
        jobUSDetailsParts.claim = claim.id;
        System.enqueueJob(jobUSDetailsParts);
        Test.setMock(HttpCalloutMock.class, new CSS_WS_WebServicesMock());
        System.enqueueJob(jobUSDetailsParts);
        Test.stopTest();
    }
    
    Public Static TestMethod Void methodDealer(){
        CSS_WS_Warranty__c claim = new CSS_WS_Warranty__c(
            CSS_WS_Warranty_Start_Date__c = system.today(),
            CSS_WS_Engine_Serial_Number__c = '10000000',
            CSS_WS_Service_Provider_DR__c = '54734',
            CSS_WS_Service_Provider_Dealer__c = '54322',
            CSS_WS_Policy_Flag__c = 'Warranty',
            CSS_WS_Account_Code__c = null,
            CSS_WS_Failure_Date_Time__c = system.today(),
            CSS_WS_Engine_Family_Code__c = '12',
            CSS_WS_Model_Series__c = 'XLF-124',
            Is_Clone__c = 1,
            CSS_WS_US_Details_Status__c = 'Success Response',
            CSS_WS_Failure_Point_Quantity__c = '1200');
        insert claim; 
        
        CSS_WS_Warranty_Parts__c partsWarranty = new CSS_WS_Warranty_Parts__c(
            CSS_WS_PartNumber__c = '90001', 
            CSS_WS_Quantity__c = 2, 
            CSS_WS_Description__c = 'Example', 
            CSS_WS_Siebel_Unit_Part_Price__c = 1, 
            CSS_WS_Unit_Part_Price__c = 1.2,
            CSS_WS_WarrantyID__c = claim.id);
        insert partsWarranty;
        
        CSS_WS_Failure__c Failures = new CSS_WS_Failure__c( 
            CSS_WS_ComponentCode__c = '12',
            CSS_WS_EngineSystemCode__c = '13',
            CSS_WS_FailureModeName__c = '14',
            CSS_WS_FailureModeCode__c = '15',
            CSS_WS_Warranty__c = claim.Id);
        insert Failures;
        
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '54322',
            CSS_DBCode__c = '54734',
            Type = 'Dealer Account',
            Name = 'DUMMY DEALER',
            CMI_Account_Status__c = 'Active',
            CSS_WS_Region_Code__c = 'USCA',
            BillingCountry = 'MEXICO',
            CSS_WS_Claim_Allow_Days__c = 10,
            Warranty_Training_Certification__c = true,
            CSS_WS_Max_Claim_Amount__c = 9999);
        insert SPDLTest;
        
        CSS_WS_US_Details__c detail1 =  new CSS_WS_US_Details__c(
            CSS_WS_Type_Section__c = 'Parts',
            CSS_WS_Part_Number__c = '90001',
            CSS_WS_Claim__c = claim.id);
        insert detail1; 
        
        CSS_WS_US_Details__c detail2 =  new CSS_WS_US_Details__c(
            CSS_WS_Type_Section__c = 'Parts',
            CSS_WS_Part_Number__c = '90002',
            CSS_WS_Claim__c = claim.id);
        insert detail2; 
           
        Test.StartTest();
        CSS_WS_PartsGridUSDetailsController jobUSDetailsParts = new CSS_WS_PartsGridUSDetailsController();
        jobUSDetailsParts.claim = claim.id;
        System.enqueueJob(jobUSDetailsParts);
        Test.setMock(HttpCalloutMock.class, new CSS_WS_WebServicesMock());
        System.enqueueJob(jobUSDetailsParts);   
        Test.stopTest();
    }
}