objects/Account.object
<CustomObject>
    <fields>
        <fullName>ccrz__E_AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_AccountGroup__c.object
<CustomObject>
    <description>This object is used to group multiple accounts together to provide pricing and/or entitlements.  An account group can have 1 or more accounts associated with it.  It also can have 1 or more pricelists (used for pricing and entitlements) associated.  This object then ties the accounts and entitlements/pricing together, ultimately controlling the product list and pricing that a given account can see within B2B Commerce.</description>
    <label>CC Account Group</label>
    <nameField>
        <label>Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__ActiveCart__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a new Cart is created, the cart is active by default. Whenever, we want to make anyother cart active, the current active cart should be deactivated</description>
        <label>Active Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CartStatus__c</fullName>
        <description>Cart Status: Every cart is created with a &quot;Open&quot; state, and set to &quot;Closed&quot; state after a corresponding order is placed.</description>
        <label>Cart Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__CartType__c</fullName>
        <description>Cart type &quot;WishList&quot; can be used to keep track of items users want.</description>
        <label>Cart Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read-Only WishList</fullName>
                </value>
                <value>
                    <fullName>WishList</fullName>
                </value>
                <value>
                    <fullName>Cart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>SoftwareStore</fullName>
                    <default>true</default>
                    <label>SoftwareStore</label>
                </value>
                <value>
                    <fullName>CSSNAStore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_SubProdTerm__c.object
<CustomObject>
    <description>B2B Commerce product subscription definition.</description>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront to which this subscription is available.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC SubProdTerm</label>
    <nameField>
        <label>CC SubProdTerm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC SubProdTerms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OSM_SW_Cart_Wishlist_Comp_CtrlTest.cls
@isTest
private class OSM_SW_Cart_Wishlist_Comp_CtrlTest{

    static testMethod void testfetchWishListItems_Success()
    {
        TestDataRes testDataRes = setUpData();
         
        // Start Test
        Test.StartTest();
        
            // Create RemoteActionContext Class Data
            ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
            objRemoteClass.storefront = 'SoftwareStore';
            objRemoteClass.currentCartId = testDataRes.lstECart2[0].Id;
            objRemoteClass.portalUserId = testDataRes.loggedInUser.Id;
            objRemoteClass.userLocale = 'en_US';
        
            OSM_SW_Cart_Wishlist_Comp_Ctrl.fetchWishListItems(objRemoteClass);
        
        Test.stopTest();
    }
    
    static testMethod void testfetchWishListItems_Failure()
    {
        TestDataRes testDataRes = setUpData();
        
        // Start Test
        Test.StartTest();
        
        // Create RemoteActionContext Class Data
        ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
        objRemoteClass.storefront = 'SoftwareStore';
        objRemoteClass.currentCartId = testDataRes.lstECart2[0].Id;
        objRemoteClass.portalUserId = testDataRes.loggedInUser.Id;
        objRemoteClass.userLocale = 'en_US';
        
        ID cartId = testDataRes.lstECart2[0].Id;
        
        ccrz__E_Cart__c cart = [Select id from ccrz__E_Cart__c where id=:cartId];
        cart.ccrz__Storefront__c = 'TestStorefront';
        update cart;
        
        OSM_SW_Cart_Wishlist_Comp_Ctrl.fetchWishListItems(objRemoteClass);
        
        Test.stopTest();
    }
    
    static testMethod void testHandleMovetoCart_Failure()
    {
        TestDataRes testDataRes = setUpData();
        
        Test.StartTest();
        
        // Create RemoteActionContext Class Data
            ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
            objRemoteClass.storefront = 'SoftwareStore';
            objRemoteClass.currentCartId = testDataRes.lstECart2[0].Id;
            objRemoteClass.portalUserId = testDataRes.loggedInUser.Id;
            objRemoteClass.userLocale = 'en_US';
        
        ID cartId = testDataRes.lstECart2[0].Id;
        
        ccrz__E_Cart__c cart = [Select id from ccrz__E_Cart__c where id=:cartId];
        cart.ccrz__CartType__c = 'Cart';
        cart.ccrz__ActiveCart__c = true;
        cart.ccrz__CartStatus__c='Open';
        cart.ccrz__User__c = testDataRes.loggedInUser.Id;
        cart.ccrz__Storefront__c='TestSoftwareStore';
        
        update cart;
        
        OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMovetoCart(objRemoteClass,testDataRes.ECartItem_1[0].Id);
        //OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMovetoCart(objRemoteClass,cart.id);  
        
        Test.stopTest();
    }
    
    static testMethod void testHandleMovetoCart_Success()
    {
        TestDataRes testDataRes = setUpData();
        
        Test.StartTest();
        
        // Create RemoteActionContext Class Data
            ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
            objRemoteClass.storefront = 'SoftwareStore';
            objRemoteClass.currentCartId = testDataRes.lstECart2[0].Id;
            objRemoteClass.portalUserId = testDataRes.loggedInUser.Id;
            objRemoteClass.userLocale = 'en_US';
        
        ID cartId = testDataRes.lstECart2[0].Id;
        
        ccrz__E_Cart__c cart = [Select id from ccrz__E_Cart__c where id=:cartId];
        cart.ccrz__CartType__c = 'Cart';
        cart.ccrz__ActiveCart__c = true;
        cart.ccrz__CartStatus__c='Open';
        cart.ccrz__User__c = testDataRes.loggedInUser.Id;
        cart.ccrz__Storefront__c='SoftwareStore';
        
        update cart;
        
        OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMovetoCart(objRemoteClass,testDataRes.ECartItem_1[0].Id);
        
        Test.stopTest();
    }
    
    static testMethod void testHandleMoveToWishlist_Success()
    {
        TestDataRes testDataRes = setUpData();
         
        // Start Test
        Test.StartTest();
        
        // Create RemoteActionContext Class Data
            ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
            objRemoteClass.storefront = 'SoftwareStore';
            objRemoteClass.currentCartId = testDataRes.lstECart2[0].Id;
            objRemoteClass.portalUserId = testDataRes.loggedInUser.Id;
            objRemoteClass.userLocale = 'en_US';
        
        OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMoveToWishlist(objRemoteClass, testDataRes.ECartItem_1[0].Id);
        
        // Stop Test
        Test.StopTest();
    }
    
    static testMethod void testHandleMoveToWishlist_Failure()
    {
        TestDataRes testDataRes = setUpData();
         
        // Start Test
        Test.StartTest();
        
        // Create RemoteActionContext Class Data
            ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
            objRemoteClass.storefront = 'SoftwareStore';
            objRemoteClass.currentCartId = testDataRes.lstECart2[0].Id;
            objRemoteClass.portalUserId = testDataRes.loggedInUser.Id;
            objRemoteClass.userLocale = 'en_US';
        
        OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMoveToWishlist(objRemoteClass, testDataRes.lstECart2[0].Id);
        
        // Stop Test
        Test.StopTest();
    }
    
    
    static testMethod void testfetchWishListItems(){
        
        TestDataRes testDataRes = setUpData();
         
        // Start Test
        Test.StartTest();
        
            // Create RemoteActionContext Class Data
            ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
            objRemoteClass.storefront = 'SoftwareStore';
            objRemoteClass.currentCartId = testDataRes.lstECart2[0].Id;
            objRemoteClass.portalUserId = testDataRes.loggedInUser.Id;
            objRemoteClass.userLocale = 'en_US';
            
            // Call Apex Class Methods
           // OSM_SW_Cart_Wishlist_Comp_Ctrl.fetchWishListItems(objRemoteClass);
            OSM_SW_Cart_Wishlist_Comp_Ctrl.handleDeleteWLItem(objRemoteClass, testDataRes.ECartItem_1[0].Id);
            OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMoveToWishlist(objRemoteClass, testDataRes.ECartItem_1[0].Id);
            OSM_SW_Cart_Wishlist_Comp_Ctrl.createNewCart();
            OSM_SW_Cart_Wishlist_Comp_Ctrl.createNewWishlist();
           // OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMovetoCart(objRemoteClass,testDataRes.ECartItem_1[0].Id);
        
        // Stop Test
        Test.StopTest();
        
    }
    static testMethod void testhandleMovetoCart(){
        
        // Create User
        User loggedInUser = [Select id from User where id=: UserInfo.getUserId()];
        
        // Create E Cart
        List<ccrz__E_Cart__c> lstECart2 = TestingUtils.CreateCart(1, 'SoftwareStore', 'Cart', loggedInUser.Id, true, 'Open', true);
        
        // Create E Product
        List<ccrz__E_Product__c> lstEProduct = TestingUtils.createEProduct(3, 'TestProduct', 'Released', 2, 'SK100-1', 'DA', true);
        
        // Create E SubProdTerm
        List<ccrz__E_SubProdTerm__c> lstESubProdTerm = new List<ccrz__E_SubProdTerm__c>();
        for(Integer i=0; i<lstEProduct.size(); i++){
            List<ccrz__E_SubProdTerm__c> lstprodterm = TestingUtils.createSubProdTerm(1, 'TestSubProdTerm', lstEProduct[i].Id, '*', true);
            lstESubProdTerm.addAll(lstprodterm);
        }
        
        // Create E CartItem
        List<ccrz__E_CartItem__c> ECartItem_1 = TestingUtils.createCartItem(1, 'SoftwareStore', lstECart2[0].Id, 'Cart', 1, lstEProduct[0].Id, lstESubProdTerm[2].Id, 500, true);
        //List<ccrz__E_CartItem__c> ECartItem_2 = TestingUtils.createCartItem(1, 'CMIMarketplace', lstECart2[0].Id, 'Cart', 1, lstEProduct[1].Id, lstESubProdTerm[2].Id, 500, true);
        
        // Start Test
        Test.startTest();
            
            // Create RemoteActionContext Class Data
            ccrz.cc_RemoteActionContext objRemoteClass = new ccrz.cc_RemoteActionContext();
            objRemoteClass.storefront = 'SoftwareStore';
            objRemoteClass.currentCartId = lstECart2[0].Id;
            objRemoteClass.portalUserId = loggedInUser.Id;
            objRemoteClass.userLocale = 'en_US';
        
            // Call Apex Class Methods
            //OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMovetoCart(objRemoteClass, ECartItem_1[0].Id);
            OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMoveToWishlist(objRemoteClass, ECartItem_1[0].Id);
            OSM_SW_Cart_Wishlist_Comp_Ctrl.createNewCart();
            OSM_SW_Cart_Wishlist_Comp_Ctrl.createNewWishlist();
            //OSM_SW_Cart_Wishlist_Comp_Ctrl.handleMovetoCart(objRemoteClass,ECartItem_1[0].Id);
        // Stop Test
        Test.stopTest();
    }
    
    public static TestDataRes setUpData()
    {
        // Create User
        User loggedInUser = [Select id from User where id=: UserInfo.getUserId()];
        // Query Profile Id
        List<Profile> listObjProfile = [Select id, name from profile where name = 'CloudBurst Customer Community Profile'];
        
        // Create User
        User objUser;
        if(listObjProfile.size() > 0){
            objUser = TestingUtils.createUser('TestUserDA', listObjProfile[0].Id, true);  
        }else{
            listObjProfile = [Select id, name from profile where name = 'Customer Community Plus User'];
            if(listObjProfile.size() > 0){
                objUser = TestingUtils.createUser('TestUserDA', listObjProfile[0].Id, true); 
            }
        } 
        
        //Create Account Group
        List<ccrz__E_AccountGroup__c> listAccountGrp = TestingUtils.createAccountGroup(5, 'TestAccntGrp', 'Best Price', true);
        
        //Create Account
        List<Account> listAccount = TestingUtils.createAccount(5, 'TestAccountMoulika', listAccountGrp[0].Id, objUser.Id, true) ;
        
        //Create Contact
        List<Contact> listContact  = TestingUtils.createContact(1, listAccount[0].Id, objUser.Id, true);
        
        // Create E Cart
        List<ccrz__E_Cart__c> lstECart2 = TestingUtils.CreateCart(1, 'SoftwareStore', 'Wishlist', loggedInUser.Id, true, 'Open', true);
        
        // Create E Product
        List<ccrz__E_Product__c> lstEProduct = TestingUtils.createEProduct(3, 'TestProduct', 'Released', 2, 'SK100-1', 'DA', true);
        
        // Create E SubProdTerm
        List<ccrz__E_SubProdTerm__c> lstESubProdTerm = new List<ccrz__E_SubProdTerm__c>();
        for(Integer i=0; i<lstEProduct.size(); i++){
            List<ccrz__E_SubProdTerm__c> lstprodterm = TestingUtils.createSubProdTerm(1, 'TestSubProdTerm', lstEProduct[i].Id, '*', true);
            lstESubProdTerm.addAll(lstprodterm);
        }
        
        // Create E CartItem
        List<ccrz__E_CartItem__c> ECartItem_1 = TestingUtils.createCartItem(1, 'SoftwareStore', lstECart2[0].Id, 'Cart', 1, lstEProduct[0].Id, lstESubProdTerm[2].Id, 500, true);
        
        TestDataRes testDataRes = new TestDataRes();
        
        testDataRes.loggedInUser = loggedInUser;
        testDataRes.objUser = objUser;
        testDataRes.listAccountGrp = listAccountGrp;
        testDataRes.listContact = listContact;
        testDataRes.lstECart2 = lstECart2;
        testDataRes.lstEProduct = lstEProduct;
        testDataRes.lstESubProdTerm = lstESubProdTerm;
        testDataRes.ECartItem_1 = ECartItem_1;
        
        return testDataRes;
    }
    
    public class TestDataRes
    {
        User loggedInUser;
        User objUser;
        List<ccrz__E_AccountGroup__c> listAccountGrp;
        List<Contact> listContact;
        List<ccrz__E_Cart__c> lstECart2;
        List<ccrz__E_Product__c> lstEProduct;
        List<ccrz__E_SubProdTerm__c> lstESubProdTerm;
        List<ccrz__E_CartItem__c> ECartItem_1;
    }    
}