objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to Store Region Value based on SP code</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPName__c</fullName>
        <label>SPName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CG_StgSPClaimHistory__c.object
<CustomObject>
    <fields>
        <fullName>ClaimCreatedDate__c</fullName>
        <label>ClaimCreatedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClaimFiledDate__c</fullName>
        <label>ClaimFiledDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClaimStatus__c</fullName>
        <label>ClaimStatus</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimSubmittedDate__c</fullName>
        <label>ClaimSubmittedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <label>CustomerName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FailureDate__c</fullName>
        <label>FailureDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FailureReason__c</fullName>
        <label>FailureReason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastUpdatedBy__c</fullName>
        <label>LastUpdatedBy</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastUpdatedDate__c</fullName>
        <label>LastUpdatedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSN__c</fullName>
        <label>PSN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PartiallyPaidFlag__c</fullName>
        <label>PartiallyPaidFlag</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPCode__c</fullName>
        <label>SPCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPName__c</fullName>
        <label>SPName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiebelClaimNumber__c</fullName>
        <externalId>true</externalId>
        <label>SiebelClaimNumber</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceSystemName__c</fullName>
        <label>SourceSystemName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WarrantyStartDate__c</fullName>
        <label>WarrantyStartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WorkOrderNumber__c</fullName>
        <label>WorkOrderNumber</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CG_StgSPClaimHistory</label>
    <nameField>
        <label>CG_StgSPClaimHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CG_StgSPClaimHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Claim_Submission__c.object
<CustomObject>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS Claim Submissions</relationshipLabel>
        <relationshipName>CSS_Claim_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClaimCreatedDate__c</fullName>
        <label>ClaimCreatedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastUpdatedBy__c</fullName>
        <label>LastUpdatedBy</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastUpdatedDate__c</fullName>
        <label>LastUpdatedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PartiallyPaidFlag__c</fullName>
        <label>PartiallyPaidFlag</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Claim_Number__c</fullName>
        <label>Siebel Claim Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceSystemName__c</fullName>
        <label>SourceSystemName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CSS Claim Submission</label>
    <nameField>
        <label>CSS Claim Submission  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Claim Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_PSN__c.object
<CustomObject>
    <description>To handle multiple ESN scenarios with respect to Claims</description>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS PSNs</relationshipLabel>
        <relationshipName>CSS_PSNs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PSN__c</fullName>
        <label>PSN</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>CSS PSN</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS PSNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CG_SPClaimHistoryBatch_Test.cls
@istest
public class CG_SPClaimHistoryBatch_Test 
{
    static testmethod void Method()
    {
        //Create Claims History list
        list<CG_StgSPClaimHistory__c> slhsrty =new list<CG_StgSPClaimHistory__c>();
        CG_StgSPClaimHistory__c clmhobj=new CG_StgSPClaimHistory__c();
        clmhobj.ClaimCreatedDate__c =date.today();
        clmhobj.ClaimFiledDate__c   =date.today();
        clmhobj.ClaimStatus__c  ='Admin Outfile';
        clmhobj.ClaimSubmittedDate__c   =date.today();
        clmhobj.CustomerName__c ='JACINTO LIMON CORTES';
        clmhobj.FailureDate__c  =date.today();
        clmhobj.FailureReason__c=   'TEST';
        clmhobj.LastUpdatedBy__c=   'TEST';
        clmhobj.LastUpdatedDate__c  =date.today();
        clmhobj.Name    ='TEST';
        clmhobj.OwnerId =UserInfo.getUserId();
        clmhobj.PartiallyPaidFlag__c    ='N';
        clmhobj.PSN__c  ='79155862';
        clmhobj.SiebelClaimNumber__c=   '1-6344798';
        clmhobj.SourceSystemName__c ='RSS';
        clmhobj.SPCode__c   ='13362';
        clmhobj.SPName__c   ='MEGAMAK ORIENTE'; 
        clmhobj.WarrantyStartDate__c    =date.today();
        clmhobj.WorkOrderNumber__c='165810';
        upsert clmhobj;
        slhsrty.add(clmhobj);
        upsert slhsrty;
        
        //Create Account list
        Account acc=new Account();
        acc.name='ZAPATA CAMIONES S.A. DE C.V.';
        acc.IAM_Service_Provider_Code__c='13362';
        //acc.IAM_Service_Provider_Code__c = '13362';
        acc.Type='Dealer Account';
        acc.Region__c = 'US and Canada';
        acc.CMI_Account_Status__c = 'Active';
        //acc.IAM_Service_Provider_Code__c = '562551';
        //acc.IAM_Service_Provider_Code__c = '33333';
        acc.CSS_DistributorCode__c='19134';
        //acc.dealerCodeSet = '13362';
        insert acc;
        list<account> aclist=new list<account>();
        aclist.add(acc);
        upsert acc;
        
        //Create Group list
        Group newGroup = new Group();
        newGroup.Name = 'CQ-19134-13362';
        newGroup.Type='queue';
        insert newGroup;
        list<Group> grplist=new list<Group>();
        grplist.add(newGroup);
        upsert grplist;
        
        //Create Claims list
        CSS_Claims__c clm1=CSS_TestData.createclaims(false,null);
        clm1.SiebelClaimNumber__c='1-6344798';insert clm1;
        CSS_Claims__c clm2=CSS_TestData.createclaims(false,null);
        clm2.SiebelClaimNumber__c='1-6344798';insert clm2;
        list<CSS_Claims__c> clsmlist=new list<CSS_Claims__c>();
        clsmlist.add(clm1);
        clsmlist.add(clm2);
        upsert clsmlist;
        
        //Create PSN list
        list<CSS_PSN__c> psnlist=new list<CSS_PSN__c>();
        CSS_PSN__c psnrec1=CSS_TestData.createpsn(false,clsmlist[0].id);
        psnrec1.CSS_Claims__c=clsmlist[0].id;
        insert psnrec1;
        CSS_PSN__c psnrec2=CSS_TestData.createpsn(false,clsmlist[1].id);
        psnrec2.CSS_Claims__c=clsmlist[1].id;
        insert psnrec2;
        psnlist.add(psnrec1);
        psnlist.add(psnrec2);
        upsert psnlist;
        
        //Create Claim Sumbmission list
        list<CSS_Claim_Submission__c> csblist=new list<CSS_Claim_Submission__c>();
        CSS_Claim_Submission__c csbrec1=CSS_TestData.createclaimsub(false,clsmlist[0].id);
        csbrec1.Siebel_Claim_Number__c='1-6344798';insert csbrec1;
        CSS_Claim_Submission__c csbrec2=CSS_TestData.createclaimsub(false,clsmlist[1].id);
        csbrec1.Siebel_Claim_Number__c='1-6344798';insert csbrec2;
        csblist.add(csbrec1);
        csblist.add(csbrec2);
        upsert csblist;
        
        //Query Created  Claims History
        list<CG_StgSPClaimHistory__c> slhsrtyupd=[SELECT Id, FailureReason__c, ClaimCreatedDate__c,ClaimStatus__c,ClaimSubmittedDate__c, CustomerName__c,FailureDate__c,LastUpdatedBy__c,LastUpdatedDate__c, PartiallyPaidFlag__c,PSN__c,SiebelClaimNumber__c,SourceSystemName__c,SPCode__c,SPName__c,WarrantyStartDate__c,WorkOrderNumber__c FROM CG_StgSPClaimHistory__c ORDER BY lastmodifieddate];
        system.debug('slhsrty:::::'+slhsrtyupd);
        
        //Testing Start and execute batch methods
        Test.startTest();
        CG_SPClaimHistoryBatch cb = New CG_SPClaimHistoryBatch();
        Database.QueryLocator ql = cb.start(null);
        cb.execute(null,slhsrty);
        //cb.Finish(null);
        Test.stopTest();
        
    }
   static testmethod void finishMethod(){
        Test.startTest();
     list<CG_StgSPClaimHistory__c> slhsrty =new list<CG_StgSPClaimHistory__c>();
        CG_StgSPClaimHistory__c clmhobj=new CG_StgSPClaimHistory__c();
        clmhobj.ClaimCreatedDate__c =date.today();
        clmhobj.ClaimFiledDate__c   =date.today();
        clmhobj.ClaimStatus__c  ='Draft';
        clmhobj.ClaimSubmittedDate__c   =date.today();
        clmhobj.CustomerName__c ='JACINTO LIMON CORTES';
        clmhobj.FailureDate__c  =date.today();
        clmhobj.FailureReason__c=  null;
        clmhobj.LastUpdatedBy__c=   'TEST';
        slhsrty.add(clmhobj);
        
        CG_StgSPClaimHistory__c clmhobj1=new CG_StgSPClaimHistory__c();
        clmhobj1.ClaimCreatedDate__c =date.today();
        clmhobj1.ClaimFiledDate__c   =date.today();
        clmhobj1.ClaimStatus__c  ='Draft';
        clmhobj1.ClaimSubmittedDate__c   =date.today();
        clmhobj1.CustomerName__c ='JACINTO LIMON CORTES';
        clmhobj1.FailureDate__c  =date.today();
        clmhobj1.FailureReason__c=  null;
        clmhobj1.LastUpdatedBy__c=   'TEST';
        slhsrty.add(clmhobj1);
        
        CG_SPClaimHistoryBatch cb = New CG_SPClaimHistoryBatch();
        cb.Finish(null);
       
        Test.stopTest();
    }
}