objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSS_DBCode__c</fullName>
        <description>DistributorBranchCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Branch Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_DealerCode__c</fullName>
        <description>DealerCode stores the 5 digit valueof the Dealer</description>
        <label>Dealer Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CMI_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reclaim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Internal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for IDM Purpose and is used to know if the user is internal or external</description>
        <label>Internal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Legacy_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legacy User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>this is for IDM purpose and to store cummins LDAP ID of all the users having the WWID from LDAP</description>
        <externalId>true</externalId>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IAM_Application__c.object
<CustomObject>
    <fields>
        <fullName>IAM_Application_Name__c</fullName>
        <label>Application Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Guidanz</fullName>
                </value>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>INSITE</fullName>
                </value>
                <value>
                    <fullName>Cummins Service Training</fullName>
                </value>
                <value>
                    <fullName>QuickServe Online</fullName>
                </value>
                <value>
                    <fullName>India ABO</fullName>
                </value>
                <value>
                    <fullName>Repair logistics and Service</fullName>
                </value>
                <value>
                    <fullName>CUMPAS 2.0</fullName>
                </value>
                <value>
                    <fullName>Marketplace</fullName>
                </value>
                <value>
                    <fullName>Connected Solutions</fullName>
                </value>
                <value>
                    <fullName>WWSPS</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Fleetguard FIT</fullName>
                </value>
                <value>
                    <fullName>NextGen</fullName>
                </value>
                <value>
                    <fullName>Rapid Serve Web</fullName>
                </value>
                <value>
                    <fullName>DBU EFSR</fullName>
                </value>
                <value>
                    <fullName>BOX External Partners</fullName>
                </value>
                <value>
                    <fullName>Mexico Warranty</fullName>
                </value>
                <value>
                    <fullName>Archer</fullName>
                </value>
                <value>
                    <fullName>Electrified Powertrain Specification Tool</fullName>
                </value>
                <value>
                    <fullName>PowerSpec</fullName>
                </value>
                <value>
                    <fullName>Field Test Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Fluids Registration</fullName>
                </value>
                <value>
                    <fullName>FluidWatch</fullName>
                </value>
                <value>
                    <fullName>HighRadius</fullName>
                </value>
                <value>
                    <fullName>My Fleetguard Customer Portal</fullName>
                </value>
                <value>
                    <fullName>Shop Cummins Online Store</fullName>
                </value>
                <value>
                    <fullName>FT - NPBU Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Global Dealer Portal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Role__c</fullName>
        <label>Role/Feature</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>IAM_Application_Name__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AccountExecutive</fullName>
                </value>
                <value>
                    <fullName>AccountManager</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Advance</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>API Developer</fullName>
                </value>
                <value>
                    <fullName>API Owner</fullName>
                </value>
                <value>
                    <fullName>Application Manager</fullName>
                </value>
                <value>
                    <fullName>Applications Developer</fullName>
                </value>
                <value>
                    <fullName>BASIC</fullName>
                </value>
                <value>
                    <fullName>Beta Testing Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Channel Admin</fullName>
                </value>
                <value>
                    <fullName>CLAIMFILER</fullName>
                </value>
                <value>
                    <fullName>CUMMINS</fullName>
                </value>
                <value>
                    <fullName>CUMMINSBASIC</fullName>
                </value>
                <value>
                    <fullName>CumminsCare</fullName>
                </value>
                <value>
                    <fullName>CumminsTechnician</fullName>
                </value>
                <value>
                    <fullName>Customer Admin</fullName>
                </value>
                <value>
                    <fullName>Customer View and Pay</fullName>
                </value>
                <value>
                    <fullName>Dealer Admin</fullName>
                </value>
                <value>
                    <fullName>Dealer User</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Distributor Admin</fullName>
                </value>
                <value>
                    <fullName>Distributor Customer Support Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor Customer Support Rep</fullName>
                </value>
                <value>
                    <fullName>Distributor DFSE</fullName>
                </value>
                <value>
                    <fullName>Distributor Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor Sales Representative</fullName>
                </value>
                <value>
                    <fullName>Enabler</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Features &amp; Access</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Access Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Features &amp; Access</pluralLabel>
    <recordTypes>
        <fullName>FluidWatch</fullName>
        <active>true</active>
        <label>FluidWatch</label>
    </recordTypes>
    <recordTypes>
        <fullName>IAM_WWSPS</fullName>
        <active>true</active>
        <label>WWSPS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Marketplace</fullName>
        <active>true</active>
        <label>Marketplace</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IAM_Contact_Provisioning__c.object
<CustomObject>
    <fields>
        <fullName>IAM_Application_Name__c</fullName>
        <label>Application Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>Cummins Service Training</fullName>
                </value>
                <value>
                    <fullName>QuickServe Online</fullName>
                </value>
                <value>
                    <fullName>India ABO</fullName>
                </value>
                <value>
                    <fullName>Repair logistics and Service</fullName>
                </value>
                <value>
                    <fullName>Connected Solutions</fullName>
                </value>
                <value>
                    <fullName>CUMPAS 2.0</fullName>
                </value>
                <value>
                    <fullName>Guidanz</fullName>
                </value>
                <value>
                    <fullName>Marketplace</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>WWSPS</fullName>
                </value>
                <value>
                    <fullName>BOX External Partners</fullName>
                </value>
                <value>
                    <fullName>Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Fleetguard FIT</fullName>
                </value>
                <value>
                    <fullName>NextGen</fullName>
                </value>
                <value>
                    <fullName>Rapid Serve Web</fullName>
                </value>
                <value>
                    <fullName>Mexico Warranty</fullName>
                </value>
                <value>
                    <fullName>Archer</fullName>
                </value>
                <value>
                    <fullName>BOX</fullName>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>CSS</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Campaigns</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Free Registration</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - ImmediateAssessment</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Service</fullName>
                </value>
                <value>
                    <fullName>INSITE</fullName>
                </value>
                <value>
                    <fullName>Product Connectivity</fullName>
                </value>
                <value>
                    <fullName>DBU India - Field Service Lightning</fullName>
                </value>
                <value>
                    <fullName>Electrified Powertrain Specification Tool</fullName>
                </value>
                <value>
                    <fullName>PowerSpec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Contact_Status__c</fullName>
        <formula>TEXT(IAM_Contact__r.IAM_Contact_Status__c)</formula>
        <label>Contact Status</label>
        <type>Text</type>
    </fields>
    <label>User Feature &amp; Access</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Rec Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Features_And_ Access</pluralLabel>
    <recordTypes>
        <fullName>FluidWatch</fullName>
        <active>true</active>
        <label>FluidWatch</label>
    </recordTypes>
    <recordTypes>
        <fullName>IAM_WWSPS</fullName>
        <active>true</active>
        <label>WWSPS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Marketplace</fullName>
        <active>true</active>
        <label>Marketplace</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IAM_PermissionSet_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IAM_Permission_Set_Name__c</fullName>
        <label>IAM Permission Set Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>IAM PermissionSet Assignment</label>
</CustomObject>

classes/IAM_AssignApplication_PS_Extension_Test.cls
/************************************************************
Name:  IAM_AssignApplication_PS_Extension_Test
Copyright © 2019  Cummins
=============================================================
=============================================================
Purpose:                                                            
This is test class for IAM_AssignApplication_PS_Extension_Test class.
//below class is mainly used as a invokable class fron process builder in order to assaign and delete permission sets from users.
//this class will have two functions which gets invoked on insertion and update on the application status                           
=============================================================
=============================================================
History                                                            
-------                                                            
VERSION  AUTHOR                     DATE              DETAIL                                
1.0 -    Nishant Verma             02/10/2020        Fluidwatch Changes for site admin page -INITIAL DEVELOPMENT
1.2 -    Karthik Raj Golakaram     01/25/2021        Making Changes for OSM High Prod issue - INC1022619
1.3 -    Karthik Raj Golakaram     03/25/2021        Making Changes for bulk user provisioning
*****************************************************/
/********************************************************************************
***********************************************************************************/ 
@isTest
public class IAM_AssignApplication_PS_Extension_Test{
         static testMethod void testMethodOSMRole(){
          Map<Id,String> roleUrsIdsMap = new Map<Id,String>();
            Map<String,Id> rolepsIdSMap=new Map<String,Id>();
         map<string,string> mapofConIdOsmRoles =  new map<string,string>();
         IAM_PermissionSet_Assignment__c cst = new IAM_PermissionSet_Assignment__c();
        cst.Name='Distributor Admin';
        cst.IAM_Permission_Set_Name__c ='OSM_Distributor_Admin';
        insert cst;
        Account acc1 = new Account();
        acc1.Name = 'TestAccount1';
        acc1.Type = 'Distributor Account';
        acc1.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName()
                  .get(System.Label.IAM_WWSPS).getRecordTypeId();
        insert acc1;
        
        Account acc = new Account();
        acc.Name = 'TestAccount';
        acc.IAM_Service_Provider_Code__c = '123';
        acc.Type = 'Dealer Account';
        acc.CSS_DistributorCode__c = '1234';
        acc.CSS_DBCode__c = '12345';
        acc.CSS_DealerCode__c = '456';
        insert acc;
        
        Contact con2 = new contact();
        con2.lastName = 'Tes';
        con2.AccountId = acc.id;
        con2.firstName = 'fis';
        con2.Email = 'testContact1@test.com';
        con2.IAM_Contact_Status__c = 'Active';
        con2.CMI_Contact_Type__c = 'Secondary';
        con2.phone = '8989898989';
        Con2.Username__c = 'test_user_helper8@eidm.com';
        con2.IAM_Contact_Status__c ='Active';
        con2.IAM_Internal__c =true;
        con2.IAM_Legacy_User__c =true;
        insert con2;
        List<profile> pf = [select Id,Name from Profile WHERE Name ='IAM_Admin_User'limit 1];
       User newUser = new User();
        newUser.FirstName = con2.FirstName;
        newUser.LastName = con2.LastName;
        newUser.Email = con2.Email;   
        newUser.CompanyName = acc.Name;        
        newUser.CommunityNickname = 'tts';
        newUser.Username = con2.Username__c ;
        newUser.Alias = 'tts';
        newUser.TimeZoneSidKey = 'GMT';
        newUser.LocaleSidKey= 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.LanguageLocaleKey = 'en_US';         
        newUser.ProfileId = pf[0].Id ;                                  
        //newUser.ContactId = con2.Id;                   
        newUser.isActive = true;
        newUser.Street = '123 Test St';
        newUser.FederationIdentifier = Con2.Username__c;
        insert newUser;
    
        IAM_Application__c app = new IAM_Application__c();
        app.IAM_Application_Name__c = 'Marketplace';
        app.IAM_Role__c = 'Distributor Admin';
        app.IAM_Status__c = 'Active';
        app.IAM_Account_Name__c = acc.id;
        app.IAM_Subscription_Name__c = 'test';
        app.recordtypeid = Schema.getGlobalDescribe().get('IAM_Application__c').getDescribe().getRecordTypeInfosByName().get('Marketplace').getRecordTypeId();
        insert app;
        list<IAM_Contact_Provisioning__c> lstconpro = new list<IAM_Contact_Provisioning__c>();
         IAM_Contact_Provisioning__c conApp = new IAM_Contact_Provisioning__c();
        conApp.IAM_Application_Name__c = app.IAM_Application_Name__c;
        conApp.IAM_Role__c = 'Distributor Admin';
        //conApp.IAM_Start_Date__c = system.now();
        conApp.IAM_Status__c = 'Active';
        conApp.IAM_Contact__c = con2.id; 
        conApp.IAM_Account_Application__c = app.id;
        conApp.recordtypeid = Schema.getGlobalDescribe().get('IAM_Contact_Provisioning__c').getDescribe().getRecordTypeInfosByName().get('Marketplace').getRecordTypeId();
        lstconpro.add(conapp);
        insert lstconpro;
          PermissionSet PS =[SELECT Id,Label,Name,NamespacePrefix,ProfileId FROM PermissionSet where Name ='OSM_Distributor_Admin'];
         roleUrsIdsMap.put(newUser.id,'Distributor Admin');
         rolepsIdSMap.put('Distributor Admin',ps.id);
         mapofConIdOsmRoles.put(newUser.FederationIdentifier,'Distributor Admin');
        System.enqueueJob(new IAM_AssignApplication_PS_Extension(roleUrsIdsMap,rolepsIdSMap,'Insert'));

    }
    
    static testMethod void testMethodOSMRole1(){
          Map<Id,String> roleUrsIdsMap = new Map<Id,String>();
            Map<String,Id> rolepsIdSMap=new Map<String,Id>();
         map<string,string> mapofConIdOsmRoles =  new map<string,string>();
         IAM_PermissionSet_Assignment__c cst = new IAM_PermissionSet_Assignment__c();
        cst.Name='Distributor Admin';
        cst.IAM_Permission_Set_Name__c ='OSM_Distributor_Admin';
        insert cst;
        Account acc1 = new Account();
        acc1.Name = 'TestAccount1';
        acc1.Type = 'Distributor Account';
        acc1.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName()
                  .get(System.Label.IAM_WWSPS).getRecordTypeId();
        insert acc1;
        
        Account acc = new Account();
        acc.Name = 'TestAccount';
        acc.IAM_Service_Provider_Code__c = '123';
        acc.Type = 'Dealer Account';
        acc.CSS_DistributorCode__c = '1234';
        acc.CSS_DBCode__c = '12345';
        acc.CSS_DealerCode__c = '456';
        insert acc;
        
        Contact con2 = new contact();
        con2.lastName = 'Tes';
        con2.AccountId = acc.id;
        con2.firstName = 'fis';
        con2.Email = 'testContact1@test.com';
        con2.IAM_Contact_Status__c = 'Active';
        con2.CMI_Contact_Type__c = 'Secondary';
        con2.phone = '8989898989';
        Con2.Username__c = 'test_user_helper8@eidm.com';
        con2.IAM_Contact_Status__c ='Active';
        con2.IAM_Internal__c =true;
        con2.IAM_Legacy_User__c =true;
        insert con2;
        List<profile> pf = [select Id,Name from Profile WHERE Name ='IAM_Admin_User'limit 1];
       User newUser = new User();
        newUser.FirstName = con2.FirstName;
        newUser.LastName = con2.LastName;
        newUser.Email = con2.Email;   
        newUser.CompanyName = acc.Name;        
        newUser.CommunityNickname = 'tts';
        newUser.Username = con2.Username__c ;
        newUser.Alias = 'tts';
        newUser.TimeZoneSidKey = 'GMT';
        newUser.LocaleSidKey= 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.LanguageLocaleKey = 'en_US';         
        newUser.ProfileId = pf[0].Id ;                                  
        //newUser.ContactId = con2.Id;                   
        newUser.isActive = true;
        newUser.Street = '123 Test St';
        newUser.FederationIdentifier = Con2.Username__c;
        insert newUser;
    
        IAM_Application__c app = new IAM_Application__c();
        app.IAM_Application_Name__c = 'Marketplace';
        app.IAM_Role__c = 'Distributor Admin';
        app.IAM_Status__c = 'Active';
        app.IAM_Account_Name__c = acc.id;
        app.IAM_Subscription_Name__c = 'test';
        app.recordtypeid = Schema.getGlobalDescribe().get('IAM_Application__c').getDescribe().getRecordTypeInfosByName().get('Marketplace').getRecordTypeId();
        insert app;
        list<IAM_Contact_Provisioning__c> lstconpro = new list<IAM_Contact_Provisioning__c>();
         IAM_Contact_Provisioning__c conApp = new IAM_Contact_Provisioning__c();
        conApp.IAM_Application_Name__c = app.IAM_Application_Name__c;
        conApp.IAM_Role__c = 'Distributor Admin';
        //conApp.IAM_Start_Date__c = system.now();
        conApp.IAM_Status__c = 'Active';
        conApp.IAM_Contact__c = con2.id; 
        conApp.IAM_Account_Application__c = app.id;
        conApp.recordtypeid = Schema.getGlobalDescribe().get('IAM_Contact_Provisioning__c').getDescribe().getRecordTypeInfosByName().get('Marketplace').getRecordTypeId();
        lstconpro.add(conapp);
        insert lstconpro;
          PermissionSet PS =[SELECT Id,Label,Name,NamespacePrefix,ProfileId FROM PermissionSet where Name ='OSM_Distributor_Admin'];
         roleUrsIdsMap.put(newUser.id,'Distributor Admin');
         rolepsIdSMap.put('Distributor Admin',ps.id);
         mapofConIdOsmRoles.put(newUser.FederationIdentifier,'Distributor Admin');
        System.enqueueJob(new IAM_AssignApplication_PS_Extension(roleUrsIdsMap,rolepsIdSMap,'Delete'));
       
    }
    
    Static testMethod void futturemethod(){
    
    
    Profile p = [SELECT Id FROM Profile WHERE Name='IAM_Admin_User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id,isActive=True, 
            TimeZoneSidKey='America/Los_Angeles', UserName='34343fnamelnamereclaim@test.com',FederationIdentifier='34343fnamelname@test.com');
        insert u;
        
      List<PermissionSet>pSet=[SELECT Id,Label,Name,NamespacePrefix,ProfileId FROM PermissionSet where Label='EDS'];
      
       PermissionSetAssignment psa = new PermissionSetAssignment (PermissionSetId = pset[0].id, AssigneeId = u.Id);
       test.StartTest();
       insert psa;
       
       Set<id> uIds=new Set<id>();
       uIds.add(u.id);
       Set<id> pids=new Set<id>();
       pids.add(psa.id);
       IAM_AssignApplication_PS_Extension.removePermissionSetsFromUser(pids,uids);
       test.StopTest();
    
    }
    
}