objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to Store Region Value based on SP code</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Used to store Territory value based on SP code</description>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engines</fullName>
                    <default>true</default>
                    <label>Engines</label>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>FIREPUMP</fullName>
                </value>
                <value>
                    <fullName>ENGINE</fullName>
                </value>
                <value>
                    <fullName>GENSET</fullName>
                </value>
                <value>
                    <fullName>ENGINE CORE</fullName>
                </value>
                <value>
                    <fullName>SWITCH GEAR</fullName>
                </value>
                <value>
                    <fullName>TRANSFER SWITCH</fullName>
                </value>
                <value>
                    <fullName>TRANSMISSIONS</fullName>
                </value>
                <value>
                    <fullName>BATTERY</fullName>
                </value>
                <value>
                    <fullName>PARSYS</fullName>
                </value>
                <value>
                    <fullName>MARINE GEAR</fullName>
                </value>
                <value>
                    <fullName>ONAN</fullName>
                </value>
                <value>
                    <fullName>REFRIG</fullName>
                </value>
                <value>
                    <fullName>KOMATSU EQUIPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FSL__User_Territory__c.object
<CustomObject>
    <description>Which Territories are visible to this user (Default = All)</description>
    <fields>
        <fullName>FSL__ServiceTerritory__c</fullName>
        <label>Service Territory</label>
        <referenceTo>ServiceTerritory</referenceTo>
        <relationshipName>User_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FSL__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>ULID-{000000}</displayFormat>
        <label>User Territory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FSL_Labor_Multiplier__c.object
<CustomObject>
    <label>FSL_Labor Multiplier</label>
    <nameField>
        <label>TIER</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSL_Labor Multipliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>FSL_Service_Territory_Code__c</fullName>
        <description>Territory Code of the Service Location</description>
        <inlineHelpText>Territory Code of the Service Location</inlineHelpText>
        <label>Service Territory Code</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <label>Location Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DEALER</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-BRANCH</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-HEADQUARTERS</fullName>
                </value>
                <value>
                    <fullName>GROUP</fullName>
                </value>
                <value>
                    <fullName>HOLSET - DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>INDUSTRIAL/VOCATIONAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Location__c</fullName>
        <label>User Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FSL_IntakeViewHistoryCtrl_Test.cls
//Adding comment for deployment -- Akansha MV_688 8/25/2022

//Adding Comment for Deploment --- Sriprada
//test class modified by Naveen -----Naveen  26/08/2022
@isTest
public class FSL_IntakeViewHistoryCtrl_Test {
    
    @testSetup
    public static void setupMethod(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        UserRole ur = [SELECT id from UserRole WHERE PortalType = 'None' LIMIT 1];
        
        User newUser = new User(Alias = 'standt',Email='test1@gmail.com',UserRoleId = ur.Id,EmailEncodingKey='UTF-8',LastName='Testing',LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', UserName='test11newUser@gmail.com',User_Location__c='05306-40582-036-I');
        insert newUser;  
        
    }    
    public static testMethod void test1() {
        /*Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        UserRole ur = [SELECT id from UserRole WHERE PortalType = 'None' LIMIT 1];
        
        User newUser = new User(Alias = 'standt',Email='test1@gmail.com',UserRoleId = ur.Id,EmailEncodingKey='UTF-8',LastName='Testing',LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', UserName='test11newUser@gmail.com');
        insert newUser;*/
        User userObj = [SELECT Id FROM User WHERE Alias = 'standt'];
        System.runAs(userObj){ 
            BusinessHours bhs=[select id from BusinessHours where IsDefault=true];
            
            Id accRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
            Account acc = new Account();
            acc = TestUtility.createTestAccount('Test Account', accRecId);
            
            Id conRecId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
            Contact con=new Contact();
            con = TestUtility.createNewCon(acc.id, conRecId);
            
            OperatingHours  oh = new OperatingHours ();
            oh = TestUtility.createOperatingHours('new');
            
            ServiceTerritory sT= new ServiceTerritory();
            st = TestUtility.createServiceTerritory('TEST ST Mobile', true, oh.id);
            
            Test.startTest();
            FSL_Labor_Multiplier__c lm = new FSL_Labor_Multiplier__c();
            lm.Name = 'TIER B';
            insert lm;
            
            Asset asst = new Asset();
            asst = TestUtility.createTestAsset(acc, 'Engines-79644334');
             
            case cs=new case();
            cs = TestUtility.createTestCasewithContact(acc.id, asst.id, con.id);
            
            List<WorkOrder> WorkOrderList = new List<WorkOrder>();
            WorkOrder wo = new WorkOrder();
            wo = TestUtility.createNewWorkOrder(sT.id, acc.id, con.id, asst.id);
            wo.Type__c = 'Dealer';
            WorkOrderList.add(wo);
            
            WorkOrder wo1 = new WorkOrder();
            wo1 = TestUtility.createNewWorkOrder(sT.id, acc.id, con.id, asst.id);
            WorkOrderList.add(wo1);
            insert WorkOrderList;
            
            ApexPages.currentPage().getParameters().put('Id', wo.Id);
            FSL_IntakeViewHistoryCtrl vh = new FSL_IntakeViewHistoryCtrl();
            vh.workOrderId = wo.Id; 
            Test.stopTest();
            
        }
    }
    public static testMethod void test2() {
        /*Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        UserRole ur = [SELECT id from UserRole WHERE PortalType = 'None' LIMIT 1];
        
        User newUser = new User(Alias = 'standt',Email='test1@gmail.com',UserRoleId = ur.Id,EmailEncodingKey='UTF-8',LastName='Testing',LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', UserName='test11newUser@gmail.com',User_Location__c='05306-40582-036-I');
        insert newUser;*/
        User userObj = [SELECT Id FROM User WHERE Alias = 'standt'];
        System.runAs(userObj){ 
            BusinessHours bhs=[select id from BusinessHours where IsDefault=true];
            
            Id accRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
            Account acc = new Account();
            acc = TestUtility.createTestAccount('Test Account', accRecId);
            
            Id conRecId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
            Contact con=new Contact();
            con = TestUtility.createNewCon(acc.id, conRecId);
            
            OperatingHours  oh = new OperatingHours ();
            oh = TestUtility.createOperatingHours('new');
            
            ServiceTerritory sT= new ServiceTerritory();
            st = TestUtility.createServiceTerritory('TEST ST Mobile', true, oh.id);
            
            Test.startTest();
            FSL_Labor_Multiplier__c lm = new FSL_Labor_Multiplier__c();
            lm.Name = 'TIER B';
            insert lm;
            
            Asset asst = new Asset();
            asst = TestUtility.createTestAsset(acc, 'Engines-79644334');
            
            case cs=new case();
            cs = TestUtility.createTestCasewithContact(acc.id, asst.id, con.id);
            
            List<WorkOrder> WorkOrderList = new List<WorkOrder>();
            WorkOrder wo = new WorkOrder();
            wo = TestUtility.createNewWorkOrder(sT.id, acc.id, con.id, asst.id);
            WorkOrderList.add(wo);
            
            WorkOrder wo1 = new WorkOrder();
            wo1 = TestUtility.createNewWorkOrder(sT.id, acc.id, con.id, asst.id);
            WorkOrderList.add(wo1);
            insert WorkOrderList;
            
            ServiceTerritory testServiceTerritory = new ServiceTerritory(Name = 'Europe test',
                                                                         IsActive = true,
                                                                         OperatingHoursId = oh.id, 
                                                                         Type__c = 'Group',
                                                                         Location_Code__c	='00000-I00004',Region__c = 'EUROPE', Territory__c = 'UK',
                                                                         FSL_Service_Territory_Code__c='I00004');
            
            insert testServiceTerritory;     
            
            
            List<FSL__User_Territory__c> lstUT = new List<FSL__User_Territory__c>();
            FSL__User_Territory__c Ut = new FSL__User_Territory__c();
            Ut.FSL__ServiceTerritory__c = testServiceTerritory.id;
            Ut.FSL__User__c = userObj.id;
            lstUT.add(Ut);
            
            insert lstUT;
            
            ApexPages.currentPage().getParameters().put('Id', wo.Id);
            FSL_IntakeViewHistoryCtrl vh = new FSL_IntakeViewHistoryCtrl();
            vh.workOrderId = wo.Id; 
            Test.stopTest();
            
        }
    }
    
}