objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IAM</fullName>
        <active>true</active>
        <description>Please use this only for creating non-WWSPS managed locations (Fleet, Individual, Business, etc.). For any Service Provider additions cancel this creation and please visit and use existing WWSPS process.</description>
        <label>IAM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/App_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Back_page__c</fullName>
        <label>Back page</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMI_External_Start_Url__c</fullName>
        <label>External_Start_Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_App_Protected_By__c</fullName>
        <label>App Protected By</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAML</fullName>
                </value>
                <value>
                    <fullName>SM</fullName>
                </value>
                <value>
                    <fullName>OAM11g</fullName>
                </value>
                <value>
                    <fullName>OAM12c</fullName>
                </value>
                <value>
                    <fullName>AWS Cognito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Authroization_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authroization Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Default_Role__c</fullName>
        <label>Default Role</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IAM_Different_Request_Access_URL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used to check if applications redirection URL is IAM_Request_Access_Page</description>
        <label>Different Request Access URL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_OAM_Resource_URL_Redirection__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is define if we need to add  resource url getting from OAM to cummins redirect page.</description>
        <label>OAM Resource URL Redirection Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Request_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request_Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Login_Url__c</fullName>
        <label>Login Url</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>App Mapping</label>
    <nameField>
        <label>App Mapping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CMI_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reclaim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Internal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for IDM Purpose and is used to know if the user is internal or external</description>
        <label>Internal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IAM_Legacy_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legacy User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>this is for IDM purpose and to store cummins LDAP ID of all the users having the WWID from LDAP</description>
        <externalId>true</externalId>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>IAM</fullName>
        <active>true</active>
        <description>Please use this for creating external users, for creating Cummins users please follow WWIMS process. After creating user, please assign needed Application-Role&apos;s by clicking on &quot;Assign App/Feature&quot; to complete user setup without which user cannot access.</description>
        <label>IAM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>IAM_Challange_Answer1__c</fullName>
        <label>Challange Answer1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Challenge_Question_1__c</fullName>
        <label>Challenge Question 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>What city were you born in?</fullName>
                    <default>true</default>
                    <label>What city were you born in?</label>
                </value>
                <value>
                    <fullName>What is the first company that you worked for?</fullName>
                </value>
                <value>
                    <fullName>What is the first name of your spouse&apos;s father?</fullName>
                </value>
                <value>
                    <fullName>What is the make of your first car?</fullName>
                </value>
                <value>
                    <fullName>What is the name of the place your wedding reception was held?</fullName>
                </value>
                <value>
                    <fullName>What is the name of your first pet?</fullName>
                </value>
                <value>
                    <fullName>What is the name of your first school?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite food?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite sport?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite vacation place?</fullName>
                </value>
                <value>
                    <fullName>What is your High School Mascot?</fullName>
                </value>
                <value>
                    <fullName>What is your mother’s maiden name?</fullName>
                </value>
                <value>
                    <fullName>Where did you first meet your spouse?</fullName>
                </value>
                <value>
                    <fullName>Who is your favorite actor, musician or artist?</fullName>
                </value>
                <value>
                    <fullName>Who is your favorite Sports star?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Challenge_Question_2__c</fullName>
        <label>Challenge Question 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>What city were you born in?</fullName>
                </value>
                <value>
                    <fullName>What is the first company that you worked for?</fullName>
                </value>
                <value>
                    <fullName>What is the first name of your spouse&apos;s father?</fullName>
                </value>
                <value>
                    <fullName>What is the make of your first car?</fullName>
                </value>
                <value>
                    <fullName>What is the name of the place your wedding reception was held?</fullName>
                </value>
                <value>
                    <fullName>What is the name of your first pet?</fullName>
                </value>
                <value>
                    <fullName>What is the name of your first school?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite food?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite sport?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite vacation place?</fullName>
                </value>
                <value>
                    <fullName>What is your High School Mascot?</fullName>
                </value>
                <value>
                    <fullName>What is your mother’s maiden name?</fullName>
                </value>
                <value>
                    <fullName>Where did you first meet your spouse?</fullName>
                </value>
                <value>
                    <fullName>Who is your favorite actor, musician or artist?</fullName>
                </value>
                <value>
                    <fullName>Who is your favorite Sports star?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Challenge_Question_3__c</fullName>
        <label>Challenge Question 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>What city were you born in?</fullName>
                </value>
                <value>
                    <fullName>What is the first company that you worked for?</fullName>
                </value>
                <value>
                    <fullName>What is the first name of your spouse&apos;s father?</fullName>
                </value>
                <value>
                    <fullName>What is the make of your first car?</fullName>
                </value>
                <value>
                    <fullName>What is the name of the place your wedding reception was held?</fullName>
                </value>
                <value>
                    <fullName>What is the name of your first pet?</fullName>
                </value>
                <value>
                    <fullName>What is the name of your first school?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite food?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite sport?</fullName>
                </value>
                <value>
                    <fullName>What is your favorite vacation place?</fullName>
                </value>
                <value>
                    <fullName>What is your High School Mascot?</fullName>
                </value>
                <value>
                    <fullName>What is your mother’s maiden name?</fullName>
                </value>
                <value>
                    <fullName>Where did you first meet your spouse?</fullName>
                </value>
                <value>
                    <fullName>Who is your favorite actor, musician or artist?</fullName>
                </value>
                <value>
                    <fullName>Who is your favorite Sports star?</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_External_User_Num__c</fullName>
        <description>Auto assigned number for external users to be used in Guidanz Mobile primarily.</description>
        <displayFormat>{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>IAM_External_User_Num</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/IAM_CIHR_ChangePasswordController_Test.cls
/*********************************************************************************
Author       :   Chetan Gaikwad
Created Date :   6th Feb,2020
Description  :   Unit test class for  IAM_CIHR_ChangePasswordController.
*********************************************************************************/
@isTest(seeAllData=True)
public class IAM_CIHR_ChangePasswordController_Test{
    
    
     Static testMethod void test1(){
    Account a= new Account();       
        a.Name = 'Test Company';
        a.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('IAM').getRecordTypeId();  
        a.phone = '6884382997';
        a.BillingCity='Columbus';
        a.BillingStreet='340 Brown Street';
        a.BillingCountry='United States';
        a.BillingPostalCode='47201';
        a.BillingState='Indiana';
        a.CMI_Account_Status__c='Active';
        insert a;
    
    contact Con=new contact();
        con.RecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('IAM').getRecordTypeId();
        Con.FirstName = 'Change';
        Con.LastName = 'Password';
        Con.AccountId = a.Id;
        con.Username__c='testChangepassowrd@eiam.com';   
        Con.Email = 'testChangepassowrd@eiam.com';     
        Con.IAM_Internal__c = False;
        Con.IAM_Legacy_User__c=false;
        con.CMI_Contact_Type__c = 'secondary';
        Con.IAM_Contact_Status__c='Active';
        insert Con;
        
        App_Mapping__c app=new App_Mapping__c();
        app.name='test app';
        app.Back_page__c='https://login.salesforce.com/';
        app.Login_Url__c='https://www.facebook.com/';
        app.CMI_External_Start_Url__c = 'https://qs-dev.cummins.com/';        
        app.IAM_Default_Role__c='User';
        app.IAM_Authroization_Required__c = false;
        app.IAM_OAM_Resource_URL_Redirection__c = true;
        app.IAM_App_Protected_By__c='SAML';
        app.IAM_Request_Access__c = false;
        app.IAM_Different_Request_Access_URL__c = true;
        insert app;
        
        
 
    
    
   
        // App_Mapping__c appMap = [Select Id,Name,IAM_Request_Access__c From App_Mapping__c Where Name='test app' LIMIT 1];
    Contact c=[Select id from Contact where email='testChangepassowrd@eiam.com']; 
    User loggedUser = [Select Id, isActive, Email,LastLoginDate, FederationIdentifier,UserName, ContactId, CompanyName,LanguageLocaleKey,IAM_Challenge_Question_1__c,IAM_Challenge_Question_2__c,IAM_Challenge_Question_3__c,IAM_External_User_Num__c From User Where isActive = true AND Contactid=:c.id LIMIT 1];  
     System.debug('external user number'+loggedUser.IAM_External_User_Num__c);
       System.runAs(loggedUser){
              
        
        Apexpages.currentpage().getParameters().put('selectedLanguage',loggedUser.LanguageLocaleKey);
        String startUrl = '';
        ApexPages.currentPage().getParameters().put('starturl',startUrl );
        String referUrl = 'https://www.facebook.com/';
         ApexPages.currentPage().getHeaders().put('referer',referUrl);
        //ApexPages.currentPage().getParameters().put('appid','a1a6C0000001pm0' ); //appMap.id
        ApexPages.currentPage().getParameters().put('uNumber',loggedUser.IAM_External_User_Num__c);
        IAM_CIHR_ChangePasswordController objClass=new IAM_CIHR_ChangePasswordController();
        
        
        //objClass.oldPassword = 'test123';
        //objClass.newPassword = 'test123';
        objclass.questioninput = True;
        objclass.answrquestion = False;
        objClass.challangequestion1 = 'What is your name?';
        objClass.challangequestion2 = 'In which city you stay?';
        objClass.challangequestion3 = 'What city were you born in?'; 
        ObjClass.challangeAnswer1='test';
        ObjClass.challangeAnswer2='test1';
        ObjClass.challangeAnswer3='test2';
               
        objclass.setAnswer();
        objClass.newPassword = 'verifyNewPassword';
        objclass.InvalidPass = true;
       // objclass.challangeAnswer = 'testing12';
        objclass.newpassword();
        objclass.reclaimUserCheck();
        objclass.resetAnswer();
        objclass.passerrordiv = false;        
        
        objclass.Changelanguage();
        List<SelectOption> options = objclass.getselectedquestionfields();
       }  
     }
     
     
    
    Static testMethod void test2(){
    Account a= new Account();       
        a.Name = 'Test Company1';
        a.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('IAM').getRecordTypeId();  
        a.phone = '6884382997';
        a.BillingCity='Columbus';
        a.BillingStreet='340 Brown Street';
        a.BillingCountry='United States';
        a.BillingPostalCode='47201';
        a.BillingState='Indiana';
        a.CMI_Account_Status__c='Active';
        insert a;
    
    contact Con=new contact();
        con.RecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get('IAM').getRecordTypeId();
        Con.FirstName = '1Change';
        Con.LastName = '2Password';
        Con.AccountId = a.Id;
        con.Username__c='testChangepassowrd12@eiam.com';   
        Con.Email = 'testChangepassowrd12@eiam.com';     
        Con.IAM_Internal__c = False;
        Con.IAM_Legacy_User__c=false;
        con.CMI_Contact_Type__c = 'secondary';
        Con.IAM_Contact_Status__c='Active';
        insert Con;
        
        App_Mapping__c app=new App_Mapping__c();
        app.name='test app';
        app.Back_page__c='https://login.salesforce.com/';
        app.Login_Url__c='https://www.facebook.com/';
        app.CMI_External_Start_Url__c = 'https://qs-dev.cummins.com/';        
        app.IAM_Default_Role__c='User';
        app.IAM_Authroization_Required__c = false;
        app.IAM_OAM_Resource_URL_Redirection__c = true;
        app.IAM_App_Protected_By__c='SAML';
        app.IAM_Request_Access__c = false;
        app.IAM_Different_Request_Access_URL__c = true;
        insert app;
        
        
 
    
    
   
        // App_Mapping__c appMap = [Select Id,Name,IAM_Request_Access__c From App_Mapping__c Where Name='test app' LIMIT 1];
    Contact c=[Select id from Contact where email='testChangepassowrd12@eiam.com']; 
    User loggedUser = [Select Id, isActive, Email,LastLoginDate,IAM_Challange_Answer1__c, FederationIdentifier,UserName, ContactId, CompanyName,LanguageLocaleKey,IAM_Challenge_Question_1__c,IAM_Challenge_Question_2__c,IAM_Challenge_Question_3__c,IAM_External_User_Num__c From User Where isActive = true AND Contactid=:c.id LIMIT 1];  
     System.debug('external user number'+loggedUser.IAM_External_User_Num__c);
      
       System.runAs(loggedUser){
              
        
        Apexpages.currentpage().getParameters().put('selectedLanguage',loggedUser.LanguageLocaleKey);
        String startUrl = '';
        ApexPages.currentPage().getParameters().put('starturl',startUrl );
        String referUrl = 'https://www.facebook.com/';
         ApexPages.currentPage().getHeaders().put('referer',referUrl);
        //ApexPages.currentPage().getParameters().put('appid','a1a6C0000001pm0' ); //appMap.id
        ApexPages.currentPage().getParameters().put('uNumber',loggedUser.IAM_External_User_Num__c);
        ApexPages.currentPage().getParameters().put('randomNumber','123456');
        IAM_CIHR_ChangePasswordController objClass=new IAM_CIHR_ChangePasswordController();
        
        
        //objClass.oldPassword = 'test123';
        //objClass.newPassword = 'test123';
        objclass.questioninput = True;
        objclass.answrquestion = False;
        objClass.challangequestion1 = 'In which city you stay?';
        objClass.challangequestion2 = 'In which city you stay?';
        objClass.challangequestion3 = 'In which city you stay?'; 
        ObjClass.challangeAnswer1='';
        ObjClass.challangeAnswer2='';
        ObjClass.challangeAnswer3='';
               
        ObjClass.setAnswer();
        ObjClass.reclaimUserCheck();
        ObjClass.oldPassword='Test_123';
        ObjClass.verifyNewPassword='Test_123';
        ObjClass.challangeAnswer='Test_!23';
        ObjClass.randomNumber='1231213';
       
       }  
     }
     
     
     Static testMethod void test3(){
     
     
     
        IAM_CIHR_ChangePasswordController objClass=new IAM_CIHR_ChangePasswordController();
        
        
        //objClass.oldPassword = 'test123';
        //objClass.newPassword = 'test123';
        
        objclass.questioninput = True;
        objclass.answrquestion = False;
        objClass.challangequestion1 = 'In which city you stay?';
        objClass.challangequestion2 = '';
        objClass.challangequestion3 = 'In which city you stay?'; 
        
        
               
        ObjClass.setAnswer();
        
       
     }
    
    
     Static testMethod void test4(){
     
     
     
        IAM_CIHR_ChangePasswordController objClass=new IAM_CIHR_ChangePasswordController();
        
        
        //objClass.oldPassword = 'test123';
        //objClass.newPassword = 'test123';
        
        objclass.questioninput = True;
        objclass.answrquestion = False;
        objClass.challangequestion2 = 'In which city you stay?';
        objClass.challangequestion1 = '';
        objClass.challangequestion3 = 'In which city you stay?'; 
        
        
               
        ObjClass.setAnswer();
        
       
     }
}