objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DBCode__c</fullName>
        <description>DistributorBranchCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Branch Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_WS_No_Availability__c.object
<CustomObject>
    <fields>
        <fullName>CSS_WS_After_Sales_Engineer__c</fullName>
        <label>After Sales Engineer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Attention_DR__c</fullName>
        <label>Attention DR</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Attention_Dealer__c</fullName>
        <label>Attention Dealer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Authorizer__c</fullName>
        <label>Authorizer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Brand_Unit__c</fullName>
        <label>Brand</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Client__c</fullName>
        <label>Client</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Comments__c</fullName>
        <label>Comments</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Created_By_Display__c</fullName>
        <defaultValue>IF(
   OR (CONTAINS($UserRole.Name, &quot;Distributor&quot;) 
      ,CONTAINS($UserRole.Name, &quot;distributor&quot;)
      ,CONTAINS($UserRole.Name, &quot;DISTRIBUTOR&quot;)
      )
  ,($User.FirstName + &quot; &quot; + $User.LastName)
  , IF(
       OR (CONTAINS($UserRole.Name, &quot;Factory&quot;) 
          ,CONTAINS($UserRole.Name, &quot;factory&quot;)
          ,CONTAINS($UserRole.Name, &quot;FACTORY&quot;)
          )
      ,&quot;Factory&quot;
      ,&quot;Role not allowed&quot;)
)</defaultValue>
        <label>Created by</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Creation_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Creation date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSS_WS_DR_Contact__c</fullName>
        <label>DR Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Dealer__c</fullName>
        <label>Dealer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_ESN__c</fullName>
        <label>Engine Serial Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Factory_Distribution__c</fullName>
        <label>Factory Distribution</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Model_Unit__c</fullName>
        <label>Model</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_No_attention_reason__c</fullName>
        <label>No attention reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CSS_WS_No_attention_reasons_picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_WS_Number_Unit__c</fullName>
        <label>Economic Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_OEM__c</fullName>
        <label>Original Equipment Manufacturers</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Regional_Distributor__c</fullName>
        <label>Regional Distributor</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Special_Delivery__c</fullName>
        <label>Special Delivery</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending authorization</fullName>
                </value>
                <value>
                    <fullName>Authorized by planta</fullName>
                </value>
                <value>
                    <fullName>Denied by planta</fullName>
                </value>
                <value>
                    <fullName>Authorization pending</fullName>
                    <isActive>false</isActive>
                    <label>Authorization pending</label>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                    <isActive>false</isActive>
                    <label>Authorized</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS WS No Availability</label>
    <nameField>
        <label>No Availability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS WS No Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/CSS_WS_No_attention_reasons_picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>El camino estaba accidentado</fullName>
    </customValue>
    <customValue>
        <fullName>El camino estaba muy sinuoso</fullName>
    </customValue>
    <customValue>
        <fullName>El camino estaba obstruido</fullName>
    </customValue>
    <customValue>
        <fullName>El clima adverso fué la causa de la demora</fullName>
    </customValue>
    <customValue>
        <fullName>El operador movió la unidad</fullName>
    </customValue>
    <customValue>
        <fullName>El operador no estaba en la unidad</fullName>
    </customValue>
    <customValue>
        <fullName>El primer diagnóstico fue erróneo</fullName>
    </customValue>
    <customValue>
        <fullName>Falló otro componenete del OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Falló otro componente del motor</fullName>
    </customValue>
    <customValue>
        <fullName>Fue necesario dar dos salidas</fullName>
    </customValue>
    <customValue>
        <fullName>La distancia fué la causa de la demora</fullName>
    </customValue>
    <customValue>
        <fullName>La falla no es reparable en carretera</fullName>
    </customValue>
    <customValue>
        <fullName>La falla requirió de una reparación mayor</fullName>
    </customValue>
    <customValue>
        <fullName>La ubicación dada fué errónea</fullName>
    </customValue>
    <customValue>
        <fullName>Los técnicos estaban en otro rescate</fullName>
    </customValue>
    <customValue>
        <fullName>Los técnicos estaban en taller reparando unidades</fullName>
    </customValue>
    <customValue>
        <fullName>No se autorizó la salida de los técnicos (¿Porqué?)</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía el insite</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía la Calibración</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía la herramienta electrónica</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía la herramienta mecánica</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía la Lap Top</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía la parte en el DR</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía la parte en mi almacén</fullName>
    </customValue>
    <customValue>
        <fullName>No se tenía la parte en Planta</fullName>
    </customValue>
    <customValue>
        <fullName>Otra</fullName>
    </customValue>
    <customValue>
        <fullName>Porque la zona de noche es insegura</fullName>
    </customValue>
    <customValue>
        <fullName>Volvió a presentar la misma falla</fullName>
    </customValue>
    <masterLabel>No attention reasons picklist</masterLabel>
</GlobalValueSet>

classes/CSS_WS_NoAvailabilityController_Test.cls
@isTest(SeeAllData=true)
Public Class CSS_WS_NoAvailabilityController_Test{

    Public Static TestMethod Void testMethodSave(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '54734',
            Type = 'Dealer Account',
            Name = 'DUMMY DEALER',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO');
        insert SPDLTest;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c ='A C INDUSTRIES',
            CSS_WS_Client__c ='Castores',
            CSS_WS_Comments__c ='No comments',
            CSS_WS_Created_By_Display__c ='No',
            CSS_WS_Creation_Date__c = Date.today(),
            CSS_WS_Dealer__c ='12345',
            CSS_WS_After_Sales_Engineer__c ='No',
            CSS_WS_DR_Contact__c ='73011',
            CSS_WS_Number_Unit__c ='111',
            CSS_WS_ESN__c ='11111111',
            CSS_WS_Factory_Distribution__c ='No',
            CSS_WS_Model_Unit__c ='DM1',
            CSS_WS_No_attention_reason__c ='Otra',
            CSS_WS_Attention_Dealer__c ='54699',
            CSS_WS_Attention_DR__c ='73011',
            CSS_WS_OEM__c ='No',
            CSS_WS_Regional_Distributor__c ='54734',
            CSS_WS_Special_Delivery__c ='No',
            CSS_WS_Status__c ='Draft');
            
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        controller.Save_NoAvailability_Format();
        controller.language = 'es_MX';
        controller.esn='';
        controller.model ='';
        controller.brand = '';
        controller.startDate=String.valueOf(system.today());
        controller.getPermissionSet('CSS_WS_Factory_Warranty_Manager');
        Test.stopTest();      
    }

    Public Static TestMethod Void testMethodSaveError(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account account = new Account(
            Name = 'TestAccount2',
            type = 'Dealer Account',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO',
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '54734');
        insert account;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c = 'A C INDUSTRIES',
            CSS_WS_Client__c = 'Castores',
            CSS_WS_Comments__c = 'No Comments',
            CSS_WS_Created_By_Display__c = 'No',
            CSS_WS_Creation_Date__c =  Date.today(),
            CSS_WS_Dealer__c = '12345',
            CSS_WS_After_Sales_Engineer__c = 'No',
            CSS_WS_DR_Contact__c = 'kiwl099',
            CSS_WS_Number_Unit__c = '111',
            CSS_WS_ESN__c = '11111111',
            CSS_WS_Factory_Distribution__c = 'No',
            CSS_WS_Model_Unit__c = 'DM1',
            CSS_WS_No_attention_reason__c = 'Otra',
            CSS_WS_Attention_Dealer__c = '54699',
            CSS_WS_Attention_DR__c = '73011',
            CSS_WS_OEM__c = 'No',
            CSS_WS_Regional_Distributor__c = '54734',
            CSS_WS_Special_Delivery__c = 'No',
            CSS_WS_Status__c = 'Draft');

        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        controller.Save_NoAvailability_Format();   
        controller.deletESN();
    }
        
    Public Static TestMethod Void testMethodIncompleteInfo(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '54734',
            Type = 'Dealer Account',
            Name = 'DUMMY DEALER',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO');
        insert SPDLTest;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c = 'A C INDUSTRIES',
            CSS_WS_Client__c = 'Castores',
            CSS_WS_Comments__c = null,
            CSS_WS_Created_By_Display__c = 'No',
            CSS_WS_Creation_Date__c = Date.today(),
            CSS_WS_Dealer__c = '12345',
            CSS_WS_After_Sales_Engineer__c = 'No',
            CSS_WS_DR_Contact__c = '73011',
            CSS_WS_Number_Unit__c = '111',
            CSS_WS_ESN__c = '12345678',
            CSS_WS_Factory_Distribution__c = 'No',
            CSS_WS_Model_Unit__c = 'DM1',
            CSS_WS_No_attention_reason__c = 'Otra',
            CSS_WS_Attention_Dealer__c = '54699',
            CSS_WS_Attention_DR__c = '73011',
            CSS_WS_OEM__c = 'No',
            CSS_WS_Regional_Distributor__c = '54734',
            CSS_WS_Special_Delivery__c =  null,
            CSS_WS_Status__c = 'Draft');
        
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        controller.Save_NoAvailability_Format();
        Test.stopTest();
    }
    
    Public Static TestMethod Void testMethodDealerAndDR(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '54321',
            CSS_DBCode__c = '54321',
            Type = 'Distributor Account',
            Name = 'MEGAMAK SURESTE',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO');
        insert SPDLTest;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c = 'A C INDUSTRIES',
            CSS_WS_Client__c = 'Castores',
            CSS_WS_Comments__c = 'No comments',
            CSS_WS_Created_By_Display__c = 'No',
            CSS_WS_Creation_Date__c = Date.today(),
            CSS_WS_Dealer__c = '54321',
            CSS_WS_After_Sales_Engineer__c = 'No',
            CSS_WS_DR_Contact__c = '73011',
            CSS_WS_Number_Unit__c = '111',
            CSS_WS_ESN__c = '11111111',
            CSS_WS_Factory_Distribution__c = 'No',
            CSS_WS_Model_Unit__c = 'DM1',
            CSS_WS_No_attention_reason__c = 'Otra',
            CSS_WS_Attention_Dealer__c = '54321',
            CSS_WS_Attention_DR__c = '54321',
            CSS_WS_OEM__c = 'No',
            CSS_WS_Regional_Distributor__c = '54321',
            CSS_WS_Special_Delivery__c = 'No',
            CSS_WS_Status__c = 'Draft');
              
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);   
        controller.getnaDistributorsSelectList();
        controller.getnaDealersSelectList();
        Test.stopTest();
    }

    Public Static TestMethod Void testMethodAttentionDealerAndDR(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '54321',
            CSS_DBCode__c = '54321',
            Type = 'Distributor Account',
            Name = 'MEGAMAK SURESTE',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO');
        insert SPDLTest;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c = 'A C INDUSTRIES',
            CSS_WS_Client__c = 'Castores',
            CSS_WS_Comments__c = 'No comments',
            CSS_WS_Created_By_Display__c = 'No',
            CSS_WS_Creation_Date__c = Date.today(),
            CSS_WS_Dealer__c = '54321',
            CSS_WS_After_Sales_Engineer__c = 'No',
            CSS_WS_DR_Contact__c = '73011',
            CSS_WS_Number_Unit__c = '111',
            CSS_WS_ESN__c = '11111111',
            CSS_WS_Factory_Distribution__c = 'No',
            CSS_WS_Model_Unit__c = 'DM1',
            CSS_WS_No_attention_reason__c = 'Otra',
            CSS_WS_Attention_Dealer__c = '54321',
            CSS_WS_Attention_DR__c = '54321',
            CSS_WS_OEM__c = 'No',
            CSS_WS_Regional_Distributor__c = '54321',
            CSS_WS_Special_Delivery__c = 'No',
            CSS_WS_Status__c ='Draft');
        
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);   
        controller.getnaAttentionDRSelectList();
        controller.getnaAttentionDealersSelectList();
        Test.stopTest();
    }
        
    Public Static TestMethod Void testMethodIncompleteESN(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '54734',
            Type = 'Dealer Account',
            Name = 'DUMMY DEALER',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO');
        insert SPDLTest;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c = 'A C INDUSTRIES',
            CSS_WS_Client__c = 'Castores',
            CSS_WS_Comments__c = 'No comments',
            CSS_WS_Created_By_Display__c = 'No',
            CSS_WS_Creation_Date__c = Date.today(),
            CSS_WS_Dealer__c = '12345',
            CSS_WS_After_Sales_Engineer__c = 'No',
            CSS_WS_DR_Contact__c = '73011',
            CSS_WS_Number_Unit__c = '111',
            CSS_WS_ESN__c = 'ESN',
            CSS_WS_Factory_Distribution__c = 'No',
            CSS_WS_Model_Unit__c = 'DM1',
            CSS_WS_No_attention_reason__c = 'Otra',
            CSS_WS_Attention_Dealer__c = '54699',
            CSS_WS_Attention_DR__c = '73011',
            CSS_WS_OEM__c = 'No',
            CSS_WS_Regional_Distributor__c = '54734',
            CSS_WS_Special_Delivery__c = 'No',
            CSS_WS_Status__c = 'Draft');
    
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        controller.nagetESN();
        Test.stopTest();
    }
    
    Public Static TestMethod Void testMethodNullESN(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '54743',
            Type = 'Dealer Account',
            Name = 'DUMMY DEALER',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO');
        insert SPDLTest;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c = 'A C INDUSTRIES',
            CSS_WS_Client__c = 'Castores',
            CSS_WS_Comments__c = 'No comments',
            CSS_WS_Created_By_Display__c = 'No',
            CSS_WS_Creation_Date__c = Date.today(),
            CSS_WS_Dealer__c = '12345',
            CSS_WS_After_Sales_Engineer__c = 'No',
            CSS_WS_DR_Contact__c = '73011',
            CSS_WS_Number_Unit__c = '111',
            CSS_WS_ESN__c = null,
            CSS_WS_Factory_Distribution__c = 'No',
            CSS_WS_Model_Unit__c = 'DM1',
            CSS_WS_No_attention_reason__c  = 'Otra',
            CSS_WS_Attention_Dealer__c = '54699',
            CSS_WS_Attention_DR__c = '73011',
            CSS_WS_OEM__c = 'No',
            CSS_WS_Regional_Distributor__c = '54743',
            CSS_WS_Special_Delivery__c = 'No',
            CSS_WS_Status__c = 'Draft');
        
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        controller.nagetESN();   
        Test.stopTest();
    }    
    
    Public Static TestMethod Void testMethodgetESN(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        Account SPDLTest = new Account(
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '54743',
            Type = 'Dealer Account',
            Name = 'DUMMY DEALER',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO');
        insert SPDLTest;
        
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Authorizer__c = null,
            CSS_WS_Brand_Unit__c = 'A C INDUSTRIES',
            CSS_WS_Client__c = 'Castores',
            CSS_WS_Comments__c = 'No comments',
            CSS_WS_Created_By_Display__c = 'No',
            CSS_WS_Creation_Date__c = Date.today(),
            CSS_WS_Dealer__c = '12345',
            CSS_WS_After_Sales_Engineer__c = 'No',
            CSS_WS_DR_Contact__c = '73011',
            CSS_WS_Number_Unit__c = '111',
            CSS_WS_ESN__c = '11111111',
            CSS_WS_Factory_Distribution__c = 'No',
            CSS_WS_Model_Unit__c = 'DM1',
            CSS_WS_No_attention_reason__c = 'Otra',
            CSS_WS_Attention_Dealer__c = '54699',
            CSS_WS_Attention_DR__c = '73011',
            CSS_WS_OEM__c = 'No',
            CSS_WS_Regional_Distributor__c = '54743',
            CSS_WS_Special_Delivery__c = 'No',
            CSS_WS_Status__c = 'Draft');
            
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController (NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        Test.setCurrentPage(pageRef);
        Test.setMock(HttpCalloutMock.class, new CSS_WS_WebServicesMock());       
        controller.nagetESN();
        Test.stopTest();
    }   

    Public Static TestMethod Void testMethodgetSPListDR(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Dealer__c ='12345',
            CSS_WS_Regional_Distributor__c = '12345');
        Database.insert(NoAvailability);
    
        Account account = new Account(
            Name = 'TestAccount',
            type = 'Distributor Account',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO',
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '12345');
        insert account;
                      
        Test.startTest();
        //System.runAs(user){
        ApexPages.StandardController standardController = new ApexPages.StandardController (NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        Test.setCurrentPage(pageRef);
        controller.getSPList(); 
        controller.getRouter();
        //}
        Test.stopTest();
    }

    Public Static TestMethod Void testMethodgetSPListDealer(){
        PageReference pageRef = Page.CSS_WS_NoAvailability_Form;
        CSS_WS_No_Availability__c NoAvailability = new CSS_WS_No_Availability__c(
            CSS_WS_Dealer__c ='12345',
            CSS_WS_Regional_Distributor__c = '54734');
    
        Account account = new Account(
            Name = 'TestAccount2',
            type = 'Dealer Account',
            CMI_Account_Status__c = 'Active',
            BillingCountry = 'MEXICO',
            IAM_Service_Provider_Code__c = '12345',
            CSS_DBCode__c = '54734');
        insert account;
      
        //System.runAs(user){
        ApexPages.StandardController standardController = new ApexPages.StandardController(NoAvailability); 
        CSS_WS_NoAvailabilityController controller = new CSS_WS_NoAvailabilityController(standardController);  
        Test.setCurrentPage(pageRef);
        controller.getSPList(); 
        controller.getRouter();
        //} 
    }
}