objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>WWSPS</fullName>
        <active>true</active>
        <description>Record type for all WWSPS records</description>
        <label>WWSPS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_OEM_AFFILIATIONS__c.object
<CustomObject>
    <fields>
        <fullName>AFFILIATION_ROW_ID__c</fullName>
        <description>External ID for SPAffiliations Service</description>
        <externalId>true</externalId>
        <label>AFFILIATION_ROW_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AFFILIATION__c</fullName>
        <label>AFFILIATION</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS_OEM_AFFILIATIONS</relationshipLabel>
        <relationshipName>CSS_OEM_AFFILIATIONS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAST_UPDATED_BY__c</fullName>
        <label>LAST_UPDATED_BY</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAST_UPDATED_DATE__c</fullName>
        <label>LAST_UPDATED_DATE</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRIMARY__c</fullName>
        <label>PRIMARY</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SP_CODE__c</fullName>
        <label>SP_CODE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpRowId__c</fullName>
        <label>SpRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CSS_OEM_AFFILIATIONS</label>
    <nameField>
        <label>CSS_ Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_OEM_AFFILIATIONS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FSL_SPAffilations_Stage__c.object
<CustomObject>
    <fields>
        <fullName>AffiliationRowId__c</fullName>
        <externalId>true</externalId>
        <label>AffiliationRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>Affiliation</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastUpdatedDate__c</fullName>
        <label>LastUpdatedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastUpdated_By__c</fullName>
        <label>LastUpdated By</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <label>Primary</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPCode__c</fullName>
        <label>SPCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPRowId__c</fullName>
        <label>SPRowId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>FSL_SPAffilations_Stage</label>
    <nameField>
        <label>FSL_SPAffilations_Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSL_SPAffilations_Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSLSPAffilationsInfoScheduler_Test.cls
/**********************************************************************
Name: FSLSPAffilationsInfoScheduler_Test
Copyright © 2020  Cummins
=======================================================================
=======================================================================
Purpose:    Test Class for FSLSPAffilationsInfoScheduler
=======================================================================
=======================================================================
History                                                            
-------                                                            
VERSION  AUTHOR                 DATE                DETAIL                                 
1.0     Krishnamoorthi         03/31/2020           INITIAL DEVELOPMENT                    
1.1     Vamsi
***********************************************************************/
@istest
public class FSLSPAffilationsInfoScheduler_Test 
{
	static testmethod void testScheduledJob() {
        RecordType rtbms = [SELECT id,Name 
                                FROM RecordType 
                                WHERE name='WWSPS' and sobjecttype='Account'];
								
        List<Account> accountList = new List<Account>();
        for(integer i=0; i<=5; i++) {
            Account Acc = new Account();
            Acc.Name = string.valueOf('krishna ' + i);
            Acc.recordtypeId = rtbms.Id;
            Acc.CSS_DistributorCode__c = string.valueOf(i+ '2345');
            Acc.IAM_Service_Provider_Code__c = string.valueOf('5432' + i);
            accountList.add(Acc);
        }
        insert accountList;
        
        //Test Records:
        list<CSS_OEM_AFFILIATIONS__c> testRecords = new list<CSS_OEM_AFFILIATIONS__c>();
        for(integer i=0; i<=10; i++) {
            CSS_OEM_AFFILIATIONS__c testR = new CSS_OEM_AFFILIATIONS__c();
            testR.AFFILIATION__c = string.valueOf('krishna ' + i);
            testR.LAST_UPDATED_BY__c = string.valueOf('moorthi ' + i);
            testR.PRIMARY__c = string.valueOf('nkm ' + i);
            //testR.SP_CODE__c = fslspAff.SPCode__c;
            testR.SpRowId__c = string.valueOf('nkm ' + i);
            testR.AFFILIATION_ROW_ID__c = string.valueOf('ARID-' + i);	//External Id - unique Key
            testR.LAST_UPDATED_DATE__c = string.valueOf(Date.Today());
            //testR.account__c = mapSpCodeAccountId.get(fslspAff.SPCode__c); //Map Account Id as lookup Id 
            testRecords.add(testR);
        }
        insert testRecords;
        
        //Batch Records:
        list<FSL_SPAffilations_Stage__c> listRecords = new list<FSL_SPAffilations_Stage__c>();
        for(integer i=0; i<=75; i++) {
            FSL_SPAffilations_Stage__c record = new FSL_SPAffilations_Stage__c();
            record.Name = string.valueOf('krishna ' + i);
            record.Affiliation__c = string.valueOf('krishna ' + i);
            record.LastUpdated_By__c = string.valueOf('moorthi ' + i);
            record.Primary__c = string.valueOf('nkm ' + i);
            record.SPCode__c = string.valueOf('5432' + i);
            record.SPRowId__c = string.valueOf('812-' + i);
            record.AffiliationRowId__c = string.valueOf('ARID-' + i);
            record.LastUpdatedDate__c = Date.Today();
            listRecords.add(record);
        }
        insert listRecords;
        
    	Test.startTest();
		FSLSPAffilationsInfoScheduler sh1 = new FSLSPAffilationsInfoScheduler();
		String sch = '0 0 23 * * ?'; 
    	system.schedule('FSL SP Affilations Info Scheduler', sch, sh1); 
    	Test.stoptest();
    }
}