objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>Component_Id__c</fullName>
        <description>Captures the Component or Failure ID for the Repair</description>
        <label>Component Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Component__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected Component</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Job for this Component</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solutions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Solutions linked to the Component</description>
        <label>CSS Solutions</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>Failure Selected By Technician</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A field to differentiate Camp,TRP &amp; ATCs from Solution Component</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Diagnostic_Response__c</fullName>
        <description>Values for Verification</description>
        <label>Diagnostic Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not the solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Repair_Response__c</fullName>
        <label>Repair Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair Successful.</fullName>
                </value>
                <value>
                    <fullName>Repair Successful with additional parts/procedures.</fullName>
                </value>
                <value>
                    <fullName>Repair performed but didnot resolve the root cause.</fullName>
                </value>
                <value>
                    <fullName>Repair not performed.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup for Service Job object that stores the  Job order number associated with it.</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_SRT__c.object
<CustomObject>
    <fields>
        <fullName>Access_Code_A__c</fullName>
        <label>Access Code A</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Component ID for this Repair</description>
        <label>CSS Solution Component</label>
        <referenceTo>CSS_Solution_Component__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRT_AccessiblityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accessiblity CheckBox Option from the SRT Table</description>
        <label>SRT AccessiblityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRT_Category__c</fullName>
        <label>SRT Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_ID__c</fullName>
        <label>SRT ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Quantity__c</fullName>
        <label>SRT Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SRT_Time__c</fullName>
        <label>SRT Time</label>
        <precision>13</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solution_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution Number</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diagnosis</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Diag Access</fullName>
                </value>
                <value>
                    <fullName>Repair Access</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>99Time</fullName>
                </value>
                <value>
                    <fullName>Overlap</fullName>
                </value>
                <value>
                    <fullName>Field Action</fullName>
                </value>
                <value>
                    <fullName>Field Action Access</fullName>
                </value>
                <value>
                    <fullName>BMS SRT</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS SRT</label>
    <nameField>
        <label>CSS SRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS SRTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSS_DARSRT_RO_Test.cls
@isTest
public class CSS_DARSRT_RO_Test {
    public static testMethod void testAddSRT() { 
        
        
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        
        CSS_Job_Order__c JO1 = new CSS_Job_Order__c();
        JO1.Customer_Name__c = 'CumminsTnD';
        JO1.Equipment_ID__c = 'EQ7667';
        JO1.Qsol_Engine_Family_Code__c ='56';
        JO1.AccessCode__c = 'A';
        JO1.Account__c=acc.id;
        insert JO1;
        
        css_solutions__c sol = new css_solutions__c();
        sol.Service_Job__c=jo1.id;
        insert sol;
        
        CSS_Solution_Component__c solcomp = new CSS_Solution_Component__c();
        solComp.Service_Job__c=jo1.Id;
        insert solcomp;
        
        PageReference pg = Page.CSS_JobTnDRj;
        
        Test.setCurrentPage(pg);    
        ApexPages.currentPage().getParameters().put('id', JO1.Id);
        
        List<CSS_SRT__C> lstsrt = new List<CSS_SRT__C>();
        CSS_SRT__C srtRef = new CSS_SRT__C();
        srtRef.Solution_Number__c = null;
        srtRef.Job_Order__c = JO1.id;
        srtRef.SRT_AccessiblityCheck__c=True;
        srtRef.Access_Code_A__c = 65;
        srtRef.name = 'TestClassName';
        srtRef.SRT_ID__c = '00-901-00';
        insert srtRef;
        lstsrt.add(srtRef); 
        
        PageReference pref = new PageReference('/'+JO1.id);
        pref.getParameters().put('id',JO1.id);
        Test.setCurrentPage(pref);
        
        test.startTest();          
        CSS_DARSRT_RO srta = new CSS_DARSRT_RO(); 
        srta.lstDisplayDiagSRT = lstsrt;
        // srta.searchValue='Testing';
        Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        // srta.getDiagnosisSRTs();
        srta.gotoJobPlanSrt();
        //srta.searchDiagSRTCodeAndDescription();
        //srta.getRepairSRTs();
        //  srta.saveDiagBox();
        //    srta.saveRepBox();
        //   srta.getsVfComp();
        //   srta.getRepairAccessTime();
        //srta.getrepairTime();
        //  srta.getDiagAccessTime();
        //  srta.getAllACS();
        //   srta.changeDownOrder();
        //   srta.setsVfComp(JO1.id);
        //   srta.getallData();
        //   srta.searchSRTCodeAndDescription();
        //   srta.showPopup();
        //   srta.closePopup();
        //    srta.showPopup1();
        //    srta.closePopup1();
        //    srta.getdiagnosisTime();
        //    srta.getrepairTime();
        //    srta.changeUpOrder();
        //    srta.saveDiagData();
        //    srta.saveRepairData();
        srta.diagTotal= true;
        srta.repAccTime= 'test';
        
        
        test.stopTest();
        //CSS_WS_SRT wssrt = new CSS_WS_SRT();
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Diagnostic');  
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Repair');  
    }
    
    public static testMethod void testAddSRT_Method1() { 
        
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        CSS_Job_Order__c JO1 = new CSS_Job_Order__c();
        JO1.Account__c=acc.id;
        JO1.Customer_Name__c = 'CumminsTnD';
        JO1.Equipment_ID__c = 'EQ7667';
        JO1.Qsol_Engine_Family_Code__c ='56';
        JO1.AccessCode__c = 'A';
        insert JO1;
        
        css_solutions__c sol = new css_solutions__c();
        sol.Diagnostic_Response__c = 'Most likely the solution';
        sol.Service_Job__c=jo1.id;
        insert sol;
        
        CSS_Solution_Component__c solcomp = new CSS_Solution_Component__c();
        solComp.Component_Id__c ='F0051111';
        solComp.Service_Job__c=jo1.Id;
        solComp.Solutions__c = sol.id;
        insert solcomp;
        
        PageReference pg = Page.CSS_JobTnDRj;
        
        Test.setCurrentPage(pg);    
        ApexPages.currentPage().getParameters().put('id', JO1.Id);
        
        List<CSS_SRT__C> lstsrt = new List<CSS_SRT__C>();
        CSS_SRT__C srtRef = new CSS_SRT__C();
        srtRef.Solution_Number__c = sol.Id;
        srtRef.Component_Id__c = solcomp.id;
        srtRef.Job_Order__c = JO1.id;
        srtRef.SRT_AccessiblityCheck__c=True;
        srtRef.Access_Code_A__c = 65;
        srtRef.name = 'TestClassName';
        srtRef.SRT_ID__c = '00-901-00';
        srtRef.Type__c = 'Repair';
        srtRef.Assignment__c = 'Primary';
        insert srtRef;
        lstsrt.add(srtRef);
        
        //insert lstsrt;
        
        PageReference pref = new PageReference('/'+JO1.id);
        pref.getParameters().put('id',JO1.id);
        Test.setCurrentPage(pref);
        
        test.startTest();          
        CSS_DARSRT_RO srta = new CSS_DARSRT_RO(); 
        srta.lstDisplayDiagSRT = lstsrt;
        ///    srta.searchValue='00-901-00';
        Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        //    srta.getDiagnosisSRTs();
        srta.gotoJobPlanSrt();
        //    srta.searchDiagSRTCodeAndDescription();
        //    srta.getRepairSRTs();
        //    srta.saveDiagBox();
        //    srta.saveRepBox();
        //    srta.getsVfComp();
        //    srta.getRepairAccessTime();
        //srta.getrepairTime();
        //     srta.getDiagAccessTime();
        //    srta.getAllACS();
        //    srta.changeDownOrder();
        //    srta.setsVfComp(JO1.id);
        //    srta.getallData();
        //    srta.searchSRTCodeAndDescription();
        //    srta.showPopup();
        //    srta.closePopup();
        //    srta.showPopup1();
        //    srta.closePopup1();
        //    srta.getdiagnosisTime();
        //    srta.getrepairTime();
        //    srta.changeUpOrder();
        //    srta.saveDiagData();
        //    srta.saveRepairData();
        srta.diagTotal= true;
        srta.repAccTime= 'test';
        
        
        test.stopTest();
        //CSS_WS_SRT wssrt = new CSS_WS_SRT();
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Diagnostic');  
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Repair');  
    }
    
    public static testMethod void testAddSRT_Method2() { 
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        CSS_Job_Order__c JO1 = new CSS_Job_Order__c();
        JO1.Account__c=acc.id;
        JO1.Customer_Name__c = 'CumminsTnD';
        JO1.Equipment_ID__c = 'EQ7667';
        JO1.Qsol_Engine_Family_Code__c ='56';
        JO1.AccessCode__c = 'A';
        insert JO1;
        
        css_solutions__c sol = new css_solutions__c();
        sol.Diagnostic_Response__c = 'Most likely the solution';
        sol.Service_Job__c=jo1.id;
        insert sol;
        
        CSS_Solution_Component__c solcomp = new CSS_Solution_Component__c();
        solComp.Service_Job__c=jo1.Id;
        insert solcomp;
        
        PageReference pg = Page.CSS_JobTnDRj;
        
        Test.setCurrentPage(pg);    
        ApexPages.currentPage().getParameters().put('id', JO1.Id);
        
        List<CSS_SRT__C> lstsrt = new List<CSS_SRT__C>();
        CSS_SRT__C srtRef1 = new CSS_SRT__C();
        srtRef1.Solution_Number__c = sol.Id;
        srtRef1.Job_Order__c = JO1.id;
        srtRef1.SRT_AccessiblityCheck__c=True;
        srtRef1.Access_Code_A__c = 65;
        srtRef1.name = 'TestClassName';
        srtRef1.SRT_ID__c = '00-901-01';
        srtRef1.Type__c = 'Diag Access';
        insert srtRef1;
        lstsrt.add(srtRef1);
        
        //insert lstsrt;
        
        PageReference pref = new PageReference('/'+JO1.id);
        pref.getParameters().put('id',JO1.id);
        Test.setCurrentPage(pref);
        
        test.startTest();          
        CSS_DARSRT_RO srta = new CSS_DARSRT_RO(); 
        srta.lstDisplayDiagSRT = lstsrt;
        //    srta.searchValue='Testing';
        Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        //    srta.getDiagnosisSRTs();
        srta.gotoJobPlanSrt();
        //    srta.searchDiagSRTCodeAndDescription();
        //    srta.getRepairSRTs();
        //    srta.saveDiagBox();
        //    srta.saveRepBox();
        //    srta.getsVfComp();
        //srta.getRepairAccessTime();
        //srta.getrepairTime();
        //    srta.getDiagAccessTime();
        //    srta.getAllACS();
        //    srta.changeDownOrder();
        //    srta.setsVfComp(JO1.id);
        //    srta.getallData();
        //    srta.searchSRTCodeAndDescription();
        //    srta.showPopup();
        //    srta.closePopup();
        //    srta.showPopup1();
        //    srta.closePopup1();
        //    srta.getdiagnosisTime();
        //srta.getrepairTime();
        //   srta.changeUpOrder();
        //    srta.saveDiagData();
        //   srta.saveRepairData();
        srta.diagTotal= true;
        srta.repAccTime= 'test';
        
        
        test.stopTest();
        //CSS_WS_SRT wssrt = new CSS_WS_SRT();
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Diagnostic');  
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Repair');  
    }
    
    public static testMethod void testAddSRT_Method3() { 
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        CSS_Job_Order__c JO1 = new CSS_Job_Order__c();
        JO1.Account__c=acc.id;
        JO1.Customer_Name__c = 'CumminsTnD';
        JO1.Equipment_ID__c = 'EQ7667';
        JO1.Qsol_Engine_Family_Code__c ='56';
        JO1.AccessCode__c = 'A';
        insert JO1;
        
        css_solutions__c sol = new css_solutions__c();
        sol.Diagnostic_Response__c = 'Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        sol.Service_Job__c=jo1.id;
        insert sol;
        
        List<CSS_Solution_Component__c> solcompList = new List<CSS_Solution_Component__c>();
        CSS_Solution_Component__c solcomp = new CSS_Solution_Component__c();
        solComp.Component_Id__c ='F0051000';
        solComp.Service_Job__c=jo1.Id;
        solcompList.add(solcomp);
        
        CSS_Solution_Component__c solcomp1 = new CSS_Solution_Component__c();
        solComp1.Component_Id__c ='F0051011';
        solComp1.Service_Job__c=jo1.Id;
        solComp1.Selected_Component__c = true;
        solComp1.Solutions__c = sol.id;
        solcompList.add(solcomp1);
        
        insert solcompList;
        
        List<CSS_SRT__C> lstsrt = new List<CSS_SRT__C>();
        CSS_SRT__C srtRef1 = new CSS_SRT__C();
        srtRef1.Solution_Number__c = sol.Id;
        srtRef1.Job_Order__c = JO1.id;
        srtRef1.SRT_AccessiblityCheck__c=True;
        srtRef1.Access_Code_A__c = 65;
        srtRef1.name = 'TestClassName';
        srtRef1.SRT_ID__c = '00-901-01';
        srtRef1.Type__c = 'Repair Access';
        srtRef1.Assignment__c = 'Primary';
        srtRef1.SRT_Quantity__c = 1;
        //insert srtRef1;
        lstsrt.add(srtRef1);
        
        
        CSS_SRT__C srtRef = new CSS_SRT__C();
        srtRef.Solution_Number__c = sol.Id;
        srtRef.Job_Order__c = JO1.id;
        srtRef.Component_Id__c = solcompList[1].id;
        srtRef.SRT_AccessiblityCheck__c=True;
        srtRef.Access_Code_A__c = 65;
        srtRef.name = 'TestClassName';
        srtRef.SRT_ID__c = '00-901-02';
        srtRef.Type__c = 'Repair';
        srtRef.Assignment__c = 'Primary';
        srtRef.SRT_Quantity__c = 1;
        //insert srtRef1;
        lstsrt.add(srtRef);
        
        insert lstsrt;
        
        test.startTest(); 
        PageReference pg = Page.CSS_JobTnDRj;
        Test.setCurrentPage(pg);    
        ApexPages.currentPage().getParameters().put('id', JO1.Id);        
        CSS_DARSRT_RO srta = new CSS_DARSRT_RO(); 
        srta.lstDisplayDiagSRT = lstsrt;
        //      srta.searchValue='Testing';
        Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        //      srta.getDiagnosisSRTs();
        srta.gotoJobPlanSrt();
        //      srta.searchDiagSRTCodeAndDescription();
        //      srta.getRepairSRTs();
        //      srta.saveDiagBox();
        //      srta.saveRepBox();
        //      srta.getsVfComp();
        //srta.getRepairAccessTime();
        //srta.getrepairTime();
        //       srta.getDiagAccessTime();
        //      srta.getAllACS();
        //      srta.changeDownOrder();
        //      srta.setsVfComp(JO1.id);
        //      srta.getallData();
        //      srta.searchSRTCodeAndDescription();
        //     srta.showPopup();
        //      srta.closePopup();
        //      srta.showPopup1();
        //       srta.closePopup1();
        //       srta.getdiagnosisTime();
        //srta.getrepairTime();
        //       srta.changeUpOrder();
        //       srta.saveDiagData();
        //       srta.saveRepairData();
        srta.diagTotal= true;
        srta.repAccTime= 'test';
        
        
        test.stopTest();
        //CSS_WS_SRT wssrt = new CSS_WS_SRT();
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Diagnostic');  
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Repair');  
    }
    
    public static testMethod void testAddSRT_Method3_1() { 
        
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        CSS_Job_Order__c JO1 = new CSS_Job_Order__c();
        JO1.Account__c=acc.id;
        JO1.Customer_Name__c = 'CumminsTnD';
        JO1.Equipment_ID__c = 'EQ7667';
        JO1.Qsol_Engine_Family_Code__c ='56';
        JO1.AccessCode__c = 'A';
        insert JO1;
        
        css_solutions__c sol = new css_solutions__c();
        sol.Diagnostic_Response__c = 'Most likely the solution';
        sol.Repair_Response__c = 'Most likely';
        sol.Service_Job__c=jo1.id;
        insert sol;
        
        List<CSS_Solution_Component__c> solcompList = new List<CSS_Solution_Component__c>();
        CSS_Solution_Component__c solcomp = new CSS_Solution_Component__c();
        solComp.Component_Id__c ='F0051000';
        solComp.Service_Job__c=jo1.Id;
        solcompList.add(solcomp);
        
        CSS_Solution_Component__c solcomp1 = new CSS_Solution_Component__c();
        solComp1.Component_Id__c ='F0051011';
        solComp1.Service_Job__c=jo1.Id;
        solComp1.Selected_Component__c = true;
        solComp1.Solutions__c = sol.id;
        solcompList.add(solcomp1);
        
        insert solcompList;
        
        List<CSS_SRT__C> lstsrt = new List<CSS_SRT__C>();
        CSS_SRT__C srtRef1 = new CSS_SRT__C();
        srtRef1.Solution_Number__c = sol.Id;
        srtRef1.Job_Order__c = JO1.id;
        srtRef1.SRT_AccessiblityCheck__c=True;
        srtRef1.Access_Code_A__c = 65;
        srtRef1.name = 'TestClassName';
        srtRef1.SRT_ID__c = '00-901-01';
        srtRef1.Type__c = 'Repair Access';
        srtRef1.Assignment__c = 'Primary';
        srtRef1.SRT_Quantity__c = 1;
        //insert srtRef1;
        lstsrt.add(srtRef1);
        
        
        CSS_SRT__C srtRef = new CSS_SRT__C();
        srtRef.Solution_Number__c = sol.Id;
        srtRef.Job_Order__c = JO1.id;
        srtRef.Component_Id__c = solcompList[1].id;
        srtRef.SRT_AccessiblityCheck__c=True;
        srtRef.Access_Code_A__c = 65;
        srtRef.name = 'TestClassName';
        srtRef.SRT_ID__c = '00-901-02';
        srtRef.Type__c = 'Repair';
        srtRef.Assignment__c = 'Primary';
        srtRef.SRT_Quantity__c = 1;
        //insert srtRef1;
        lstsrt.add(srtRef);
        
        insert lstsrt;
        
        test.startTest(); 
        PageReference pg = Page.css_srtEditPopup;
        Test.setCurrentPage(pg);    
        ApexPages.currentPage().getParameters().put('id', JO1.Id);        
        CSS_DARSRT_RO srta = new CSS_DARSRT_RO(); 
        srta.lstDisplayDiagSRT = lstsrt;
        //       srta.searchValue='Testing';
        Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        //       srta.getDiagnosisSRTs();
        srta.gotoJobPlanSrt();
        //       srta.searchDiagSRTCodeAndDescription();
        //       srta.getRepairSRTs();
        //       srta.saveDiagBox();
        //       srta.saveRepBox();
        //       srta.getsVfComp();
        //srta.getRepairAccessTime();
        //srta.getrepairTime();
        //        srta.getDiagAccessTime();
        //        srta.getAllACS();
        //        srta.changeDownOrder();
        //        srta.setsVfComp(JO1.id);
        //        srta.getallData();
        //        srta.searchSRTCodeAndDescription();
        //        srta.showPopup();
        //        srta.closePopup();
        //        srta.showPopup1();
        //        srta.closePopup1();
        //        srta.getdiagnosisTime();
        //srta.getrepairTime();
        //        srta.changeUpOrder();
        //        srta.saveDiagData();
        //        srta.saveRepairData();
        srta.diagTotal= true;
        srta.repAccTime= 'test';
        
        
        test.stopTest();
        //CSS_WS_SRT wssrt = new CSS_WS_SRT();
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Diagnostic');  
        CSS_WS_SRT.getAllDigRepSRTs(JO1.ID,'Repair');  
    }
    
    public static testMethod void testAddSRT_Method4() { 
        
        
        Account acc = new Account();
        acc.name='Kenworth Sales Co';
        acc.CSS_DistributorCode__c='02466';
        acc.IAM_Service_Provider_Code__c='19134';
        acc.Type='Dealer Account';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        CSS_Job_Order__c JO1 = new CSS_Job_Order__c();
        JO1.Account__c=acc.id;
        JO1.Customer_Name__c = 'CumminsTnD';
        JO1.Equipment_ID__c = 'EQ7667';
        JO1.Qsol_Engine_Family_Code__c ='56';
        JO1.AccessCode__c = 'A';
        insert JO1;
        
        css_solutions__c sol = new css_solutions__c();
        sol.Service_Job__c=jo1.id;
        insert sol;
        
        CSS_Solution_Component__c solcomp = new CSS_Solution_Component__c();
        solComp.Service_Job__c=jo1.Id;
        insert solcomp;
        
        List<CSS_SRT__C> lstsrt = new List<CSS_SRT__C>();
        CSS_SRT__C srtRef = new CSS_SRT__C();
        srtRef.Job_Order__c = JO1.id;
        srtRef.SRT_AccessiblityCheck__c=True;
        srtRef.Access_Code_A__c = 65;
        srtRef.name = 'TestClassName';
        srtRef.SRT_ID__c = '128969';
        srtRef.srt_category__c = 'AdditionalDiag';
        srtRef.type__c = 'Access';
        srtRef.SRT_Quantity__c = 1;
        srtRef.SRT_Time__c = 1;
        insert srtRef;
        lstsrt.add(srtRef); 
        
        PageReference pref = new PageReference('/'+JO1.id);
        pref.getParameters().put('id',JO1.id);
        Test.setCurrentPage(pref);
        
        test.startTest();    
        PageReference pg = Page.CSS_JobTnDRj;
        
        Test.setCurrentPage(pg);    
        ApexPages.currentPage().getParameters().put('id', JO1.Id);
        CSS_DARSRT_RO srta = new CSS_DARSRT_RO(); 
        srta.lstDisplayDiagSRT = lstsrt;
        //       srta.searchValue='128969';
        //       srta.searchDiagValue='128969';
        Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
        Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        //       srta.getDiagnosisSRTs();
        srta.gotoJobPlanSrt();
        //       srta.searchDiagSRTCodeAndDescription();
        //      srta.getRepairSRTs();
        //       srta.saveDiagBox();
        //        srta.saveRepBox();
        //        srta.getsVfComp();
        //srta.getRepairAccessTime();
        //srta.getrepairTime();
        //        srta.getDiagAccessTime();
        //        srta.getAllACS();
        //        srta.changeDownOrder();
        //        srta.setsVfComp(JO1.id);
        //        srta.getallData();
        //        srta.searchSRTCodeAndDescription();
        //        srta.showPopup();
        //        srta.closePopup();
        //        srta.showPopup1();
        //        srta.closePopup1();
        //        srta.getdiagnosisTime();
        //srta.getrepairTime();
        //        srta.changeUpOrder();
        //        srta.saveDiagData();
        //        srta.saveRepairData();
        srta.diagTotal= true;
        srta.repAccTime= 'test';
        
        
        test.stopTest();
        
    }
    
}