objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>IAM</fullName>
        <active>true</active>
        <description>Please use this only for creating non-WWSPS managed locations (Fleet, Individual, Business, etc.). For any Service Provider additions cancel this creation and please visit and use existing WWSPS process.</description>
        <label>IAM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__PaymentMethod__c</fullName>
        <description>The payment method defined in E_PaymentDetail__c.Payment_Method__c.</description>
        <label>Payment Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dbu_StoreCode__c</fullName>
        <description>This field gets updated with store pickup locations store code when customer selects particular store in checkout page</description>
        <label>dbu StoreCode</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbu_storeLanguage__c</fullName>
        <label>dbu storeLanguage</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__PaymentMethod__c</fullName>
        <description>The payment method defined in E_PaymentDetail__c.Payment_Method__c.</description>
        <label>PaymentMethod</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dbu_BMS_Tracking_Number__c</fullName>
        <label>dbu BMS Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>dbu_StoreCode__c</fullName>
        <label>dbu StoreCode</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
    <description>Transaction payments represent payments made to the system.</description>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that created this transaction payment.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{0000000000}</displayFormat>
        <label>CC Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Transaction Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>IAM</fullName>
        <active>true</active>
        <description>Please use this for creating external users, for creating Cummins users please follow WWIMS process. After creating user, please assign needed Application-Role&apos;s by clicking on &quot;Assign App/Feature&quot; to complete user setup without which user cannot access.</description>
        <label>IAM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/dbu_orderProductDetailsEmailCtrl_Test.cls
@isTest
public class dbu_orderProductDetailsEmailCtrl_Test 
{
    public static testMethod void getPaypalPayment(){
        Id iamRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IAM').getRecordTypeId();
        Id ContactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('IAM').getRecordTypeId();
        Account createAccount= dbu_TestDataCreationUtility.createAccount(iamRecordTypeId);
        insert createAccount;
        Contact createContact= dbu_TestDataCreationUtility.createContact(createAccount, ContactRecordTypeId);
        insert createContact;
        ccrz__E_Product__c createProduct= dbu_TestDataCreationUtility.createProduct();
        insert createProduct;
        ccrz__E_Cart__c createCart= dbu_TestDataCreationUtility.createCart();
        createCart.dbu_storeLanguage__c = 'US';
        insert createCart;
        ccrz__E_CartItem__c createCartItem= dbu_TestDataCreationUtility.createCartItem(createProduct.Id,createCart.Id);
        insert createCartItem;
        ccrz__E_ContactAddr__c createContactAddr= dbu_TestDataCreationUtility.createContactAddr();
        insert createContactAddr;
        ccrz__E_ContactAddr__c createContactAddr1= dbu_TestDataCreationUtility.createContactAddr1();
        insert createContactAddr1;
        ccrz__E_Order__c createOrder= dbu_TestDataCreationUtility.createOrder(createContact.Id,createCart.Id,createContactAddr.id,createContactAddr1.id);
        createOrder.ccrz__User__c = UserInfo.getUserId();
        createOrder.ccrz__PaymentMethod__c = 'PayPal';
        createOrder.dbu_BMS_Tracking_Number__c = '111,112';
        insert createOrder;
        ccrz__E_OrderItem__c createOrderItem= dbu_TestDataCreationUtility.createOrderItem(createOrder.Id,createProduct.Id,createCartItem.Id);
        insert createOrderItem;
        List<String> listOrderIds = New List<String>();
        listOrderIds.add(createOrder.id);
        ccrz__E_TransactionPayment__c createTransPayment= dbu_TestDataCreationUtility.createTransactionPayment(createOrder.Id);
        insert createTransPayment;
        ccrz__E_ProductMedia__c createProductMedia=dbu_TestDataCreationUtility.createProductMedia(createProduct.Id);
        insert createProductMedia;
        

        ccrz__E_Cart__c objCart = new ccrz__E_Cart__c();
        objCart.dbu_StoreCode__c = 'test';
        objCart.Id = createCart.Id;
        update objCart;
        
        dbu_orderProductDetailsEmailController objCls = new dbu_orderProductDetailsEmailController();
        objCls.orderId = createOrder.Id;
        List<dbu_orderProductDetailsEmailController.orderItemWrapper> getOrderItems = objCls.getOrderItems();
        List<dbu_orderProductDetailsEmailController.orderItemWrapper> getOrderItemsPickup = objCls.getOrderItemsPickup();
        List<dbu_orderProductDetailsEmailController.orderItemWrapper> getAllOrderItems = objCls.getAllOrderItems();
        dbu_orderProductDetailsEmailController.TrackingNumberWrapper getTrackingNumber = objCls.getTrackingNumber();
   
    }
    public static testMethod void getPaypalPaymentEN(){
        Id iamRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IAM').getRecordTypeId();
        Id ContactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('IAM').getRecordTypeId();
        Account createAccount= dbu_TestDataCreationUtility.createAccount(iamRecordTypeId);
        insert createAccount;
        Contact createContact= dbu_TestDataCreationUtility.createContact(createAccount, ContactRecordTypeId);
        insert createContact;
        ccrz__E_Product__c createProduct= dbu_TestDataCreationUtility.createProduct();
        insert createProduct;
        ccrz__E_Cart__c createCart= dbu_TestDataCreationUtility.createCart();
        createCart.dbu_storeLanguage__c = 'EN';
        insert createCart;
        ccrz__E_CartItem__c createCartItem= dbu_TestDataCreationUtility.createCartItem(createProduct.Id,createCart.Id);
        insert createCartItem;
        ccrz__E_ContactAddr__c createContactAddr= dbu_TestDataCreationUtility.createContactAddr();
        insert createContactAddr;
        ccrz__E_ContactAddr__c createContactAddr1= dbu_TestDataCreationUtility.createContactAddr1();
        insert createContactAddr1;
        ccrz__E_Order__c createOrder= dbu_TestDataCreationUtility.createOrder(createContact.Id,createCart.Id,createContactAddr.id,createContactAddr1.id);
        createOrder.ccrz__User__c = UserInfo.getUserId();
        createOrder.ccrz__PaymentMethod__c = 'PayPal';
        createOrder.dbu_BMS_Tracking_Number__c = '111,112';
        insert createOrder;
        ccrz__E_OrderItem__c createOrderItem= dbu_TestDataCreationUtility.createOrderItem(createOrder.Id,createProduct.Id,createCartItem.Id);
        insert createOrderItem;
        List<String> listOrderIds = New List<String>();
        listOrderIds.add(createOrder.id);
        ccrz__E_TransactionPayment__c createTransPayment= dbu_TestDataCreationUtility.createTransactionPayment(createOrder.Id);
        insert createTransPayment;
        ccrz__E_ProductMedia__c createProductMedia=dbu_TestDataCreationUtility.createProductMedia(createProduct.Id);
        insert createProductMedia;
        

        ccrz__E_Cart__c objCart = new ccrz__E_Cart__c();
        objCart.dbu_StoreCode__c = 'test';
        objCart.Id = createCart.Id;
        update objCart;
        
        dbu_orderProductDetailsEmailController objCls = new dbu_orderProductDetailsEmailController();
        objCls.orderId = createOrder.Id;
        List<dbu_orderProductDetailsEmailController.orderItemWrapper> getOrderItems = objCls.getOrderItems();
        List<dbu_orderProductDetailsEmailController.orderItemWrapper> getOrderItemsPickup = objCls.getOrderItemsPickup();
        List<dbu_orderProductDetailsEmailController.orderItemWrapper> getAllOrderItems = objCls.getAllOrderItems();
        dbu_orderProductDetailsEmailController.TrackingNumberWrapper getTrackingNumber = objCls.getTrackingNumber();
   
    }
}