objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMI_Cummins_Support_Email__c</fullName>
        <label>Cummins Support Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMI_Cummins_Support_First_Name__c</fullName>
        <label>Cummins Support First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMI_Cummins_Support_Last_Name__c</fullName>
        <label>Cummins Support Last Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMI_Other_Fault_Notifications_Email__c</fullName>
        <label>Other Fault Notifications Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMI_Other_Fault_Notifications__c</fullName>
        <label>Other Fault Notifications</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OnCommand</fullName>
                </value>
                <value>
                    <fullName>Saucon TDS Fault Code Response Interface</fullName>
                </value>
                <value>
                    <fullName>No System</fullName>
                    <default>true</default>
                    <label>No System</label>
                </value>
                <value>
                    <fullName>Galaxy Telematics</fullName>
                    <isActive>false</isActive>
                    <label>Galaxy Telematics</label>
                </value>
                <value>
                    <fullName>Other Customer System</fullName>
                    <isActive>false</isActive>
                    <label>Other Customer System</label>
                </value>
                <value>
                    <fullName>Tata Fleetman</fullName>
                    <isActive>false</isActive>
                    <label>Tata Fleetman</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMI_Telematics_Service_Provider__c</fullName>
        <label>Telematics Service Provider</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Eye</fullName>
                </value>
                <value>
                    <fullName>Copiloto Satelital</fullName>
                </value>
                <value>
                    <fullName>DriverTech</fullName>
                </value>
                <value>
                    <fullName>Faria Entelnet</fullName>
                </value>
                <value>
                    <fullName>Fleet Complete</fullName>
                </value>
                <value>
                    <fullName>Geotab</fullName>
                </value>
                <value>
                    <fullName>Hyundai Construction Equipment</fullName>
                </value>
                <value>
                    <fullName>KomtraxPlus</fullName>
                </value>
                <value>
                    <fullName>LHP Telematics</fullName>
                </value>
                <value>
                    <fullName>Microlise</fullName>
                </value>
                <value>
                    <fullName>omnitracs</fullName>
                </value>
                <value>
                    <fullName>OnCommand Link</fullName>
                </value>
                <value>
                    <fullName>PACCAR Solutions</fullName>
                </value>
                <value>
                    <fullName>peoplenet</fullName>
                </value>
                <value>
                    <fullName>RoadAdvisor</fullName>
                </value>
                <value>
                    <fullName>Saucon</fullName>
                </value>
                <value>
                    <fullName>Shaw Tracking</fullName>
                </value>
                <value>
                    <fullName>Specto</fullName>
                </value>
                <value>
                    <fullName>Traffilog</fullName>
                </value>
                <value>
                    <fullName>zonar</fullName>
                </value>
                <value>
                    <fullName>Other TSP</fullName>
                </value>
                <value>
                    <fullName>IDEX Fire &amp; Safety</fullName>
                </value>
                <value>
                    <fullName>KMAP</fullName>
                </value>
                <value>
                    <fullName>Streamline</fullName>
                </value>
                <value>
                    <fullName>Platform Science</fullName>
                </value>
                <value>
                    <fullName>Cummins</fullName>
                </value>
                <value>
                    <fullName>India_Edge</fullName>
                </value>
                <value>
                    <fullName>Edison</fullName>
                </value>
                <value>
                    <fullName>Navistar</fullName>
                </value>
                <value>
                    <fullName>Infobric</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMI_Urgent_Fault_Notification_Email__c</fullName>
        <label>Urgent Fault Notification Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CMI_Urgent_Fault_Notification__c</fullName>
        <label>Urgent Fault Notification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saucon TDS Fault Code Response Interface</fullName>
                </value>
                <value>
                    <fullName>OnCommand</fullName>
                </value>
                <value>
                    <fullName>No System</fullName>
                    <default>true</default>
                    <label>No System</label>
                </value>
                <value>
                    <fullName>Equitel&apos;s Response system</fullName>
                    <isActive>false</isActive>
                    <label>Equitel&apos;s Response system</label>
                </value>
                <value>
                    <fullName>FWTelematics Portal</fullName>
                    <isActive>false</isActive>
                    <label>FWTelematics Portal</label>
                </value>
                <value>
                    <fullName>Galaxy Telematics</fullName>
                    <isActive>false</isActive>
                    <label>Galaxy Telematics</label>
                </value>
                <value>
                    <fullName>LHP Telematics system</fullName>
                    <isActive>false</isActive>
                    <label>LHP Telematics system</label>
                </value>
                <value>
                    <fullName>Other Customer System</fullName>
                    <isActive>false</isActive>
                    <label>Other Customer System</label>
                </value>
                <value>
                    <fullName>PCI System</fullName>
                    <isActive>false</isActive>
                    <label>PCI System</label>
                </value>
                <value>
                    <fullName>RoadAdvisor System</fullName>
                    <isActive>false</isActive>
                    <label>RoadAdvisor System</label>
                </value>
                <value>
                    <fullName>Saucon System</fullName>
                    <isActive>false</isActive>
                    <label>Saucon System</label>
                </value>
                <value>
                    <fullName>Tata Fleetman</fullName>
                    <isActive>false</isActive>
                    <label>Tata Fleetman</label>
                </value>
                <value>
                    <fullName>TecnoMotum system</fullName>
                    <isActive>false</isActive>
                    <label>TecnoMotum system</label>
                </value>
                <value>
                    <fullName>Witronix</fullName>
                    <isActive>false</isActive>
                    <label>Witronix</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CMI_CustomerpageTest1.cls
@isTest
public with sharing class CMI_CustomerpageTest1 {
    static testMethod void simpleTests() {
        PageReference pageRef = Page.CMI_CompanyReg;
        Account a = new account();
        contact c = new contact();
        ApexPages.StandardController controller=new ApexPages.StandardController(a);
        CMI_Customerpage re=new CMI_Customerpage(controller);
        a.CMI_Urgent_Fault_Notification__c = 'Email';
        a.CMI_Other_Fault_Notifications__c = 'Email';
        a.name='';
        try{
            re.send();
            
        }catch (exception e){
            
        }
    }
    
    static testMethod void simpleTests2() {
        Account  a=new Account();
        Contact c= new Contact();
        PageReference pageRef = Page.CMI_CompanyReg;
        //Test.setCurrentPageReference(pageRef);
        apexPages.StandardController controller=new ApexPages.StandardController(a);
        CMI_Customerpage re=new CMI_Customerpage(controller);
        a.CMI_Urgent_Fault_Notification__c = 'Email';
        a.CMI_Other_Fault_Notifications__c = 'Email';
        a.name='';
        a.Name='Cummins';
        a.BillingStreet='303 washington street';
        a.BillingCity='Columbus';
        a.BillingPostalCode='47201';
        c.FirstName='Keerthy';
        c.LastName='Guru';
        c.Email='abc@gmail.com';
        c.phone='3198765489';  
        a.CMI_Cummins_Support_First_Name__c='Cummins';
        a.CMI_Cummins_Support_Last_Name__c='CS';
        a.CMI_Cummins_Support_Email__c='abc1@gmail.com';
        a.CMI_Telematics_Service_Provider__c='Other';
        a.CMI_Urgent_Fault_Notification__c  ='Email';  
        a.CMI_Other_Fault_Notifications__c='Email';
        //a.CMI_Urgent_Fault_Notification_Email__c='test@gmail.com';
        a.CMI_Other_Fault_Notifications_Email__c='test1@gmail.com';
        CMI_Customerpage re2=new CMI_Customerpage(controller);
        try{
            re2.send();
            
        }catch (exception e){
            
        }try{
            re.reset();
            
        }catch (exception e){
            
        }
        try{
            re.getURL();
            
        }catch (exception e){
            
        }
    }
}