objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_ERP_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>ERP Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FSL_Source_ERP__c</fullName>
        <defaultValue>CASE($User.ERP__c, &quot;BMS&quot;, &quot;BMS&quot;, &quot;MOVEX&quot;, &quot;MOVEX&quot;, &quot;MOVEX-MYD&quot;, &quot;MOVEX-MYD&quot;, &quot;MOVEX-UK&quot;, &quot;MOVEX-UK&quot;, &quot;MOVEX-190&quot;,&quot;MOVEX-190&quot;,&quot;MOVEX-200&quot;,&quot;MOVEX-200&quot;,&quot;MOVEX-250&quot;,&quot;MOVEX-250&quot;,&quot;MOVEX-270&quot;,&quot;MOVEX-270&quot;,&quot;MOVEX-175&quot;,&quot;MOVEX-175&quot;,&quot;MOVEX-CDK&quot;,&quot;MOVEX-CDK&quot;,&quot;MOVEX-CSP&quot;,&quot;MOVEX-CSP&quot;,&quot;&quot;)</defaultValue>
        <label>Source ERP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BMS</fullName>
                </value>
                <value>
                    <fullName>MOVEX</fullName>
                </value>
                <value>
                    <fullName>MOVEX-MYD</fullName>
                </value>
                <value>
                    <fullName>MOVEX-UK</fullName>
                </value>
                <value>
                    <fullName>MOVEX-190</fullName>
                </value>
                <value>
                    <fullName>MOVEX-200</fullName>
                </value>
                <value>
                    <fullName>MOVEX-250</fullName>
                </value>
                <value>
                    <fullName>MOVEX-270</fullName>
                </value>
                <value>
                    <fullName>MOVEX-175</fullName>
                </value>
                <value>
                    <fullName>MOVEX-CSP</fullName>
                </value>
                <value>
                    <fullName>MOVEX-CDK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address.object
<CustomObject>
    <fields>
        <fullName>FSL_Site_ID__c</fullName>
        <externalId>true</externalId>
        <label>Site ID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Site_Name__c</fullName>
        <label>Site Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IAM Site</label>
        <referenceTo>IAM_CDH_Cross_references__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Site for the Asset</description>
        <label>Site</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>IAM_CDH_Cross_references__c.IAM_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>IAM_CDH_Cross_references__c.FSL_Site_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>IAM_CDH_Cross_references__c.FSL_Site_Status__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IAM_CDH_Cross_references__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_PSN__c</fullName>
        <externalId>true</externalId>
        <label>Type-PSN</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engines</fullName>
                    <default>true</default>
                    <label>Engines</label>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>FIREPUMP</fullName>
                </value>
                <value>
                    <fullName>ENGINE</fullName>
                </value>
                <value>
                    <fullName>GENSET</fullName>
                </value>
                <value>
                    <fullName>ENGINE CORE</fullName>
                </value>
                <value>
                    <fullName>SWITCH GEAR</fullName>
                </value>
                <value>
                    <fullName>TRANSFER SWITCH</fullName>
                </value>
                <value>
                    <fullName>TRANSMISSIONS</fullName>
                </value>
                <value>
                    <fullName>BATTERY</fullName>
                </value>
                <value>
                    <fullName>PARSYS</fullName>
                </value>
                <value>
                    <fullName>MARINE GEAR</fullName>
                </value>
                <value>
                    <fullName>ONAN</fullName>
                </value>
                <value>
                    <fullName>REFRIG</fullName>
                </value>
                <value>
                    <fullName>KOMATSU EQUIPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FSL_Contact_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reclaim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Contact_source__c</fullName>
        <label>Contact source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SwReg</fullName>
                </value>
                <value>
                    <fullName>OIM</fullName>
                </value>
                <value>
                    <fullName>QSOL Service Accounts</fullName>
                </value>
                <value>
                    <fullName>FCP</fullName>
                </value>
                <value>
                    <fullName>QSOL</fullName>
                </value>
                <value>
                    <fullName>LDAP</fullName>
                </value>
                <value>
                    <fullName>WEB</fullName>
                    <default>true</default>
                    <label>WEB</label>
                </value>
                <value>
                    <fullName>MoveX</fullName>
                </value>
                <value>
                    <fullName>PC</fullName>
                </value>
                <value>
                    <fullName>Penske</fullName>
                </value>
                <value>
                    <fullName>Ryder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>This field is being added as part of wave initiative story number 9322</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IAM_CDH_Cross_references__c.object
<CustomObject>
    <fields>
        <fullName>FSL_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_MoveX_Contact_Id__c</fullName>
        <label>Contact Id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_MoveX_Site_Id__c</fullName>
        <externalId>true</externalId>
        <label>Site Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IAM_CDH_Cross_references</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IAM Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IAM Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>FSL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (1 AND 2 AND 4)</booleanFilter>
            <errorMessage>Please select an Active Guidanz Account!</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guidanz-Cash, Guidanz</value>
            </filterItems>
            <filterItems>
                <field>Account.CMI_Account_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Account.FSL_Source_ERP__c</field>
                <operation>equals</operation>
                <valueField>$User.ERP__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>CSS Integration</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FSL_Contact_ID__c</fullName>
        <label>Contact ID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DEALER</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-BRANCH</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-HEADQUARTERS</fullName>
                </value>
                <value>
                    <fullName>GROUP</fullName>
                </value>
                <value>
                    <fullName>HOLSET - DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>INDUSTRIAL/VOCATIONAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FSL_UpdateSiteToAddressBatch_Test.cls
@isTest
public class FSL_UpdateSiteToAddressBatch_Test{
    @testsetup
    public static void createTestData(){
        Id accRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
        Account acc = new Account();
        acc.RecordTypeId = accRecId;
        acc.FSL_ERP_Customer_Code__c = '102686';
        acc.Name = 'Test Acc';
        acc.Cmi_account_status__c = 'Active';
        acc.Type = 'Customer';
        //added by Harsha
        acc.FSL_Source_ERP__c = 'BMS';
        insert acc;
        
        
        
        Contact con = new Contact();
        con.FirstName = 'Travis';
        con.LastName = 'Grigg';
        con.AccountId = acc.Id;
        con.FSL_Contact_Id__c = '40';
        con.Phone = '(042) 988-3045';
        con.Email = 'test@test.com';
        con.IAM_Contact_Status__c = 'Inactive';
        //con.Mobile_Phone__c='1234567890'; // Migrating from Mobile_Phone__c custom field to MobilePhone standard field
        con.MobilePhone ='1234567890';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
        // con.IAM_Contact_source__c = 'BMS';
        insert con;
        
        IAM_CDH_Cross_references__c objSite1 = new IAM_CDH_Cross_references__c();
        objSite1.Name = 'TestNew';
        objSite1.IAM_Account__c = acc.Id;
        objSite1.FSL_MoveX_Contact_Id__c = '10';
        objSite1.FSL_MoveX_Site_Id__c = '1';
        objSite1.FSL_City__c = 'Brisbane';
        insert objSite1;
        
        Schema.Location loc = new Schema.Location();
        loc.Name = 'TestNew';
        loc.FSL_Account__c = acc.Id;
        loc.FSL_Contact_ID__c = '10';
        insert loc;
        
        Schema.Address addr = new Schema.Address();
        addr.parentId = loc.id;
        addr.FSL_Site_Name__c = 'TestNew';
        addr.FSL_Site_ID__c = '1';
        addr.street = '123 street';
        addr.City = 'Brisbane';
        addr.IAM_Site__c = objSite1.id;
        addr.state = 'Alabama';
        addr.postalCode = '12345';
        addr.country = 'United States';
        insert addr;
        
        
        Asset asset1 = new Asset();
        asset1.Name = '342819';
        asset1.Type_PSN__c = 'External-78';
        asset1.Type__c = 'Engines';
        asset1.AccountId = acc.Id;
        asset1.FSL_Site__c = addr.Id;
        asset1.Site__c = objSite1.id;
        insert asset1;
        
        OperatingHours objOperatingHours = new OperatingHours();
        objOperatingHours.Name = 'Test OperatingHours';
        objOperatingHours.Description = 'Test OperatingHours';
        insert objOperatingHours;
        
        ServiceTerritory objServiceTerritory = new ServiceTerritory();
        objServiceTerritory.Name = 'Test ServiceTerritory In Shop OR Mobile';
        objServiceTerritory.IsActive = true;
        objServiceTerritory.Location_Code__c = '12345-12345';
        objServiceTerritory.FSL_Service_Territory_Code__c = '1234-1234';
        objServiceTerritory.OperatingHoursId = objOperatingHours.Id;
        objServiceTerritory.Region__c = 'AUSTRALIA/ NEW ZEALAND';
        objServiceTerritory.Territory__c = 'AUSTRALIA';
        insert objServiceTerritory;
        
        WorkOrder objWorkOrder = new WorkOrder();
        objWorkOrder.ServiceTerritoryId = objServiceTerritory.Id;
        objWorkOrder.Status = 'Intake';
        objWorkOrder.Process_Step__c = 'Intake';
        objWorkOrder.AccountId = acc.Id;
        objWorkOrder.AssetId = asset1.Id;
        objWorkOrder.Shop_Work_Order__c='49440';
        objWorkOrder.Repair_Site_Name__c = objSite1.id;
        insert objWorkOrder;
    }
    
    @isTest
    public static void testWorkOrder(){
        FSL_UpdateSiteToAddressBatch batchObj = new FSL_UpdateSiteToAddressBatch('WorkOrder');
        Database.executeBatch(batchObj);
    }
    
    @isTest
    public static void testAsset(){
        FSL_UpdateSiteToAddressBatch batchObj = new FSL_UpdateSiteToAddressBatch('Asset');
        Database.executeBatch(batchObj);
    }
}