objects/Account.object
<CustomObject>
    <fields>
        <fullName>FSL_ERP_Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>ERP Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to Store Region Value based on SP code</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Used to store Territory value based on SP code</description>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CSS</fullName>
        <active>true</active>
        <label>CSS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_PSN__c</fullName>
        <externalId>true</externalId>
        <label>Type-PSN</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engines</fullName>
                    <default>true</default>
                    <label>Engines</label>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>FIREPUMP</fullName>
                </value>
                <value>
                    <fullName>ENGINE</fullName>
                </value>
                <value>
                    <fullName>GENSET</fullName>
                </value>
                <value>
                    <fullName>ENGINE CORE</fullName>
                </value>
                <value>
                    <fullName>SWITCH GEAR</fullName>
                </value>
                <value>
                    <fullName>TRANSFER SWITCH</fullName>
                </value>
                <value>
                    <fullName>TRANSMISSIONS</fullName>
                </value>
                <value>
                    <fullName>BATTERY</fullName>
                </value>
                <value>
                    <fullName>PARSYS</fullName>
                </value>
                <value>
                    <fullName>MARINE GEAR</fullName>
                </value>
                <value>
                    <fullName>ONAN</fullName>
                </value>
                <value>
                    <fullName>REFRIG</fullName>
                </value>
                <value>
                    <fullName>KOMATSU EQUIPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FSL_Contact_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Guidanz</fullName>
        <active>true</active>
        <description>To be used for Customer records from ERP</description>
        <label>Guidanz</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>FSL_Contact_ID__c</fullName>
        <label>Contact ID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>FSL_Service_Territory_Code__c</fullName>
        <description>Territory Code of the Service Location</description>
        <inlineHelpText>Territory Code of the Service Location</inlineHelpText>
        <label>Service Territory Code</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <label>Location Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DEALER</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-BRANCH</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-HEADQUARTERS</fullName>
                </value>
                <value>
                    <fullName>GROUP</fullName>
                </value>
                <value>
                    <fullName>HOLSET - DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>INDUSTRIAL/VOCATIONAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FSL_JobContactInfo_Test.cls
//Sriprada - Added Comment to deploy changes as part of mule integration updates 
//Shirisha- Added Named Credentials
@isTest
public class FSL_JobContactInfo_Test {
    @testSetup static void dataSetup() 
    {
        Id accRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
        Account acc = new Account();
        acc.RecordTypeId = accRecId;
        acc.Name = 'Test Account';
        acc.FSL_ERP_Customer_Code__c = '11234';
        insert acc;
        
        Id conRecId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
        Contact con=new Contact();
        con.RecordTypeId = conRecId;
        con.FirstName='Steve';
        con.LastName='Johnson';
        con.Phone='1234567890';
        con.AccountId=acc.id;
        //con.FSL_Contact_Id__c= con.Id;
        insert con;
        
        OperatingHours  oh = new OperatingHours ();
        oh.Name = 'new';
        oh.TimeZone = 'America/Chicago';
        insert oh;
        
        ServiceTerritory sT = new ServiceTerritory(); 
        sT.Name = 'ST001 Mobile';
        sT.OperatingHoursId = oh.Id;
        st.IsActive = true;
        sT.Location_Code__c = '05340-05351';
        sT.FSL_Service_Territory_Code__c = '05351';
        sT.Region__c = 'AUSTRALIA/ NEW ZEALAND';
        sT.Territory__c = 'AUSTRALIA';
        Insert sT;
        
        Asset asst = new Asset();
        asst.Name = '79704393';
        asst.Type_PSN__c = 'Engines-79704393';
        asst.Type__c = 'Engines';
        insert asst;
        
        Id WORecId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Guidanz').getRecordTypeId();
        WorkOrder wo    = new WorkOrder();
        wo.RecordTypeId = WORecId;
        wo.AssetId      = asst.Id;
        wo.AccountId    = acc.Id;
        wo.Payer__c     = acc.Id;
        wo.ServiceTerritoryId = sT.Id;
        wo.Status       = 'Intake';
        wo.Category1__c = 'Leak';
        wo.Process_Step__c = 'Intake';
        wo.ContactId = con.Id;
        wo.Shop_Work_Order__c = 'test1012';
        wo.Application__c = '130 - AUTOMOTIVE';
        //wo.createdDate=system.now().addDays(-29);
        wo.Repair_Location__c = 'Mobile';
        // wo.Failure_Date__c = system.now().addDays(-29);
        insert wo;
        
    }
    
    @isTest static void testCalloutForContactCreate()
    {
        // Set mock callout class 
        
        WorkOrder wo = new WorkOrder();
        wo = [Select id,Account.FSL_ERP_Customer_Code__c,Payer_ContactID__c,Payer__c,Payer__r.FSL_ERP_Customer_Code__c,ContactID from WorkOrder where Shop_Work_Order__c = 'test1012' Limit 1];
        Test.setMock(HttpCalloutMock.class, new FSL_MockTest());
        test.startTest();
        FSL_JobContactInfo.checkContactId(wo.id,wo.Account.FSL_ERP_Customer_Code__c);
        FSL_JobContactInfo.checkPayerContactId(wo.id,wo.Payer__r.FSL_ERP_Customer_Code__c);
        test.stopTest();
    }
    //Added Changes for Named Credentials
    @isTest static void testCalloutDirect()
    {
       Workorder wo = [Select id,Account.FSL_ERP_Customer_Code__c,Payer_ContactID__c,Payer__c,Payer__r.FSL_ERP_Customer_Code__c,ContactID from WorkOrder where Shop_Work_Order__c = 'test1012' Limit 1];
        Test.setMock(HttpCalloutMock.class, new FSL_MockTest());
        Test.startTest();
        FSL_JobContactInfo.updatePayerContactId('{"Header": {"Sender": {"ServiceName": "CreateUpdateContact","SenderID": "CSS"},"Target": {"TargetID": "MOVEX"},"Location": {"LocationID": "05340-05351"}},"DataArea": {"DistributorCode": "05340","BranchCode": "05351","JobContactName": "TRAVIS G","JobContactPhone": "041 842 1993","CustomerCode": "1310102","ContactID": "","JobContactEmail": "aaron.hilton@cummins.com","EmailNotAvailable": "Y","CSSJobID": "00002045","EmailNotification":"Y","TextNotification":"Y", "NightlyCommunication":"N", "LanguagePreference":"EN","MobilePhoneNumber":"3323456789"}}',wo.id);
        Test.stopTest();
    }
}