objects/Account.object
<CustomObject>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>ccrz__Contact__r.FirstName +&apos; &apos;+ccrz__Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OSMSecondaryEmail__c</fullName>
        <label>OSM Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Purchased_By_User_Type__c</fullName>
        <label>Purchased By User Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_SSOEM_Customer_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Branch Customer Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Should_Show_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Price To SSOEM User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this order was placed for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this order was placed for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isOnBehalf__c</fullName>
        <formula>IF( ((ccrz__Contact__r.IAM_Contact_Owner__r.Id &lt;&gt; CreatedById &amp;&amp; Purchased_By_User_Type__c = &apos;Distributor Admin&apos; )|| (ccrz__User__c &lt;&gt; CreatedById) || (ccrz__Contact__r.IAM_Contact_Owner__r.Id &lt;&gt; CreatedById &amp;&amp; Purchased_By_User_Type__c = &apos;SSOEM Admin&apos;) || (ccrz__Contact__r.IAM_Contact_Owner__r.Id &lt;&gt; CreatedById &amp;&amp; Purchased_By_User_Type__c = &apos;Reseller Admin&apos;)) , true, false)


/*
IF( ((ccrz__Contact__r.IAM_Contact_Owner__r.Id &lt;&gt; CreatedById &amp;&amp; CONTAINS(CreatedBy.Profile.Name, &apos;Distributor&apos;) &amp;&amp; CONTAINS(CreatedBy.Profile.Name, &apos;Admin&apos;))|| (ccrz__User__c &lt;&gt; CreatedById) || (ccrz__Contact__r.IAM_Contact_Owner__r.Id &lt;&gt; CreatedById &amp;&amp; Purchased_By_User_Type__c = &apos;SSOEM Admin&apos;)) , true, false) 
*/

/*
comment this condition to fix the issue 599 and 687
|| ISBLANK(ccrz__Contact__r.IAM_Contact_Owner__r.Id)

*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>On Behalf</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>ccrz__Order__r.ccrz__Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OSM_Revocation_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OSM Revocation Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Revoke Initiated</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Subscription__c.object
<CustomObject>
    <description>This is a subscription, the record of purchased subscription</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CC_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OSM_Display_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OSM Display Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Subscriptions (OSM Display Product)</relationshipLabel>
        <relationshipName>CC_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OSM_Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account associated with this subscription.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__CCOrderItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to original order item used to create this subscription.</description>
        <label>CC Order Item</label>
        <referenceTo>ccrz__E_OrderItem__c</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__CCOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to original order used to create this subscription.</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product that this subscription is for.  When recurring orders are used this is the product that will be ordered.</description>
        <label>Subscription Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionStartDate__c</fullName>
        <description>The start date of the subscription</description>
        <label>Subscription Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionStatus__c</fullName>
        <description>The status of the subscription</description>
        <label>Subscription Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User associated with the subscription</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Subscription</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>CC Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OSM_Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Batch_Failure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Batch Failure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Batch_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Batch Log</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_of_Jobs_Failed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Jobs Failed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OSM Integration Log</label>
    <nameField>
        <displayFormat>OSM- {0000000000}</displayFormat>
        <label>OSM Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_Subscription_RevokedAlertbatch.cls
global class OSM_Subscription_RevokedAlertbatch implements Database.Batchable<sObject>, Database.Stateful{
    
    global Database.QueryLocator start(Database.BatchableContext BC){        
        
        return Database.getQueryLocator([Select id,ccrz__CCOrder__r.ccrz__Contact__c,ccrz__CCOrder__r.OSMSecondaryEmail__c,ccrz__CCOrder__r.ccrz__Contact__r.Email,ccrz__CCOrder__r.ccrz__User__c,OSM_Display_Product__r.name,
                                         ccrz__SubscriptionProduct__r.Name,ccrz__SubscriptionStartDate__c,ccrz__SubscriptionStatus__c,OwnerId,Contact__c,
                                         OSM_Subscription_End_Date__c,ccrz__CCOrder__r.Should_Show_Price__c,ccrz__CCOrderItem__c,ccrz__CCOrder__r.ccrz__Account__r.BillingCountry,ccrz__CCOrderItem__r.id,
                                         ccrz__CCOrder__r.isOnBehalf__c,ccrz__Account__r.Name,ccrz__Account__r.IAM_Service_Provider_Code__c,ccrz__CCOrder__r.Send_SSOEM_Customer_Email__c,ccrz__CCOrder__r.Purchased_By_User_Type__c
                                         from ccrz__E_Subscription__c 
                                         where ccrz__CCOrderItem__r.Revocation_Status__c='Revoked' AND ccrz__CCOrderItem__r.OSM_Revocation_Email_Sent__c=false]); 
        // and id='a3W1F000000ikUv']);
    }
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_Subscription__c> scope){
        Set<String> emailtemplateName = new Set<String>{'OSM_SW_Revoke_Temp', 'OSM_SW_Revoke_Temp_SSOEM'};  
            EmailTemplate tempRevoke;
        EmailTemplate tempRevokeSSOEM;
        for(EmailTemplate temp : [Select id, Name from EmailTemplate where name IN: emailtemplateName]){
            if(temp.Name == 'OSM_SW_Revoke_Temp'){
                tempRevoke = temp;
            }  
            if(temp.Name == 'OSM_SW_Revoke_Temp_SSOEM'){
                tempRevokeSSOEM = temp;
            }  
        }
        Messaging.Email[] messages = new List<Messaging.SingleEmailMessage>();
        
        String[] toaddress = new String[]{}; 
            
            //List<ccrz__E_Subscription__c> subList = new List<ccrz__E_Subscription__c>();
            list<ccrz__E_OrderItem__c> items = new list<ccrz__E_OrderItem__c>();
            for(ccrz__E_Subscription__c sub: scope){
                
                toaddress.add(sub.ccrz__CCOrder__r.ccrz__Contact__r.Email);
                toaddress.add(sub.ccrz__CCOrder__r.OSMSecondaryEmail__c);
                //if(intervalValues.contins(intDays)){
                
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                
                if(Label.OSM_SSOEM_Admin_UserType != sub.ccrz__CCOrder__r.Purchased_By_User_Type__c){
                    email = Messaging.renderStoredEmailTemplate(tempRevoke.id, sub.ccrz__CCOrder__r.ccrz__Contact__c, sub.id);
                    email.setTargetObjectId(sub.ccrz__CCOrder__r.ccrz__User__c);
                    if(sub.ccrz__SubscriptionProduct__r.Name.Contains('INCAL')){
                        toaddress.add(Label.INCAL_EmailAddress);
                    }
                    
                    if(sub.ccrz__CCOrder__r.ccrz__Account__r.BillingCountry == 'United States'){
                        email.setToAddresses(toaddress);
                    }
                    email.setTemplateId(tempRevoke.id);
                    email.setSaveAsActivity(false);
                    for(OrgWideEmailAddress owa : [select id, Address, DisplayName from OrgWideEmailAddress where Address='noreply.identity@cummins.com']) 
                    {
                        email.setOrgWideEmailAddressId(owa.id); 
                    }
                    
                    email.setSubject(sub.ccrz__Account__r.Name+'('+sub.ccrz__Account__r.IAM_Service_Provider_Code__c +') '+'subscriptions have been revoked');
                    System.debug('email--if1--'+email);
                    messages.add(email);
                }
                if((Label.OSM_SSOEM_Admin_UserType == sub.ccrz__CCOrder__r.Purchased_By_User_Type__c) && ((sub.ccrz__CCOrder__r.Send_SSOEM_Customer_Email__c == True) || (sub.ccrz__CCOrder__r.Send_SSOEM_Customer_Email__c == False))){
                    email = Messaging.renderStoredEmailTemplate(tempRevoke.id, sub.ccrz__CCOrder__r.ccrz__Contact__c, sub.id);
                    email.setTargetObjectId(sub.ccrz__CCOrder__r.ccrz__User__c);
                    email.setTemplateId(tempRevoke.id);
                    if(sub.ccrz__SubscriptionProduct__r.Name.Contains('INCAL')){
                        toaddress.add(Label.INCAL_EmailAddress);
                        email.setToAddresses(toaddress);
                    }
                    email.setSaveAsActivity(false);
                    for(OrgWideEmailAddress owa : [select id, Address, DisplayName from OrgWideEmailAddress where Address='noreply.identity@cummins.com']) 
                    {
                        email.setOrgWideEmailAddressId(owa.id); 
                    }
                    email.setSubject(sub.ccrz__Account__r.Name +'('+sub.ccrz__Account__r.IAM_Service_Provider_Code__c +') '+'subscriptions have been revoked');
                    System.debug('email--if2--'+email);
                    messages.add(email);
                }
                if((Label.OSM_SSOEM_Admin_UserType == sub.ccrz__CCOrder__r.Purchased_By_User_Type__c) && (sub.ccrz__CCOrder__r.isOnBehalf__c== True) && (sub.ccrz__CCOrder__r.Send_SSOEM_Customer_Email__c == True)){
                    email = Messaging.renderStoredEmailTemplate(tempRevokeSSOEM.id, sub.ccrz__CCOrder__r.ccrz__Contact__c, sub.id);
                    email.setTargetObjectId(sub.ccrz__CCOrder__r.ccrz__Contact__c);
                    email.setTemplateId(tempRevokeSSOEM.id);
                    if(sub.ccrz__SubscriptionProduct__r.Name.Contains('INCAL')){
                        toaddress.add(Label.INCAL_EmailAddress);
                        email.setToAddresses(toaddress);
                    }
                    email.setSaveAsActivity(false);
                    for(OrgWideEmailAddress owa : [select id, Address, DisplayName from OrgWideEmailAddress where DisplayName='noreply.identity@cummins.com']) 
                    {
                        email.setOrgWideEmailAddressId(owa.id); 
                    }
                    email.setSubject(sub.ccrz__Account__r.Name +'('+sub.ccrz__Account__r.IAM_Service_Provider_Code__c +') '+'subscriptions have been revoked');
                    System.debug('email-if3---'+email);
                    messages.add(email);
                } 
                
                items.add(new ccrz__E_OrderItem__c(id=sub.ccrz__CCOrderItem__r.id,OSM_Revocation_Email_Sent__c=true));
            }
        
        
        If(messages.size()>0){
            if(!test.isRunningTest()){
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages); 
                system.debug('Send Eamil to user'+messages);
                Database.upsert(items);
            }
        }
        
        
    }    
    global void finish(Database.BatchableContext BC){
        OSM_Integration_Log__c log = new OSM_Integration_Log__c();
        log.Service_Name__c='OSM_Subscription_RevokedAlertbatch' ;
        log.Internal_Batch_Log__c=true;
        AsyncApexJob jobstatus = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        log.Status__c = jobstatus.Status;
        if(jobstatus.Status=='Completed'){
            log.Status__c = 'Processed'; 
        }else if(jobstatus.Status=='Failed'){
            log.Internal_Batch_Failure__c=true;
            log.No_of_Jobs_Failed__c=jobstatus.NumberOfErrors;
        }
        insert log;
        
    }
}