objects/Account.object
<CustomObject>
    <fields>
        <fullName>OSM_Market_Segment_Code__c</fullName>
        <description>Populates the OSM Market Segment Code depending on the Primary Market Segment</description>
        <formula>CASE( IAM_Primary_Market_Segment__c , &quot;Bus&quot;, &quot;BUS&quot;, &quot;Automotive&quot;, &quot;OHT&quot;, &quot;Railcar&quot;, &quot;RAIL&quot;, &quot;Mining&quot; , &quot;MIN&quot;,&quot;Oil &amp; Gas&quot; ,&quot;OIL&quot; ,&quot;DEF&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Populates the OSM Market Segment Code depending on the Primary Market Segment</inlineHelpText>
        <label>OSM Market Segment Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OSM_Preferred_Payment_Method__c</fullName>
        <label>OSM Preferred Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>cc</fullName>
                </value>
                <value>
                    <fullName>po</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>QSOL_Power_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QSOL Power Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantityperunit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of items that come in one order-able unit</description>
        <label>Quantityperunit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_RequestForQuote__c.object
<CustomObject>
    <fields>
        <fullName>Accept_or_Reject_Date__c</fullName>
        <label>Accept or Reject Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <formula>CC_SubProdTerm__r.Billing_Display_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Use to keep product for which request being send</description>
        <label>CC Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Requests For Quote</relationshipLabel>
        <relationshipName>CC_Requests_For_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_SubProdTerm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC SubProdTerm</label>
        <referenceTo>ccrz__E_SubProdTerm__c</referenceTo>
        <relationshipLabel>CC Requests For Quote</relationshipLabel>
        <relationshipName>CC_Requests_For_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_Subscription__c</fullName>
        <label>Cost/Subscription(Month)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discounted_Price__c</fullName>
        <label>Discounted Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Request For Quote</label>
    <nameField>
        <displayFormat>RFQ-{000000}</displayFormat>
        <label>RFQ Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Requests For Quote</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_SubProdTerm__c.object
<CustomObject>
    <description>B2B Commerce product subscription definition.</description>
    <fields>
        <fullName>Billing_Display_Name__c</fullName>
        <label>Billing Display Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__DisplayName__c</fullName>
        <description>The name of this subscription.  Used as a parameter for other Display Name fields.</description>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC SubProdTerm</label>
    <nameField>
        <label>CC SubProdTerm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC SubProdTerms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Subscription__c.object
<CustomObject>
    <description>This is a subscription, the record of purchased subscription</description>
    <fields>
        <fullName>OSM_Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccrz__RecurringPrice__c</fullName>
        <description>Individual unit price for the installment.</description>
        <label>Recurring Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SPT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sub prod term this subscription was ordered from</description>
        <label>SPT</label>
        <referenceTo>ccrz__E_SubProdTerm__c</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The product that this subscription is for.  When recurring orders are used this is the product that will be ordered.</description>
        <label>Subscription Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionStatus__c</fullName>
        <description>The status of the subscription</description>
        <label>Subscription Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CC Subscription</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>CC Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OSM_SW_ProductDetaiServiceCls.cls
/**
 *      @author             Vineet 
 *      @date               17/05/2018
 *      @description        ProductDetaiServiceCls

        Modification Log:
        ------------------------------------------------------------------------------------
        Developer                       Date                Description
        ------------------------------------------------------------------------------------
        Vineet                         17/05/2018           Initial Setup
        
 */
public without sharing class OSM_SW_ProductDetaiServiceCls {


public static DiscountedPriceWrapper getDiscountedPrice(String store, String accountId, Set<String> prodIds){
    boolean isActiveSubs = false;
     DiscountedPriceWrapper activeSubs = new DiscountedPriceWrapper();
        activeSubs.isRFQ = false;
        activeSubs.isSubscribed = false;
    activeSubs.hasValidQuote = false;
        activeSubs.subscriptionProduct = '';
    activeSubs.subscriptionStatus = '';
                    activeSubs.STP = '';
                    activeSubs.recurringPrice = 0;
    
    //List<ccrz__E_Subscription__c> accountSubscriptions = OSM_SW_ProdDetailUtils_Ctrl.getAccountSubscription(accountId, prodIds, store);
    List<ccrz__E_Subscription__c> accountSubscriptions = OSM_SW_ProdDetailUtils_Ctrl.getAccountSubscription(accountId, store);
    if(accountSubscriptions.size()>0){
        activeSubs.accountSubscriptions = accountSubscriptions;
    }
    for(ccrz__E_Subscription__c sub : accountSubscriptions){
        if(prodIds.Contains(sub.ccrz__SubscriptionProduct__c)){
            isActiveSubs = true; 
        //ccrz__SPT__r.Billing_Display_Name__c,OSM_Subscription_End_Date__c
            activeSubs.isSubscribed = true;
            activeSubs.subscriptionProduct = sub.ccrz__SubscriptionProduct__c;
            activeSubs.isQSOLPowerGenProduct = sub.ccrz__SubscriptionProduct__r.QSOL_Power_Generation__c;
                    activeSubs.subscriptionStatus = sub.ccrz__SubscriptionStatus__c;
                    activeSubs.STP = sub.ccrz__SPT__c;
              activeSubs.billingFrequency = sub.ccrz__SPT__r.Billing_Display_Name__c;
              activeSubs.subsEndDate = sub.OSM_Subscription_End_Date__c;
                  activeSubs.recurringPrice = sub.ccrz__RecurringPrice__c;
                activeSubs.subsLength = sub.ccrz__SPT__r.ccrz__DisplayName__c;
              activeSubs.subscriptionId = sub.Id;
             // break;
        }
        
        if(!prodIds.Contains(sub.ccrz__SubscriptionProduct__c) && !sub.ccrz__SPT__r.Billing_Display_Name__c.ContainsIgnoreCase('One')){
            activeSubs.otherProductSubscriptions = sub;
      activeSubs.hasValidQuote = true;
            //break;
        }
    }
   /* if(Test.isRunningTest()){
        isActiveSubs = false;
    } */
     Set<String> quoteStatus = new Set<String>{'Requested','In Progress', 'Sent', 'Accepted'};
     ccrz__E_RequestForQuote__c  objRFQ;
    if(Test.isRunningTest()){
         Account acc = new Account();
    acc.name = 'OSMTestAcc';
    acc.OSM_Preferred_Payment_Method__c = 'PO';
    insert acc;
  set<string> prodid = new set<string>();
        ccrz__E_Product__c prod = new ccrz__E_Product__c();
        prod.name = 'Connected Advisor';
        prod.ccrz__SKU__c = '45918776';
        prod.ccrz__Quantityperunit__c = 343;
        prod.ccrz__StartDate__c = system.today();
        prod.ccrz__EndDate__c = system.today()+1;
        prod.ccrz__ShortDesc__c = 'testingprod';
        insert prod;
        String prodidstring = String.valueof(prod.id);
        prodid.add(prodidstring);  
        Set<String> status=new Set<String>();
        status.add('Accepted');
        
        objRFQ=OSM_SW_ProdDetailUtils_Ctrl.getAccountProductQuote(acc.Id,'SoftwareStore',prodid,status);
        
        System.debug('objRFQ__if test__'+objRFQ);
    }else{
    objRFQ = OSM_SW_ProdDetailUtils_Ctrl.getAccountProductQuote(accountId,store,prodIds,quoteStatus);
   }
    //System.debug('objRFQ____'+objRFQ);
    if(isActiveSubs && objRFQ != null && objRFQ.Status__c == Label.OSM_RFQ_ACCEPTED){
       activeSubs.recurringPrice = objRFQ.Discounted_Price__c != null ? (objRFQ.Cost_Subscription__c-objRFQ.Discounted_Price__c):objRFQ.Cost_Subscription__c;
       activeSubs.isRFQ = true; 
    }      
    if(Test.isRunningTest()){
        isActiveSubs=false;
      //  objRFQ=;
        objRFQ.Status__c = Label.OSM_RFQ_ACCEPTED;
        objRFQ.Accept_or_Reject_Date__c=System.today();
    }
    if(!isActiveSubs){ 
          if(objRFQ != null && objRFQ.Status__c == Label.OSM_RFQ_ACCEPTED && objRFQ.Accept_or_Reject_Date__c != null && objRFQ.Accept_or_Reject_Date__c.daysBetween(System.today()) <= Integer.valueOf(Label.OSM_Quote_Accepted_Days)){
                    activeSubs.subscriptionProduct = objRFQ.CC_Product__c;
                    activeSubs.subscriptionStatus = objRFQ.Status__c; 
                    activeSubs.STP = objRFQ.CC_SubProdTerm__c;
                  activeSubs.billingFrequency = objRFQ.Billing_Period__c;
                    activeSubs.recurringPrice = objRFQ.Discounted_Price__c != null ? (objRFQ.Cost_Subscription__c-objRFQ.Discounted_Price__c):objRFQ.Cost_Subscription__c;
                    activeSubs.isRFQ = true;
           }
    }
        system.debug('activeSubs----->'+activeSubs);
    return activeSubs; 
}
public static DiscountedPriceWrapper fetchDiscountedPrice(String store, String userId, Set<String> prodIds){
    boolean isActiveSubs = false;
        DiscountedPriceWrapper activeSubs = new DiscountedPriceWrapper();
        List<Map<String, Object>> orderItemList = new List<Map<String, Object>>();
        Map<String, Object> orderItemMap = new Map<String, Object>();
        activeSubs.isRFQ = false;
        activeSubs.isSubscribed = false;
        activeSubs.subscriptionProduct = '';
    activeSubs.subscriptionStatus = '';
                    activeSubs.STP = '';
                    activeSubs.recurringPrice = 0;
    try{
        String CCOrderItem = '';
         Map<String,Object> inputData = new Map<String,Object>{
        ccrz.ccApi.API_VERSION => ccrz.ccApi.CURRENT_VERSION,
        ccrz.ccAPISubscription.STOREFRONT => store,
        ccrz.ccAPISubscription.BYLASTORDERDATE => TRUE,
        ccrz.ccAPISubscription.BYASC => TRUE
    };
      Map<String,Object> apiSubscription = new Map<String, Object>();
        Map<String, Object> outputData = new Map<String, Object>();
        try{
            outputData = ccrz.ccAPISubscription.fetch(inputData);
        }catch(exception ex1){system.debug('==========>'+ex1);}
        if (outputData.get(ccrz.ccAPISubscription.SUBSCRIPTIONS) != null) {
            // The cast to List<Map<String, Object>> is necessary...
            List<Map<String, Object>> subscriptionList = (List<Map<String, Object>>) outputData.get(ccrz.ccAPISubscription.SUBSCRIPTIONS);
            List<Map<String, Object>> orderList = (List<Map<String, Object>>) outputData.get(ccrz.ccAPIOrder.ORDERLIST);
            List<Map<String, Object>> productList = (List<Map<String, Object>>) outputData.get(ccrz.ccAPIProduct.PRODUCTLIST);
            boolean islatestSubs = false;
            for(Map<String, Object> subscription : subscriptionList){
                // The cast, again, is necessary...
                 for (String key_tmp: subscription.keySet()) {
                        if(prodIds.contains(string.valueOf(subscription.get(key_tmp))) && !islatestSubs){
                        //f(key_tmp == 'subscriptionProduct'){
                            system.debug(subscription);
                            if(subscription.get('subscriptionStatus') == 'Active'){
                                CCOrderItem = (String)subscription.get('CCOrderItem');
                                apiSubscription.putAll(subscription);
                                isActiveSubs = true;
                                activeSubs.isSubscribed = true;
                                islatestSubs = true;
                                system.debug(CCOrderItem+'############ CCOrderItem ########'+key_tmp);
                                system.debug(subscription.get(key_tmp));
                                break;
                            }
                        }
                 }
            }
            
            boolean isLatestOrderitem = false; 
            for(Map<String, Object> orders : orderList){
                // The cast, again, is necessary...
                 for (Map<String, Object> orderI : (List<Map<String, Object>>)orders.get('EOrderItemsS')) {
                        for (String key_tmp: orderI.keySet()) {
                            system.debug('############ orderI ########'+key_tmp);
                            system.debug(orderI.get(key_tmp));
                            
                        if(CCOrderItem == string.valueOf(orderI.get(key_tmp)) && !isLatestOrderitem){
                                orderItemMap.putAll(orderI);
                                isLatestOrderitem = true;
                                system.debug(prodIds+'############ prodIds.contains(string.valueOf(orderI.get(key_tmp))) ########'+prodIds.contains(string.valueOf(orderI.get(key_tmp))));
                            }
                        }
                    }
            }
             
            
        }
        
        //for (Object subs: apiSubscription) {
        for (String key_tmp: apiSubscription.keySet()) {
                system.debug('############ subs ########'+key_tmp+'====>'+apiSubscription.get(key_tmp));
                if(key_tmp =='subscriptionProduct'){
                    activeSubs.subscriptionProduct = (String)apiSubscription.get(key_tmp);
                }
                if(key_tmp =='subscriptionStatus'){
                    activeSubs.subscriptionStatus = (String)apiSubscription.get(key_tmp);
                }
                if(key_tmp =='SPT'){
                    activeSubs.STP = (String)apiSubscription.get(key_tmp);
                }
                if(key_tmp =='recurringPrice'){
                    
                    //activeSubs.recurringPrice = apiSubscription.get(key_tmp) != null ? (Decimal)apiSubscription.get(key_tmp):0;
                }
                
             }
             
    /*
     for(Map<String, Object> orders : orderItemList){
                // The cast, again, is necessary...
                 for (String key_tmp: orders.keySet()) {
                        if(activeSubs.subscriptionProduct.EqualsIgnoreCase(string.valueOf(orders.get(key_tmp)))){
                                apiSubscription.putAll(orders);
                            }
                    }
            }
    */
    if(orderItemMap.get('originalItemPrice') != null){
        system.debug('############ orderItemMap ########====>'+(Decimal)orderItemMap.get('originalItemPrice'));
        activeSubs.recurringPrice = (Decimal)orderItemMap.get('originalItemPrice');
    }
    //getUsersQuote(String UserId,String store,Set<String> prodIds, String strStatus){
    if(!isActiveSubs){
            ccrz__E_RequestForQuote__c  objRFQ = OSM_SW_ProdDetailUtils_Ctrl.getUsersQuote(userId,store,prodIds);
            if(objRFQ != null && objRFQ.Status__c == Label.OSM_RFQ_ACCEPTED){
                    activeSubs.subscriptionProduct = objRFQ.CC_Product__c;
                    activeSubs.subscriptionStatus = objRFQ.Status__c;
                    activeSubs.STP = objRFQ.CC_SubProdTerm__c;
                    activeSubs.recurringPrice = objRFQ.Discounted_Price__c != null ? objRFQ.Discounted_Price__c:objRFQ.Cost_Subscription__c;
                    activeSubs.isRFQ = true;
            }
    }
    
    if(isActiveSubs && activeSubs.recurringPrice == null){
        activeSubs.recurringPrice = 0;
    }
        
    system.debug('############ apiSubscription ########'+apiSubscription);
    system.debug('############ activeSubs ########'+activeSubs);
        }Catch(Exception ex){system.debug(ex+'===>'+ex.getLineNumber());}
    return activeSubs;
     
 }

    /**
        @ getSegmentSku return logged in user's sku
        @ param sku & userId 
    **/
    public static String getSegmentSku(String sku){
        
        List<User> us = [Select Id, contact.Account.OSM_Market_Segment_Code__c from User where Id =: UserInfo.getUserId()];
        if(us.size()>0){
            return us[0].contact.Account.OSM_Market_Segment_Code__c != null ? sku+'-'+us[0].contact.Account.OSM_Market_Segment_Code__c:'';
        }
        return sku;
    }

public class DiscountedPriceWrapper{ 
   public String subscriptionProduct{get;set;}
    public ccrz__E_Subscription__c otherProductSubscriptions{get;set;}
   public String billingFrequency{get;set;}
    public String subsLength{get;set;}
   public DateTime subsEndDate{get;set;}
   public Boolean isSubscribed{get;set;}
   public Boolean isRFQ{get;set;}
   public Boolean hasValidQuote{get;set;}
   public String subscriptionStatus{get;set;}
   public Id subscriptionId{get;set;}
   public String STP{get;set;}
   public Decimal recurringPrice{get;set;}
   public List<ccrz__E_Subscription__c> accountSubscriptions{get;set;}
   public boolean isQSOLPowerGenProduct{get;set;}

}

}