objects/Account.object
<CustomObject>
    <fields>
        <fullName>BMS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BMS Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used to Store Region Value based on SP code</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_UserLocation__c.object
<CustomObject>
    <fields>
        <fullName>BMS_Enabled__c</fullName>
        <formula>AccountId__r.BMS_Enabled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BMS Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_code__c</fullName>
        <externalId>true</externalId>
        <label>Location_code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSS_UserLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS_UserLocation</label>
    <nameField>
        <label>CSS_UserLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_UserLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Location__c</fullName>
        <label>User Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CSS_LoginUserCacheVariables_Test.cls
@isTest
public class CSS_LoginUserCacheVariables_Test {
   
    static testMethod void myTest() {
    
    Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt1', Email='standardusernandigam1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing111', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standardusernandigamsas111@testorg.com',User_Location__c='test-P12345');
          insert u;
          Account a=new Account();
        a.name='name';
        a.CSS_DistributorCode__c='test';
        a.IAM_Service_Provider_Code__c='P12345';
        a.Type='Dealer Account';
        a.Region__c = 'US and Canada';
        a.CMI_Account_Status__c = 'Active';
        a.IAM_Service_Provider_Code__c = '562551';
		a.BMS_Enabled__c = true;
        insert a;
            System.runAs(u){
            
            
         Test.startTest();
       
        CSS_LoginUserCacheVariables.getUserAttributes();
        CSS_LoginUserCacheVariables.addLocations('test-P12345678901244','test',u.Id,'profile');
                CSS_LoginUserCacheVariables loginuser = new CSS_LoginUserCacheVariables();
                CSS_LoginUserCacheVariables.getUnitTypeSubTyp('test');
        Test.stopTest();
        
        }
        }
    //written this method to cover else part
    static testMethod void myTest1(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt1', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing111', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standardusertest111@testorg.com',User_Location__c='test-S12345');
          insert u;
          
          CSS_UserLocation__c  usloc = new CSS_UserLocation__c (UserId__c=u.id,Location_code__c='test-S12345',isActive__c=true);
          insert usloc ;
        CSS_LoginUserCacheVariables.addLocations('test-S12345678901244','test',u.Id,'profile');
        Set<String> locIds = new Set<String>();
        locIds.add('test-S12345678901244');
        locIds.add('test-S12345678901244');
        locIds.add('test-S12345678901244');
        CSS_LoginUserCacheVariables.addUsersToQueues(locIds);
    }
    
    
    //written this method to cover else part
    static testMethod void myTest2(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt1', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing111', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standardusertester111@testorg.com',User_Location__c='test-P12345');
          insert u;
          
          CSS_UserLocation__c  usloc = new CSS_UserLocation__c (UserId__c=u.id,Location_code__c='test-P12345',isActive__c=true);
          insert usloc ;
        CSS_LoginUserCacheVariables.addLocations('test-P12345678901244','test',u.Id,'profile');
    }
    
    
     static testMethod void myTest3() {
    
    Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt1', Email='standarduser1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing111', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standardusersasi111@testorg.com',User_Location__c='test-S12345');
          insert u;
           Account a=new Account();
        a.name='name';
        a.CSS_DistributorCode__c='test';
        a.IAM_Service_Provider_Code__c='S12345';
         a.Type='Dealer Account';
         a.Region__c = 'US and Canada';
        a.CMI_Account_Status__c = 'Active';
        a.IAM_Service_Provider_Code__c = '562551';

        insert a;
            System.runAs(u){
            
           
         Test.startTest();
       
       
        CSS_LoginUserCacheVariables.addLocations('test-S12345678901244','test',u.Id,'profile');
        Test.stopTest();
        
        }
        }
   }