objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <formula>IF(AND(ISBLANK(CSS_DealerCode__c), ISBLANK(CSS_DBCode__c), ISBLANK(CSS_DBCode__c), ISBLANK(IAM_Service_Provider_Code__c)), &apos;&apos;, IF(CSS_DistributorCode__c=&apos;50000&apos;, CSS_DBCode__c+&apos;-&apos;+IAM_Service_Provider_Code__c, CSS_DistributorCode__c+&apos;-&apos;+IAM_Service_Provider_Code__c))</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>ERP__c</fullName>
        <description>To store the ERP system against each Asset</description>
        <label>ERP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MoveX</fullName>
                </value>
                <value>
                    <fullName>BMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engines</fullName>
                    <default>true</default>
                    <label>Engines</label>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>FIREPUMP</fullName>
                </value>
                <value>
                    <fullName>ENGINE</fullName>
                </value>
                <value>
                    <fullName>GENSET</fullName>
                </value>
                <value>
                    <fullName>ENGINE CORE</fullName>
                </value>
                <value>
                    <fullName>SWITCH GEAR</fullName>
                </value>
                <value>
                    <fullName>TRANSFER SWITCH</fullName>
                </value>
                <value>
                    <fullName>TRANSMISSIONS</fullName>
                </value>
                <value>
                    <fullName>BATTERY</fullName>
                </value>
                <value>
                    <fullName>PARSYS</fullName>
                </value>
                <value>
                    <fullName>MARINE GEAR</fullName>
                </value>
                <value>
                    <fullName>ONAN</fullName>
                </value>
                <value>
                    <fullName>REFRIG</fullName>
                </value>
                <value>
                    <fullName>KOMATSU EQUIPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FSL__User_Territory__c.object
<CustomObject>
    <description>Which Territories are visible to this user (Default = All)</description>
    <fields>
        <fullName>FSL__ServiceTerritory__c</fullName>
        <label>Service Territory</label>
        <referenceTo>ServiceTerritory</referenceTo>
        <relationshipName>User_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FSL__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>ULID-{000000}</displayFormat>
        <label>User Territory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>ERP__c</fullName>
        <label>ERP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BMS</fullName>
                </value>
                <value>
                    <fullName>MOVEX</fullName>
                </value>
                <value>
                    <fullName>MOVEX-MYD</fullName>
                </value>
                <value>
                    <fullName>MOVEX-UK</fullName>
                </value>
                <value>
                    <fullName>MOVEX-190</fullName>
                </value>
                <value>
                    <fullName>MOVEX-200</fullName>
                </value>
                <value>
                    <fullName>MOVEX-250</fullName>
                </value>
                <value>
                    <fullName>MOVEX-270</fullName>
                </value>
                <value>
                    <fullName>MOVEX-175</fullName>
                </value>
                <value>
                    <fullName>MOVEX-CSP</fullName>
                </value>
                <value>
                    <fullName>MOVEX-CDK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_Service_Territory_Code__c</fullName>
        <description>Territory Code of the Service Location</description>
        <inlineHelpText>Territory Code of the Service Location</inlineHelpText>
        <label>Service Territory Code</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <label>Location Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DEALER</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-BRANCH</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-HEADQUARTERS</fullName>
                </value>
                <value>
                    <fullName>GROUP</fullName>
                </value>
                <value>
                    <fullName>HOLSET - DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>INDUSTRIAL/VOCATIONAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ERP__c</fullName>
        <label>ERP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BMS</fullName>
                </value>
                <value>
                    <fullName>MOVEX</fullName>
                </value>
                <value>
                    <fullName>MOVEX-175</fullName>
                </value>
                <value>
                    <fullName>MOVEX-190</fullName>
                </value>
                <value>
                    <fullName>MOVEX-200</fullName>
                </value>
                <value>
                    <fullName>MOVEX-250</fullName>
                </value>
                <value>
                    <fullName>MOVEX-270</fullName>
                </value>
                <value>
                    <fullName>MOVEX-CDK</fullName>
                </value>
                <value>
                    <fullName>MOVEX-CSP</fullName>
                </value>
                <value>
                    <fullName>MOVEX-MYD</fullName>
                </value>
                <value>
                    <fullName>MOVEX-UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_Primary_Service_Territory_Code__c</fullName>
        <description>Primary Service Territory of User to auto populate on WorkOrder</description>
        <inlineHelpText>Primary Service Territory of User to auto populate on WorkOrder</inlineHelpText>
        <label>Primary Service Territory Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Distributorbranchcode__c</fullName>
        <label>IAM_Distributorbranchcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_Distributorcode__c</fullName>
        <label>IAM_Distributorcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Location__c</fullName>
        <label>User Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FSL_UserToolsViewHistoryCtrl.cls
/*****************************************************
Name:FSL_UserToolsViewHistoryCtrl
Copyright © 2018  Cummins
======================================================
======================================================
Purpose:                                                            
-------  
We are using this controller for view history in User Tools
======================================================
======================================================
History                                                            
-------                                                            
VERSION  AUTHOR                DATE                DETAIL                                 
1.0 -   Karthik Gorantla       1-/07/2020        INITIAL DEVELOPMENT 
***********************************************************************/
global class FSL_UserToolsViewHistoryCtrl {
    global string assetName {get;set;}
    global DateTime createdDate {get;set;}
    global String jobId {get;set;}
    global String sLocation {get;set;}
    global List<String> sLocationTerritory {get;set;} //added by Naveen, PHOEN-209
    global String sLocationCode {get;set;}
    global WorkOrder workOrderRecord;
    public Id workOrderId;
    global FSL_UserToolsViewHistoryCtrl() {
        system.debug('kkkkk');
         try{
             sLocationTerritory = new List<String>();
             List<FSL__User_Territory__c> UT = new List<FSL__User_Territory__c>();
        assetName = ApexPages.currentPage().getParameters().get('Id');
        //createdDate = System.today();
        createdDate = DateTime.now();//added by sai as part of CT1-420
            system.debug('karthikassetName>>>'+assetName);
          //assetName =  '79950304';
       
        User u = [select Id, username,User_Location__c,ERP__c,IAM_Distributorbranchcode__c,IAM_Distributorcode__c,FSL_Primary_Service_Territory_Code__c from User where Id = :UserInfo.getUserId()];
        sLocationCode = u.User_Location__c;
        system.debug('karthikUserinfo>>>>'+sLocationCode);
// Start - code changes done by Naveen, PHOEN-209 ----------------------------
             if(u.ERP__c != null){
                  UT =[SELECT id,FSL__ServiceTerritory__c,FSL__User__c FROM FSL__User_Territory__c WHERE FSL__User__c =:u.id];
                  system.debug('UT==>'+UT);
                 if(UT.size() > 0 || Test.isRunningTest()){
                     set<string> STids = new set<string>();
                     for(FSL__User_Territory__c utr : UT){
                         if(utr.FSL__ServiceTerritory__c != null || Test.isRunningTest()){
                             STids.add(utr.FSL__ServiceTerritory__c);
                         }
                     }
						List<ServiceTerritory> STname =new List<ServiceTerritory>( [SELECT id,name,FSL_Service_Territory_Code__c ,Location_Code__c,ParentTerritoryId FROM ServiceTerritory WHERE (Id IN :STids OR  ParentTerritoryId IN :STids OR ParentTerritory.ParentTerritoryId IN :STids) AND Type__c = 'DISTRIBUTOR-BRANCH']);
                		system.debug('STname==>'+STname);  
                     if(STname.size() > 0 || Test.isRunningTest()){
                         set<string> setofST = new set<string>();
                         for(ServiceTerritory st : STname){
                             setofST.add(st.name);
                         sLocationTerritory.add(st.name);
                     	}
                     }
                 }else{   
                     
                 }
                 
             }else{
                  	Account acc = [Select Id, Name,Location__c from Account where Location__c =: sLocationCode LIMIT 1];
        			system.debug('acc.Location__c>>>>'+acc.Location__c);
        			sLocation = acc.Name; 
                    
                 	system.debug('karthikacc.Name>>>>'+acc.Name);
             }
// END - code changes done by Naveen, PHOEN-209 ----------------------------------------
        system.debug('karthikUSerinfo>>>>'+sLocationCode);
        system.debug('karthikUSerinfocreatedDate>>>>'+createdDate);
       //system.debug('karthikUSerinfoaccName>>>>'+accName);
        }catch(Exception e) { 
            system.debug('exception '+e.getMessage());
        }
      /*   workOrderId = ApexPages.currentPage().getParameters().get('Id');
        system.debug('workOrderId . :: '+workOrderId);
        workOrderRecord = new WorkOrder();
        workOrderRecord = [SELECT Id, Asset.Name, ServiceTerritory.Name, ServiceTerritory.Location_Code__c, CreatedDate 
                           FROM WorkOrder WHERE Id = :workOrderId]; //AssetId
        if(workOrderRecord!=null) {
            assetName = workOrderRecord.Asset.Name;
            createdDate = workOrderRecord.CreatedDate;
            jobId = workOrderRecord.id;
            sLocation = workOrderRecord.ServiceTerritory.Name;
            sLocationCode = workOrderRecord.ServiceTerritory.Location_Code__c;
        }
        system.debug('check debug'+workOrderRecord); */
    }
}