objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMI_Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending CDA</fullName>
                    <isActive>false</isActive>
                    <label>Pending CDA</label>
                </value>
                <value>
                    <fullName>Pending Data Flow Verification</fullName>
                    <isActive>false</isActive>
                    <label>Pending Data Flow Verification</label>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                    <isActive>false</isActive>
                    <label>Pending Final Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Signed CDA</fullName>
                    <isActive>false</isActive>
                    <label>Signed CDA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_DistributorCode__c</fullName>
        <defaultValue>$User.IAM_Distributorcode__c</defaultValue>
        <description>DistributorCode stores the 5 digit valueof the Distributor</description>
        <label>Distributor Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBU_Channel_of_Distribution__c</fullName>
        <label>EBU Channel of Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFFILIATE SALES ASSOCIA</fullName>
                    <isActive>false</isActive>
                    <label>AFFILIATE SALES ASSOCIA</label>
                </value>
                <value>
                    <fullName>AFFILIATE SALES ASSOCIATE</fullName>
                </value>
                <value>
                    <fullName>BUS OEM</fullName>
                </value>
                <value>
                    <fullName>BUS - OTHER</fullName>
                </value>
                <value>
                    <fullName>CAREER CENTERS</fullName>
                </value>
                <value>
                    <fullName>CIHR</fullName>
                </value>
                <value>
                    <fullName>CONTRACTED ALTERNATOR SP</fullName>
                </value>
                <value>
                    <fullName>DEALER</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-BRANCH</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-HEADQUARTERS</fullName>
                </value>
                <value>
                    <fullName>END USER</fullName>
                </value>
                <value>
                    <fullName>EXPORT HOUSE</fullName>
                </value>
                <value>
                    <fullName>FEDERAL GOVERNMENT</fullName>
                </value>
                <value>
                    <fullName>FILTRATION DEALER</fullName>
                </value>
                <value>
                    <fullName>FILTRATION HEADQUARTER</fullName>
                </value>
                <value>
                    <fullName>FLEET</fullName>
                </value>
                <value>
                    <fullName>FLEETGUARD DEALER</fullName>
                    <isActive>false</isActive>
                    <label>FLEETGUARD DEALER</label>
                </value>
                <value>
                    <fullName>FLEETGUARD DISTRIBUTOR</fullName>
                    <isActive>false</isActive>
                    <label>FLEETGUARD DISTRIBUTOR</label>
                </value>
                <value>
                    <fullName>FLEETGUARD HEAD QUARTER</fullName>
                    <isActive>false</isActive>
                    <label>FLEETGUARD HEAD QUARTER</label>
                </value>
                <value>
                    <fullName>FUEL SYSTEMS ASSOCIATE</fullName>
                </value>
                <value>
                    <fullName>FUEL SYSTEMS SPECIALIST</fullName>
                </value>
                <value>
                    <fullName>GOEM</fullName>
                    <isActive>false</isActive>
                    <label>GOEM</label>
                </value>
                <value>
                    <fullName>HOLSET - DEALER</fullName>
                </value>
                <value>
                    <fullName>HOLSET - DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>HOLSET - HEAD QUARTER</fullName>
                </value>
                <value>
                    <fullName>INDEPENDENT AFTER MARKET</fullName>
                </value>
                <value>
                    <fullName>INDUSTRIAL/VOCATIONAL</fullName>
                </value>
                <value>
                    <fullName>MAJOR LEASING CO. ACCTS.</fullName>
                    <isActive>false</isActive>
                    <label>MAJOR LEASING CO. ACCTS.</label>
                </value>
                <value>
                    <fullName>NATIONAL ACCOUNT-REFUSE</fullName>
                </value>
                <value>
                    <fullName>NATIONAL ACCT_CIHR - HQ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Service_Provider_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field shows all types of Codes depending upon the Type of the Account.</inlineHelpText>
        <label>Customer Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>WWSPS</fullName>
        <active>true</active>
        <description>Record type for all WWSPS records</description>
        <label>WWSPS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CSS_Accreditation__c.object
<CustomObject>
    <description>Object to capture information related to Technician and Account Accreditations</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS Accreditations</relationshipLabel>
        <relationshipName>CSS_Accreditations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MARKET_APPLICATION__c</fullName>
        <label>MARKET_APPLICATION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRODUCT_RANGE__c</fullName>
        <label>PRODUCT_RANGE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SP_CODE__c</fullName>
        <label>SP_CODE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Level_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To identify if the record need to be picked by the batch to populate Service Level. Story # MAR-615</description>
        <label>Service Level Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Level__c</fullName>
        <label>Service Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpRowId__c</fullName>
        <label>SpRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSMNAccountLevel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSMNAccountLevel</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS Accreditation</label>
    <nameField>
        <label>CSS_Accreditation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Accreditations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_AccreditationInsert_Batch_Test.cls
//This class is test class for OSM_AccreditationInsert_Batch and OSM_AccreditationUpdate_Batch
@isTest
public class OSM_AccreditationInsert_Batch_Test {
     static testMethod void OSM_AccreditationInsert_BatchMethod(){
        RecordType recid =[select id from recordType where name='WWSPS' limit 1]; 
        Account acc = new Account();
        acc.Name = 'US Xpress - Terrell';
        acc.IAM_Service_Provider_Code__c = '38409';
        acc.CSS_DistributorCode__c = '23093';
        acc.Type = 'CIHR';
        acc.RecordTypeId= recid.id;
        acc.EBU_Channel_of_Distribution__c = 'CIHR';
        acc.CMI_Account_Status__c = 'Active';
        insert acc;
        
        CSS_Accreditation__c accredRec = new CSS_Accreditation__c();
        accredRec.Name = 'Test Accred Record one';
        accredRec.Account__c = acc.Id;
        accredRec.isSMNAccountLevel__c = false;
        accredRec.MARKET_APPLICATION__c = 'AUTOMOTIVE';
        accredRec.PRODUCT_RANGE__c = 'Heavy Duty';
        accredRec.Service_Level__c = 'CIHR LEVEL 2';
        accredRec.SP_CODE__c = '38409';
        accredRec.SpRowId__c = '1-3WDM-9';
        accredRec.Service_Level_Update__c = false;
        insert accredRec;
        
        CSS_Accreditation__c accredRec1 = new CSS_Accreditation__c();
        accredRec1.Name = 'Test Accred Record two';
        accredRec1.Account__c = acc.Id;
        accredRec1.isSMNAccountLevel__c = false;
        accredRec1.MARKET_APPLICATION__c = 'AUTOMOTIVE';
        accredRec1.PRODUCT_RANGE__c = 'Heavy Duty';
        accredRec1.Service_Level__c = 'CIHR LEVEL 2';
        accredRec1.SP_CODE__c = '38409';
        accredRec1.SpRowId__c = '1-3WDM-9';
        accredRec1.Service_Level_Update__c = false;
        insert accredRec1;
        
        OSM_AccreditationInsert_Batch batchIns = new OSM_AccreditationInsert_Batch();
        database.executeBatch(batchIns);
        
        accredRec1.Service_Level_Update__c = true;
        update accredRec1;
        
        OSM_AccreditationUpdate_Batch batchUpd = new OSM_AccreditationUpdate_Batch();
        database.executeBatch(batchUpd);
    }
}