objects/Address.object
<CustomObject>
    <fields>
        <fullName>IAM_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IAM Site</label>
        <referenceTo>IAM_CDH_Cross_references__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>FSL_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND (2 OR 3)) OR 4</booleanFilter>
            <filterItems>
                <field>Address.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Address.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Address.Status__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>CSS Integration</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Site for the Asset</description>
        <label>Site</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>IAM_CDH_Cross_references__c.IAM_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>IAM_CDH_Cross_references__c.FSL_Site_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>IAM_CDH_Cross_references__c.FSL_Site_Status__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IAM_CDH_Cross_references__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSL_UpdateSiteToAddressBatch.cls
/****
Run Batch for WorkOrder->

UpdateSiteToAddressBatch batchObj = new UpdateSiteToAddressBatch('WorkOrder');
Database.executeBatch(batchObj);

Run Batch for Asset->

UpdateSiteToAddressBatch batchObj = new UpdateSiteToAddressBatch('Asset');
Database.executeBatch(batchObj);
****/

public class FSL_UpdateSiteToAddressBatch implements Database.Batchable<sobject> {
    
    public String sobjectName;
    
    public FSL_UpdateSiteToAddressBatch(String sobjectName){
        this.sobjectName = sobjectName;
    }
    
    public Database.QueryLocator start(Database.batchablecontext BC){
        String query = '';
        if(sobjectName.equalsIgnoreCase('WorkOrder')){
            query = 'select id,Repair_Site_Name__c,Repair_Site_Address__c From WorkOrder Where Repair_Site_Address__c = null AND Repair_Site_Name__c != null';
        } else if(sobjectName.equalsIgnoreCase('Asset')){
            query = 'Select id,Site__c,FSL_Site__c From Asset Where FSL_Site__c = null AND Site__c != null';
        }
        return Database.getQueryLocator(query);
    } 
    
    public void execute(Database.BatchableContext BC,List<sobject> scope){
        Set<Id> SiteIdSet = new Set<Id>();
        //FOR WORKORDER
        if(sobjectName.equalsIgnoreCase('WorkOrder')){
            List<WorkOrder> woList = (List<WorkOrder>)scope;
            for(WorkOrder wo : woList){
                SiteIdSet.add(wo.Repair_Site_Name__c);      
            }
            Map<Id,Id> siteToAddressMap = getSiteToAddressMap(SiteIdSet);
            for(WorkOrder wo : woList){
                if(siteToAddressMap.containsKey(wo.Repair_Site_Name__c)){
                    wo.Repair_Site_Address__c = siteToAddressMap.get(wo.Repair_Site_Name__c);
                }
            }
            Database.update(woList,false); 
        }
        //FOR ASSET
        if(sobjectName.equalsIgnoreCase('Asset')){
            List<Asset> assetList = (List<Asset>)scope;
            for(Asset assetObj : assetList){
                SiteIdSet.add(assetObj.Site__c);      
            }
            Map<Id,Id> siteToAddressMap = getSiteToAddressMap(SiteIdSet);
            for(Asset assetObj : assetList){
                if(siteToAddressMap.containsKey(assetObj.Site__c)){
                    assetObj.FSL_Site__c = siteToAddressMap.get(assetObj.Site__c);
                }
            }
            Database.update(assetList ,false); 
        }
        
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
    
    public Map<ID,ID> getSiteToAddressMap(Set<Id> SiteIdSet){
        List<Schema.Address> addressList = [Select id,IAM_Site__c From Address Where IAM_Site__c IN :SiteIdSet];
        Map<Id,Id> siteToAddressMap = new Map<Id,Id>();
        for(Schema.Address addr:addressList){
            siteToAddressMap.put(addr.IAM_Site__c,addr.id);
        }
        return siteToAddressMap;
    }
}