objects/Address.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IAM_CDH_Cross_references__c.object
<CustomObject>
    <fields>
        <fullName>FSLSite_Contact_Phone__c</fullName>
        <label>Site Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>FSL_Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Branch_Code__c</fullName>
        <label>Branch Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Country__c</fullName>
        <defaultValue>$User.Country</defaultValue>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                    <isActive>false</isActive>
                    <label>Afghanistan</label>
                </value>
                <value>
                    <fullName>Albania</fullName>
                    <isActive>false</isActive>
                    <label>Albania</label>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                    <isActive>false</isActive>
                    <label>Algeria</label>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Angola</fullName>
                    <isActive>false</isActive>
                    <label>Angola</label>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                    <isActive>false</isActive>
                    <label>Anguilla</label>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                    <isActive>false</isActive>
                    <label>Antigua and Barbuda</label>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                    <isActive>false</isActive>
                    <label>Aruba</label>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                    <isActive>false</isActive>
                    <label>Azerbaijan</label>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                    <isActive>false</isActive>
                    <label>Bahrain</label>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                    <isActive>false</isActive>
                    <label>Bangladesh</label>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                    <isActive>false</isActive>
                    <label>Barbados</label>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                    <isActive>false</isActive>
                    <label>Belize</label>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                    <isActive>false</isActive>
                    <label>Bermuda</label>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                    <isActive>false</isActive>
                    <label>Bolivia</label>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                    <isActive>false</isActive>
                    <label>Bosnia and Herzegovina</label>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                    <isActive>false</isActive>
                    <label>Brazil</label>
                </value>
                <value>
                    <fullName>British Virgin Islands</fullName>
                    <isActive>false</isActive>
                    <label>British Virgin Islands</label>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                    <isActive>false</isActive>
                    <label>Cameroon</label>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cape Verde</fullName>
                    <isActive>false</isActive>
                    <label>Cape Verde</label>
                </value>
                <value>
                    <fullName>Caribbean</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                    <isActive>false</isActive>
                    <label>Cayman Islands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_Distributor_Code__c</fullName>
        <label>Distributor Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Job_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.IAM_Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>IAM Sites</relationshipLabel>
        <relationshipName>CDH_Cross_references</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FSL_Latitude__c</fullName>
        <label>Latitude</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Longitude__c</fullName>
        <label>Longitude</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_MoveX_Contact_Id__c</fullName>
        <label>Contact Id</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_MoveX_Site_Id__c</fullName>
        <externalId>true</externalId>
        <label>Site Id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Site_Status__c</fullName>
        <label>Site Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>FSL_Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>&apos;Eua</fullName>
                </value>
                <value>
                    <fullName>3090 Overjise</fullName>
                </value>
                <value>
                    <fullName>Aberdeen</fullName>
                </value>
                <value>
                    <fullName>Aberdeenshire</fullName>
                </value>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Acquaviva</fullName>
                </value>
                <value>
                    <fullName>Adana</fullName>
                </value>
                <value>
                    <fullName>Adiyaman</fullName>
                </value>
                <value>
                    <fullName>Afyonkarahisar</fullName>
                </value>
                <value>
                    <fullName>Agder</fullName>
                </value>
                <value>
                    <fullName>Agri</fullName>
                </value>
                <value>
                    <fullName>Agrigento</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Aileu</fullName>
                </value>
                <value>
                    <fullName>Ainaro</fullName>
                </value>
                <value>
                    <fullName>Aitutak</fullName>
                </value>
                <value>
                    <fullName>Akershus</fullName>
                </value>
                <value>
                    <fullName>Aksaray</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Álava</fullName>
                </value>
                <value>
                    <fullName>Alba</fullName>
                </value>
                <value>
                    <fullName>Albacete</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alessandria</fullName>
                </value>
                <value>
                    <fullName>Alicante</fullName>
                </value>
                <value>
                    <fullName>Almeria</fullName>
                </value>
                <value>
                    <fullName>Alsace</fullName>
                </value>
                <value>
                    <fullName>Amasya</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IAM_CDH_Cross_references</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IAM Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IAM Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>FSL_Branch_Code__c</fullName>
        <label>Branch Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Distributor_Code__c</fullName>
        <label>Distributor Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSL_CreateAddressAndLocationBatch.cls
/**********************************************************************
Name:CreateAddressAndLocationBatch
Copyright Â© 2019  Cummins
=================================================================================================================
=================================================================================================================
Purpose:                                                            
-----------------------------------------------------------------------------------------------------------------
Batch Job which retrieves the data from IAM_CDH_Cross_references__c  and updates in Addresses and Locations Object.
=================================================================================================================
=================================================================================================================
History                                                            
-------                                                            
VERSION     AUTHOR                     DATE          DETAIL                         
1.0       Vijay Avula                03/19/2021    Batch Job to update Load Data into Address and Location Object
********************************************************************************************************************/

public class FSL_CreateAddressAndLocationBatch implements Database.batchable<sobject> {

    public static Database.queryLocator start(Database.batchableContext BC){
        String query = 'Select Id, Name, FSL_Distributor_Code__c, FSL_Branch_Code__c, FSL_MoveX_Contact_Id__c,' +
                       'IAM_Account__c, FSL_Job_Contact__c, FSLSite_Contact_Phone__c, FSL_MoveX_Site_Id__c,' +
                       'FSL_Site_Status__c, FSL_Address_Line_1__c, FSL_Address_Line_2__c, FSL_Address_Line_3__c, FSL_City__c,' + 
                       'FSL_State__c, FSL_Postal_Code__c, FSL_Country__c, FSL_Latitude__c, FSL_Longitude__c, FSL_Tax_District__c ' +
                       'From IAM_CDH_Cross_references__c Where IsConverted__c = false Order By CreatedDate DESC ';
        return Database.getQueryLocator(query);
    }
    
    public static void execute(Database.batchableContext BC, List<sobject> scope){
        List<Schema.Location> locationList = new List<Schema.Location>();
        List<Schema.Address> addressList = new List<Schema.Address>();
        List<IAM_CDH_Cross_references__c> iamList = (List<IAM_CDH_Cross_references__c>) scope;
        
        for(IAM_CDH_Cross_references__c iamRecord: iamList){
            Schema.Location loc = new Schema.Location();
            loc.Name = iamRecord.Name;
            loc.FSL_Distributor_Code__c = iamRecord.FSL_Distributor_Code__c;
            loc.FSL_Branch_Code__c = iamRecord.FSL_Branch_Code__c;
            loc.FSL_Contact_ID__c = iamRecord.FSL_MoveX_Contact_Id__c;
            loc.FSL_Account__c = iamRecord.IAM_Account__c;
            loc.FSL_Contact__c = iamRecord.FSL_Job_Contact__c;
            loc.FSL_Contact_Phone__c = iamRecord.FSLSite_Contact_Phone__c;
            locationList.add(loc);  
            
            Schema.Address addr = new Schema.Address();
            addr.IAM_Site__c = iamRecord.Id;
            addr.FSL_Site_Name__c = iamRecord.Name;
            addr.FSL_Site_ID__c = iamRecord.FSL_MoveX_Site_Id__c;
            addr.Status__c = iamRecord.FSL_Site_Status__c;
            addr.Street = iamRecord.FSL_Address_Line_1__c;
            addr.Street += iamRecord.FSL_Address_Line_2__c != null ? ',' + iamRecord.FSL_Address_Line_2__c : '';
            addr.Street += iamRecord.FSL_Address_Line_3__c != null ? ',' + iamRecord.FSL_Address_Line_3__c : '';
            addr.City = iamRecord.FSL_City__c;
            addr.State = iamRecord.FSL_State__c;
            addr.PostalCode = iamRecord.FSL_Postal_Code__c;
            addr.Country = iamRecord.FSL_Country__c;
            addr.Latitude = iamRecord.FSL_Latitude__c != null ? Decimal.valueOf(iamRecord.FSL_Latitude__c) : null;
            addr.Geolocation__Latitude__s = iamRecord.FSL_Latitude__c != null ? Decimal.valueOf(iamRecord.FSL_Latitude__c) : null;
            addr.Longitude = iamRecord.FSL_Longitude__c != null ? Decimal.valueOf(iamRecord.FSL_Longitude__c) : null;
            addr.Geolocation__Longitude__s = iamRecord.FSL_Longitude__c != null ? Decimal.valueOf(iamRecord.FSL_Longitude__c) : null;
            addr.FSL_Tax_District__c = iamRecord.FSL_Tax_District__c;
            addressList.add(addr);
             
        }
        
        List<Database.SaveResult> srLocation = Database.insert(locationList,false);
        Integer i = 0;
        for(Database.SaveResult sr: srLocation){
            if(sr.isSuccess()){
                addressList[i].parentId = sr.getId();
            }
            i++;
        }
        
        List<Database.SaveResult> srAddress = Database.insert(addressList,false);
        i=0;
        for(Database.SaveResult sr: srAddress){
            if(sr.isSuccess()){
                iamList[i].isConverted__c = true; 
            }
            i++;
        }
        
        update iamList;
    }
    
    public static void finish(Database.batchableContext BC){
    
    }
}