objects/App_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Back_page__c</fullName>
        <label>Back page</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAM_App_Protected_By__c</fullName>
        <label>App Protected By</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAML</fullName>
                </value>
                <value>
                    <fullName>SM</fullName>
                </value>
                <value>
                    <fullName>OAM11g</fullName>
                </value>
                <value>
                    <fullName>OAM12c</fullName>
                </value>
                <value>
                    <fullName>AWS Cognito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Default_Role__c</fullName>
        <label>Default Role</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Registration__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Registration</label>
        <type>Checkbox</type>
    </fields>
    <label>App Mapping</label>
    <nameField>
        <label>App Mapping  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IAM_PWC_CumminsRedirectPage_Test.cls
@isTest
private class  IAM_PWC_CumminsRedirectPage_Test{
    
    static testMethod void myUnitTest() 
    {  
    App_Mapping__c obj=new App_Mapping__c();
    obj.name='test';
    obj.Back_page__c='test';
    obj.Registration__c=true;
    obj.IAM_Default_Role__c='User';
    obj.IAM_App_Protected_By__c='SAML';
    insert obj;
    
    
        string strlabel=system.Label.RLS_AppID;
        ApexPages.currentPage().getParameters().put('appid',obj.id  );
        ApexPages.currentPage().getParameters().put('UID','pwc_paccar1');
        ApexPages.currentPage().getParameters().put('FedexemailId','gmail@gmail.com');
       
         IAM_PWC_CumminsRedirectPage objCls=new  IAM_PWC_CumminsRedirectPage();
        objCls.Redirect();
        
        App_Mapping__c objApp=new App_Mapping__c();
        ApexPages.currentPage().getParameters().put('appid',obj.id);
        ApexPages.standardController controllernew = new ApexPages.standardController(obj);
        

    }
}