objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Application_Code__c</fullName>
        <label>Application Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Description__c</fullName>
        <label>Application Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Engine_Family__c</fullName>
        <defaultValue>IF(NOT(ISPICKVAL($User.ERP__c, &apos;BMS&apos;)), &quot;BB&quot;, &quot;&quot;)</defaultValue>
        <label>Engine Family</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labor_Multiplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Labor Multiplier influences labor rates in BMS</inlineHelpText>
        <label>Labor Multiplier</label>
        <referenceTo>FSL_Labor_Multiplier__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <defaultValue>IF($Profile.Name = &apos;CSS_Service_Advanced&apos;, &apos;UNLISTED&apos;, &apos;&apos;)</defaultValue>
        <label>Make</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <defaultValue>IF($Profile.Name = &apos;CSS_Service_Advanced&apos;, &apos;ALL&apos;, &apos;&apos;)</defaultValue>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Model__c</fullName>
        <defaultValue>&quot;NONCUMMINS&quot;</defaultValue>
        <label>Service Model</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_PSN__c</fullName>
        <externalId>true</externalId>
        <label>Type-PSN</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engines</fullName>
                    <default>true</default>
                    <label>Engines</label>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>FIREPUMP</fullName>
                </value>
                <value>
                    <fullName>ENGINE</fullName>
                </value>
                <value>
                    <fullName>GENSET</fullName>
                </value>
                <value>
                    <fullName>ENGINE CORE</fullName>
                </value>
                <value>
                    <fullName>SWITCH GEAR</fullName>
                </value>
                <value>
                    <fullName>TRANSFER SWITCH</fullName>
                </value>
                <value>
                    <fullName>TRANSMISSIONS</fullName>
                </value>
                <value>
                    <fullName>BATTERY</fullName>
                </value>
                <value>
                    <fullName>PARSYS</fullName>
                </value>
                <value>
                    <fullName>MARINE GEAR</fullName>
                </value>
                <value>
                    <fullName>ONAN</fullName>
                </value>
                <value>
                    <fullName>REFRIG</fullName>
                </value>
                <value>
                    <fullName>KOMATSU EQUIPMENT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.ERP__c, &apos;BMS&apos;), &quot;OTHER&quot;, &apos;&apos;)</defaultValue>
        <label>Unit Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FSL_Additional_Sub_Type__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Number__c</fullName>
        <label>Assignment Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Job_Line_Number__c</fullName>
        <label>ERP Job Line Number</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Account__c</fullName>
        <label>Payer Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Order__c</fullName>
        <label>Service Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Additional Sub Types</relationshipLabel>
        <relationshipName>Additional_Sub_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Additional Sub Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Sub Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FSL_SubType__c.object
<CustomObject>
    <description>Used to store subtype data by distributor code</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <label>Location Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sub Type</label>
    <nameField>
        <label>Code Value - Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FSL_Timesheet__c.object
<CustomObject>
    <description>Custom object for FSL Times</description>
    <fields>
        <fullName>Additional_Sub_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Sub Type/Payer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose Additional Sub Type associated with the Service Order.</errorMessage>
            <filterItems>
                <field>$Source.Service_Order__c</field>
                <operation>equals</operation>
                <valueField>FSL_Additional_Sub_Type__c.Service_Order__c</valueField>
            </filterItems>
            <filterItems>
                <field>FSL_Additional_Sub_Type__c.TimesheetFlag__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FSL_Additional_Sub_Type__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>WorkOrder.Status</field>
                <operation>notEqual</operation>
                <value>Closed, Canceled, Intake</value>
            </filterItems>
            <filterItems>
                <field>WorkOrder.Type__c</field>
                <operation>equals</operation>
                <value>External</value>
            </filterItems>
            <filterItems>
                <field>WorkOrder.Status</field>
                <operation>notEqual</operation>
                <value>Closed, Canceled</value>
            </filterItems>
            <filterItems>
                <field>WorkOrder.Type__c</field>
                <operation>equals</operation>
                <value>Internal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>FSL Timesheets</relationshipLabel>
        <relationshipName>FSL_Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Submit</fullName>
                    <isActive>false</isActive>
                    <label>Submit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Intake</fullName>
                </value>
                <value>
                    <fullName>Schedule</fullName>
                </value>
                <value>
                    <fullName>Triage &amp; Diagnosis</fullName>
                    <default>true</default>
                    <label>Triage &amp; Diagnosis</label>
                </value>
                <value>
                    <fullName>Job Plan</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Warranty Claims</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>FSL_Service_Territory_Code__c</fullName>
        <description>Territory Code of the Service Location</description>
        <inlineHelpText>Territory Code of the Service Location</inlineHelpText>
        <label>Service Territory Code</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <label>Location Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DEALER</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-BRANCH</fullName>
                </value>
                <value>
                    <fullName>DISTRIBUTOR-HEADQUARTERS</fullName>
                </value>
                <value>
                    <fullName>GROUP</fullName>
                </value>
                <value>
                    <fullName>HOLSET - DISTRIBUTOR</fullName>
                </value>
                <value>
                    <fullName>INDUSTRIAL/VOCATIONAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FSL_GetTimesheetStatus_Test.cls
@isTest
public class FSL_GetTimesheetStatus_Test {

    @testSetup
    static void dataSetup() {
        worktype  wType = new worktype();
        wType.EstimatedDuration = Decimal.valueOf('40.02');
        wType.Name = 'Test';
        insert wType;
        
        
        FSL_Labor_Multiplier__c labMultiplier = new FSL_Labor_Multiplier__c();
        labMultiplier.Name='TIER B';
        insert labMultiplier;
        
        Asset  ast = new Asset();
        ast.Service_Model__c = 'ISL9 CM2350 L101';
        ast.Unit_Number__c = '1234';
        ast.Make__c = 'KENWORTH';
        ast.Model__c = 'T800';
        ast.Name = '79963830';
        ast.Unit_Type__c = 'EQ8349';
        ast.VIN__c = '1NKDX4TX6JJ180253';
        ast.Type_PSN__c = 'Engines-79963830';
        ast.Application_Description__c = 'AUTOMOTIVE';
        ast.Application_Code__c = '130';
        ast.Engine_Family__c    ='56'; 
        ast.Type__c = 'Engines';
        ast.Labor_Multiplier__c = labMultiplier.Id;
        insert ast;
        
        Asset  ast1 = new Asset();
        ast1.Service_Model__c = 'ISL9 CM2350 L101';
        ast1.Unit_Number__c = '1234';
        ast1.Make__c = 'KENWORTH';
        ast1.Model__c = 'T800';
        ast1.Name = '79963831';
        ast1.Unit_Type__c = 'EQ8349';
        ast1.VIN__c = '1NKDX4TX6JJ180253';
        ast1.Type_PSN__c = 'Engines-79963831';
        ast1.Application_Description__c = 'AUTOMOTIVE';
        ast1.Application_Code__c = '130';
        ast1.Engine_Family__c    ='56'; 
        ast1.Type__c = 'Engines';
        ast1.Labor_Multiplier__c = labMultiplier.Id;
        insert ast1;
        
        OperatingHours  oh = new OperatingHours ();
        oh.Name = 'new';
        oh.TimeZone = 'America/Chicago';
        insert oh;
        
        ServiceTerritory serTer1 = new ServiceTerritory();
        serTer1.Name = 'ST005 In Shop';
        serTer1.OperatingHoursId = oh.Id;
        serTer1.IsActive = true;
        serTer1.Location_Code__c = '03522-04893';
        serTer1.FSL_Service_Territory_Code__c = '04893';
        serTer1.Region__c = 'AUSTRALIA/ NEW ZEALAND';
        serTer1.Territory__c = 'AUSTRALIA';
        insert serTer1; 
        
        ServiceTerritory serTer = new ServiceTerritory();
        serTer.Name = 'ST001 Mobile';
        serTer.OperatingHoursId = oh.Id;
        serTer.IsActive = true;
        serTer.Location_Code__c = '03520';
        serTer.FSL_Service_Territory_Code__c = '04892';
        serTer.Region__c = 'AUSTRALIA/ NEW ZEALAND';
        serTer.Territory__c = 'AUSTRALIA';
        insert serTer;
        
        Case  cs = new Case();
        cs.Status = 'Triage & Diagnosis';
        //cs.Service_Territory__c = serTer.id;
        cs.AssetId = ast.id;
        cs.Priority = 'Medium';
        insert cs; 
        
        FSL_SubType__c subType = new FSL_SubType__c();
        subType.name = 'Test Sub Type';
        subType.Branch_Code__c =10;
        subType.Status__c='Active';
        insert subType;
        
        List<workorder> woInfo = new List<workorder>();
        workorder wo1 = new workorder();
        wo1.Status = 'Triage & Diagnosis';
        wo1.Process_Step__c = 'Triage & Diagnosis'; 
        wo1.Asset = ast1;
        wo1.Repair_Location__c = 'Mobile';
        wo1.EditComplaint__c = 'Testing';
        wo1.EditCause__c = 'Testing';
        wo1.EditCorrection__c = 'Testing';
        wo1.EditCoverage__c = 'Testing';
        wo1.ServiceTerritoryid = serTer.id;
        wo1.Case = cs;
        //wo1.sub_status__c = 'Troubleshooting Complete';
        //wo1.FSL_Additional_Email_Notifications__c='test@test.com';
        woInfo.add(wo1);
        
        insert woInfo;
        wo1.FSL_Sub_Type__c = subType.Id;
        wo1.Asset = ast1;
        update wo1;
        
        List<FSL_Additional_Sub_Type__c> ASTList = new List<FSL_Additional_Sub_Type__c>();
        FSL_Additional_Sub_Type__c ASType1 = new FSL_Additional_Sub_Type__c();
        ASType1.Service_Order__c = wo1.id;
        ASType1.Assignment_Number__c = '12345';
        ASType1.name = wo1.payer__c;
        ASType1.ERP_Job_Line_Number__c = '';
        // AST.Payer_Account__c = wo1.payer__c.split(':')[1];
        ASTList.add(ASType1);

        FSL_Additional_Sub_Type__c ASType = new FSL_Additional_Sub_Type__c();
        ASType.Service_Order__c = wo1.id;
        ASType.Assignment_Number__c = '001';
        ASType.name = wo1.payer__c;
        ASType.ERP_Job_Line_Number__c = '1234';
        // AST.Payer_Account__c = wo1.payer__c.split(':')[1];
        ASType.Primary__c = true;
        ASTList.add(ASType);

        insert ASTList;

	    List<FSL_Timesheet__c> TSList = new List<FSL_Timesheet__c>();
        FSL_Timesheet__c ts = new FSL_Timesheet__c();
        ts.Service_Order__c = wo1.Id;
        //ts.StartTime__c = System.Datetime.now()+1;
        ts.Reason__c = 'Travel';
        ts.Status__c = 'Invalid';
        ts.Additional_Sub_Type__c = ASType.Id;
        ts.StartTime__c = system.today()+1;
        TSList.add(ts);
        insert TSList;

    }

    @isTest
    static void getTimesheetStatus_positiveTest() {
		List<workorder> woList = [SELECT Id, WorkOrderNumber FROM workorder];
        String requestJSON =  '{'+
		'  "Header": {'+
		'    "Sender": {'+
		'      "ServiceName": "getTimesheetStatus",'+
		'      "SenderID": "MoveX"'+
		'    },'+
		'    "Target": {'+
		'      "TargetID": "Guidanz"'+
		'    }'+
		'  },'+
		'  "DataArea": {'+
		'    "CSSJobID": "'+woList[0].WorkOrderNumber+'",'+
		'    "ERPJobLineNumber": "1234",'+
		'    "AssignmentNumber": ""'+
		'  }'+
		'}';
system.debug('requestJSON++++'+requestJSON);
        RestResponse response = new RestResponse();
        RestRequest request = new RestRequest(); 
        request.requestURI = '/services/data/apexrest/getTimesheetStatus/';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(requestJSON);
        RestContext.request = request;
        RestContext.response= response;
        Test.startTest();
        FSL_GetTimesheetStatus.getTimesheetStatus();
        FSL_GetTimesheetStatusRequest.parse(requestJSON);
        Test.stopTest();
    }

    @isTest
    static void getTimesheetStatus_positiveTest2() {
        List<workorder> woList = [SELECT Id, WorkOrderNumber FROM workorder];
        String requestJSON =  '{'+
		'  "Header": {'+
		'    "Sender": {'+
		'      "ServiceName": "getTimesheetStatus",'+
		'      "SenderID": "MoveX"'+
		'    },'+
		'    "Target": {'+
		'      "TargetID": "Guidanz"'+
		'    }'+
		'  },'+
		'  "DataArea": {'+
		'    "CSSJobID": "'+woList[0].WorkOrderNumber+'",'+
		'    "ERPJobLineNumber": "",'+
		'    "AssignmentNumber": "12345"'+
		'  }'+
		'}';

        RestResponse response = new RestResponse();
        RestRequest request = new RestRequest(); 
        request.requestURI = '/services/data/apexrest/getTimesheetStatus/';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(requestJSON);
        RestContext.request = request;
        RestContext.response= response;
        Test.startTest();
        FSL_GetTimesheetStatus.getTimesheetStatus();
        Test.stopTest();
    }

    @isTest
    static void getTimesheetStatus_positiveTest3() {
        List<workorder> woList = [SELECT Id, WorkOrderNumber FROM workorder];
        String requestJSON =  '{'+
		'  "Header": {'+
		'    "Sender": {'+
		'      "ServiceName": "getTimesheetStatus",'+
		'      "SenderID": "MoveX"'+
		'    },'+
		'    "Target": {'+
		'      "TargetID": "Guidanz"'+
		'    }'+
		'  },'+
		'  "DataArea": {'+
		'    "CSSJobID": "'+woList[0].WorkOrderNumber+'",'+
		'    "ERPJobLineNumber": "",'+
		'    "AssignmentNumber": "123456"'+
		'  }'+
		'}';

        RestResponse response = new RestResponse();
        RestRequest request = new RestRequest(); 
        request.requestURI = '/services/data/apexrest/getTimesheetStatus/';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(requestJSON);
        RestContext.request = request;
        RestContext.response= response;
        
        Test.startTest();
        FSL_GetTimesheetStatus.getTimesheetStatus();
        
        boolean isException = false;
        try{
            FSL_Additional_Sub_Type__c ASType = [SELECT Id FROM FSL_Additional_Sub_Type__c WHERE Assignment_Number__c = '12345' LIMIT 1];
            workorder wo1 = [SELECT Id FROM workorder LIMIT 1];
            List<FSL_Timesheet__c> TSList = new List<FSL_Timesheet__c>();
            FSL_Timesheet__c ts = new FSL_Timesheet__c();
            ts.Service_Order__c = wo1.Id;
            ts.StartTime__c = System.Datetime.now();
            ts.Reason__c = 'Travel';
            ts.Status__c = 'Invalid';
            ts.Additional_Sub_Type__c = ASType.Id;
            TSList.add(ts);
            insert TSList;
        }catch(exception ex){
            isException = true;
        }
        system.assertEquals(true, isException);
        Test.stopTest();
    }   

}