objects/Audit_Trail_Event__mdt.object
<CustomObject>
    <fields>
        <fullName>Diagnostic_Audit_Trail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diagnostic Audit Trail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <label>Event Description</label>
        <length>6000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Audit Trail Event Types for Diagnostic and Repair</description>
        <label>Event Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Added failure</fullName>
                </value>
                <value>
                    <fullName>Campaign or TRP viewed</fullName>
                </value>
                <value>
                    <fullName>Changed Failure</fullName>
                </value>
                <value>
                    <fullName>Comments on Field Actions</fullName>
                </value>
                <value>
                    <fullName>Diagnostic Tool Launch</fullName>
                </value>
                <value>
                    <fullName>Faults received from Diagnostic Tool</fullName>
                </value>
                <value>
                    <fullName>Performed Repair</fullName>
                </value>
                <value>
                    <fullName>Performed Solution</fullName>
                </value>
                <value>
                    <fullName>Procedure was viewed</fullName>
                </value>
                <value>
                    <fullName>Search results or Solution Count</fullName>
                </value>
                <value>
                    <fullName>Select</fullName>
                    <default>true</default>
                    <label>Select</label>
                </value>
                <value>
                    <fullName>Selected root cause on Repair</fullName>
                </value>
                <value>
                    <fullName>Selected root cause on T&amp;D</fullName>
                </value>
                <value>
                    <fullName>Supervisor checked if need review/perform</fullName>
                </value>
                <value>
                    <fullName>Technician checked if performed checkbox</fullName>
                </value>
                <value>
                    <fullName>Technician checked if reviewed checkbox</fullName>
                </value>
                <value>
                    <fullName>TSB is viewed</fullName>
                </value>
                <value>
                    <fullName>User searched faults or symptoms</fullName>
                </value>
                <value>
                    <fullName>User selected Access SRT Details</fullName>
                </value>
                <value>
                    <fullName>User viewed FC Overview</fullName>
                </value>
                <value>
                    <fullName>Verified solution</fullName>
                </value>
                <value>
                    <fullName>Viewed solution on Repair</fullName>
                </value>
                <value>
                    <fullName>Viewed solution on T&amp;D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FSL Audit Trail Event</label>
    <pluralLabel>FSL Audit Trail Events</pluralLabel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Diagnostic_Response__c</fullName>
        <description>Values for Verification</description>
        <label>Diagnostic Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not the solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fault_Codes__c</fullName>
        <label>Fault Codes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <description>It’s a solution Id obtained from EDS.</description>
        <label>Solution Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Symptom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS_SymptomQA</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CSS_SymptomQA__c.Type__c</field>
                <operation>equals</operation>
                <value>SearchString</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CSS_SymptomQA__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FSL_Audit_Trail__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Added failure</fullName>
                </value>
                <value>
                    <fullName>Campaign or TRP viewed</fullName>
                </value>
                <value>
                    <fullName>Comments on Field Actions</fullName>
                </value>
                <value>
                    <fullName>Diagnostic Tool Launch</fullName>
                </value>
                <value>
                    <fullName>Faults received from Diagnostic Tool</fullName>
                </value>
                <value>
                    <fullName>Performed Repair</fullName>
                </value>
                <value>
                    <fullName>Procedure was viewed</fullName>
                </value>
                <value>
                    <fullName>Selected root cause on Repair</fullName>
                </value>
                <value>
                    <fullName>Selected root cause on T&amp;D</fullName>
                </value>
                <value>
                    <fullName>Supervisor checked if need review/perform</fullName>
                </value>
                <value>
                    <fullName>Technician checked if performed checkbox</fullName>
                </value>
                <value>
                    <fullName>Technician checked if reviewed checkbox</fullName>
                </value>
                <value>
                    <fullName>TSB is viewed</fullName>
                </value>
                <value>
                    <fullName>User searched faults or symptoms</fullName>
                </value>
                <value>
                    <fullName>User selected Access SRT Details</fullName>
                </value>
                <value>
                    <fullName>User viewed FC Overview</fullName>
                </value>
                <value>
                    <fullName>Verified solution</fullName>
                </value>
                <value>
                    <fullName>Viewed solution on Repair</fullName>
                </value>
                <value>
                    <fullName>Viewed solution on T&amp;D</fullName>
                </value>
                <value>
                    <fullName>Performed Solution</fullName>
                </value>
                <value>
                    <fullName>Search results or Solution Count</fullName>
                </value>
                <value>
                    <fullName>Changed Failure</fullName>
                </value>
                <value>
                    <fullName>Performed 4Cs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FSL_Diagnostic_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diagnostic Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipName>FSL_Audit_Trail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Response__c</fullName>
        <label>Solution Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>4Cs-Cause</fullName>
                </value>
                <value>
                    <fullName>4Cs-Complaint</fullName>
                </value>
                <value>
                    <fullName>4Cs-Correction</fullName>
                </value>
                <value>
                    <fullName>4Cs Coverage-User Notes</fullName>
                </value>
                <value>
                    <fullName>Could not Perform Solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
                <value>
                    <fullName>Most Likely Solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution. Repair recommended.</fullName>
                </value>
                <value>
                    <fullName>Not the Solution</fullName>
                </value>
                <value>
                    <fullName>Not the solution. Continue troubleshooting.</fullName>
                </value>
                <value>
                    <fullName>Repair not Performed.</fullName>
                </value>
                <value>
                    <fullName>Repair performed but didnot resolve the root cause.</fullName>
                </value>
                <value>
                    <fullName>Repair Successful</fullName>
                    <isActive>false</isActive>
                    <label>Repair Successful</label>
                </value>
                <value>
                    <fullName>Repair Successful.</fullName>
                </value>
                <value>
                    <fullName>Repair Successful with additional parts/procedures.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Symptom__c</fullName>
        <label>Symptom</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FSL Audit Trail</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Audit Trail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSL Audit Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSLAuditTrialEventLogger.cls
public class FSLAuditTrialEventLogger {
    public Boolean logFCOverviewEvent(Audit_Trail_Event__mdt auditEvent, String woId)
    {
        try
        {
            FSL_Audit_Trail__c objAuditTrail = new FSL_Audit_Trail__c();
        objAuditTrail.Event__c = auditEvent.Event_Type__c;
        objAuditTrail.FSL_Diagnostic_Audit__c = auditEvent.Diagnostic_Audit_Trail__c;            
        objAuditTrail.FSL_Description__c =  auditEvent.Event_Description__c;
        objAuditTrail.Service_Order__c = woId;
        insert objAuditTrail;
        return true;
        }
        catch(System.Exception ex)
        {
            return false;
        }
    }
    public Boolean logAccessSRTEvent(Audit_Trail_Event__mdt auditEvent, String woId, CSS_Solutions__c cssSol)
    {
        try
        {
            FSL_Audit_Trail__c objAuditTrail = new FSL_Audit_Trail__c();
            objAuditTrail.Event__c = auditEvent.Event_Type__c;
            objAuditTrail.FSL_Diagnostic_Audit__c = auditEvent.Diagnostic_Audit_Trail__c;            
            objAuditTrail.FSL_Description__c =  auditEvent.Event_Description__c + ' for Solution: '+cssSol.Name+'-'+cssSol.Solution_Title__c;
            objAuditTrail.Service_Order__c = woId;
            objAuditTrail.Rank__c = String.valueOf(cssSol.Rank__c);
            objAuditTrail.Service_Order__c = woId;
            objAuditTrail.Solution_Response__c = cssSol.Diagnostic_Response__c;
            objAuditTrail.Symptom__c = cssSol.Fault_Codes__c;
            insert objAuditTrail;
            return true;
        }
        catch(System.Exception ex)
        {
            return false;
        }
    }
}