objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>The currency that the order was place in.</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderDate__c</fullName>
        <description>The date of the order.</description>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partially Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partial Cancellation Requested</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Order Delayed</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Return Received and Approved</fullName>
                </value>
                <value>
                    <fullName>Return Request</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Approved</fullName>
                </value>
                <value>
                    <fullName>Return Complete</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Picked up</fullName>
                </value>
                <value>
                    <fullName>Return Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__TotalAmount__c</fullName>
        <description>ShipAmount__c + SubtotalAmount__c + TaxAmount__c + AdjustmentAmount__c + ShipDiscountAmount__c + TotalSurcharge__c</description>
        <formula>ccrz__ShipAmount__c + ccrz__SubtotalAmount__c + ccrz__TaxAmount__c +  ccrz__AdjustmentAmount__c  +  ccrz__ShipDiscountAmount__c + ccrz__TotalSurcharge__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dbu_Is_Cloned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>dbu_Is Cloned</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <inlineHelpText>The order that this order line is a part of.</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_myOrders.cls
public class dbu_myOrders {

    /**
* Author : Mounika V
* Created on 22nd September 2020
* Description : This class will do all the order related search operation
*/
    public dbu_myOrders() {}
     public class dbu_MyOrderWrapper{
public dbu_MyOrderWrapper(){}

@AuraEnabled public string orderDate;
@AuraEnabled public ccrz__E_Order__c orderRecord;
}



    @AuraEnabled(cacheable=true)
    // To fetch the list of order when clicked on the Tab - My Orders
    public static list<dbu_MyOrderWrapper> fetchOrders(){
        
        list<ccrz__E_Order__c> getOrders = new list<ccrz__E_Order__c>();
        list<dbu_MyOrderWrapper> wrapperList = new list<dbu_MyOrderWrapper>();
        
        Id loggedUserId = UserInfo.getUserId();
        if(loggedUserId != NULL){
        getOrders = [select Id,ccrz__CurrencyISOCode__c,name,ccrz__OrderDate__c,ccrz__TotalAmount__c,ccrz__OrderStatus__c,ccrz__User__c,dbu_Is_Cloned__c  from ccrz__E_Order__c WHERE ccrz__User__c =:loggedUserId  AND dbu_Is_Cloned__c = false ORDER BY Name DESC];
        }
        System.debug('OrderList===================>'+getOrders);
        if(getOrders.size() > 0){
        for(ccrz__E_Order__c orderObj : getOrders){
        dbu_MyOrderWrapper wrapperObj = new dbu_MyOrderWrapper();
        wrapperObj.orderRecord = orderObj;
         Date dt = orderObj.ccrz__OrderDate__c;
        wrapperObj.orderDate = DateTime.newInstance(dt.year(),dt.month(),dt.day()).format('MMMM dd, yyyy');
        wrapperList.add(wrapperObj);
        }
        }
        return wrapperList;
    } 
    
// To fetch the Details of each order
    @AuraEnabled(cacheable=true)
    public static List<dbu_CCOrderAPIResponseWrapper> fetchOrderDetail(String orderId){
        List<dbu_CCOrderAPIResponseWrapper> ccOrderWrapLst = new List<dbu_CCOrderAPIResponseWrapper>();
        if(orderId != ''){
            ccOrderWrapLst =  dbu_CallCCOrderApi.fetchOrderDetailsOnClick(orderId);
        }
        return ccOrderWrapLst;
    }
    
    @AuraEnabled(cacheable=true)
    public static list<ccrz__E_OrderItem__c> fetchOrderItemsBasedonInput(string searchval){
        string searchinput ='%'+searchval+'%';
        list<ccrz__E_OrderItem__c > orderitem= [select id,name ,ccrz__Order__r.name,ccrz__Product__r.name from ccrz__E_OrderItem__c where ccrz__Product__r.name like :searchinput];
        
        return orderitem;
    }
    
    @AuraEnabled(cacheable=true)
    public static list<dbu_MyOrderWrapper > orderFilter(string orderSearchText,string orderStatus,string orderTimeInterval){
        System.debug('orderStatus: '+orderStatus);
        list<ccrz__E_Order__c> order = new list<ccrz__E_Order__c>();
        list<dbu_MyOrderWrapper> wrapperList = new list<dbu_MyOrderWrapper>();
        Map<String, ccrz__E_Order__c> orderFileterdByProductName = new Map<String,ccrz__E_Order__c>();
        
        string neworderSearchText;
        if(String.isNotBlank(orderSearchText)){
            neworderSearchText ='%'+orderSearchText+'%';
        }
        Id loggedUserId = UserInfo.getUserId();
        date myDate =date.today();
        date newDate = mydate.addMonths(-integer.valueof(orderTimeInterval));
        System.debug('neworderSearchText====>'+neworderSearchText);
        System.debug('newDate====>'+newDate);
        if(newDate < date.today()){
            System.debug('newDate < date.today()\t');
        }else if(newDate > date.today()){
            System.debug('newDate > date.today()\t');
        }
        if (orderstatus=='allorderstatus' && String.isBlank(neworderSearchText)){
            order= [select Id,name,ccrz__OrderDate__c,ccrz__TotalAmount__c,ccrz__OrderStatus__c,ccrz__User__c from ccrz__E_Order__c where
                    (ccrz__OrderDate__c>:newDate) AND ccrz__User__c =:loggedUserId ];
        }
        else if(orderstatus=='allorderstatus' && String.isNotBlank(neworderSearchText)){
            list<ccrz__E_OrderItem__c > orderitem= [select id,name ,ccrz__Order__c,ccrz__Product__r.name from ccrz__E_OrderItem__c where ccrz__Product__r.name like :neworderSearchText];
            Set<String> orderIds = new Set<String>();
            for(ccrz__E_OrderItem__c obj : orderitem){
                orderIds.add(obj.ccrz__Order__c);
            }
            order = [select Id,ccrz__CurrencyISOCode__c,name,ccrz__OrderDate__c,ccrz__TotalAmount__c,ccrz__OrderStatus__c,ccrz__User__c,(select id,name ,ccrz__Order__c,ccrz__Product__r.name from ccrz__E_OrderItems__r where ccrz__Product__r.name like :neworderSearchText )  from ccrz__E_Order__c where
                     (name like :neworderSearchText OR Id =:orderSearchText OR id IN : orderIds) AND (ccrz__OrderDate__c>:newDate)
                     AND ccrz__User__c =:loggedUserId];
        }else if(orderstatus != 'allorderstatus' && String.isBlank(neworderSearchText)){
            order= [select Id,ccrz__CurrencyISOCode__c,name,ccrz__OrderDate__c,ccrz__TotalAmount__c,ccrz__OrderStatus__c,ccrz__User__c from ccrz__E_Order__c where
                    ccrz__OrderStatus__c =: orderstatus AND ccrz__OrderDate__c>:newDate
                    AND ccrz__User__c =:loggedUserId ];
        }else if(orderstatus != 'allorderstatus' && String.isBlank(neworderSearchText)){
            order= [select Id,ccrz__CurrencyISOCode__c,name,ccrz__OrderDate__c,ccrz__TotalAmount__c,ccrz__OrderStatus__c,ccrz__User__c from ccrz__E_Order__c where
                    (ccrz__OrderDate__c>:newDate
                     AND ccrz__OrderStatus__c =: orderstatus) AND ccrz__User__c =:loggedUserId];
        }
        
        if(order.size() > 0){
            for(ccrz__E_Order__c orderObj : order){
                dbu_MyOrderWrapper wrapperObj = new dbu_MyOrderWrapper();
                wrapperObj.orderRecord = orderObj;
                Date dt = orderObj.ccrz__OrderDate__c;
                wrapperObj.orderDate = DateTime.newInstance(dt.year(),dt.month(),dt.day()).format('MMMM dd, yyyy');
                wrapperList.add(wrapperObj);
            }
        }
        
        //order= [select Id,name,ccrz__OrderDate__c,ccrz__TotalAmount__c,ccrz__OrderStatus__c,ccrz__User__c from ccrz__E_Order__c WHERE ccrz__User__c =:loggedUserId];
        return wrapperList;
    }
    
}