objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>Activation_Key_Failure_Mail_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activation Key Failure Mail Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Activation_Keys__c</fullName>
        <label>Max Activation Keys</label>
        <summaryFilterItems>
            <field>ccrz__E_OrderItem__c.OMS_Product__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ccrz__E_OrderItem__c.ccrz__Order__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OSM_SW_Should_mail_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Should mail Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this order was placed for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>CancelLicenseAPICalled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CancelLicenseAPICalled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRevokeLicenseSucess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRevokeLicenseSucess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OMS_Item_ID__c</fullName>
        <label>OMS Item ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMS_Order_ID__c</fullName>
        <label>OMS Order ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMS_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OMS Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tool_Instance_Key__c</fullName>
        <label>Tool Instance Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__DisplayProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When this line refers to a product that is part of an aggregate product this field contains a reference to the parent aggregate product.</description>
        <label>Display Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Order Items (Display Product)</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <inlineHelpText>The order that this order line is a part of.</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>The sub-total amount for the order. This will be calculated as price * quantity - coupon adjustments during order placement.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantityperunit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of items that come in one order-able unit</description>
        <label>Quantityperunit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <label>Sequence</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>SoftwareStore</fullName>
                    <default>true</default>
                    <label>SoftwareStore</label>
                </value>
                <value>
                    <fullName>CSSNAStore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Subscription__c.object
<CustomObject>
    <description>This is a subscription, the record of purchased subscription</description>
    <fields>
        <fullName>OSM_Display_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OSM Display Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Subscriptions (OSM Display Product)</relationshipLabel>
        <relationshipName>CC_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items shipped for this subscriptions</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SPT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sub prod term this subscription was ordered from</description>
        <label>SPT</label>
        <referenceTo>ccrz__E_SubProdTerm__c</referenceTo>
        <relationshipLabel>CC Subscriptions</relationshipLabel>
        <relationshipName>CCSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <description>Used for modifiers to determine order in which they are processed.</description>
        <label>Sequence</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC Subscription</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>CC Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
    <description>Transaction payments represent payments made to the system.</description>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact of the user that created this transaction payment.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Transaction Payments</relationshipLabel>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{0000000000}</displayFormat>
        <label>CC Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Transaction Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IAM_Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reclaim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>this is for IDM purpose and to store cummins LDAP ID of all the users having the WWID from LDAP</description>
        <externalId>true</externalId>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OSM_Order_Item_License__c.object
<CustomObject>
    <fields>
        <fullName>OMS_Item_Id__c</fullName>
        <label>OMS Item Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMS_Order_ID__c</fullName>
        <label>OMS_Order_ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Revoked/ReIssue</fullName>
                </value>
                <value>
                    <fullName>ReIssued</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Revoke/ReIssue Pending</fullName>
                </value>
                <value>
                    <fullName>Create And Get Done</fullName>
                </value>
                <value>
                    <fullName>Create And Get Failed</fullName>
                </value>
                <value>
                    <fullName>Revoke Initiated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tool_Instance_Key__c</fullName>
        <label>Tool Instance Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>OSM Order Item License</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>OSM License Activation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Order Item Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OSM_CancelLicensesRetryIntBatch_Test.cls
//This is the test class for OSM_CancelLicensesRetryIntBatch
//updated on 29th Oct 2021.
@isTest
public class OSM_CancelLicensesRetryIntBatch_Test {
    /*public static testMethod void testMethodforCallingCancelLicenseApi()
    {
        //Create account
        Account portalAccount1 = new Account(
            Name = 'TestAccount',
            OwnerId = UserInfo.getUserId()
        );
        Database.insert(portalAccount1);
        
        //Create contact
        Contact contact1 = new Contact(
            FirstName = 'Test 1',
            Lastname = 'McTesty',
            AccountId = portalAccount1.Id,IAM_Contact_Status__c = 'Active',
            Username__c='unique1Test666'+'test@test.com',
            Email = 'test' + 'test@test.com'
        );
        
        Database.insert(contact1);
        ccrz__E_Order__c order = new ccrz__E_Order__c();
        order.ccrz__Contact__c=contact1.id;
        order.Activation_Key_Failure_Mail_Sent__c=true;
        order.OSM_SW_Should_mail_Send__c=false;
        //order.Max_Activation_Keys__c =1;
        insert order;
        
        ccrz__E_Product__c prod = new ccrz__E_Product__c();
        prod.name = 'INSITE™ Pro';
        prod.ccrz__SKU__c = '15458776';
        prod.ccrz__Quantityperunit__c = 3343;
        prod.ccrz__StartDate__c = system.today();
        prod.ccrz__EndDate__c = system.today()+1;
        prod.ccrz__ShortDesc__c = 'testing';
        insert prod;      
        
        ccrz__E_OrderItem__c orderItem = new ccrz__E_OrderItem__c();
        orderItem.ccrz__Order__c = order.ID; 
        orderItem.ccrz__Price__c = 50.00;
        orderItem.OMS_Item_ID__c='1234';
        orderItem.OMS_Product__c=true;
        orderItem.Tool_Instance_Key__c='';
        orderItem.ccrz__Quantity__c = 1;
        orderItem.ccrz__SubAmount__c = 50.00;
        orderItem.ccrz__Product__c=prod.id;
        orderItem.OMS_Product__c=true;
        //orderItem.CancelLicenseAPICalled__c=false;
        orderItem.OMS_Order_ID__c = '123';
        //orderItem.IsRevokeLicenseSucess__c=true;
        orderItem.ccrz__DisplayProduct__c=prod.id;
        insert orderItem;
        
        ccrz__E_Subscription__c sub = new ccrz__E_Subscription__c();
        sub.OSM_Display_Product__c = prod.id;
        sub.ccrz__Quantity__c = 10;
        sub.ccrz__Sequence__c = 2;
        //sub.ccrz__SPT__c = spt.Billing_Display_Name__c;
        sub.ccrz__Storefront__c = 'SoftwareStore';
        sub.ccrz__SubscriptionStartDate__c  = system.today();
        sub.ccrz__SubscriptionStatus__c = 'Active';
        sub.OSM_Subscription_End_Date__c = system.today()-2;
        sub.ccrz__CCOrderItem__c=orderItem.id;
        //sub.OSM_Free_Trial__c =true;
        //sub.OSM_Display_Product__r.ccrz__ShortDesc__c = 'test description';
        
        //insert sub;
        
        Set<Id> orderItemIdSet=new Set<Id>();
        orderItemIdSet.add(orderItem.id);
        
        OSM_Order_Item_License__c license=new OSM_Order_Item_License__c();
        license.CC_Order_Item__c=orderItem.id;
        license.Status__c ='New';
        license.OMS_Item_Id__c='1234';
        license.Tool_Instance_Key__c='';
        //license.Activation_Key__c='D8QV7BPP1BJ2';
        //     license.OMS_Item_Id_Basic__c='3333';
        insert license;
        
        OSM_Order_Item_License__c licenseChild=new OSM_Order_Item_License__c();
        licenseChild.CC_Order_Item__c=orderItem.id;
        licenseChild.Status__c ='New';
        licenseChild.OMS_Item_Id__c='1244';
        licenseChild.Tool_Instance_Key__c='F11111';
        licenseChild.Parent_Activation_Key__c=license.id;
        //  licenseChild.Activation_Key__c='D8QV7BPP1BJ2';
        licenseChild.IsCancelCalledSuccess__c=true;
        licenseChild.Revoked_ReIssue_Lisence__c=license.id;
        //     licenseChild.OMS_Item_Id_Basic__c='3333';
        insert licenseChild;
        
        Test.StartTest();
        OSM_CancelLicenses_ServiceHandler.callCancelLicensesAPI(orderItemIdSet);
        String jsonInput='{"Header":{"Target":{"TargetID":"OMS"},"Sender":{"ServiceName":"CancelLicense","SenderID":"Mrktplc"}},"CancelLicensesInput":{"TotalCopies":1,"ToolName":"INSITE","RequesterId":"nu6155@cummins.com","ItemId":"8559950"}}';
        String jsonOutput='{"Header":{"Sender":{"ServiceName":"CancelLicense","SenderID":"Mrktplc"},"Status":"Success","Target":{"TargetID":"OMS"},"ReturnCodeDescription":"Success"},"CancelLicensesOutput":{"CancelledCopies":1,"CancelLicenseStatus":true,"RemainingCopies":0}}';
        OSM_CancelLicensesREQWrapper reqWrap=new OSM_CancelLicensesREQWrapper();
        OSM_CancelLicensesREQWrapper.parse(jsonInput);
        OSM_CancelLicensesREQ_GeneralizedWrapper reqGenWrap=new OSM_CancelLicensesREQ_GeneralizedWrapper();
        OSM_CancelLicensesREQ_GeneralizedWrapper.parse(jsonInput);
        OSM_CancelLicensesRESWrapper resWrap=new OSM_CancelLicensesRESWrapper();
        OSM_CancelLicensesRESWrapper.parse(jsonOutput);
        OSM_CancelLicensesRES_GeneralizedWrapper resGenWrap=new OSM_CancelLicensesRES_GeneralizedWrapper();
        OSM_CancelLicensesRES_GeneralizedWrapper.parse(jsonOutput);
        
        Test.StopTest();
    }*/
    
    public static testMethod void testMethodforCallingCancelAndRefund()
    {
        //Create account
        Account portalAccount1 = new Account(
            Name = 'TestAccount',
            OwnerId = UserInfo.getUserId()
        );
        Database.insert(portalAccount1);
        
        //Create contact
        Contact contact1 = new Contact(
            FirstName = 'Test',
            Lastname = 'McTesty',
            AccountId = portalAccount1.Id,IAM_Contact_Status__c = 'Active',
            Username__c='Test666unique2'+'test@test.com',
            Email = 'test' + 'test@test.com'
        );
        
        Database.insert(contact1);
        
        ccrz__E_Order__c order = new ccrz__E_Order__c();
        order.ccrz__Contact__c=contact1.id;
        order.OrderProcessedforFSD__c=true;
        order.ccrz__OrderStatus__c='Cancellation Pending';
        order.OSM_SW_Should_mail_Send__c=false;
        //order.OSM_SW_Is_Refund_FSD_Done__c=true;
        //order.OSM_SW_Is_OMS_Revoke_and_Cancel_Not_Done__c=false;
        // order.Is_OMS_Revoke_and_Cancel_Not_Done_Count__c=0;
        insert order;
        
        ccrz__E_TransactionPayment__c transPayment=new ccrz__E_TransactionPayment__c();
        transPayment.ccrz__CCOrder__c=order.id;
        
        transPayment.ccrz__AccountType__c='cc';
        insert transPayment;
        ccrz__E_Product__c prod = new ccrz__E_Product__c();
        prod.name = 'INSITE™ Pro';
        prod.ccrz__SKU__c = '15458776';
        prod.ccrz__Quantityperunit__c = 3343;
        prod.ccrz__StartDate__c = system.today();
        prod.ccrz__EndDate__c = system.today()+1;
        prod.ccrz__ShortDesc__c = 'testing';
        insert prod;
        
        ccrz__E_OrderItem__c orderItem = new ccrz__E_OrderItem__c();
        orderItem.OSM_GetTI_Success__c = true;
        //orderItem.OSM_SW_Is_OMS_Revoke_and_Cancel_Not_Done__c =false;
        orderItem.ccrz__Order__c = order.ID; 
        orderItem.ccrz__Price__c = 50.00;
        orderItem.OMS_Item_ID__c='6666';
        orderItem.OMS_Product__c=true;
        orderItem.CancelLicenseAPICalled__c=false;
        orderItem.Is_Revoked__c=true;
        orderItem.ccrz__Quantity__c = 1;
        orderItem.ccrz__SubAmount__c = 50.00;
        orderItem.ccrz__Product__c=prod.id;
        orderItem.OMS_Order_ID__c = '123';
        orderItem.OSM_Tool_Instance_Key__c='';
        //   orderItem.Tool_Instance_Count__c=1;
        orderItem.ccrz__DisplayProduct__c=prod.id;
        orderItem.IsRevokeLicenseSucess__c=false;
        orderItem.ccrz__OriginalQuantity__c=1;
        orderItem.isRenew__c=true;
        orderItem.OSM_SW_Is_Refund_FSD_Done__c=true;
        insert orderItem;
        
        ccrz__E_Subscription__c sub = new ccrz__E_Subscription__c();
        sub.OSM_Display_Product__c = prod.id;
        sub.ccrz__Quantity__c = 10;
        sub.ccrz__Sequence__c = 2;
        //sub.ccrz__SPT__c = spt.Billing_Display_Name__c;
        sub.ccrz__Storefront__c = 'SoftwareStore';
        sub.ccrz__SubscriptionStartDate__c  = system.today();
        sub.ccrz__SubscriptionStatus__c = 'Active';
        sub.OSM_Subscription_End_Date__c = system.today()-2;
        sub.ccrz__CCOrderItem__c=orderItem.id;
        sub.OSM_Free_Trial__c =false;
        //sub.OSM_Display_Product__r.ccrz__ShortDesc__c = 'test description';
        
        //   insert sub;
        
        
        OSM_Order_Item_License__c license=new OSM_Order_Item_License__c();
        license.CC_Order_Item__c=orderItem.id;
        license.Status__c ='New';
        license.OMS_Item_Id__c='12348';
        license.Tool_Instance_Key__c='';
        //      license.Activation_Key__c='C8QV7CPP1BJ2';
        license.OMS_Item_Id__c='3113';
        //        license.OMS_Item_Id_Basic__c='3333';
        insert license;
        
        OSM_Order_Item_License__c licenseChild=new OSM_Order_Item_License__c();
        licenseChild.CC_Order_Item__c=orderItem.id;
        licenseChild.Status__c ='New';
        licenseChild.OMS_Item_Id__c='1234';
        licenseChild.Tool_Instance_Key__c='';
        //licenseChild.Basic_Tool_Instance_Key__c='';
        licenseChild.Parent_Activation_Key__c=license.id;
        // licenseChild.Activation_Key__c='D8QV7BPP1BJ2';
        licenseChild.IsCancelCalledSuccess__c=false;
        licenseChild.Revoked_ReIssue_Lisence__c=license.id;
        //  licenseChild.OMS_Item_Id_Basic__c='3333';
        insert licenseChild;
        
        Test.StartTest();
        OSM_CancelLicensesRetryIntBatch batch=new OSM_CancelLicensesRetryIntBatch();
        Database.executeBatch(batch);
        Test.StopTest();
    }
    
   /* public static testMethod void testMethodforMandatoryFieldsMissingCheck()
    {
        //Create account
        Account portalAccount1 = new Account(
            Name = 'TestAccount',
            OwnerId = UserInfo.getUserId()
        );
        Database.insert(portalAccount1);
        
        //Create contact
        Contact contact1 = new Contact(
            FirstName = 'Test',
            Lastname = 'McTesty',
            AccountId = portalAccount1.Id,IAM_Contact_Status__c = 'Active',
            Username__c='unique3Test666'+'test@test.com',
            Email = 'test' + 'test@test.com'
        );
        
        Database.insert(contact1);
        ccrz__E_Order__c order = new ccrz__E_Order__c();
        order.ccrz__Contact__c=contact1.id;
        order.OrderProcessedforFSD__c=true;
        //order.Is_OMS_Revoke_and_Cancel_Not_Done_Count__c=0;
        order.OSM_SW_Should_mail_Send__c=false;
        insert order;
        ccrz__E_TransactionPayment__c transPayment=new ccrz__E_TransactionPayment__c();
        transPayment.ccrz__CCOrder__c=order.id;
        transPayment.ccrz__AccountType__c='po';
        insert transPayment;
        
        ccrz__E_Product__c prod = new ccrz__E_Product__c();
        prod.name = 'Fleet Count';
        prod.ccrz__SKU__c = '15458776';
        prod.ccrz__Quantityperunit__c = 3343;
        prod.ccrz__StartDate__c = system.today();
        prod.ccrz__EndDate__c = system.today()+1;
        prod.ccrz__ShortDesc__c = 'testing';
        insert prod;
        
        ccrz__E_OrderItem__c orderItem = new ccrz__E_OrderItem__c();
        orderItem.ccrz__Order__c = order.ID; 
        orderItem.ccrz__Price__c = 50.00;
        // orderItem.OMS_Item_ID__c='';
        orderItem.OMS_Product__c=true;
        orderItem.CancelLicenseAPICalled__c=false;
        orderItem.Tool_Instance_Key__c='';
        orderItem.ccrz__Quantity__c = 1;
        orderItem.ccrz__SubAmount__c = 50.00;
        orderItem.ccrz__Product__c=prod.id;
        orderItem.OMS_Order_ID__c = '123';
        orderItem.ccrz__DisplayProduct__c=prod.id;
        orderItem.Number_of_Bundles__c=1;
        // orderItem.OMS_Item_Id_Basic__c=777;
        insert orderItem;
        
        ccrz__E_Subscription__c sub = new ccrz__E_Subscription__c();
        sub.OSM_Display_Product__c = prod.id;
        sub.ccrz__Quantity__c = 10;
        sub.ccrz__Sequence__c = 2;
        //sub.ccrz__SPT__c = spt.Billing_Display_Name__c;
        sub.ccrz__Storefront__c = 'SoftwareStore';
        sub.ccrz__SubscriptionStartDate__c  = system.today();
        sub.ccrz__SubscriptionStatus__c = 'Active';
        sub.OSM_Subscription_End_Date__c = system.today()-2;
        sub.ccrz__CCOrderItem__c=orderItem.id;
        sub.OSM_Free_Trial__c =false;
        //sub.OSM_Display_Product__r.ccrz__ShortDesc__c = 'test description';
        
        //   insert sub;
        
        
        Set<Id> orderItemIdSet=new Set<Id>();
        orderItemIdSet.add(orderItem.id);
        OSM_Order_Item_License__c license=new OSM_Order_Item_License__c();
        license.CC_Order_Item__c=orderItem.id;
        license.Status__c ='New';
        license.OMS_Item_Id__c='';
        license.Tool_Instance_Key__c='';
        license.Activation_Key__c='';
        insert license;
        
        OSM_Order_Item_License__c licenseChild=new OSM_Order_Item_License__c();
        licenseChild.CC_Order_Item__c=orderItem.id;
        licenseChild.Status__c ='New';
        licenseChild.OMS_Item_Id__c='1234';
        licenseChild.Tool_Instance_Key__c='F11111';
        licenseChild.Parent_Activation_Key__c=license.id;
        // licenseChild.Activation_Key__c='D8QV7BPP1BJ2';
        licenseChild.IsCancelCalledSuccess__c=true;
        licenseChild.Revoked_ReIssue_Lisence__c=license.id;
        //licenseChild.OMS_Item_Id_Basic__c='3333';
        insert licenseChild;
        
        Test.StartTest();
        OSM_CancelLicenses_ServiceHandler.callCancelLicensesAPI(orderItemIdSet);
        Test.StopTest();
    }
    public static testMethod void testMethodforMandatoryFieldsCheck()
    {
        //Create account
        Account portalAccount1 = new Account(
            Name = 'TestAccount',
            OwnerId = UserInfo.getUserId()
        );
        Database.insert(portalAccount1);
        
        //Create contact
        Contact contact1 = new Contact(
            FirstName = 'Test',
            Lastname = 'McTesty',
            AccountId = portalAccount1.Id,IAM_Contact_Status__c = 'Active',
            Username__c='uniqie4Test666'+'test@test.com',
            Email = 'test' + 'test@test.com'
        );
        
        Database.insert(contact1);
        ccrz__E_Order__c order = new ccrz__E_Order__c();
        order.ccrz__Contact__c=contact1.id;
        order.OrderProcessedforFSD__c=true;
        //order.Is_OMS_Revoke_and_Cancel_Not_Done_Count__c=0;
        order.OSM_SW_Should_mail_Send__c=false;
        insert order;
        ccrz__E_TransactionPayment__c transPayment=new ccrz__E_TransactionPayment__c();
        transPayment.ccrz__CCOrder__c=order.id;
        transPayment.ccrz__AccountType__c='po';
        insert transPayment;
        
        ccrz__E_Product__c prod = new ccrz__E_Product__c();
        prod.name = 'INSITE™ Pro';
        prod.ccrz__SKU__c = '15458776';
        prod.ccrz__Quantityperunit__c = 3343;
        prod.ccrz__StartDate__c = system.today();
        prod.ccrz__EndDate__c = system.today()+1;
        prod.ccrz__ShortDesc__c = 'testing';
        insert prod;
        
        ccrz__E_OrderItem__c orderItem = new ccrz__E_OrderItem__c();
        orderItem.ccrz__Order__c = order.ID; 
        orderItem.ccrz__Price__c = 50.00;
        //orderItem.OMS_Item_ID__c='';
        orderItem.OMS_Product__c=true;
        orderItem.CancelLicenseAPICalled__c=false;
        orderItem.Tool_Instance_Key__c='1234';
        orderItem.ccrz__Quantity__c = 1;
        orderItem.ccrz__SubAmount__c = 50.00;
        orderItem.ccrz__Product__c=prod.id;
        orderItem.OMS_Order_ID__c = '123';
        orderItem.ccrz__DisplayProduct__c=prod.id;
        orderItem.Number_of_Bundles__c=1;
        //   orderItem.OMS_Item_Id_Basic__c=777;
        
        insert orderItem;
        
        ccrz__E_Subscription__c sub = new ccrz__E_Subscription__c();
        sub.OSM_Display_Product__c = prod.id;
        sub.ccrz__Quantity__c = 10;
        sub.ccrz__Sequence__c = 2;
        //sub.ccrz__SPT__c = spt.Billing_Display_Name__c;
        sub.ccrz__Storefront__c = 'SoftwareStore';
        sub.ccrz__SubscriptionStartDate__c  = system.today();
        sub.ccrz__SubscriptionStatus__c = 'Active';
        sub.OSM_Subscription_End_Date__c = system.today()-2;
        sub.ccrz__CCOrderItem__c=orderItem.id;
        sub.OSM_Free_Trial__c =false;
        //sub.OSM_Display_Product__r.ccrz__ShortDesc__c = 'test description';
        
        //insert sub;
        
        
        Set<Id> orderItemIdSet=new Set<Id>();
        orderItemIdSet.add(orderItem.id);
        OSM_Order_Item_License__c license=new OSM_Order_Item_License__c();
        license.CC_Order_Item__c=orderItem.id;
        license.Status__c ='New';
        license.OMS_Item_Id__c='1234';
        license.Tool_Instance_Key__c='';
        // license.Activation_Key__c='C8QV7BPP1BJ2';
        
        insert license;
        
        OSM_Order_Item_License__c licenseChild=new OSM_Order_Item_License__c();
        licenseChild.CC_Order_Item__c=orderItem.id;
        licenseChild.Status__c ='New';
        licenseChild.OMS_Item_Id__c='1234';
        licenseChild.Tool_Instance_Key__c='F11111';
        licenseChild.Parent_Activation_Key__c=license.id;
        //  licenseChild.Activation_Key__c='D8QV7BPP1BJ2';
        licenseChild.IsCancelCalledSuccess__c=true;
        licenseChild.Revoked_ReIssue_Lisence__c=license.id;
        //licenseChild.OMS_Item_Id_Basic__c='3333';
        insert licenseChild;
        
        Test.StartTest();
        OSM_CancelLicenses_ServiceHandler.callCancelLicensesAPI(orderItemIdSet);
        Test.StopTest();
    }*/
    
    
}