objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>FW_Product_Count__c</fullName>
        <label>FW Product Count</label>
        <summaryFilterItems>
            <field>ccrz__E_OrderItem__c.Is_FW_OrderItem__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>ccrz__E_OrderItem__c.OSM_SW_Is_Included_Product__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>ccrz__E_OrderItem__c.ccrz__Order__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>IsInterCompanyProcessSuccess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created to check the intercompany record creation process is success or not in retry batch class.</description>
        <label>IsInterCompanyProcessSuccess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OSM_SW_Is_InterCompany_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is InterCompany Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderProcessedforFSD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Processed for FSD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partially Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partial Cancellation Requested</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Order Delayed</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Return Received and Approved</fullName>
                </value>
                <value>
                    <fullName>Return Request</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Approved</fullName>
                </value>
                <value>
                    <fullName>Return Complete</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Picked up</fullName>
                </value>
                <value>
                    <fullName>Return Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_InterCompanyInvoice_RetryBatch.cls
/************************************************************
Name:  OSM_InterCompanyInvoice_RetryBatch
Copyright © 2018  Cummins
=============================================================
=============================================================
Purpose:                                                            
This batch class will be used to initiate the Intercompany 
record creation process.
============================================================
=============================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE              DETAIL                                
1.0 -   Sangeeta         27th Dec 2018     INITIAL DEVELOPMENT  
1.1 -   Nandigam Sasi    19th APR 2021     Updated   Batch Execution as part of MAR-1548 
*************************************************************/
global class OSM_InterCompanyInvoice_RetryBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable,Database.RaisesPlatformEvents{
    global OSM_InterCompanyInvoice_RetryBatch(){
        // do nothing
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
       return Database.getQueryLocator([select Id from ccrz__E_Order__c where ccrz__OrderStatus__c = 'Order Submitted' AND OrderProcessedforFSD__c=true And IsInterCompanyProcessSuccess__c=false And OSM_SW_Is_InterCompany_Order__c=false And CreatedDate = THIS_MONTH AND FW_Product_Count__c<=0 AND ccrz__Storefront__c='SoftwareStore' ORDER BY LastModifiedDate DESC]);
    }
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_Order__c> scope){
        Set<Id> set_OrderId = new Set<Id>();
        for(ccrz__E_Order__c order : scope){
            set_OrderId.add(order.id);
        }
        if(set_OrderId.size() > 0){
            System.enqueueJob(new OSM_InterCompanyQueueable(set_OrderId));
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
    global void execute(SchedulableContext SC){
        Database.executeBatch(new OSM_InterCompanyInvoice_RetryBatch(),Integer.valueOf(Label.OSM_InterCompany_Batch_Size));
    }
}