objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ByPassFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ToByPassFlow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partially Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partial Cancellation Requested</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Order Delayed</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Return Received and Approved</fullName>
                </value>
                <value>
                    <fullName>Return Request</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Approved</fullName>
                </value>
                <value>
                    <fullName>Return Complete</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Picked up</fullName>
                </value>
                <value>
                    <fullName>Return Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <formula>TEXT(ccrz__Product__r.Group_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <inlineHelpText>The order that this order line is a part of.</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>The sub-total amount for the order. This will be calculated as price * quantity - coupon adjustments during order placement.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DA</fullName>
                </value>
                <value>
                    <fullName>SES</fullName>
                </value>
                <value>
                    <fullName>FluidWatch</fullName>
                </value>
                <value>
                    <fullName>Ecom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductStatus__c</fullName>
        <description>The status of the product. In Creation - Newly created product, that still requires augmentation and is not visible on the site; Blocked - product has been blocked from being displayed on the site; Not Orderable - product can be viewed, but cannot be added to a cart or ordered; Released - fully availble product</description>
        <label>Product Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Not Orderable</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>In Creation</fullName>
                    <default>true</default>
                    <label>In Creation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Quantityperunit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of items that come in one order-able unit</description>
        <label>Quantityperunit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>SoftwareStore</fullName>
                    <default>true</default>
                    <label>SoftwareStore</label>
                </value>
                <value>
                    <fullName>CSSNAStore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dbu_Has_Core_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>dbu_Has Core Child</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dbu_mostPopularParts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Most Popular Parts</description>
        <label>dbu_mostPopularParts</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_mostPopularPartsBatch_Test.cls
@isTest
public class dbu_mostPopularPartsBatch_Test 
{
    static testMethod void test() 
    {
        List<ccrz__E_OrderItem__c> orderItemList = new List<ccrz__E_OrderItem__c>();
        List<ccrz__E_Product__c> productList = new List<ccrz__E_Product__c>(); 
        
        //ccrz__E_Product__c objProduct = new ccrz__E_Product__c();
        ccrz__E_OrderItem__c orderItem = new ccrz__E_OrderItem__c();
        //Product
          ccrz__E_Product__c objProduct = new ccrz__E_Product__c(ccrz__SKU__c = '15458776',
                                                               Name = 'Connected Advisor',
                                                               ccrz__ShortDesc__c = 'testing',
                                                               ccrz__Quantityperunit__c = 3343,
                                                               ccrz__StartDate__c = system.today(),
                                                               ccrz__EndDate__c = system.today()+1,
        													   dbu_mostPopularParts__c = false,
                                                               dbu_Has_Core_Child__c = false,
                                                               Group_Name__c='Ecom');
        insert objProduct;
        
        ccrz__E_Product__c objProduct2 = new ccrz__E_Product__c(Name = 'Test',
                                                                ccrz__SKU__c = '15458777',
                                                                ccrz__ShortDesc__c = 'testing',
                                                                ccrz__Quantityperunit__c = 3343,
                                                                ccrz__StartDate__c = system.today(),
                                                                ccrz__EndDate__c = system.today()+1,
            												    dbu_mostPopularParts__c = false,
                                                                dbu_Has_Core_Child__c = false,
                                                                Group_Name__c='Ecom');
        insert objProduct2;
        //Order
        ccrz__E_Order__c order = new ccrz__E_Order__c(ByPassFlow__c = true);
        order.ccrz__OrderStatus__c='Cancellation Pending'; 
        Insert order;
        
        // OrderItem 
        orderItem.ccrz__Price__c = 500;
        orderItem.ccrz__Quantity__c = 55;
        orderItem.ccrz__SubAmount__c = 250;
        orderItem.ccrz__Order__c = order.id;
        //orderItem.Group_Name__c = 'Ecom';
        orderItem.ccrz__Product__c = objProduct.Id; 
         
        Insert orderItem;
        
        ccrz__E_OrderItem__c orderItem2 = new ccrz__E_OrderItem__c();
        orderItem2.ccrz__Price__c = 500;
        orderItem2.ccrz__Quantity__c = 75;
        orderItem2.ccrz__SubAmount__c = 250;
        //orderItem2.Group_Name__c = 'Ecom';
        orderItem2.ccrz__Order__c = order.id;
        orderItem2.ccrz__Product__c = objProduct2.Id;
        
        Insert orderItem2;
        
        
        // OrderItem
            //orderItem.ccrz__Product__c = objProduct.Id;
			//orderItem.ccrz__Quantity__c =  3;
        	//orderItem.ccrz__Order__c = 'a2V3J0000001FC4UAM'; 
			//orderItem.ccrz__Price__c = 	320.0;
			//orderItem.ccrz__SubAmount__c = 	640.0;
          //Insert orderItem; 
        /*
        for(Integer i=0;i<2;i++)
        {
            objProduct.Name = 'Cummins Rectangular Ring Seal 100099 ' + i;
            objProduct.ccrz__SKU__c = '100099CECO ' + i;
            //objProduct.ccrz__ProductStatus__c = 'Released';
            //objProduct.ccrz__Storefront__c = 'CSSNAStore';
            //objProduct.Group_Name__c = 'Ecom';
        	objProduct.dbu_mostPopularParts__c = false;
            //productList.add(objProduct);
        }  
        Insert	objProduct; 
		System.debug('objProduct>>>' + objProduct);
        
        for(Integer i = 0 ; i < 3; i++)
        {
            orderItem.ccrz__Product__c = objProduct.Id;
			orderItem.ccrz__Quantity__c =  i;
            orderItemList.add(orderItem);
        }
        System.debug('orderItemList>>>' + orderItemList);
        Insert orderItemList;
        */
        
        Test.startTest();
			dbu_mostPopularPartsBatch obj = new dbu_mostPopularPartsBatch();
			DataBase.executeBatch(obj); 
        Test.stopTest();
         
        //Verify orderItem updated
        //List<ccrz__E_OrderItem__c> accUpdatedList = [SELECT Id, Name FROM ccrz__E_OrderItem__c];
        //System.assert(accUpdatedList[0].Name.Contains('Updated'));
    }

}