objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The B2B Commerce pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>ccrz__CurrencyISOCode__c</fullName>
        <description>Required - The 3-character ISO currency code corresponding to this list. For example, USD</description>
        <label>Currency ISO Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the pricelist to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>SoftwareStore</fullName>
                </value>
                <value>
                    <fullName>CSSNAStore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dbu_Discount_Percent__c</fullName>
        <label>Discount Percent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>dbu_Original_Price__c</fullName>
        <description>To display the original price of the product</description>
        <label>dbu_Original Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>SoftwareStore</fullName>
                    <default>true</default>
                    <label>SoftwareStore</label>
                </value>
                <value>
                    <fullName>CSSNAStore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_discountPriceUpdate_Test.cls
/**

* @description : Test class for dbu_discountPriceUpdate.cls

* @author : Yash Sethi

* @group :

* @last modified on : 07-22-2022

* @last modified by : ChangeMeIn@UserSettingsUnder.SFDoc

**/

@isTest
public class dbu_discountPriceUpdate_Test 
{
	@testSetup
    public static void testData()
    {
        ccrz__E_PriceList__c priceList = dbu_FactoryDataTest.createPriceList('Demo Price List');
        insert priceList;
        
        ccrz__E_Product__c lstEProduct = dbu_FactoryDataTest.createProduct('Demo Product', False, False, False, False);
        insert lstEProduct;
        
        ccrz__E_PriceListItem__c priceListItem = dbu_FactoryDataTest.createPriceListItem('Demo price list item', 100, 50, 'Percentage', 50, lstEProduct.id, priceList.id);
        insert priceListItem;
        
        ccrz__E_PriceList__c priceList2 = dbu_FactoryDataTest.createPriceList('Demo Price List CAD');
        priceList2.ccrz__CurrencyISOCode__c = 'CAD';
        insert priceList2;
        
        ccrz__E_Product__c lstEProduct2 = dbu_FactoryDataTest.createProduct('Demo Product CAD', False, False, False, False);
        insert lstEProduct2;
        
        ccrz__E_PriceListItem__c priceListItem2 = dbu_FactoryDataTest.createPriceListItem('Demo price list item CAD', 80, 50, 'Percentage', 50, lstEProduct2.id, priceList2.id);
        priceListItem2.dbu_Discount_Percent__c = 10;
        priceListItem2.dbu_Original_Price__c = null;
        insert priceListItem2;
    }
    
    @isTest
    public static void updateDiscount()
    {
        List<ccrz__E_PriceList__c> priceList = [Select id, ccrz__Storefront__c from ccrz__E_PriceList__c];
        List<ccrz__E_PriceListItem__c> itemList = [select id, dbu_Discount_Percent__c, dbu_Original_Price__c, ccrz__Price__c, ccrz__Pricelist__c, ccrz__Product__c from ccrz__E_PriceListItem__c WHERE dbu_Original_Price__c = 100  LIMIT 1];
        List<ccrz__E_PriceListItem__c> OriginalPriceChange = [select id, dbu_Discount_Percent__c, dbu_Original_Price__c, ccrz__Price__c, ccrz__Pricelist__c, ccrz__Product__c from ccrz__E_PriceListItem__c LIMIT 1];
        List<ccrz__E_PriceListItem__c> discountChange = [select id, dbu_Discount_Percent__c, dbu_Original_Price__c, ccrz__Price__c, ccrz__Pricelist__c, ccrz__Product__c from ccrz__E_PriceListItem__c LIMIT 1];
        
        List<ccrz__E_PriceListItem__c> itemListCAD = [select id, dbu_Discount_Percent__c, dbu_Original_Price__c, ccrz__Price__c, ccrz__Pricelist__c, ccrz__Product__c from ccrz__E_PriceListItem__c WHERE dbu_Discount_Percent__c = 10 LIMIT 1];
        
        map<id, ccrz__E_PriceListItem__c> oldItemMap = new map<id, ccrz__E_PriceListItem__c>();
        map<id, ccrz__E_PriceListItem__c> oriPriceMap = new map<id, ccrz__E_PriceListItem__c>();
        map<id, ccrz__E_PriceListItem__c> discountChangeMap = new map<id, ccrz__E_PriceListItem__c>();
        
        ccrz__E_PriceListItem__c pr = itemList[0];
        pr.ccrz__Price__c = 200;
        pr.dbu_Original_Price__c = 150;
        pr.dbu_Discount_Percent__c = 10;
        update pr;
        
        pr.dbu_Discount_Percent__c = null;
        update pr;
        
        ccrz__E_PriceListItem__c prCAD = itemListCAD[0];
        prCAD.ccrz__Price__c = 200;
        prCAD.dbu_Original_Price__c = 150;
        prCAD.dbu_Discount_Percent__c = 10;
        update prCAD;
        
        ccrz__E_PriceListItem__c pri = OriginalPriceChange[0];
        pri.dbu_Original_Price__c = 200;
        update pri;
        
        ccrz__E_PriceListItem__c dpri = discountChange[0];
        dpri.dbu_Discount_Percent__c = 20;
        update dpri;
        
        oldItemMap.put(pr.id, pr);
        oriPriceMap.put(pri.id, pri);
        discountChangeMap.put(dpri.id, dpri);
    }
}