objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DA</fullName>
                </value>
                <value>
                    <fullName>SES</fullName>
                </value>
                <value>
                    <fullName>FluidWatch</fullName>
                </value>
                <value>
                    <fullName>Ecom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__AverageRating__c</fullName>
        <description>Formula field - average product rating for this product</description>
        <formula>IF(ccrz__NumberOfReviews__c &gt; 0, ccrz__TotalRating__c / ccrz__NumberOfReviews__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Rating</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantityperunit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of items that come in one order-able unit</description>
        <label>Quantityperunit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dbu_Image_Src__c</fullName>
        <label>dbu_Image Src</label>
        <type>Url</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_CustomSearchController.cls
public with sharing class dbu_CustomSearchController {
    /**
     * Author : Mounika T 
     * Created on 7th July 2020
     * Description : This class will do all the product related custom search operation
     */
    public dbu_CustomSearchController() {}
     @AuraEnabled(cacheable=true)
     public static list<ccrz__E_Product__c> getProductList(string searchKey) {
        // create product list to store search result 
        list<ccrz__E_Product__c> lstproduct = new list<ccrz__E_Product__c>();
        try{
            string sTempSearchKey = '%' + searchKey + '%';
            // query profuct records
            for(ccrz__E_Product__c prod : [select id, name,Group_Name__c, dbu_Image_Src__c, ccrz__AverageRating__c,ccrz__Quantityperunit__c
            ,(select id,ccrz__Price__c from ccrz__E_PriceListItems__r)From ccrz__E_Product__c
                                 WHERE Group_Name__c='Ecom' And name LIKE : sTempSearchKey limit 10]){
                lstproduct.add(prod);
            }
            //If there are no records found with searchKey then, throw aura exception with a message
            if(lstproduct.size() == 0){
                throw new AuraHandledException('No Record Found..'); 
            }
        }catch (Exception ex){
            System.debug(ex.getMessage()+'\t'+ex.getLineNumber());
        }
        return lstproduct;
    }

}