objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__AdjustmentAmount__c</fullName>
        <description>Post order placement adjustment amount that can be used by back-end processing to adjust an order total without adjusting other fields. This information is captured here and transferred to order during place-order call.</description>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__AdjustmentReason__c</fullName>
        <description>Optional reason text for the Adjustment Amount field. This information is captured here and transferred to order during place-order call.</description>
        <label>Adjustment Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbu_Cart_StoreCountry__c</fullName>
        <label>dbu_Cart_StoreCountry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_CartCoupon__c.object
<CustomObject>
    <description>It creates many-to many relationship between E_Coupon and E_Cart</description>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Coupons</relationshipLabel>
        <relationshipName>E_CartCoupons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ccrz__Coupon__c</fullName>
        <label>Coupon</label>
        <referenceTo>ccrz__E_Coupon__c</referenceTo>
        <relationshipLabel>Cart Coupons</relationshipLabel>
        <relationshipName>E_CartCoupons</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>CC Cart Coupon</label>
    <nameField>
        <label>E_CartCoupon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Cart Coupons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__AdjustmentAmount__c</fullName>
        <description>Additional Adjustment from the CSR</description>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Cart__c</fullName>
        <description>Reference to the parent cart.</description>
        <label>Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Coupon applied to this line item.</description>
        <label>Coupon</label>
        <referenceTo>ccrz__E_Coupon__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ItemStatus__c</fullName>
        <description>Cart item status driven by inventory rules.  With inventory enabled if there is insufficient inventory then the item will be marked Pre-Order.  Otherwise it will be Available.</description>
        <label>Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Pre-Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OriginalItemPrice__c</fullName>
        <description>The original price of the item before any modifiers are applied</description>
        <label>Original Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The unit price of the line.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line item.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Cart Items (ProductID)</relationshipLabel>
        <relationshipName>E_CartItem2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of the line item.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>Sub Amount total for the line.  Typically will be Price times Quantity.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Coupon__c.object
<CustomObject>
    <description>Coupons provide special pricing Rules that can be applied to User&apos;s Carts and Orders</description>
    <fields>
        <fullName>ccrz__CouponType__c</fullName>
        <label>Coupon Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ccrz__RuleType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absolute</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__RuleType__c</fullName>
        <label>Rule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CartTotal</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Coupon</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Coupon Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>Holds the price for the item. If pricing is not being utilized, fill in a default value, such as 0.</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/dbu_CountryCurrencyMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used by CSSNA store to get the currency code for a given country.</description>
    <fields>
        <fullName>dbuCountryCode__c</fullName>
        <label>dbuCountryCode</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbuCurrencyCode__c</fullName>
        <label>dbuCurrencyCode</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>dbu Country Currency Mapping</label>
</CustomObject>

classes/dbu_EXTEND_ccLogicCouponRemove.cls
global without sharing class dbu_EXTEND_ccLogicCouponRemove extends ccrz.ccLogicCouponRemove {
    
    global virtual override Map<String, Object> remove(Map<String, Object> inputData) {
		system.debug('INPUTDATA KEYS > ' +  inputData.keySet());
        system.debug('inputData VALUES > ' + inputData.values());
        
        Map<string,object> RetMap = super.remove(inputData);
        
        system.debug('RETMAP KEYS > ' + RetMap.keySet());
        system.debug('RETMAP VALUES > ' + RetMap.values());
        
        return RetMap;
    }
    
    global virtual override Map<String, Object> performDML(Map<String, Object> inputData) {
		system.debug('INPUTDATA PERFROM DML  KEYS > ' +  inputData.keySet());
        system.debug('inputData PERFROM DML VALUES > ' + inputData.values());      
        
        //##################### Logic for Absolute carttotal discount - begins 
        //get cartid
        string currentCartidBef = (string)inputData.get('cartId');
        
        //get cartCoupon for current cartCoupon
        //list<ccrz__E_CartCoupon__c> currentCartCoupon = new list<ccrz__E_CartCoupon__c>();
        //currentCartCoupon = [select ID,ccrz__Cart__c from ccrz__E_CartCoupon__c where ccrz__Cart__c =: currentCartidBef and ccrz__Coupon__r.ccrz__CouponType__c = 'Absolute' and ccrz__Coupon__r.ccrz__RuleType__c = 'CartTotal'];
        
        /*
        if(currentCartCoupon.size() > 0){
            list<ccrz__E_Cart__c> CurrentCartToUpdate = new list<ccrz__E_Cart__c>();
            CurrentCartToUpdate = [select id, ccrz__AdjustmentAmount__c, ccrz__AdjustmentReason__c from ccrz__E_Cart__c where id =: currentCartidBef];
            if(CurrentCartToUpdate.size() > 0){
                for(ccrz__E_Cart__c eachCart : CurrentCartToUpdate){
                    eachCart.ccrz__AdjustmentAmount__c = 0;
                    eachCart.ccrz__AdjustmentReason__c = '';
                }
                
                //Update Cart - AdjustmentAmount and Reson
                try{
                    Database.SaveResult[] updatedCartIDList = Database.update(CurrentCartToUpdate, true);
                     
                    // Iterate through each returned result
                    for (Database.SaveResult sr : updatedCartIDList) {
                        if (sr.isSuccess()) {
                            // Operation was successful, so get the ID of the record that was processed
                            System.debug('Successfully updated Cart. Cart ID: ' + sr.getId());
                        }
                        else {
                            // Operation failed, so get all errors                
                            for(Database.Error err : sr.getErrors()) {
                                System.debug('The following error has occurred.');                    
                                System.debug(err.getStatusCode() + ': ' + err.getMessage());
                                System.debug('Cart fields that affected this error: ' + err.getFields());
                            }
                        }
                    }			
                }catch(Exception e){
                    system.debug('Exception while updating Cart > '  + e.getMessage());
                }		
            }
            
        }   
		*/
        //#################### Logic for Absolute carttotal discount - ends 
       
        
        Map<string,object> RetMap = super.performDML(inputData);
		
        system.debug('RETMAP PERFROM DML KEYS > ' + RetMap.keySet());
        system.debug('RETMAP PERFROM DML VALUES > ' + RetMap.values());
        
        for(String eachkey :  RetMap.keySet()){
            system.debug('KEY > ' + eachkey + ' VALUE > ' + RetMap.get(eachkey));
        }
        
        //getting current cart
        ccrz__E_Cart__c currentCart = new ccrz__E_Cart__c();
        currentCart = (ccrz__E_Cart__c)RetMap.get('ccLogicCouponRemove.fetchCartData');
        system.debug('currentCart > ' + currentCart);                
        
        string currentCartID =  currentCart.id;
        system.debug('currentCartID > ' + currentCartID);
        
        string currentCartStoreLocation = currentCart.dbu_Cart_StoreCountry__c;
        system.debug('currentCartStoreLocation > ' + currentCartStoreLocation);
                                
        //get the country cureency iso mapping from custom settings
        Map<string,string> countryCurrencyMap = new Map<string,string>();
        for(dbu_CountryCurrencyMapping__c eachsetting : (list<dbu_CountryCurrencyMapping__c>)dbu_CountryCurrencyMapping__c.getall().values()){
            system.debug('dbuCountryCode__c > ' + (string)eachsetting.get('dbuCountryCode__c'));
            system.debug('dbuCurrencyCode__c > ' + (string)eachsetting.get('dbuCurrencyCode__c'));
            countryCurrencyMap.put((string)eachsetting.get('dbuCountryCode__c'), (string)eachsetting.get('dbuCurrencyCode__c'));
        }
        system.debug('countryCurrencyMap > ' + countryCurrencyMap);   
        string CurrencyISOcodeValue = (string)countryCurrencyMap.get(currentCartStoreLocation);        
        if(Test.isRunningTest() == true){
            CurrencyISOcodeValue = 'USD';
        }
        system.debug('CurrencyISOcodeValue > ' + CurrencyISOcodeValue);
        
        list<ccrz__E_CartItem__c> currentCartCartitems = new list<ccrz__E_CartItem__c>();
		currentCartCartitems = 	(list<ccrz__E_CartItem__c>)RetMap.get('ccLogicCouponRemove.dmlCartItems');
        system.debug('currentCartCartitems > ' + currentCartCartitems);
        
        list<string> ProductIds = new List<string>();
        list<string> CartitemIds = new list<string>();
        for(ccrz__E_CartItem__c eachcartitem : currentCartCartitems){
            ProductIds.add(eachcartitem.ccrz__Product__c); 
            CartitemIds.add(eachcartitem.id);
        }
        
        list<ccrz__E_CartItem__c> cartitemdetails = new list<ccrz__E_CartItem__c>();
        cartitemdetails=   [select id, 
                            ccrz__Product__c,
                            ccrz__ItemStatus__c, 
                            ccrz__Quantity__c,
                            ccrz__OriginalItemPrice__c, 
                            ccrz__Price__c, 
                            ccrz__SubAmount__c 
                            from ccrz__E_CartItem__c 
                            where id in : CartitemIds];
        
        
        system.debug('cartitemdetails > ' + cartitemdetails);
        
        Map<string,double> pricingofproducts = new Map<string,double>();
        for(ccrz__E_PriceListItem__c eachpricelistitem : [select ccrz__Price__c,ccrz__Product__c from ccrz__E_PriceListItem__c where CurrencyIsoCode =: CurrencyISOcodeValue and ccrz__Product__c in : ProductIds]){
            pricingofproducts.put((string)eachpricelistitem.ccrz__Product__c, eachpricelistitem.ccrz__Price__c);            
        }
        system.debug('pricingofproducts > ' + pricingofproducts);
        
        
        for(ccrz__E_CartItem__c eachcartitem : cartitemdetails){
            eachcartitem.ccrz__Price__c = (double)pricingofproducts.get((string)eachcartitem.ccrz__Product__c);
            eachcartitem.ccrz__OriginalItemPrice__c = (double)pricingofproducts.get((string)eachcartitem.ccrz__Product__c);
            eachcartitem.ccrz__SubAmount__c = eachcartitem.ccrz__Price__c * eachcartitem.ccrz__Quantity__c;
            eachcartitem.ccrz__ItemStatus__c = 'Available';            
        }
        
        update cartitemdetails;
        
        
        
        return RetMap;        
    }
    
}