objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>DBU_Product_Location__c</fullName>
        <description>This field will indicate the BMS Instance which determines the location of the product</description>
        <inlineHelpText>This field will indicate the BMS Instance which determines the location of the product</inlineHelpText>
        <label>DBU Product Location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A1</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dbu_Crate_Engine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Field is used to differentiate a normal product from Crate Engine</description>
        <label>dbu Crate Engine</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_validateproductwithstore_Test.cls
@isTest
public class dbu_validateproductwithstore_Test {
	
    
    @isTest static void testmethod1(){
        Test.startTest();
        ccrz__E_Product__c TestProduct3 = dbu_FactoryDataTest.createProduct('TestProduct3', true, false, false, true);
        TestProduct3.dbu_Crate_Engine__c = false; 
        TestProduct3.DBU_Product_Location__c = 'US';
        insert TestProduct3;
        
        Map<string,object> ty = dbu_validateproductwithstore.getdata('US',TestProduct3.id);
        Test.stopTest();
           
    }
}
//CumminsLogoFix