objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
    <description>Transaction payments represent payments made to the system.</description>
    <fields>
        <fullName>OSM_Order_Update_Integration_Failure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OSM Order Update Integration Failure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__CCOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the order this payment was applied to (optional).</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Transaction Payments</relationshipLabel>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{0000000000}</displayFormat>
        <label>CC Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Transaction Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OSM_SW_RetryOrderUpdateJobs.cls
/************************************************************
Name:  OSM_SW_RetryOrderUpdateJobs
Copyright © 2018  Cummins
=============================================================
=============================================================
Purpose:                                                            
This is batch class which will take all failed order 
cancellation jobs and will send it to scheduler which 
will run every 1 hr.               
=============================================================
=============================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE              DETAIL                                
1.0 -   Ankit S            12/07/2018     INITIAL DEVELOPMENT          

*************************************************************/

global class OSM_SW_RetryOrderUpdateJobs implements Database.Batchable<sObject>,Database.AllowsCallouts{
    
    global String query{get;set;}
    Set<Id> OrderId = new Set<Id>();
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'Select id, OSM_Order_Update_Integration_Failure__c,ccrz__CCOrder__c from ccrz__E_TransactionPayment__c where OSM_Order_Update_Integration_Failure__c = true';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<ccrz__E_TransactionPayment__c> scope){               
        for(ccrz__E_TransactionPayment__c payment :scope){
            OrderId.add(payment.ccrz__CCOrder__c);
            }
        system.debug('OrderID'+OrderId);     
        OSM_SW_OrderActions.call_DA_OrderUpdatesAsync(OrderId);        
    }

    global void finish(Database.BatchableContext BC){
        OSM_SW_RetryOrderCancellationJobs bjobs = new OSM_SW_RetryOrderCancellationJobs();
        database.executebatch(bjobs,Integer.valueOf(label.OSM_OrderCancellation_Batch_Size));        
    }   
}