objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>ccrz__AddressFirstline__c</fullName>
        <description>First line of the street address.</description>
        <label>Address Firstline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressSecondline__c</fullName>
        <description>Second line of the street address.</description>
        <label>Address Secondline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressThirdline__c</fullName>
        <description>Third line of the street address.</description>
        <label>Address Thirdline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__City__c</fullName>
        <description>City for the address.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Country__c</fullName>
        <description>Descriptive country name.  Typically country ISO code is used.</description>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__FirstName__c</fullName>
        <description>Person first name associated with the address.</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__LastName__c</fullName>
        <description>Person last name associated with the address.</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__PostalCode__c</fullName>
        <description>Postal Code associated with the address.</description>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__State__c</fullName>
        <description>For non-US or non-Canadian addresses this is the name of the state for the address.</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>CC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Orders (CC Order)</relationshipLabel>
        <relationshipName>CC_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this order was placed for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BuyerEmail__c</fullName>
        <description>Email address captured during the checkout process.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ccrz__BuyerFirstName__c</fullName>
        <description>First name captured during the checkout process.</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__BuyerLastName__c</fullName>
        <description>Last name captured during the checkout process.</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__BuyerMobilePhone__c</fullName>
        <description>Deprecated</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this order was placed for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Note__c</fullName>
        <description>Note</description>
        <label>Note</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the User that this order was placed for.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dbu_Dropoff_Location__c</fullName>
        <label>dbu_Dropoff Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbu_Estimated_Return_Amount__c</fullName>
        <label>dbu_Estimated Return Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dbu_Shipto__c</fullName>
        <defaultValue>false</defaultValue>
        <label>dbu_Shipto</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dbu_StoreLocationAddress__c</fullName>
        <label>dbu_StoreLocationAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>CC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Order Items (CC Order)</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vertex_Tax__c</fullName>
        <label>Vertex Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__AbsoluteDiscount__c</fullName>
        <description>When a coupon has been applied to the order this field contains the discount amount applied with that coupon. This field is for reference only and is not used in calculations.</description>
        <label>Absolute Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__ItemTotal__c</fullName>
        <description>AdjustmentAmount__c + SubAmount__c</description>
        <formula>ccrz__AdjustmentAmount__c  +  ccrz__SubAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderItemStatus__c</fullName>
        <description>Status field at the line level. The initial value is always Order Submitted. Other values are non-functional and can be used by external systems for post-order placement status tracking.</description>
        <label>Order Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <inlineHelpText>The order that this order line is a part of.</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product_Name__c</fullName>
        <description>Product__r.Name</description>
        <formula>ccrz__Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dbu_Dropoff_Location__c</fullName>
        <label>dbu_Dropoff Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbu_Estimated_Return_Amount__c</fullName>
        <label>dbu_Estimated Return Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dbu_Is_return_mail_sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>dbu Is return mail sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dbu_Reason_for_Return__c</fullName>
        <label>dbu_Reason for Return</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbu_Shipto__c</fullName>
        <defaultValue>false</defaultValue>
        <label>dbu_Shipto</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>dbu_GenuinePart__c</fullName>
        <defaultValue>false</defaultValue>
        <label>dbu_GenuinePart</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_send_Email.cls
public class dbu_send_Email{

    @InvocableMethod(label='ForMailSend' description='yourDescription')
    public static void toSendMailForReturn(List<Id> orderIds)
    {
        dbuSendMailForReturn(orderIds);
   }
   
    public static void dbuSendMailForReturn(List<Id> lstOrderId)
    {
        EmailTemplate emailTemplate = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where name = 'dbu Return Documents'];
        List<ccrz__E_Order__c> listOrders = new List<ccrz__E_Order__c>();
        Map < String, List < ccrz__E_OrderItem__c >> mapOrderItemList = new Map < String, List < ccrz__E_OrderItem__c >> ();
        listOrders =[Select id,name,CC_Order__c,dbu_StoreLocationAddress__c,ccrz__User__c,ccrz__Note__c,dbu_Dropoff_Location__c,ccrz__ShipTo__c,ccrz__ShipTo__r.ccrz__FirstName__c,ccrz__ShipTo__r.ccrz__LastName__c,ccrz__ShipTo__r.ccrz__AddressFirstline__c,ccrz__ShipTo__r.ccrz__AddressSecondline__c,ccrz__ShipTo__r.ccrz__AddressThirdline__c,ccrz__ShipTo__r.ccrz__City__c,ccrz__ShipTo__r.ccrz__State__c,ccrz__ShipTo__r.ccrz__Country__c,ccrz__ShipTo__r.ccrz__PostalCode__c, ccrz__Contact__c,ccrz__BuyerFirstName__c,ccrz__BuyerLastName__c,ccrz__BuyerEmail__c,ccrz__BuyerMobilePhone__c,
        (Select id,Name,ccrz__Product__c,dbu_Estimated_Return_Amount__c,ccrz__Price__c,ccrz__AbsoluteDiscount__c,ccrz__Product_Name__c,ccrz__Product__r.dbu_GenuinePart__c,ccrz__Quantity__c,Vertex_Tax__c,dbu_Dropoff_Location__c,
        ccrz__Order__r.ccrz__Account__c, ccrz__OrderItemStatus__c,dbu_Reason_for_Return__c,ccrz__ItemTotal__c,dbu_Is_return_mail_sent__c,dbu_Shipto__c from ccrz__E_OrderItems__r where ccrz__OrderItemStatus__c = 'Return Initiated' and dbu_Is_return_mail_sent__c = false) from ccrz__E_Order__c where id IN: lstOrderId And CC_Order__c != Null];
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        
        String shippingIns = '<h3>Return Shipping Instructions:</h3><strong>Here is what you need to do next:</strong> ' + 
    '<ul><li> Pack the item(s) you are returning. </li><li> Print and include the return document inside your return package.</li><li> Ship back to the appropriate location.</li><li> Use a carrier/shipper that provides package tracking capability. This is vital for resolving any dispute related to the return to Cummins; it also provides a record of the return date. </li><li>  Be sure to cover any prior shipping labels on the package. </li></ul>'+ 
    '<h6>Reminders:</h6> '+
    '<ul><li>Eligible parts can be returned for up to 30 days from the date of purchase. Products purchased on shop.cummins,com must be returned in saleable condition — in other words, unused, in the original packaging, and undamaged. Please note, all accepted returns will incur a 15% handling fee. </li><li>If Cummins shipped the wrong product or the product is damaged, we will cover the cost of shipping and send you a return label. For all other types of returns, you will be responsible for shipping the return package to the appropriate Cummins location. </li><li>We will let you know when your return is received and a decision on approval or rejection has been made.</li><li>Once we have approved the return, a refund will be issued within 7-10 business days. </li></ul>';
        
        String dropOffIns = '<h3>Return Drop Off Instructions:</h3><strong>Here is what you need to do next:</strong> ' + 
        '<ul><li> Pack the item(s) you are returning. </li><li> Print and include the return document inside your return package.</li><li> Ship back to the appropriate location.</li><li> Use a carrier/shipper that provides package tracking capability. This is vital for resolving any dispute related to the return to Cummins; it also provides a record of the return date. </li><li>  Be sure to cover any prior shipping labels on the package. </li></ul>'+ 
        '<h6>Reminders:</h6> '+
        '<ul><li>Eligible parts can be returned for up to 30 days from the date of purchase. Products purchased on shop.cummins,com must be returned in saleable condition — in other words, unused, in the original packaging, and undamaged. Please note, all accepted returns will incur a 15% handling fee. </li><li>If Cummins shipped the wrong product or the product is damaged, we will cover the cost of shipping and send you a return label. For all other types of returns, you will be responsible for shipping the return package to the appropriate Cummins location. </li><li>We will let you know when your return is received and a decision on approval or rejection has been made.</li><li>Once we have approved the return, a refund will be issued within 7-10 business days. </li></ul>';

        for(ccrz__E_Order__c ord : listOrders)
        {   
            if(ord.ccrz__E_OrderItems__r.size() == 0)
                continue;
            String body;
                        
            String lineItemHTML = '';
            boolean flag;
            String droppLocation;
            for(ccrz__E_OrderItem__c oItem: ord.ccrz__E_OrderItems__r)
            {
               system.debug('oItem---->>>'+oItem);
               if(oItem.dbu_Dropoff_Location__c != Null){
                    droppLocation=oItem.dbu_Dropoff_Location__c;
               }
                if(oItem.dbu_Shipto__c == false){
                    flag = true;
                    
                if(ord.ccrz__ShipTo__r.ccrz__Country__c == 'US'){    
                    if(oItem.dbu_Reason_for_Return__c != null){
                        lineItemHTML = lineItemHTML + '<tr><td class="tg-0lax">'+ oItem.ccrz__Product_Name__c+'</td><td class="tg-0lax">'+ oItem.ccrz__Quantity__c+'</td> <td class="tg-0lax">'+oItem.dbu_Reason_for_Return__c+'</td><td class="tg-0lax">Drop Off</td><td class="tg-0lax">'+'$'+(oItem.dbu_Estimated_Return_Amount__c).setScale(2)+'</td></tr>';
                    }
                    else{
                        lineItemHTML = lineItemHTML + '<tr><td class="tg-0lax">'+ oItem.ccrz__Product_Name__c+'</td><td class="tg-0lax">'+ oItem.ccrz__Quantity__c+'</td> <td class="tg-0lax">Core Refund</td><td class="tg-0lax">Drop Off</td><td class="tg-0lax">'+'$'+(oItem.dbu_Estimated_Return_Amount__c).setScale(2)+'</td></tr>';
                        }
                  }else if(ord.ccrz__ShipTo__r.ccrz__Country__c == 'CA' && (oItem.dbu_Reason_for_Return__c == 'Part no longer wanted' || oItem.dbu_Reason_for_Return__c == 'Ordered the wrong part')){
                        lineItemHTML = lineItemHTML + '<tr><td class="tg-0lax">'+ oItem.ccrz__Product_Name__c+'</td><td class="tg-0lax">'+ oItem.ccrz__Quantity__c+'</td> <td class="tg-0lax">'+oItem.dbu_Reason_for_Return__c+'</td><td class="tg-0lax">Ship To</td><td class="tg-0lax">'+'$'+(oItem.dbu_Estimated_Return_Amount__c).setScale(2)+'</td></tr>';
                    }
                  
                }else{
                    flag = false;
                    
                    if(ord.ccrz__ShipTo__r.ccrz__Country__c == 'US'){
                        if(oItem.dbu_Reason_for_Return__c != Null){
                            lineItemHTML = lineItemHTML + '<tr><td class="tg-0lax">'+ oItem.ccrz__Product_Name__c+'</td><td class="tg-0lax">'+ oItem.ccrz__Quantity__c+'</td> <td class="tg-0lax">'+oItem.dbu_Reason_for_Return__c+'</td><td class="tg-0lax">Ship To</td><td class="tg-0lax">'+'$'+(oItem.dbu_Estimated_Return_Amount__c).setScale(2)+'</td></tr>';
                        }
                        else{
                            lineItemHTML = lineItemHTML + '<tr><td class="tg-0lax">'+ oItem.ccrz__Product_Name__c+'</td><td class="tg-0lax">'+ oItem.ccrz__Quantity__c+'</td> <td class="tg-0lax">Core Refund</td><td class="tg-0lax">Ship To</td><td class="tg-0lax">'+'$'+(oItem.dbu_Estimated_Return_Amount__c).setScale(2)+'</td></tr>';
                        }
                        
                    }else if(ord.ccrz__ShipTo__r.ccrz__Country__c == 'CA' && (oItem.dbu_Reason_for_Return__c == 'Part no longer wanted' || oItem.dbu_Reason_for_Return__c == 'Ordered the wrong part')){
                        lineItemHTML = lineItemHTML + '<tr><td class="tg-0lax">'+ oItem.ccrz__Product_Name__c+'</td><td class="tg-0lax">'+ oItem.ccrz__Quantity__c+'</td> <td class="tg-0lax">'+oItem.dbu_Reason_for_Return__c+'</td><td class="tg-0lax">Ship To</td><td class="tg-0lax">'+'$'+(oItem.dbu_Estimated_Return_Amount__c).setScale(2)+'</td></tr>';
                    }
                }
            }
            if(flag){
                body = '<html><body><h1 style=\"text-align:center;\">Return Order information</h1><br/><br/><p>'+ 'Return Confirmation Code :' + ord.Name +'</p><p><div><div style=\"width: 10%;float: left;\">Drop off location : </div><div style=\"width: 90%;float: left;\">'+droppLocation+'';
                 body = body+ '</div></div></p><br/><br/><p>Return order items:</p><br/><table border="1"  ><thead><tr><th style="width: 40.0743%; background-color: rgb(239, 239, 239); text-align: left;">Product</th><th style="width: 10.0743%; background-color: rgb(239, 239, 239); text-align: left;">Quantity<br></th><th style="background-color: rgb(239, 239, 239); text-align: left;">Reason for Return</th><th style="background-color: rgb(239, 239, 239); text-align: left;">Return method</th><th style="background-color: rgb(239, 239, 239); text-align: left;">Estimated refund amount</th></tr></thead><tbody>';
                 body = body + lineItemHTML + '</tbody></table>';
                body = body + dropOffIns + '</body></html>';
                
            }else{
                body = '<html><body><h1 style=\"text-align:center;\">Return Order information</h1><br/><br/><p>'+ 'Return Confirmation Code :' + ord.Name +'</p><p><div style=\"width: 10%;float: left;\">Ship to location : </div><div>'+ord.dbu_StoreLocationAddress__c+'';
                body = body + '</div></div></p><br/><br/><p>Return order items:</p><br/><table border="1"  ><thead><tr><th style="width: 40.0743%; background-color: rgb(239, 239, 239); text-align: left;">Product</th><th style="width: 10.0743%; background-color: rgb(239, 239, 239); text-align: left;">Quantity<br></th><th style="background-color: rgb(239, 239, 239); text-align: left;">Reason for Return</th><th style="background-color: rgb(239, 239, 239); text-align: left;">Return method</th><th style="background-color: rgb(239, 239, 239); text-align: left;">Estimated refund amount</th></tr></thead><tbody>';
                body = body + lineItemHTML +'</tbody></table>';
                body = body + shippingIns + '</body></html>';
            }
            
            System.debug('HTML is ' + body);

            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
            attach.setContentType('application/pdf');
            attach.setFileName('Return Order information.pdf');
            System.debug('HTML is ' + body);
            System.debug('UserInfo.getUserType()---->>' + UserInfo.getUserType());
            attach.Body = Blob.toPDF(body);
            String[] toaddress = new String[]{}; 
            toaddress.add(ord.ccrz__BuyerEmail__c);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            if(UserInfo.getUserType() == 'Guest'){
            mail.setToAddresses(toaddress);
            mail.setTargetObjectId(ord.ccrz__User__c);
            }else{
            mail.setTargetObjectId(ord.ccrz__Contact__c); 
            }
            mail.setSenderDisplayName('Company Support'); 
            mail.setReplyTo('no-reply@company.com');
            mail.setUseSignature(false);
            mail.setBccSender(false);
            mail.setSaveAsActivity(false);
            mail.setTemplateID(emailTemplate.Id);
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach });     

            mails.add(mail);
        }
        system.debug('mails---->>'+mails);                       
        if(!mails.isEmpty())
        {
            Messaging.SendEmail(mails);
        }
        List<ccrz__E_OrderItem__c> toUpdateOI = new List<ccrz__E_OrderItem__c>();
        for(ccrz__E_Order__c ord : listOrders)
        {   
            for(ccrz__E_OrderItem__c oItem: ord.ccrz__E_OrderItems__r)
            {
                oItem.dbu_Is_return_mail_sent__c = true;
                toUpdateOI.add(oItem);
            }
        }
        if(toUpdateOI.size() > 0)
            update toUpdateOI;
    }
}