objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>ByPassFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ToByPassFlow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>OMS_Item_ID__c</fullName>
        <label>OMS Item ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tool_Instance_Key__c</fullName>
        <label>Tool Instance Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <inlineHelpText>The order that this order line is a part of.</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__SubAmount__c</fullName>
        <description>The sub-total amount for the order. This will be calculated as price * quantity - coupon adjustments during order placement.</description>
        <label>Sub Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OSM_Order_Item_License__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Key__c</fullName>
        <label>Activation Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Order_Item__c</fullName>
        <label>CC Order Item</label>
        <referenceTo>ccrz__E_OrderItem__c</referenceTo>
        <relationshipName>OSM_Oreder_Item_Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OMS_Item_Id__c</fullName>
        <label>OMS Item Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Activation_Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OSM Order Item License</label>
        <referenceTo>OSM_Order_Item_License__c</referenceTo>
        <relationshipLabel>OSM Order Item Licenses (OSM Order Item License)</relationshipLabel>
        <relationshipName>OSM_Order_Item_Licenses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revoked_ReIssue_Lisence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revoked &amp; ReIssue Lisence</label>
        <referenceTo>OSM_Order_Item_License__c</referenceTo>
        <relationshipLabel>OSM Order Item Licenses</relationshipLabel>
        <relationshipName>OSM_Order_Item_Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Revoked/ReIssue</fullName>
                </value>
                <value>
                    <fullName>ReIssued</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Revoke/ReIssue Pending</fullName>
                </value>
                <value>
                    <fullName>Create And Get Done</fullName>
                </value>
                <value>
                    <fullName>Create And Get Failed</fullName>
                </value>
                <value>
                    <fullName>Revoke Initiated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tool_Instance_Key__c</fullName>
        <label>Tool Instance Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Functional</fullName>
                </value>
                <value>
                    <fullName>Tool instance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OSM Order Item License</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>OSM License Activation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Order Item Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OSM_SW_RevokeInstanceBatch_Test.cls
//Test class of OSM_SW_CreateGetOrder_ON_ReIssueBatch
// Test class of OSM_OMS_GetTI_ON_Revoked_Batch
// Test class
@isTest
public class OSM_SW_RevokeInstanceBatch_Test {
    
    @testSetup static void testData() {
        
        ccrz__E_Order__c order = new ccrz__E_Order__c(ByPassFlow__c = true);
        insert order;
        
        
        
        ccrz__E_OrderItem__c orderItem = new ccrz__E_OrderItem__c();
        orderItem.ccrz__Order__c       = order.id;
        orderItem.ccrz__Price__c       = 500;
        orderItem.ccrz__Quantity__c    = 55;
        orderItem.ccrz__SubAmount__c   = 250;
        insert orderItem;
        
        OSM_Order_Item_License__c ParentActivationKey = new OSM_Order_Item_License__c();
        ParentActivationKey.Activation_Key__c         = 'testActivationKey';
        ParentActivationKey.CC_Order_Item__c          = orderItem.id;
        ParentActivationKey.Parent_Activation_Key__c  = null;
        ParentActivationKey.OMS_Item_Id__c            = '1234';
        ParentActivationKey.Tool_Instance_Key__c      = '12345';
        ParentActivationKey.Status__c                 = 'Revoke Intitiated';
        ParentActivationKey.type__c                   = 'Tool instance';
        insert ParentActivationKey;
        
        OSM_Order_Item_License__c orderItemLicense = new OSM_Order_Item_License__c();
        orderItemLicense.Activation_Key__c         = 'testActivationKey';
        orderItemLicense.CC_Order_Item__c          = orderItem.id;
        orderItemLicense.Parent_Activation_Key__c  = ParentActivationKey.id;
        orderItemLicense.OMS_Item_Id__c            = '1234';
        orderItemLicense.Tool_Instance_Key__c      = '12345';
        orderItemLicense.Status__c                 = 'Revoke Intitiated';
        orderItemLicense.type__c                   = 'Tool instance';
        insert orderItemLicense;
        
        OSM_Order_Item_License__c orderItemLicense2 = new OSM_Order_Item_License__c();
        orderItemLicense2.Activation_Key__c         = 'testActivationKey';
        orderItemLicense2.CC_Order_Item__c          = orderItem.id;
        orderItemLicense2.Parent_Activation_Key__c  = ParentActivationKey.id;
        orderItemLicense2.OMS_Item_Id__c            = '1234';
        orderItemLicense2.Tool_Instance_Key__c      = '12345';
        orderItemLicense2.Status__c                 = 'Revoked/ReIssue';
        orderItemLicense2.type__c                   = 'Tool instance';
        insert orderItemLicense2;
        
        OSM_Order_Item_License__c orderItemLicense3  = new OSM_Order_Item_License__c();
        orderItemLicense3.Activation_Key__c          = 'testActivationKey';
        orderItemLicense3.CC_Order_Item__c           = orderItem.id;
        orderItemLicense3.Parent_Activation_Key__c   = orderItemLicense2.id;
        orderItemLicense3.Revoked_ReIssue_Lisence__c = orderItemLicense.id;
        orderItemLicense3.OMS_Item_Id__c             = '1234';
        orderItemLicense3.Tool_Instance_Key__c       = '12345';
        orderItemLicense3.Status__c                  = 'Create And Get Done';
        insert orderItemLicense3;
        
        
    } 
    
    @isTest static void testMethod1() {
        test.startTest();
        dataBase.executeBatch(new OSM_SW_RevokeInstanceBatch());
        dataBase.executeBatch(new OSM_SW_CreateGetOrder_ON_ReIssueBatch());
        dataBase.executeBatch(new OSM_OMS_GetTI_ON_Revoked_Batch());
        test.stopTest();
    }  
}