objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <label>Sequence</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                </value>
                <value>
                    <fullName>SoftwareStore</fullName>
                    <default>true</default>
                    <label>SoftwareStore</label>
                </value>
                <value>
                    <fullName>CSSNAStore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Subscription__c.object
<CustomObject>
    <description>This is a subscription, the record of purchased subscription</description>
    <fields>
        <fullName>OSM_Display_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OSM Display Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Subscriptions (OSM Display Product)</relationshipLabel>
        <relationshipName>CC_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OSM_Subscription_End_Date__c</fullName>
        <label>Subscription End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items shipped for this subscriptions</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <description>Used for modifiers to determine order in which they are processed.</description>
        <label>Sequence</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront to which this subscription belongs.</description>
        <label>Storefront</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionStartDate__c</fullName>
        <description>The start date of the subscription</description>
        <label>Subscription Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ccrz__SubscriptionStatus__c</fullName>
        <description>The status of the subscription</description>
        <label>Subscription Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CC Subscription</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>CC Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OSM_SW_SubscriptionExperssionBatch_Test.cls
@isTest 
public class OSM_SW_SubscriptionExperssionBatch_Test 
{
    static testMethod void OSM_SW_SubscriptionExperssion() 
    {
        List<ccrz__E_Subscription__c > lstSub= new List<ccrz__E_Subscription__c >();
        for (Integer i=0;i<200;i++) {
         ccrz__E_Subscription__c sub = new ccrz__E_Subscription__c();
      //  sub.OSM_Display_Product__c = prod.id;
        sub.ccrz__Quantity__c = 10;
        sub.ccrz__Sequence__c = 2;
        sub.ccrz__SubscriptionStatus__c = 'Requested';
        sub.ccrz__Storefront__c = 'SoftwareStore';
        sub.ccrz__SubscriptionStartDate__c  = system.today();
        sub.OSM_Subscription_End_Date__c=Date.newInstance(2020,03,6);
        sub.ccrz__SubscriptionStatus__c = 'Active';
        //sub.OSM_Display_Product__r.ccrz__ShortDesc__c = 'test description';
        lstSub.add(sub);
        }
        insert lstSub;
        //lstSub.ccrz__SubscriptionStatus__c = 'Expired';
        
        update lstSub;
        
        Test.startTest();

            OSM_SW_SubscriptionExperssionBatch obj = new OSM_SW_SubscriptionExperssionBatch();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
        
        ccrz__E_Subscription__c [] accUpdatedList = [SELECT Id,ccrz__SubscriptionStatus__c,Name FROM ccrz__E_Subscription__c];
        //System.assert(accUpdatedList[0].ccrz__SubscriptionStatus__c .Contains('Expired'));
    }
}