objects/ccrz__E_AccountAddressBook__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ccrz__E_ContactAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Contact Address</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Address Books</relationshipLabel>
        <relationshipName>E_Account_Address_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Account Address Book</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Account Address Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>Bolt_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Checked, its an active address else address is inactive</description>
        <label>Bolt Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bolt_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bolt Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressFirstline__c</fullName>
        <description>First line of the street address.</description>
        <label>Address Firstline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__City__c</fullName>
        <description>City for the address.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_BoltAddressDeletionTrigger_Test.cls
@isTest
public class OSM_BoltAddressDeletionTrigger_Test 
{
    static testMethod void testMethod1()
    {
        try
        {
            ccrz__E_ContactAddr__c contactAddress = new ccrz__E_ContactAddr__c();
            contactAddress.ccrz__AddressFirstline__c = 'Test Address Line 1';
            contactAddress.ccrz__City__c = 'Columbus';
            contactAddress.Bolt_Site__c = true;
            
            insert contactAddress;
            
            ccrz__E_AccountAddressBook__c addressBook = new ccrz__E_AccountAddressBook__c();
            addressBook.Name = 'TestName'; 
            addressBook.ccrz__E_ContactAddress__c = contactAddress.ID;
            
            insert addressBook;
            
            // now to call the delete
            delete addressBook;
            
            // now to call the delete
            delete contactAddress;
            
        }
        catch(Exception e)
        {
            System.debug('Exception thrown properly');
        }
        
    }
    
    static testMethod void testMethod2()
    {
        try
        {
            ccrz__E_ContactAddr__c contactAddress = new ccrz__E_ContactAddr__c();
            contactAddress.ccrz__AddressFirstline__c = '1460 N National Rd';
            contactAddress.ccrz__City__c = 'Columbus';
            contactAddress.Bolt_Site__c = true;
            
            insert contactAddress;
            
            // contactAddress.Bolt_Active__c = true;
            //update contactAddress;
            delete contactAddress;
        }
        catch(Exception e)
        {
            System.debug('Exception thrown properly');
        }
        
    }
    
}