objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__ShipMethod__c</fullName>
        <description>Shipment method captured during the checkout process.This information is captured here and transferred to order during place-order call.</description>
        <label>Ship Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbu_Pick_Up_From_Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>dbu Pick Up From Store</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>CC Carts (dbu Pick Up From Store)</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>ccrz__AddressFirstline__c</fullName>
        <description>First line of the street address.</description>
        <label>Address Firstline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__City__c</fullName>
        <description>City for the address.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Country__c</fullName>
        <description>Descriptive country name.  Typically country ISO code is used.</description>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__HomePhone__c</fullName>
        <description>Secondary phone associated with the address.</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ccrz__PostalCode__c</fullName>
        <description>Postal Code associated with the address.</description>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShippingComments__c</fullName>
        <description>If the user enters any shipping comments during checkout those comments will be in this field on the shipping address associated with the order.</description>
        <label>Shipping Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__State__c</fullName>
        <description>For non-US or non-Canadian addresses this is the name of the state for the address.</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dbu_PickUp_Store_Name__c</fullName>
        <label>dbu PickUp Store Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_ReviewOrder.cls
public without sharing class dbu_ReviewOrder {
    
    @AuraEnabled(cacheable=true)
    public static  list<dbu_ReviewOrderAddressWrapper> fetchOrderDetails(String cartId){
        system.debug('cartId>>' +cartId);
        Set<String> cartIdList = new Set<String>{cartId};  
            list<dbu_ReviewOrderShippingAddWrapper> AddressList = new list<dbu_ReviewOrderShippingAddWrapper>();
        List<dbu_ReviewOrderBillingAddWrapper> billingAddressList = new List<dbu_ReviewOrderBillingAddWrapper>();
        dbu_ReviewOrderAddressWrapper addressWrapper = new dbu_ReviewOrderAddressWrapper();
        List<dbu_ReviewOrderAddressWrapper> shippingBillingAddWrapperList = new List<dbu_ReviewOrderAddressWrapper>();


        Map<String, Object> cartFetchQuery = new Map<String, Object>{
            ccrz.ccApiCart.CART_IDLIST => cartIdList,
                ccrz.ccApi.API_VERSION => ccrz.ccApi.CURRENT_VERSION,
                
                /*API SIZING set to XL which returns All possible fields*/
                ccrz.ccApi.SIZING => new Map<String, Object> {
                    ccrz.ccApiCart.ENTITYNAME => new Map<String, Object> {
                        ccrz.ccApi.SZ_DATA => ccrz.ccApi.SZ_XL
                            },
                                ccrz.ccApiAddress.ENTITYNAME => new Map<String, Object> {
                                    ccrz.ccApi.SZ_DATA => ccrz.ccApi.SZ_XL
                                        }
                }
        };
            
            //############################### FIRE FETCH METHOD OF CC CART API #########################################    
            try {
                Map<String, Object> cartFetchData = ccrz.ccApiCart.fetch(cartFetchQuery); 
                system.debug('cartFetchData'+cartFetchData);
                
                //################## Fetch CC Contact Address Details BillTo & ShipTo #########################
                if(cartFetchData.get(ccrz.ccApiAddress.ADDRESSLIST) != null){
                    List<Map<String, Object>> outputAddressList = (List<Map<String, object>>) cartFetchData.get(ccrz.ccApiAddress.ADDRESSLIST);
                    
                    
                    System.debug('AddressDetails::::: ' +json.serialize(outputAddressList) );
                    if(outputAddressList !=null && outputAddressList.size()>0)
                    {
                        system.debug('inside if');
                        for(Map<String,Object> ob:outputAddressList)
                        {
                            system.debug('inside for'+(string)ob.get('shippingComments'));
                            if((string)ob.get('shippingComments') == 'Shipping Comments' || (string)ob.get('shippingComments') == 'Expédition Comments'){
                                dbu_ReviewOrderShippingAddWrapper wrap = new dbu_ReviewOrderShippingAddWrapper();
                                wrap.firstName= (String)ob.get('firstName');
                                wrap.lastName=(string)ob.get('lastName');
                                wrap.addressFirstline=(string)ob.get('addressFirstline');
                                wrap.addressSecondline=(string)ob.get('addressSecondline');
                                wrap.shippingComments = (string)ob.get('shippingComments');
                                wrap.postalCode = (string)ob.get('postalCode');
                                wrap.city = (string)ob.get('city');
                                wrap.state = (string)ob.get('state');
                                if((string)ob.get('country') == 'US'){
                                    wrap.country = 'U.S.A';
                                }else if((string)ob.get('country') == 'CA'){
                                    wrap.country = 'Canada';
                                }
                                //wrap.country = (string)ob.get('country');
                                AddressList.add(wrap);
                                system.debug('AddressList>>' +AddressList);
                            }
                            if((string)ob.get('shippingComments') == 'Billing Comments' || (string)ob.get('shippingComments') == 'Facturation Comments'){
                                dbu_ReviewOrderBillingAddWrapper wrap = new dbu_ReviewOrderBillingAddWrapper();
                                wrap.firstName= (String)ob.get('firstName');
                                wrap.lastName=(string)ob.get('lastName');
                                wrap.addressFirstline=(string)ob.get('addressFirstline');
                                wrap.addressSecondline=(string)ob.get('addressSecondline');
                                wrap.shippingComments = (string)ob.get('shippingComments');
                                wrap.postalCode = (string)ob.get('postalCode');
                                wrap.city = (string)ob.get('city');
                                wrap.state = (string)ob.get('state');
                                if((string)ob.get('country') == 'US'){
                                    wrap.country = 'U.S.A';
                                }else if((string)ob.get('country') == 'CA'){
                                    wrap.country = 'Canada';
                                }
                                //wrap.country = (string)ob.get('country');
                                billingAddressList.add(wrap);
                                 system.debug('Billing>>' +billingAddressList);
                            }
                              
                        }
                        if(AddressList != null){
                            addressWrapper.AddressList = AddressList ;
                        }
                        if(billingAddressList != null){
                            addressWrapper.billingAddressList =billingAddressList ;
                        }
                        shippingBillingAddWrapperList.add(addressWrapper);
                        system.debug('shippingBillingAddWrapperList' +shippingBillingAddWrapperList);
                    }
                }
                
                
                //################## Fetch Cart Details #########################
                if (cartFetchData.get(ccrz.ccApiCart.CART_OBJLIST) != null) {        
                    List<Map<String, Object>> outputCartList = (List<Map<String, Object>>) cartFetchData.get(ccrz.ccApiCart.CART_OBJLIST);
                    System.debug(JSON.serializePretty('CartDetails::::: ' + outputCartList));        
                }
            } catch (Exception e) {
                // Error handling...
                system.debug('Exception Line Number'+e.getLineNumber()+''+'Exception Message'+e.getMessage());
            }
        
        return shippingBillingAddWrapperList;
    }
    public class dbu_ReviewOrderShippingAddWrapper {
        @AuraEnabled public String lastName;
        @AuraEnabled public String firstName;
        @AuraEnabled public String addressSecondline;
        @AuraEnabled public String addressFirstline;
        @AuraEnabled public String shippingComments;
        @AuraEnabled public String city;
        @AuraEnabled public String postalCode;
        @AuraEnabled public String state;
        @AuraEnabled public String country;
    }
    public class dbu_ReviewOrderBillingAddWrapper {
        @AuraEnabled public String lastName;
        @AuraEnabled public String firstName;
        @AuraEnabled public String addressSecondline;
        @AuraEnabled public String addressFirstline;
        @AuraEnabled public String shippingComments;
        @AuraEnabled public String city;
        @AuraEnabled public String postalCode;
        @AuraEnabled public String state;
        @AuraEnabled public String country;
    }
    
    public class dbu_ReviewOrderAddressWrapper {
       @AuraEnabled public list<dbu_ReviewOrderShippingAddWrapper> AddressList;
       @AuraEnabled public List<dbu_ReviewOrderBillingAddWrapper> billingAddressList;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<ccrz__E_Cart__c> fetchPickUpData(String cartId){
        system.debug('cartId>>' +cartId);
        List<ccrz__E_Cart__c> cartList = new List<ccrz__E_Cart__c>();
        cartList = [Select id,ccrz__ShipMethod__c,dbu_Pick_Up_From_Store__c,dbu_Pick_Up_From_Store__r.ccrz__AddressFirstline__c,
                    dbu_Pick_Up_From_Store__r.ccrz__City__c,
                    dbu_Pick_Up_From_Store__r.ccrz__State__c,
                    dbu_Pick_Up_From_Store__r.ccrz__Country__c,
                    dbu_Pick_Up_From_Store__r.ccrz__HomePhone__c,
                    dbu_Pick_Up_From_Store__r.ccrz__PostalCode__c,
                    dbu_Pick_Up_From_Store__r.dbu_PickUp_Store_Name__c,
                    dbu_Pick_Up_From_Store__r.ccrz__ShippingComments__c
                   FROM ccrz__E_Cart__c 
                   WHERE id =:cartId];
        system.debug('cartList>>' +cartList);
        return cartList;
                                                            
    }
    
    
}