objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>Is_OMS_Revoke_and_Cancel_Not_Done_Count__c</fullName>
        <label>Is OMS Revoke and Cancel Not Done Count</label>
        <summaryFilterItems>
            <field>ccrz__E_OrderItem__c.OSM_SW_Is_OMS_Revoke_and_Cancel_Not_Done__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ccrz__E_OrderItem__c.ccrz__Order__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OSM_SW_Is_FSD_Done_Or_Not_Needed__c</fullName>
        <formula>OR( NOT(OrderProcessedforFSD__c), AND( OrderProcessedforFSD__c ,  OSM_SW_Is_FSD_refund_Call_Done__c ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is FSD Done Or Not Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderProcessedforFSD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Processed for FSD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partially Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partial Cancellation Requested</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Order Delayed</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Return Received and Approved</fullName>
                </value>
                <value>
                    <fullName>Return Request</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Approved</fullName>
                </value>
                <value>
                    <fullName>Return Complete</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Picked up</fullName>
                </value>
                <value>
                    <fullName>Return Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Basic_Tool_Instance_Key_Count__c</fullName>
        <label>Basic Tool Instance Key Count</label>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Status__c</field>
            <operation>equals</operation>
            <value>New</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Tool_Instance_Key__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Type__c</field>
            <operation>equals</operation>
            <value>Basic</value>
        </summaryFilterItems>
        <summaryForeignKey>OSM_Order_Item_License__c.CC_Order_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Instance_ID_Count__c</fullName>
        <label>Instance ID Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsCancelPending__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCancelPending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRevokeLicenseSucess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRevokeLicenseSucess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OSM_SW_Is_OMS_Revoke_and_Cancel_Not_Done__c</fullName>
        <formula>IF( OMS_Product__c,

IF(

OSM_GetTI_Success__c &amp;&amp; (


(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; CancelLicenseAPICalled__c &amp;&amp; OSM_SW_Revoked_Basic_Key_Count__c ==0 &amp;&amp; OSM_SW_Revoked_Functional_Key_Count__c == 0)
||
(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; IsRevokeLicenseSucess__c &amp;&amp; OSM_SW_Revoked_Basic_Key_Count__c == MCEILING(ccrz__OriginalQuantity__c) &amp;&amp; !OSM_SW_Non_Insite_OSM_Product__c &amp;&amp; OSM_SW_Revoked_Functional_Key_Count__c == MCEILING(ccrz__OriginalQuantity__c ))
||
(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; IsRevokeLicenseSucess__c &amp;&amp; (OSM_SW_Revoked_Basic_Key_Count__c == MCEILING(ccrz__OriginalQuantity__c) || OSM_SW_Non_Insite_OSM_Product__c) &amp;&amp; OSM_SW_Revoked_Functional_Key_Count__c == MCEILING(Number_of_Bundles__c ))
||
(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; IsRevokeLicenseSucess__c &amp;&amp; CancelLicenseAPICalled__c &amp;&amp; (OSM_SW_Revoked_Basic_Key_Count__c != MCEILING(ccrz__OriginalQuantity__c) || OSM_SW_Non_Insite_OSM_Product__c) &amp;&amp; OSM_SW_Revoked_Functional_Key_Count__c != MCEILING(Number_of_Bundles__c ))
||
(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; IsRevokeLicenseSucess__c &amp;&amp; CancelLicenseAPICalled__c)
),

false, true)





,false)




/*
IF( OMS_Product__c &amp;&amp; !isRenew__c,

IF(

OSM_GetTI_Success__c &amp;&amp; (


(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; CancelLicenseAPICalled__c &amp;&amp; OSM_SW_Revoked_Basic_Key_Count__c ==0 &amp;&amp; OSM_SW_Revoked_Functional_Key_Count__c == 0)
||
(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; IsRevokeLicenseSucess__c &amp;&amp; (OSM_SW_Revoked_Basic_Key_Count__c == MCEILING(ccrz__OriginalQuantity__c) || OSM_SW_Non_Insite_OSM_Product__c) &amp;&amp; OSM_SW_Revoked_Functional_Key_Count__c == MCEILING(ccrz__OriginalQuantity__c))
||
(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; IsRevokeLicenseSucess__c &amp;&amp; CancelLicenseAPICalled__c &amp;&amp; (OSM_SW_Revoked_Basic_Key_Count__c != MCEILING(ccrz__OriginalQuantity__c) || OSM_SW_Non_Insite_OSM_Product__c) &amp;&amp; OSM_SW_Revoked_Functional_Key_Count__c != MCEILING(ccrz__OriginalQuantity__c))
||
(Tool_Instance_Count__c == 0 &amp;&amp; Basic_Tool_Instance_Key_Count__c==0 &amp;&amp; IsRevokeLicenseSucess__c &amp;&amp; CancelLicenseAPICalled__c)
),

false, true)



,false)
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is OMS Revoke and Cancel Not Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OSM_SW_Is_Refund_FSD_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Refund FSD Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tool_Instance_Count__c</fullName>
        <label>Functional Tool Instance Count</label>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Status__c</field>
            <operation>equals</operation>
            <value>New</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Tool_Instance_Key__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Type__c</field>
            <operation>equals</operation>
            <value>Functional</value>
        </summaryFilterItems>
        <summaryForeignKey>OSM_Order_Item_License__c.CC_Order_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderItemStatus__c</fullName>
        <description>Status field at the line level. The initial value is always Order Submitted. Other values are non-functional and can be used by external systems for post-order placement status tracking.</description>
        <label>Order Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <inlineHelpText>The order that this order line is a part of.</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_TransactionPayment__c.object
<CustomObject>
    <description>Transaction payments represent payments made to the system.</description>
    <fields>
        <fullName>ccrz__AccountType__c</fullName>
        <description>The account type of the payment, e.g. PO, Credit Card, etc.</description>
        <label>Account Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__CCOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>References the order this payment was applied to (optional).</description>
        <label>CC Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>CC Transaction Payments</relationshipLabel>
        <relationshipName>TransactionPayments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Transaction Payment</label>
    <nameField>
        <displayFormat>TP-{0000000000}</displayFormat>
        <label>CC Transaction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Transaction Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OSM_Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Batch_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Batch Log</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OSM Integration Log</label>
    <nameField>
        <displayFormat>OSM- {0000000000}</displayFormat>
        <label>OSM Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_OMS_SW_RevokeAPIFailurebatch.cls
/************************************************************
Name:  OSM_OMS_SW_RevokeAPIFailurebatch
Copyright © 2018  Cummins
=============================================================
=============================================================
Purpose:                                                            
This batch class will be used to initiate the RevokedAPIFailure records and pass to same API
============================================================
=============================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE              DETAIL                                
1.0 -   Neha Sharma        22nd Feb 2019     INITIAL DEVELOPMENT          
2.0 -   Ashish Goyal       15th Sep 2020     Updated for FW release

*************************************************************/
global class OSM_OMS_SW_RevokeAPIFailurebatch implements Database.Batchable<sObject>,Database.AllowsCallouts{
    global Set<Id> set_OrderItemId = new Set<Id>();
    
    global OSM_OMS_SW_RevokeAPIFailurebatch(){
        // do nothing
    }
    
    global OSM_OMS_SW_RevokeAPIFailurebatch(Set<Id> set_OrderItemIdTemp){
        set_OrderItemId = set_OrderItemIdTemp;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        if(set_OrderItemId.size() > 0){
            return Database.getQueryLocator([SELECT ID, IsCancelPending__c, Instance_ID_Count__c,ccrz__Order__c From ccrz__E_OrderItem__c Where (ccrz__Order__r.ccrz__OrderStatus__c='Cancellation Pending' OR (IsCancelPending__c = true AND ccrz__OrderItemStatus__c = 'Order Submitted')) AND (Tool_Instance_Count__c > 0 OR Basic_Tool_Instance_Key_Count__c > 0) AND Id IN: set_OrderItemId]);
        }else{
            return Database.getQueryLocator([SELECT ID, IsCancelPending__c, Instance_ID_Count__c,ccrz__Order__c From ccrz__E_OrderItem__c Where ((ccrz__Order__r.ccrz__OrderStatus__c='Cancellation Pending' AND ccrz__OrderItemStatus__c!='Cancelled') OR (IsCancelPending__c = true AND (ccrz__OrderItemStatus__c = 'Order Submitted' or ccrz__OrderItemStatus__c='Cancellation Pending'))) AND (Tool_Instance_Count__c > 0 OR Basic_Tool_Instance_Key_Count__c > 0)]);
        }
    }
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_OrderItem__c> scope){
        Set<Id> orderItemIdSet=new Set<Id>();
        Set<Id> orderItemIdSet2=new Set<Id>();
        String orderId = '';
        //Set<Id> setOrderId= new Set<Id>();
        //Set<Id> set_PartialCancelOrder = new Set<Id>();
        
        for(ccrz__E_OrderItem__c orderItem :scope) {
            orderItemIdSet.add(orderItem.id);
            /*setOrderId.add(orderItem.ccrz__Order__c);
            if(orderItem.IsCancelPending__c){
                set_PartialCancelOrder.add(orderItem.ccrz__Order__c);
            }*/
        }
        
        OSM_OMS_SW_RevokeAPIUtility.revokeAPIcall(orderItemIdSet);
        //MAR-2175 Start
        
        //List<ccrz__E_OrderItem__c> orderItemList2=[select id,ccrz__Order__c from ccrz__E_OrderItem__c where id IN:orderItemIdSet and OSM_SW_Is_OMS_Revoke_and_Cancel_Not_Done__c = false and (OSM_SW_Is_Refund_FSD_Done__c=true OR ccrz__Order__r.OSM_SW_Is_FSD_Done_Or_Not_Needed__c=true)];
        for(ccrz__E_OrderItem__c obj: [select id,ccrz__Order__c from ccrz__E_OrderItem__c where id IN:orderItemIdSet and OSM_SW_Is_OMS_Revoke_and_Cancel_Not_Done__c = false and (OSM_SW_Is_Refund_FSD_Done__c=true OR ccrz__Order__r.OSM_SW_Is_FSD_Done_Or_Not_Needed__c=true)])
        {
         orderItemIdSet2.add(obj.Id);
         orderId=obj.ccrz__Order__c;
        } 
         
        if(orderItemIdSet2.size() > 0 )
        {
             OSM_SW_OrderCancellationUtility.updateRecordsOnOrderItemCancellation(orderItemIdSet2, Label.OSM_Order_Cancellation);
             //List<ccrz__E_OrderItem__c> orderItemList3=[select id,ccrz__OrderItemStatus__c from ccrz__E_OrderItem__c where ccrz__Order__c =:  orderId];
             boolean callCancelOrderProcess = true;
             for(ccrz__E_OrderItem__c oitem : [select id,ccrz__OrderItemStatus__c from ccrz__E_OrderItem__c where ccrz__Order__c =:  orderId])
             {
                if(oitem.ccrz__OrderItemStatus__c != 'Cancelled')
                  callCancelOrderProcess = false;
             }
                    
             if(callCancelOrderProcess)
             {
                 Set<Id> setItemId = new Set<Id>();
                 setItemId.add(orderId);
                 CallCancleOrderProcessQuable objQua = new CallCancleOrderProcessQuable();
                 objQua.orderId = orderId;
                 ID jobID = System.enqueueJob(objQua);
                 System.debug('jobID'+jobID);
             }
         }
         
        //MAR-2175 End 
        //commneting this below earlier code as part of MAR-2175 story and adding above fresh conditions to call order item cancellation and Order cancellation
        /*//Added for MAR-1412 (Ashish)
        for(ccrz__E_OrderItem__c ordItm : [Select Id, ccrz__Order__c, IsRevokeLicenseSucess__c,ccrz__CCOrder__r.OrderProcessedforFSD__c from ccrz__E_OrderItem__c where Id IN :orderItemIdList]){
            if(!ordItm.IsRevokeLicenseSucess__c && setOrderId.size() > 0) {
                setOrderId.remove(ordItm.ccrz__Order__c);
            }
            if(Test.isRunningTest()){
                setOrderId.add(ordItm.ccrz__Order__c);
            }
        }
        // End: changes for MAR-1412
        
        if(setOrderId != null && setOrderId.size() > 0 ) {
            List<ccrz__E_TransactionPayment__c> lstTP = new List<ccrz__E_TransactionPayment__c>();
            Set<Id> orderIdForOther = new Set<Id>();
            Set<Id> orderIdForDistributedPO = new Set<Id>();
            Set<Id> set_OrdrIdPartialCan = new Set<Id>();
            
            lstTP = [Select Id, ccrz__CCOrder__c, ccrz__CCOrder__r.OrderProcessedforFSD__c, ccrz__CCOrder__r.Is_OMS_Revoke_and_Cancel_Not_Done_Count__c, ccrz__CCOrder__r.ccrz__OrderStatus__c, ccrz__AccountType__c from ccrz__E_TransactionPayment__c where ccrz__CCOrder__c IN: setOrderId];
            System.debug('TP obj: '+lstTP);
            
            for(ccrz__E_TransactionPayment__c objTp : lstTP) {
                if(objTp.ccrz__CCOrder__r.Is_OMS_Revoke_and_Cancel_Not_Done_Count__c == 0 || set_PartialCancelOrder.contains(objTp.ccrz__CCOrder__c)) {
                    if(objTp.ccrz__AccountType__c == 'cc' && (!set_PartialCancelOrder.contains(objTp.ccrz__CCOrder__c) || 
                            (set_PartialCancelOrder.contains(objTp.ccrz__CCOrder__c) && objTp.ccrz__CCOrder__r.ccrz__OrderStatus__c == Label.OSM_CancellationPending))) {
                        orderIdForOther.add(objTp.ccrz__CCOrder__c);
                    }
                    else if(objTp.ccrz__AccountType__c == 'cc' && set_PartialCancelOrder.contains(objTp.ccrz__CCOrder__c) && objTp.ccrz__CCOrder__r.ccrz__OrderStatus__c == 'Order Submitted') {
                        set_OrdrIdPartialCan.add(objTp.ccrz__CCOrder__c);
                    }
                    if(objTp.ccrz__AccountType__c == 'po') {
                        System.debug('objTp.ccrz__CCOrder__r.OrderProcessedforFSD__c: '+objTp.ccrz__CCOrder__r.OrderProcessedforFSD__c);
                        if(objTp.ccrz__CCOrder__r.OrderProcessedforFSD__c) {
                            orderIdForDistributedPO.add(objTp.ccrz__CCOrder__c);
                        }
                        else {
                            orderIdForOther.add(objTp.ccrz__CCOrder__c);
                        }
                    }
                }
            }
            
            if(orderIdForDistributedPO != null && orderIdForDistributedPO.size() > 0) {
                for(Id key: orderIdForDistributedPO) {
                    System.enqueueJob(new OSM_SW_QueueSubmitOrder(key)); 
                }
            }
            System.debug('orderIdForOther: '+orderIdForOther);
            if(orderIdForOther != null && orderIdForOther.size() > 0) {
                System.enqueueJob(new OSM_SW_QueueOrderUpdateonCancel(orderIdForOther));
            }
            if(set_OrdrIdPartialCan.size() > 0){
                System.enqueueJob(new OSM_SW_QueuePartialOrderCacncellation(set_OrdrIdPartialCan, false));
            }
        }*/   
    }
    
    global void finish(Database.BatchableContext BC) {
        OSM_Integration_Log__c log = new OSM_Integration_Log__c();
        log.Service_Name__c='OSM_OMS_SW_RevokeAPIFailurebatch';
        log.Internal_Batch_Log__c=true;
        AsyncApexJob jobstatus = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        log.Status__c = jobstatus.Status;
        if(jobstatus.Status=='Completed'){
            log.Status__c = 'Processed'; 
        }else if(jobstatus.Status=='Failed'){
            log.Internal_Batch_Failure__c=true;
            log.No_of_Jobs_Failed__c=jobstatus.NumberOfErrors;
        }
        insert log;
        Database.executeBatch(new OSM_CancelLicensesRetryIntBatch(true), 1);
    }
}