objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>OSM_Term_and_Condition__c</fullName>
        <label>OSM Term and Condition</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_RequestForQuote__c.object
<CustomObject>
    <fields>
        <fullName>Display_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Keep Package(Plan) of Main Product</description>
        <label>Product Name</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>CC Requests For Quote (Display Product)</relationshipLabel>
        <relationshipName>CC_Requests_For_Quote1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Request For Quote</label>
    <nameField>
        <displayFormat>RFQ-{000000}</displayFormat>
        <label>RFQ Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Requests For Quote</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OSM_SW_Prod_TermsAndConditions_Ctrl_Test.cls
@isTest

public class OSM_SW_Prod_TermsAndConditions_Ctrl_Test{
   // public static User usr=OSM_testDataCreationUtility.getPortalUser();
    public static User usr=OSM_testDataCreationUtility.getPortalUser();
    static testMethod void testOSM_SW_ProductDetailServiceCls1()
    {
        TestProductSetupReq testReq = OSM_TestDataCreationUtility.populatedTestProductSetupReq();
        
        TestCompletedTransactionSetUpRes objResponseProductSetup = OSM_TestDataCreationUtility.createProductSetUp(testReq);
        
        System.debug('objResponseProductSetup: '+objResponseProductSetup);
        
        //TestCompletedTransactionSetUpRes transecRes = OSM_TestDataCreationUtility.createCompletedTransactionFlowTestData(objResponseProductSetup, 40, 6);
        
        //System.debug('transecRes: '+transecRes);
        System.runAs(usr){
        ccrz__E_Product__c compositeProduct=TestingUtils.createCompositeProduct(testReq.compositeProductName + '-1',testReq.compositeProductSKU + '-1',testReq.compositeProductGroupName,testReq.compositeProductProductType,true);
        compositeProduct.OSM_Term_and_Condition__c='quote';
        compositeProduct.name='test';
        upsert compositeProduct;
        Test.StartTest();
        
        PageReference myVfPage = Page.OSM_SW_Prod_TermsAndConditionsPg;
        Test.setCurrentPage(myVfPage);

        // Put Id into the current page Parameters
        ApexPages.currentPage().getParameters().put('val',compositeProduct.Id);
        
        ApexPages.StandardController con=new ApexPages.StandardController(compositeProduct);
        OSM_SW_Prod_TermsAndConditions_Ctrl condition=new OSM_SW_Prod_TermsAndConditions_Ctrl(); 
        
        //update condition;
        Test.StopTest();
        }
    }
    static testMethod void testOSM_SW_ProductDetailServiceCls2()
    {
        TestProductSetupReq testReq = OSM_TestDataCreationUtility.populatedTestProductSetupReq();
        
        TestCompletedTransactionSetUpRes objResponseProductSetup = OSM_TestDataCreationUtility.createProductSetUp(testReq);
        
        //System.debug('objResponseProductSetup: '+objResponseProductSetup);
        
        //TestCompletedTransactionSetUpRes transecRes = OSM_TestDataCreationUtility.createCompletedTransactionFlowTestData(objResponseProductSetup, 40, 6);
        
        //System.debug('transecRes: '+transecRes);
        System.runAs(usr){

        ccrz__E_Product__c compositeProduct=TestingUtils.createCompositeProduct(testReq.compositeProductName + '-1',testReq.compositeProductSKU + '-1',testReq.compositeProductGroupName,testReq.compositeProductProductType,true);
        compositeProduct.OSM_Term_and_Condition__c='quote';
        compositeProduct.name='test';
        upsert compositeProduct;
        
        ccrz__E_RequestForQuote__c rfq = TestingUtils.createRequestForQuote(1, 'In Progress', 20, 10, 100, 'Send', 'Test Data Comments', null, null, true)[0];
        rfq.Display_Product__c = compositeProduct.ID;
        upsert rfq;
        Test.StartTest();
        
        PageReference myVfPage = Page.OSM_SW_Prod_TermsAndConditionsPg;
        Test.setCurrentPage(myVfPage);

        // Put Id into the current page Parameters
        ApexPages.currentPage().getParameters().put('val','quote'+rfq.Id);
        
        ApexPages.StandardController con=new ApexPages.StandardController(compositeProduct);
        OSM_SW_Prod_TermsAndConditions_Ctrl condition=new OSM_SW_Prod_TermsAndConditions_Ctrl(); 
        condition.getProduct();
        condition.getReqForQuote();
        //update condition;
        Test.StopTest();
    }
    }
}