objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ecom_Coupon__c.object
<CustomObject>
    <fields>
        <fullName>Ecom_Coupon_Type__c</fullName>
        <label>Coupon Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Ecom_Rule_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Absolute</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Free Shipping</fullName>
                </value>
                <value>
                    <fullName>Free Products</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                    <isActive>false</isActive>
                    <label>Price</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ecom Coupon</label>
    <nameField>
        <label>Coupon Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ecom Coupons</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Ecom_Coupon_Product__c.object
<CustomObject>
    <fields>
        <fullName>Ecom_Coupon_Type__c</fullName>
        <label>Coupon Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Absolute</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ecom_Coupon__c</fullName>
        <label>Ecom Coupon</label>
        <referenceTo>Ecom_Coupon__c</referenceTo>
        <relationshipLabel>Ecom Coupon Products</relationshipLabel>
        <relationshipName>Ecom_Coupon_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ecom_Source_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Ecom Coupon Products</relationshipLabel>
        <relationshipName>Ecom_Coupon_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ecom Coupon Product</label>
    <nameField>
        <displayFormat>EPROD-{000000}</displayFormat>
        <label>Coupon Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ecom Coupon Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/dbu_CouponProductUtility_Test.cls
@isTest
private class dbu_CouponProductUtility_Test {

    @isTest
    public static void getCouponProductsTest(){
        Ecom_Coupon__c coupon = dbu_CouponFactoryDataTest.createCoupon('test','Cart Total');
        coupon.Ecom_Coupon_Type__c = 'Percentage';
        insert coupon;
        ccrz__E_Product__c productObj = dbu_FactoryDataTest.createProduct('Test',true, true, true,true);
        insert productObj;
        Ecom_Coupon_Product__c couponProduct = dbu_CouponFactoryDataTest.createCouponProduct(coupon.Id,'Exclusion');
        couponProduct.Ecom_Source_Product__c = productObj.Id;
        insert couponProduct;
        List<Ecom_Coupon_Product__c> couponProductList = new List<Ecom_Coupon_Product__c>();
        couponProductList.add(couponProduct);
        
        Test.startTest(); 
        dbu_CouponProductUtility.getCouponProducts(couponProductList);
        Test.stopTest();
    }
}