objects/ccrz__E_ContactAddr__c.object
<CustomObject>
    <description>Used to store address information.  Associated with Carts, Orders, Invoices, Subscriptions, Payments, etc.</description>
    <fields>
        <fullName>ccrz__AddressFirstline__c</fullName>
        <description>First line of the street address.</description>
        <label>Address Firstline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressSecondline__c</fullName>
        <description>Second line of the street address.</description>
        <label>Address Secondline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__AddressThirdline__c</fullName>
        <description>Third line of the street address.</description>
        <label>Address Thirdline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__City__c</fullName>
        <description>City for the address.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Country__c</fullName>
        <description>Descriptive country name.  Typically country ISO code is used.</description>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__FirstName__c</fullName>
        <description>Person first name associated with the address.</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__HomePhone__c</fullName>
        <description>Secondary phone associated with the address.</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ccrz__LastName__c</fullName>
        <description>Person last name associated with the address.</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__MiddleName__c</fullName>
        <description>Person middle name associated with the address.</description>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__PostalCode__c</fullName>
        <description>Postal Code associated with the address.</description>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__State__c</fullName>
        <description>For non-US or non-Canadian addresses this is the name of the state for the address.</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Contact Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Contact Addresss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_contactAddress_Test.cls
@isTest
public class dbu_contactAddress_Test {
    @testsetup static void setuptestdata(){
        ccrz__E_ContactAddr__c shipadd	=	dbu_FactoryDataTest.createContactAddress('12/plot 3', 'barrio estate', 'TX', '4535343', 'United States', 'Texas');
        insert shipadd;
    }
    
    @isTest public static void insertCCContactAddress(){
        ccrz__E_ContactAddr__c shipad = [SELECT Id, Name, ccrz__FirstName__c, ccrz__MiddleName__c,
                                         ccrz__LastName__c, ccrz__AddressFirstline__c, 
                                         ccrz__AddressSecondline__c,ccrz__AddressThirdline__c,
                                         ccrz__City__c,ccrz__Country__c, ccrz__State__c,
                                         ccrz__PostalCode__c, ccrz__HomePhone__c FROM ccrz__E_ContactAddr__c where ccrz__AddressFirstline__c = '12/plot 3'];
        dbu_contactAddress.getContactAddress();
    }
    
}