objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Is_Revoked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Revoked ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Revoke Initiated</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tool_Instance_Count__c</fullName>
        <label>Functional Tool Instance Count</label>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Status__c</field>
            <operation>equals</operation>
            <value>New</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Tool_Instance_Key__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Type__c</field>
            <operation>equals</operation>
            <value>Functional</value>
        </summaryFilterItems>
        <summaryForeignKey>OSM_Order_Item_License__c.CC_Order_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OSM_SW_RevokeOIBatch.cls
global class OSM_SW_RevokeOIBatch implements Database.Batchable<sObject>,Database.AllowsCallouts
{
   global Set<String> recordIds;
    
    global OSM_SW_RevokeOIBatch(Set<String> paramIds){
       recordIds = paramIds;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        if(recordIds == null){
            return Database.getQueryLocator([Select 
                                            Id
                                        From ccrz__E_OrderItem__c 
                                        where Tool_Instance_Count__c > 0  
                                           and Revocation_Status__c =: 'Revoke Initiated'
                                           and Is_Revoked__c =: false]);
        }
        return Database.getQueryLocator([Select 
                                            Id
                                        From ccrz__E_OrderItem__c 
                                        where Id IN:recordIds 
                                           and Tool_Instance_Count__c > 0  
                                           and Revocation_Status__c =: 'Revoke Initiated'
                                           and Is_Revoked__c =: false]);
    }
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_OrderItem__c> itemLicenses)
    {
        Set<ID> orderItemIdSet = new Set<ID>();
        List<OSM_ReturnWrapper> objReturnList=new List<OSM_ReturnWrapper>();
        for(ccrz__E_OrderItem__c oil: itemLicenses){
            orderItemIdSet.add(oil.Id);
        }
        OSM_OMS_SW_RevokeAPIUtility.revokeAPIcall(orderItemIdSet);
            
    }
    
    
    global void finish(Database.BatchableContext BC)
    {
        
        System.debug('End : OSM_SW_RevokeOIBatch');
    }
}