objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>OSM_SW_Days_Since_Order_Date__c</fullName>
        <formula>NOW() -  CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Order Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partially Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partial Cancellation Requested</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Order Delayed</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Return Received and Approved</fullName>
                </value>
                <value>
                    <fullName>Return Request</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Approved</fullName>
                </value>
                <value>
                    <fullName>Return Complete</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Picked up</fullName>
                </value>
                <value>
                    <fullName>Return Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent order, which originally submitted the subscription for this order, if applicable</description>
        <inlineHelpText>Parent order, which originally submitted the subscription for this order, if applicable</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Children Orders</relationshipLabel>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>Activation_Key_Generated__c</fullName>
        <label>Activation Key Generated</label>
        <summaryFilterItems>
            <field>OSM_Order_Item_License__c.Activation_Key__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>OSM_Order_Item_License__c.CC_Order_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Basic_Remaining_Lisences__c</fullName>
        <formula>IF(CONTAINS($Label.SES_OMSCreateOrder_SubscriptionProduct_List,  ccrz__Product__r.ccrz__SKU__c ) , 

IF(CONTAINS($Label.SES_OMSCreateOrder_SubscriptionProduct_List_AddOns, ccrz__Product__r.ccrz__SKU__c), 

IF(Number_of_Bundles__c &gt; 0,(MCEILING(ccrz__OriginalQuantity__c)*Number_of_Bundles__c ) - (Basic_Tool_Instance_Key_Count__c+OSM_SW_Revoked_Basic_Key_Count__c), MCEILING(ccrz__OriginalQuantity__c) - (Basic_Tool_Instance_Key_Count__c+OSM_SW_Revoked_Basic_Key_Count__c)),IF(CONTAINS($Label.OMS_ProductList_NonInsite,ccrz__Product__r.ccrz__SKU__c),Number_of_Bundles__c - (Basic_Tool_Instance_Key_Count__c+OSM_SW_Revoked_Basic_Key_Count__c),MCEILING(ccrz__OriginalQuantity__c)-(Basic_Tool_Instance_Key_Count__c+OSM_SW_Revoked_Basic_Key_Count__c)) ) 
, 
Number_of_Bundles__c - (Basic_Tool_Instance_Key_Count__c+OSM_SW_Revoked_Basic_Key_Count__c))







/*MCEILING(ccrz__OriginalQuantity__c) - (Basic_Tool_Instance_Key_Count__c+OSM_SW_Revoked_Basic_Key_Count__c)*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Basic Remaining Lisences</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OMS_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OMS Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Remaining_Lisences__c</fullName>
        <formula>IF(CONTAINS($Label.SES_OMSCreateOrder_SubscriptionProduct_List,  ccrz__Product__r.ccrz__SKU__c ) ,

IF(CONTAINS($Label.SES_OMSCreateOrder_SubscriptionProduct_List_AddOns, ccrz__Product__r.ccrz__SKU__c),

IF(Number_of_Bundles__c &gt; 0,(MCEILING(ccrz__OriginalQuantity__c)*Number_of_Bundles__c ) - (Tool_Instance_Count__c+OSM_SW_Revoked_Functional_Key_Count__c), MCEILING(ccrz__OriginalQuantity__c) - (Tool_Instance_Count__c+OSM_SW_Revoked_Functional_Key_Count__c)), IF(CONTAINS($Label.OMS_ProductList_NonInsite,ccrz__Product__r.ccrz__SKU__c),Number_of_Bundles__c - (Tool_Instance_Count__c+OSM_SW_Revoked_Functional_Key_Count__c),MCEILING(ccrz__OriginalQuantity__c)-(Tool_Instance_Count__c+OSM_SW_Revoked_Functional_Key_Count__c)))
,
Number_of_Bundles__c - (Tool_Instance_Count__c+OSM_SW_Revoked_Functional_Key_Count__c))

/*IF(CONTAINS($Label.SES_OMSCreateOrder_SubscriptionProduct_List, ccrz__Product_Name__c) , MCEILING(ccrz__OriginalQuantity__c)  -  (Tool_Instance_Count__c+OSM_SW_Revoked_Functional_Key_Count__c) ,   Number_of_Bundles__c -  (Tool_Instance_Count__c+OSM_SW_Revoked_Functional_Key_Count__c))*/</formula>
        <label>Remaining Lisences</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tool_Instance_Key__c</fullName>
        <label>Tool Instance Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderItemStatus__c</fullName>
        <description>Status field at the line level. The initial value is always Order Submitted. Other values are non-functional and can be used by external systems for post-order placement status tracking.</description>
        <label>Order Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Cancellation Pending</fullName>
                </value>
                <value>
                    <fullName>Return Initiated</fullName>
                </value>
                <value>
                    <fullName>Return Rejected</fullName>
                </value>
                <value>
                    <fullName>Available for Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Order__c</fullName>
        <description>The order that this order line is a part of.</description>
        <inlineHelpText>The order that this order line is a part of.</inlineHelpText>
        <label>Order</label>
        <referenceTo>ccrz__E_Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isRenew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isRenew</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within B2B Commerce</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OSM_Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Batch_Failure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Batch Failure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Batch_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Batch Log</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_of_Jobs_Failed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Jobs Failed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OSM Integration Log</label>
    <nameField>
        <displayFormat>OSM- {0000000000}</displayFormat>
        <label>OSM Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSM Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_OMS_GetTI_HourlyBatch.cls
global class OSM_OMS_GetTI_HourlyBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable{
    global OSM_OMS_GetTI_HourlyBatch(){
        
    }
     
    global Database.QueryLocator start(Database.BatchableContext BC){
        String emptyStr = '';
        List<string> list_BasicProd = new List<String>();
        List<string> list_FunctProd = new List<String>();
        list_FunctProd = Label.OSM_SingleLicense_Products.split(',');
        list_BasicProd = Label.OSM_SingleLicense_Basic_Products.split(',');
        String query = '';
        if(Test.isRunningTest()){
            query = 'Select ID, OMS_Product__c, ccrz__Product__r.Name, Activation_Key_Generated__c,Basic_Remaining_Lisences__c, Remaining_Lisences__c, ccrz__Quantity__c, Tool_Instance_Key__c, ccrz__Order__r.ccrz__OrderStatus__c From ccrz__E_OrderItem__c Where isRenew__c = false AND '+
                            +'(Remaining_Lisences__c >0 or Basic_Remaining_Lisences__c>0)';
        
        }else{
            query = 'Select id,oms_product__c, ccrz__product__r.NAME, activation_key_generated__c, basic_remaining_lisences__c, remaining_lisences__c, ccrz__quantity__c, tool_instance_key__c, ccrz__order__r.ccrz__orderstatus__c, ccrz__order__r.OSM_SW_Days_Since_Order_Date__c FROM ccrz__e_orderitem__c WHERE activation_key_generated__c > 0 AND ccrz__product__r.ccrz__sku__c NOT IN : list_FunctProd AND ( remaining_lisences__c > 0 OR basic_remaining_lisences__c > 0 ) AND ccrz__orderitemstatus__c != \'Cancelled\' AND ccrz__order__r.OSM_SW_Days_Since_Order_Date__c < 367 AND ccrz__order__r.ccrz__orderstatus__c = \'Order Submitted\'';
        
        }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ccrz__E_OrderItem__c> scope)
    {
        Set<ID> orderItemIdSet = new Set<ID>();
        
        for(ccrz__E_OrderItem__c orderItem :scope)
        {
            
                orderItemIdSet.add(orderItem.ID);
             System.debug('orderItemIdSet_____'+orderItemIdSet);
        }
        
       OSM_OMS_GetTI_Batch_Helper.callGetTILicensesAPI(orderItemIdSet);
    }
    
    
    global void finish(Database.BatchableContext BC)
    {
        OSM_Integration_Log__c log = new OSM_Integration_Log__c();
        log.Service_Name__c='OSM OSM_OMS_GetTI_Batch' ;
        log.Internal_Batch_Log__c=true;
        AsyncApexJob jobstatus = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
         log.Status__c = jobstatus.Status;
        if(jobstatus.Status=='Completed'){
            log.Status__c = 'Processed'; 
        }else if(jobstatus.Status=='Failed'){
            log.Internal_Batch_Failure__c=true;
            log.No_of_Jobs_Failed__c=jobstatus.NumberOfErrors;
        }
        insert log;
        System.debug('End : OSM_OMS_GetTI_Batch');
    }
    
    global void execute(SchedulableContext SC){
        Database.executeBatch(new OSM_OMS_GetTI_HourlyBatch(),1); 
    }
}