objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IAM_Contact_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User in this field should be contact owner for all approval needs.</description>
        <label>User Details</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>this is for IDM purpose and to store cummins LDAP ID of all the users having the WWID from LDAP</description>
        <externalId>true</externalId>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/effectiveAccount_enable_ProfileUserType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Enable_Effective_Account_Selection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Effective Account Selection Feat</label>
        <type>Checkbox</type>
    </fields>
    <label>Effective account selection enabled</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>OSM_Storefront_User_Type__c</fullName>
        <defaultValue>&quot;Regular&quot;</defaultValue>
        <label>OSM Storefront User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                    <default>true</default>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>Distributor Admin</fullName>
                </value>
                <value>
                    <fullName>SSOEM Admin</fullName>
                </value>
                <value>
                    <fullName>OSM Reseller Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OSM_SW_ccServiceContact_Test.cls
@isTest
private class OSM_SW_ccServiceContact_Test {

    private static testMethod void test() {
        
        Profile ObjProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        User objUser = new User(FirstName ='test', 
                                Lastname ='12345',
                                Alias = 'test123', 
                                localesidkey='en_US',
                                emailencodingkey='UTF-8',
                                languagelocalekey='en_US',
                                profileId = ObjProfile.Id,
                                Email ='test123@noemail.com',
                                username ='test01@noemail.com',
                                OSM_Storefront_User_Type__c='Regular',
                                timezonesidkey='America/Los_Angeles');
        insert objUser;
        
        PermissionSet objPS = [SELECT Id FROM PermissionSet WHERE Name = 'OSM_Distributor_Admin'];
        
        PermissionSetAssignment objPSA = new PermissionSetAssignment(AssigneeId = objUser.Id,
                                                                     PermissionSetId = objPS.Id);
        insert objPSA;
        
        System.runAs(objUser){
            
            Test.startTest();
            
            Account objAccount = new Account(Name = 'Test Account');
            insert objAccount;
            
            Contact objContact = new Contact(FirstName = 'Test', 
                                             LastName = 'Contact', 
                                             AccountId = objAccount.Id, 
                                             IAM_Contact_Owner__c = userinfo.getUserId(),
                                             Username__c = 'test776@gmail.com');
            insert objContact;
            effectiveAccount_enable_ProfileUserType__c effAccProfType = new effectiveAccount_enable_ProfileUserType__c();
            effAccProfType.Name='Regular';
            effAccProfType.Enable_Effective_Account_Selection__c = true;
            insert effAccProfType;
            OSM_SW_ccServiceContact objHand = new OSM_SW_ccServiceContact();
            objHand.getFilterMap(new Map<String, Object>());
            
            Test.stopTest();
        }
        
    }

}