objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Job for this Component</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solutions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Solutions linked to the Component</description>
        <label>CSS Solutions</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>Failure Selected By Technician</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>DSID__c</fullName>
        <formula>Service_Job__r.DSID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DSID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup for Service Job object that stores the  Job order number associated with it.</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <description>It’s a solution Id obtained from EDS.</description>
        <label>Solution Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_SRT__c.object
<CustomObject>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <formula>Solution_Number__r.Solution_Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Title</label>
        <type>Text</type>
    </fields>
    <label>CSS SRT</label>
    <nameField>
        <label>CSS SRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS SRTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSS_ComponentRequestWrapper_Test.cls
@isTest
public class CSS_ComponentRequestWrapper_Test {
 @isTest static void testCSS_ComponentRequestWrapper(){        
       List<CSS_SRT__c> srtList = new List<CSS_SRT__c>(); 
        CSS_Job_Order__c cjb = new CSS_Job_Order__c();
        cjb.Customer_Name__c = 'Test SRT';
        cjb.DSID__c = 'DSBDT4760';
        insert cjb;
        CSS_Solutions__c sol = new CSS_Solutions__c();
        sol.name = 'K81572426';
        sol.Solution_Title__c ='Engine control module (ECM) Calibration Revision History check';
        insert sol;
        List<CSS_Solution_Component__c> lstSolComp = new List<CSS_Solution_Component__c>();
        CSS_Solution_Component__c solComp = new CSS_Solution_Component__c();
        solComp.Solutions__c = sol.id;
        solComp.Service_Job__c = cjb.id;
        solComp.name = 'ABC';
        insert solComp;
        CSS_Solutions__c sol1 = new CSS_Solutions__c();
        sol1.name = 'K81572426';
        sol1.Solution_Title__c ='Engine control module (ECM) Calibration Revision History check';
        insert sol1;
        CSS_Solution_Component__c solComp1 = new CSS_Solution_Component__c();
        solComp1.Solutions__c = sol1.id;
        solComp1.Service_Job__c = cjb.id;
        solComp1.name = 'ABC';
        insert solComp1;     
        lstSolComp.add(solComp);
        lstSolComp.add(solComp1);
        CSS_ComponentRequestWrapper compRe = new CSS_ComponentRequestWrapper(lstSolComp,cjb.DSID__c);  
    }
}