objects/CSS_JobForms__c.object
<CustomObject>
    <fields>
        <fullName>Co_Worker_Name__c</fullName>
        <label>Co-Worker Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Location__c</fullName>
        <label>Job Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PowerGenPPELevel__c</fullName>
        <description>These field is for PPE level of POWERGEN JSA</description>
        <label>PowerGenPPELevel</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS_JobForms</relationshipLabel>
        <relationshipName>CSS_JobForms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CSS_JobForms</label>
    <nameField>
        <label>CSS_JobForms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_JobForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_JobHistory__c.object
<CustomObject>
    <fields>
        <fullName>CSS_JobFormId__c</fullName>
        <description>These field is store the saved JobForm ID</description>
        <label>CSS_JobFormId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_Job_Id__c</fullName>
        <label>CSS Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSS_JobHistory</label>
    <nameField>
        <label>CSS_JobHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_JobHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CG_CL_PowerGenJSA_Test.cls
@isTest
public class CG_CL_PowerGenJSA_Test
{
    static testMethod void CG_CL_PowerGenJSA_Test()
    {
        
        test.startTest(); 
        CSS_Job_Order__c servicejob = new CSS_Job_Order__c();
        servicejob.Customer_Name__c = 'test';
        insert (servicejob);

        CSS_JobForms__c  jobform= new CSS_JobForms__c();
        jobform.Service_Job__c=servicejob.id;
        jobform.name='test';
        jobform.Co_Worker_Name__c ='test1 test2 test3';
        jobform.Job_Location__c='cummins East-Bristol';
        jobform.PowerGenPPELevel__c ='test';

        insert (jobform); 
        
        CSS_JobHistory__c JH = new CSS_JobHistory__c();
        JH.CSS_JobFormId__c = jobform.id;
        JH.CSS_Job_Id__c = servicejob.id;
        insert (JH); 

        Test.stopTest();

        PageReference pageRef = Page.CG_PowerGenJSA;
        pageRef.getParameters().put('id', servicejob.id);
        pageRef.getParameters().put('jformId', jobform.id);
        Test.setCurrentPage(pageRef);
        CG_CL_PowerGenJSA c = new CG_CL_PowerGenJSA();
        c.getPowerGenPrepare1();
        c.getPPE1();
        //c.getTaskCategory();
        c.powerGenPgSave();
        c.FormCancelPopup();

        
    }
}