objects/CSS_WS_Warranty__c.object
<CustomObject>
    <description>Mexico Warranty Claims Object</description>
    <fields>
        <fullName>CSS_WS_Account_Code__c</fullName>
        <label>Account Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Claim_Status__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <description>Status of the claim</description>
        <label>Claim Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Customer_Name_Internal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS_WS_Claim</relationshipLabel>
        <relationshipName>CSS_WS_Claims_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Policy_Flag__c</fullName>
        <description>This dropdown will allow the user to select whether the claim is for Warranty or Policy.</description>
        <label>Warranty / Policy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty</fullName>
                    <default>true</default>
                    <label>Warranty</label>
                </value>
                <value>
                    <fullName>Policy</fullName>
                </value>
                <value>
                    <fullName>Policy WW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_DR__c</fullName>
        <description>Service provider code - Service provider Name format of the distributor to which the logged in dealer belongs to</description>
        <label>Service Provider (DR)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_Dealer__c</fullName>
        <description>Service provider code - Service provider Name format</description>
        <label>Service Provider (Dealer)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_Name_DR__c</fullName>
        <label>Service Provider Name (DR)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_Name_Dealer__c</fullName>
        <label>Service Provider Name Dealer</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CSS WS Claim</label>
    <nameField>
        <label>Claim Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS WS Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CSS_WS_ControllerPendingApproval_Test.cls
@IsTest
Public Class CSS_WS_ControllerPendingApproval_Test {
    Public Static TestMethod Void listPendingTSMClaims(){
               
        Account CustomerTest = new Account(
            Type = 'Customer',
            Name = 'Sony');
        insert CustomerTest;
               
        CSS_WS_Warranty__c claim = new CSS_WS_Warranty__c(
            CSS_WS_Service_Provider_DR__c = '54701',
            CSS_WS_Service_Provider_Dealer__c = '54701',
            CSS_WS_Service_Provider_Name_DR__c = 'MEGAMAK OCCIDENTE',
            CSS_WS_Service_Provider_Name_Dealer__c = 'MEGAMAK OCCIDENTE',
            CSS_WS_Claim_Status__c = 'Pending TSM',
            CSS_WS_Customer_Name_Internal__c = CustomerTest.id,
            CSS_WS_Account_Code__c = 'P88',
            CSS_WS_Policy_Flag__c = 'Policy');
        insert claim;
               
        //Query to "CSS_WS_Queue_TSM" queue
        List<GroupMember> group_test = [SELECT GroupId FROM GroupMember WHERE Group.DeveloperName = 'CSS_WS_Queue_TSM' LIMIT 1];
        
        // Create an approval request for the claim
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setObjectId(claim.id);

        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('CSS_WS_Policy_88_Approval_Proc_FA_V3');
        req1.setSkipEntryCriteria(true);

        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        
        Test.startTest();
        ApexPages.StandardController standardController = new ApexPages.StandardController(Claim);
        CSS_WS_ControllerPendingApproval controller = new CSS_WS_ControllerPendingApproval(standardController);
        
        controller.ApproverSel = 'All';
        controller.getClaimsListApprover();
        controller.ApproverSel = String.valueOf(group_test[0].GroupId);
        controller.getClaimsListApprover();
        
        controller.exitClaimsUpdate();
        controller.getApproversSelectList();

        Test.stopTest();
    }
}