objects/CSS_DataExchange_Parent__c.object
<CustomObject>
    <description>This is used for storing Request &amp; Response values from Triage mobile app or external data system</description>
    <fields>
        <fullName>ServiceName__c</fullName>
        <label>ServiceName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CSS_DataExchange_Parent</label>
    <nameField>
        <displayFormat>IAS-{0000000000}</displayFormat>
        <label>IAS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSS_DataExchange_Parent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSS_DeleteIARecordsSchedulerTest.cls
@isTest 
public class CSS_DeleteIARecordsSchedulerTest {

    static TestMethod void testScheduler() {
        CSS_DeleteIARecordsScheduler schClass = new CSS_DeleteIARecordsScheduler();
        String runTime = '0 0 23 * * ?';
        
        CSS_DataExchange_Parent__c deObj = new CSS_DataExchange_Parent__c();
        deObj.ServiceName__c = 'GetAssessData';
        insert deObj;

        Test.startTest();
        System.schedule('Test Schedule', runTime, schClass);
        Test.stopTest();
    }

}