objects/CSS_Integration_Details__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting used to store Integration Connection details</description>
    <fields>
        <fullName>ApplicationName__c</fullName>
        <label>ApplicationName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS_Integration_Details</label>
</CustomObject>

objects/CSS_JobEventTemporary__c.object
<CustomObject>
    <fields>
        <fullName>Attribute1__c</fullName>
        <label>Attribute1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute2__c</fullName>
        <label>Attribute2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute3__c</fullName>
        <label>Attribute3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpireDateTime__c</fullName>
        <label>ExpiryDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobOrder__c</fullName>
        <label>JobOrder</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Model_Name__c</fullName>
        <label>Service Model Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>QSOL</fullName>
                </value>
                <value>
                    <fullName>SRT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>TRPs</fullName>
                </value>
                <value>
                    <fullName>TSBs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS_JobEventTemporary</label>
    <nameField>
        <label>CSS_JobEventTemporary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_JobEventTemporaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup for Service Job object that stores the  Job order number associated with it.</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Model__c</fullName>
        <formula>Service_Job__r.Service_Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Model</label>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_SRT__c.object
<CustomObject>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRT_AccessiblityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accessiblity CheckBox Option from the SRT Table</description>
        <label>SRT AccessiblityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRT_Details__c</fullName>
        <label>SRT Details</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Title__c</fullName>
        <label>SRT Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Model_Name__c</fullName>
        <label>Service Model Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution Number</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diagnosis</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Diag Access</fullName>
                </value>
                <value>
                    <fullName>Repair Access</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>99Time</fullName>
                </value>
                <value>
                    <fullName>Overlap</fullName>
                </value>
                <value>
                    <fullName>Field Action</fullName>
                </value>
                <value>
                    <fullName>Field Action Access</fullName>
                </value>
                <value>
                    <fullName>BMS SRT</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS SRT</label>
    <nameField>
        <label>CSS SRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS SRTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSS_AccessCheckWBSrvcTest.cls
@isTest(seeAllData=True)
public class CSS_AccessCheckWBSrvcTest {
    /*public static void accessTokentest() {
        Test.setMock(HttpCalloutMock.class, new CSS_SRTAccessCheckTokenTest());
        CSS_SRTAccessWebService.receiveToken(); 
    }
    public static void accessSRTTest()
    {
        css_JobEventTemporary__c jobTemp = new css_JobEventTemporary__c();
            
    }*/ 
    
    public static testMethod void accessCheck(){
        // insert JobOrderId object
        css_job_order__c joborder = new css_job_order__c();
        //joborder.name = 'test';
        joborder.Equipment_ID__c = 'test';
        joborder.Qsol_Engine_Family_Code__c = '100';
        joborder.Service_Model__c = '100';
        insert joborder;
        system.debug('joborder=='+joborder);
        
        //insert CSS_Solutions__c
        CSS_Solutions__c css = new CSS_Solutions__c();
        css.service_job__c = joborder.id;
        css.name = 'test';
        insert css;
        //insert CSS_srt__c
        
        ApexPages.currentPage().getParameters().put('JobOrderId', joborder.id);
        ApexPages.currentPage().getParameters().put('solutionId', css.id);
        ApexPages.currentPage().getParameters().put('typ', 'rep');
        
        CSS_SRTAccessCheckListCL controller = new CSS_SRTAccessCheckListCL();
        controller.lstDisplaySRT[0].SRT_AccessiblityCheck__c = TRUE;
        controller.saveNClose();
        
        //insert CSS_JobEventTemporary__c    
        CSS_JobEventTemporary__c jobevent = new CSS_JobEventTemporary__c();
        jobevent.JobOrder__c = joborder.id;
        jobevent.Attribute1__c = joborder.Qsol_Engine_Family_Code__c;
        jobevent.Attribute2__c = joborder.Equipment_ID__c;
        jobevent.Attribute3__c = 'test';
        jobevent.Service_Model_Name__c = joborder.Service_Model__c;
        jobevent.Source__c = 'SRT';
        jobevent.Type__c = 'Repair Access';// give type from parameters
        jobevent.ExpireDateTime__c = System.Now()+1000;
        insert jobevent;
        system.debug('jobevent==='+jobevent);        
        
        CSS_srt__c srt = new CSS_srt__c();
        srt.Solution_Number__c = css.id;
        srt.Job_order__c = joborder.id;
        srt.Type__c = 'Repair Access';
        srt.SRT_Details__c = 'test';
        srt.SRT_Title__c = 'MR';
        insert srt;
        
        // insert CSS_Integration_Details__c
        CSS_Integration_Details__c intdetails = new CSS_Integration_Details__c();
        intdetails.ApplicationName__c = '';
        intdetails.isactive__c = true;
        // insert intdetails ;
        // inset the above later now we use exsisting
    
    }
        
}