objects/CSS_ECM__c.object
<CustomObject>
    <description>An object between JO and Fault code to store ECM for Multi ECM engines</description>
    <fields>
        <fullName>CORE__c</fullName>
        <label>CORE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECM_Number__c</fullName>
        <description>Stores ECM Number(As of now 0-11) are possible values</description>
        <label>ECM Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS ECM</relationshipLabel>
        <relationshipName>CSS_ECM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Model__c</fullName>
        <label>Service Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CSS ECM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS ECM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CSS_ecmGtisTrigger_Test.cls
@isTest
public class CSS_ecmGtisTrigger_Test {
    
    public static testMethod void testGtis() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        UserRole ur = [SELECT id from UserRole WHERE PortalType = 'None' LIMIT 1];
        User newUser = new User(Alias = 'standt', Email='test1@gmail.com', UserRoleId = ur.Id ,
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='test11newUser@gmail.com');
        CSS_Job_Order__c job1;
        CSS_Job_Order__c job2;
        CSS_ECM__c ecm;
        CSS_ECM__c ecm2;
        
        System.runAs(newUser) {
            job1 = new CSS_Job_Order__c(ownerId = newUser.id,Customer_Name__c='Nick',service_model__c='Test');
            insert job1;
             ecm = new CSS_ecm__c(ECM_Number__c=0,name='ECM1',CORE__c = 'GTIS_20' ,Job_Order__c=job1.id);
            insert ecm;           
            
            job2 = new CSS_Job_Order__c(ownerId = newUser.id,Customer_Name__c='Nick',service_model__c='Test');
            insert job2;
             ecm2 = new CSS_ecm__c(ECM_Number__c=0,name='ECM2',CORE__c = 'GTIS_38' ,Job_Order__c=job2.id);
            insert ecm2; 
            
        }
    }


}