objects/CSS_AccredUser__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <formula>Accreditation__r.Account__r.Location__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_Id__c</fullName>
        <description>This field is used to store the promotion ID from SBL</description>
        <label>Promotion Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Model_Name__c</fullName>
        <description>This field is NOT used and this field is replaced with ServiceModelName__c</description>
        <formula>Accreditation__r.Service_Model_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSS_AccredUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CSS_AccredUser</label>
    <nameField>
        <label>CSS AccredUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_AccredUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Fault_Code__c.object
<CustomObject>
    <fields>
        <fullName>FaultCode__c</fullName>
        <description>Stores the value of the Fault code.</description>
        <formula>if(Fault_Code__r.Name != null,Fault_Code__r.Name,FaultCodeR2__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FaultCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to select the job order number from the Service Job Object.</description>
        <inlineHelpText>Select the Job Order Number</inlineHelpText>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Fault Code</relationshipLabel>
        <relationshipName>Fault_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mod__c</fullName>
        <description>Stores the Mod related to Fault Code related to INSITE.</description>
        <label>Mod</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to store the Fault Code status.</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is to store the Fault or Symptom classification</description>
        <inlineHelpText>Fault or Symptom classification</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fault</fullName>
                    <default>true</default>
                    <label>Fault</label>
                </value>
                <value>
                    <fullName>Symptom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS Fault Code</label>
    <nameField>
        <label>Fault Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Fault Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Integration_Error__c.object
<CustomObject>
    <fields>
        <fullName>Auth_Call_Time__c</fullName>
        <label>Auth Call Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Description__c</fullName>
        <description>Stores the type of Error for different integrations based on different Error type.</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processed_Data__c</fullName>
        <description>Captures the Data that the integration Program is processing.</description>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Call_Time__c</fullName>
        <label>Service Call Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Job_Number__c</fullName>
        <label>Service Job Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CSS Integration Error</label>
    <nameField>
        <displayFormat>ERR-{0000000}</displayFormat>
        <label>Integration Errors Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSS Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_JobEventTemporary__c.object
<CustomObject>
    <fields>
        <fullName>ESN__c</fullName>
        <label>ESN</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Model_Name__c</fullName>
        <label>Service Model Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>TRPs</fullName>
                </value>
                <value>
                    <fullName>TSBs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS_JobEventTemporary</label>
    <nameField>
        <label>CSS_JobEventTemporary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_JobEventTemporaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_JobForm_Detail__c.object
<CustomObject>
    <fields>
        <fullName>CSS_JobForms__c</fullName>
        <label>CSS_JobForms</label>
        <referenceTo>CSS_JobForms__c</referenceTo>
        <relationshipLabel>CSS_JobForm_Details</relationshipLabel>
        <relationshipName>CSS_JobForm_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TSR_ActivityDescription__c</fullName>
        <label>TSR_ActivityDescription</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TSR_ActivityID__c</fullName>
        <label>TSR_ActivityID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSR_ActivityOwner__c</fullName>
        <label>TSR_ActivityOwner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSR_ActivitySubject__c</fullName>
        <label>TSR_ActivitySubject</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSR_ActivityType__c</fullName>
        <description>Used to store activity Type from TSR WebService(SRNumber Data)</description>
        <label>TSR_ActivityType</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSR_Request__c</fullName>
        <label>TSR_Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TSR_Response__c</fullName>
        <label>TSR_Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CSS_JobForm_Detail</label>
    <nameField>
        <label>CSS_JobForm_Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_JobForm_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSS_JobForms__c.object
<CustomObject>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS_JobForms</relationshipLabel>
        <relationshipName>CSS_JobForms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TSR_SRNumber__c</fullName>
        <description>Field to store SR Number from TSR System</description>
        <label>TSR_SRNumber</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <label>CSS_JobForms</label>
    <nameField>
        <label>CSS_JobForms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_JobForms</pluralLabel>
    <recordTypes>
        <fullName>TSREscalation</fullName>
        <active>true</active>
        <label>TSREscalation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>CSS_Nested_Solutions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Nested Solutions</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Response__c</fullName>
        <description>Values for Verification</description>
        <label>Diagnostic Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not the solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FaultCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Fault Code</label>
        <referenceTo>CSS_Fault_Code__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup for Service Job object that stores the  Job order number associated with it.</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Model__c</fullName>
        <formula>Service_Job__r.Service_Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Symptom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS_SymptomQA</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CSS_SymptomQA__c.Type__c</field>
                <operation>equals</operation>
                <value>SearchString</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>CSS_SymptomQA__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_SymptomQA__c.object
<CustomObject>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is a lookup for Service Job object that stores the Job order number associated with it.</inlineHelpText>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS_SymptomQA</relationshipLabel>
        <relationshipName>CSS_SymptomQA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SearchString__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SearchString</label>
        <referenceTo>CSS_SymptomQA__c</referenceTo>
        <relationshipLabel>CSS_SymptomQA</relationshipLabel>
        <relationshipName>CSS_SymptomQA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>CSS_SymptomQA</label>
    <nameField>
        <label>CSS_SymptomQ&amp;A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS_SymptomQA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CG_BL_TSR.cls
public class CG_BL_TSR {
    
    public static void performTSRBusinessLogic(){
        try{
            //Query User Details
            Id UserId = userinfo.getuserId();
            User currentuser = new User();
            currentuser=[Select Id,FirstName,LastName,Email,Phone from User where Id=:UserId];
            
            //QueryServiceJob
            
            Id Wid = ApexPages.CurrentPage().getParameters().get('id');
            system.debug('Wid>>>>>>>>>>>>>>>>>>>>>'+Wid);
            CSS_Job_Order__c ServiceJob = new CSS_Job_Order__c();
            ServiceJob = [Select Id,Name,ESN__c,General_Symptoms__c,CSS_Hours__c,CSS_Job_Location_Code__c,Customer_Name__c,Shop_Work_Order__c,Repeat_Visit__c,Failure_Date__c,Mileage_Measure__c,Mileage__c,Complaint_Type_Desc__c,Complaint_Type2_Desc__c,Complaint_Type3_Desc__c,Complaint_Type4_Desc__c,Complaint_Type5_Desc__c,Service_Model__c from CSS_Job_Order__c where id =: Wid ];
            
            //Query Fault Code Object
            List<CSS_Fault_Code__c> faultCodes = new List<CSS_Fault_Code__c>();
            faultCodes=[Select id,FaultCode__c,Job_Order__c,Mod__c,Status__c,
                        (Select id,name,Diagnostic_Response__c from CSS_Solutions__r) from CSS_Fault_Code__c where Job_Order__c =: Wid];
            
            //Query Symptom Object
            List<CSS_SymptomQA__c> SymptomSrch = new List<CSS_SymptomQA__c>();
            SymptomSrch = [Select id,Name,SearchString__c,Job_Order__c,Type__c,User_Name__c,
                           (Select id,name,Diagnostic_Response__c from CSS_Solutions__r) from CSS_SymptomQA__c where Job_Order__c =: Wid and Type__c = 'SearchString'];
            
            //Query Accred User Object
            List<CSS_AccredUser__c> accredUser= new List<CSS_AccredUser__c>();
            accredUser = [select Id,Promotion_Id__c,Location__c,Service_Model_Name__c,User__c from CSS_AccredUser__c where Service_Model_Name__c =: ServiceJob.Service_Model__c and Location__c =: ServiceJob.CSS_Job_Location_Code__c and User__c =: UserId];
            
            //User's Tech Id
            String TechId;
            if(accredUser.size()>0)
                TechId = (accredUser[0].Promotion_Id__c != null && accredUser[0].Promotion_Id__c != '' ? accredUser[0].Promotion_Id__c : '');
            
            //Derive Customer Support Level 
            String CustomerSupportLevel = deriveCustomerSupportLevel(ServiceJob.Repeat_Visit__c,faultCodes,SymptomSrch);
            
            //Derive Complaint Code
            String ComplaintCode = deriveComplaintCode(ServiceJob);
            
            //Call Method to check if ESN is HHP or HMLD
            String EscalationGroup = deriveEscalationGroup(ServiceJob.Service_Model__c);
            
            //Call service Layer to make Webservice Call
            CG_OP_OAGWrapper TSRCallout;
            TSRCallout = CG_SL_TSR.TSRWebservice(currentuser,ServiceJob,faultCodes,SymptomSrch,TechId,CustomerSupportLevel,ComplaintCode,EscalationGroup);
            system.debug('TSRCallout**'+TSRCallout);
            //To Store TSR Response Data
            saveTSRResponse(TSRCallout,Wid,ServiceJob.Name);
            
            
        }catch(exception e){
            system.debug('Entered into catch block of performTSRBusinessLogic in CG_BL_TSR class>>>>>>>>>>>>>>>>>>>>>>>'+e.getLineNumber() + ' ' + e.getMessage());
        }
    }
    
    
    
    public static void saveTSRResponse(CG_OP_OAGWrapper TSRCallout,Id Wid,String JobId){
        
        CSS_JobForms__c jobForm = new CSS_JobForms__c();
        CSS_Job_Order__c servJob = new CSS_Job_Order__c();
        try{
            system.debug('Anirudh>>>>>>>>>>>>Callout Details'+TSRCallout);
            String TSRRequest = TSRCallout.request.getBody();
            String strTSRResponse = TSRCallout.response.getBody();
            
            CG_TSRREsJSONParser TSRResponse; 
            TSRResponse = (CG_TSRREsJSONParser)JSON.deserialize(TSRCallout.response.getBody(),CG_TSRREsJSONParser.class);
             system.debug('Anirudh>>>>>>>>>>>>TSRResponse'+TSRResponse);   
            if(TSRCallout.exceptionFlag != true){   
                
                
                Id recTypeIdTSR = css_utility.getRecordTypeId(CSS_JobForms__c.sObjectType, 'TSREscalation');
                
                if(TSRResponse.DataArea != null && TSRResponse.DataArea.TSRNumber != null && TSRResponse.DataArea.TSRNumber != ''){
                    jobForm.TSR_SRNumber__c = TSRResponse.DataArea.TSRNumber;
                    jobForm.RecordTypeId = recTypeIdTSR; 
                    jobForm.Service_Job__c = Wid;
                    
                    insert jobForm;
                    
                    CSS_JobForm_Detail__c TSRdetails = new CSS_JobForm_Detail__c();
                    TSRdetails.CSS_JobForms__c=jobForm.Id;
                    TSRdetails.TSR_ActivityDescription__c = TSRResponse.DataArea.ActivityDescription;
                    TSRdetails.TSR_ActivityID__c = TSRResponse.DataArea.ActivityID;
                    TSRdetails.TSR_ActivityOwner__c = TSRResponse.DataArea.ActivityOwner;
                    TSRdetails.TSR_ActivitySubject__c = TSRResponse.DataArea.ActivitySubject;
                    TSRdetails.TSR_ActivityType__c = TSRResponse.DataArea.ActivityType;
                    TSRdetails.TSR_Response__c = strTSRResponse;
                    TSRdetails.TSR_Request__c = TSRRequest;
                    insert TSRdetails; 
                }
                if(TSRResponse.DataArea != null){
                servJob.TSR_EscalateNumber__c = (TSRResponse.DataArea.TSRNumber != null && TSRResponse.DataArea.TSRNumber != '' ? TSRResponse.DataArea.TSRNumber : 'Error'); 
                servJob.Id = Wid;
                update servJob;
                }
            }else{
                servJob.TSR_EscalateNumber__c = 'Error';
                servJob.Id = Wid;
                update servJob;   
            }
            try{
                CSS_Integration_Error__c intDetails = new CSS_Integration_Error__c();
                
                intDetails.Auth_Call_Time__c = (TSRCallout.totalAuthCallTime != null ? TSRCallout.totalAuthCallTime : 0);
                intDetails.Error_Description__c = (TSRResponse.DataArea != null && TSRResponse.DataArea.ErrorMessage != null && TSRResponse.DataArea.ErrorMessage != '' ? TSRResponse.DataArea.ErrorMessage : 'Failure');
                //Request Body
                intDetails.Processed_Data__c =  TSRCallout.request.getBody();
                intDetails.Response_Body__c = TSRCallout.response.getBody();
                intDetails.Service_Call_Time__c = (TSRCallout.totalServiceCallTime != null ? TSRCallout.totalServiceCallTime : 0);
                intDetails.Service_Job_Number__c = JobId;
                intDetails.Service_Name__c = 'TSREscalation';
                intDetails.Source__c = 'TSR';
                insert intDetails;
            }catch(exception e){
                system.debug('Entered into Insert Integration Error Log Method in cg_bl_tsr'+e.getMessage() + ' ' + e.getLineNumber());
            }
        }catch(exception e){
            system.debug('Entered into catch block of saveTSRResponse Method in CG_BL_TSR Class>>>>>>>>>>>>>>>'+e.getMessage() + ' ' + e.getLineNumber());
            servJob.TSR_EscalateNumber__c = 'Error';
            servJob.Id = Wid;
            update servJob; 
        } 
    }
    
    
    public static string deriveCustomerSupportLevel(Boolean RptVstFlag,List<CSS_Fault_Code__c> faultCodes,List<CSS_SymptomQA__c> SymptomSrch){
        try{
            String CustomerSupportLevel;
            if(RptVstFlag == true){
                CustomerSupportLevel = 'Cummins CARE Level 2';
            }else{
                boolean responseisNull;
                
                //Check if for any fault code all the solutions are performed
                for(CSS_Fault_Code__c fc : faultCodes){
                    responseisNull = false;
                    for(CSS_Solutions__c sol : fc.CSS_Solutions__r){
                        if(sol.Diagnostic_Response__c == null || sol.Diagnostic_Response__c == ''){
                            responseisNull = true;
                            break;
                        }
                    }
                    if(fc.CSS_Solutions__r.size()>0)
                        if(responseisNull == false){ 
                            CustomerSupportLevel = 'Cummins CARE Level 2';
                            break;
                        }
                }
                
                //Check if for any symptom all the solutions are performed
                for(CSS_SymptomQA__c sym : SymptomSrch){
                    responseisNull = false;
                    for(CSS_Solutions__c sol : sym.CSS_Solutions__r){
                        if(sol.Diagnostic_Response__c == null || sol.Diagnostic_Response__c == ''){
                            responseisNull = true;
                            break;
                        }
                    }
                    if(sym.CSS_Solutions__r.size()>0)
                        if(responseisNull == false){ 
                            CustomerSupportLevel = 'Cummins CARE Level 2';
                            break;
                        }
                }
                if(CustomerSupportLevel != 'Cummins CARE Level 2')
                    CustomerSupportLevel = 'Cummins CARE Level 1';
            }
            return CustomerSupportLevel;
        }catch(exception e){
            system.debug('Entered into catch block of deriveCustomerSupportLevel in CG_BL_TSR class>>>>>>>>>>>>>>>>>>>>>>>'+e.getLineNumber() + ' ' + e.getMessage());
        }
        return null;
    }
    
    public static string deriveComplaintCode(CSS_Job_Order__c workJob){
        try{
            String complaintType;        
            complaintType = (workJob.Complaint_Type_Desc__c != null && workJob.Complaint_Type_Desc__c != '' ? workJob.Complaint_Type_Desc__c :(workJob.Complaint_Type2_Desc__c != null && workJob.Complaint_Type2_Desc__c != '' ? workJob.Complaint_Type2_Desc__c : (workJob.Complaint_Type3_Desc__c != null && workJob.Complaint_Type3_Desc__c != '' ? workJob.Complaint_Type3_Desc__c : (workJob.Complaint_Type4_Desc__c != null && workJob.Complaint_Type4_Desc__c != '' ? workJob.Complaint_Type4_Desc__c : (workJob.Complaint_Type5_Desc__c != null && workJob.Complaint_Type5_Desc__c != '' ? workJob.Complaint_Type5_Desc__c : '')))));
            String ComplaintCode='';
            
            CSS_JobEventTemporary__c[] Categories;
            CSS_WPR_SBL_CatComplaintsListResJSON  resCatCompJSON;
            
            Categories = [select Reason__c from CSS_JobEventTemporary__c where attribute1__c = 'CategoryComplaintCodes'];
            system.debug('Categories>>>'+Categories);
            string jsonResponse = Categories[0].Reason__c;
            
            //jsonResponse='{"DataArea": {"Details": [{"ComplaintCode": "123","Description": "abc","BusinessUnit": "EBU","ActiveFlag": "Y","Category": "aaa"},{"ComplaintCode": "345","Description": "tavdg","BusinessUnit": "PSBU","ActiveFlag": "N","Category": "bbb"}]},"Header": {"ReturnCodeDescription": "","Status": "Success"}}';
            resCatCompJSON = (CSS_WPR_SBL_CatComplaintsListResJSON )JSON.deserialize(jsonResponse ,CSS_WPR_SBL_CatComplaintsListResJSON .class);
            
            if(resCatCompJSON  != null && resCatCompJSON.DataArea != null && resCatCompJSON.DataArea.Details != null){
                for(CSS_WPR_SBL_CatComplaintsListResJSON.Details det : resCatCompJSON.DataArea.Details ){
                    if(det.ActiveFlag == 'Y' && det.Description == complaintType){
                        ComplaintCode = det.ComplaintCode;
                    }
                }
            }
            return ComplaintCode;
        }catch(exception e){
            system.debug('Entered into catch block of deriveComplaintCode in CG_BL_TSR class>>>>>>>>>>>>>>>>>>>>>>>'+e.getLineNumber() + ' ' + e.getMessage());
        }
        return null;
    }
    
    public static string deriveEscalationGroup(string SMN){
        try{
            String EngineType = '';
            if(SMN != null && SMN != ''){
                Set<String> hhpSet = new Set<String>();
                for(CSS_Listof_HHP_SMNS__c hhp: CSS_Listof_HHP_SMNS__c.getAll().Values()){
                    hhpSet.add(hhp.Listof_HHP_SMN__c);
                }
                if(hhpSet.contains(SMN)){
                    EngineType = 'HHP';
                }else{
                    EngineType = 'HMLD';
                }
                hhpSet = null;
            }
            return EngineType;
        }catch(exception e){
            system.debug('Entered into catch block of deriveEscalationGroup Method of CG_BL_TSR class'+e.getLineNumber() + '  ' +e.getMessage());
            return null;
        }
    }
}