objects/CSS_WS_Engine_Application_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting that stores information about Engine Application Codes</description>
    <label>CSS WS Engine Application Code</label>
</CustomObject>

objects/CSS_WS_Rescue__c.object
<CustomObject>
    <description>Main rescues object</description>
    <fields>
        <fullName>CSS_WS_Access_Code__c</fullName>
        <label>Access Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Build_Date__c</fullName>
        <description>Engine Building Date</description>
        <label>Engine Built Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Customer_Name_Internal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS WS Rescues</relationshipLabel>
        <relationshipName>CSS_WS_Rescues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Engine_Application_Code__c</fullName>
        <description>Engine Application Code</description>
        <label>Engine Application Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Engine_Application__c</fullName>
        <label>Engine Application</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Engine_Family_Code__c</fullName>
        <label>Engine Family Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Engine_Serial_Number__c</fullName>
        <label>Engine Serial No.</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Failure_Measure__c</fullName>
        <label>Failure Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Km</fullName>
                </value>
                <value>
                    <fullName>Hr</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSS_WS_Failure_Point_Quantity__c</fullName>
        <label>Failure Point Qty</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Lodging_Amount__c</fullName>
        <label>Lodging Amount ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_LunchAmount__c</fullName>
        <description>Lunch Amount cost in USD</description>
        <label>Lunch Amount ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Manufacturer__c</fullName>
        <label>Manufacturer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Model_Series__c</fullName>
        <label>Model Series</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_RepairEnding__c</fullName>
        <label>Service Completion</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSS_WS_RescueCost__c</fullName>
        <label>Rescue Cost ($)</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CSS_WS_ServiceRequest__c</fullName>
        <label>Service Request</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Model__c</fullName>
        <label>Service Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_DR__c</fullName>
        <label>Service Provider (DR)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_Dealer__c</fullName>
        <label>Service Provider (Dealer)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_Name_DR__c</fullName>
        <label>Service Provider Name (DR)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Service_Provider_Name_Dealer__c</fullName>
        <label>Service Provider Name (Dealer)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_TechnicianName__c</fullName>
        <label>Technician Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS_WS_TechnicianPromotion__c</fullName>
        <label>Technician Promotion</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CSS_WS_TowingAmount__c</fullName>
        <label>Towing Amount ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_TravelHoursRoundTripPolicy__c</fullName>
        <label>Travel Hours (Approved)</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_TravelKmRoundTripPolicy__c</fullName>
        <label>Travel Distance (Approved)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Warranty_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field for relating rescues with claims for travel section of Claim form</description>
        <label>CSS WS Claim</label>
        <referenceTo>CSS_WS_Warranty__c</referenceTo>
        <relationshipLabel>CSS WS Rescues</relationshipLabel>
        <relationshipName>CSS_WS_Rescues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Warranty_Start_Date__c</fullName>
        <label>Warranty Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSS_WS_Years_In_Service__c</fullName>
        <label>Years in Service</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CSS WS Rescue</label>
    <nameField>
        <displayFormat>RES{0000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSS WS Rescues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CSS_WS_ClaimServiceOrder_Test.cls
@IsTest
Public Class CSS_WS_ClaimServiceOrder_Test {
    
    @isTest static void createClaimServiceOrder(){
               
        Account CustomerTest = new Account(
            Type = 'Customer',
            Name = 'Sony');
        insert CustomerTest;
               
        CSS_WS_Rescue__c rescue = new CSS_WS_Rescue__c(
            CSS_WS_Access_Code__c = 'B', 
            CSS_WS_Warranty_Relationship__c = null, 
            CSS_WS_Customer_Name_Internal__c = CustomerTest.id, 
            CSS_WS_Engine_Application__c = 'AUTOMOTIVE', 
            CSS_WS_Engine_Application_Code__c = '130', 
            CSS_WS_Build_Date__c = date.parse('9/12/2016'), 
            CSS_WS_Engine_Family_Code__c = '10', 
            CSS_WS_Engine_Serial_Number__c = '79640575', 
            CSS_WS_Failure_Measure__c = 'Km', 
            CSS_WS_Failure_Point_Quantity__c = '1000', 
            CSS_WS_Lodging_Amount__c = 53.28, 
            CSS_WS_LunchAmount__c = 26.64, 
            CSS_WS_Manufacturer__c = 'ACREMASTER', 
            CSS_WS_Model_Series__c = 'C210M', 
            CSS_WS_RescueCost__c = 409.12, 
            CSS_WS_RepairEnding__c = date.parse('5/5/2018'), 
            CSS_WS_Service_Model__c = 'ISX CM871 E', 
            CSS_WS_Service_Provider_Dealer__c = '73011', 
            CSS_WS_Service_Provider_DR__c = '73011',  
            CSS_WS_Service_Provider_Name_Dealer__c = 'CUMMINS ALESSO MONTERREY', 
            CSS_WS_Service_Provider_Name_DR__c = 'CUMMINS ALESSO MONTERREY', 
            CSS_WS_ServiceRequest__c = date.parse('4/4/2018'), 
            CSS_WS_TechnicianName__c = 'Jose Ramirez Arevalo', 
            CSS_WS_TechnicianPromotion__c = '1045839', 
            CSS_WS_TowingAmount__c = null, 
            CSS_WS_TravelKmRoundTripPolicy__c = 130, 
            CSS_WS_TravelHoursRoundTripPolicy__c = 20, 
            CSS_WS_Warranty_Start_Date__c = date.parse('9/9/2017'),
            CSS_WS_Years_In_Service__c = 2);
        insert rescue;
        
        Test.startTest();
        // 
        Id test_claim_id = CSS_WS_ClaimServiceOrder.RescueToClaim(String.ValueOf(rescue.Id));
        //stem.assertEquals(test_claim_id, true);  
        System.assert(test_claim_id != null, 'P101 has been created properly');

        Test.stopTest();
    }
}