objects/CSS_SRT__c.object
<CustomObject>
    <fields>
        <fullName>Access_Code_A__c</fullName>
        <label>Access Code A</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Component ID for this Repair</description>
        <label>CSS Solution Component</label>
        <referenceTo>CSS_Solution_Component__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS SRTS</relationshipLabel>
        <relationshipName>CSS_SRTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SRT_AccessiblityCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accessiblity CheckBox Option from the SRT Table</description>
        <label>SRT AccessiblityCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SRT_ID__c</fullName>
        <label>SRT ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRT_Time__c</fullName>
        <label>SRT Time</label>
        <precision>13</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diagnosis</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Diag Access</fullName>
                </value>
                <value>
                    <fullName>Repair Access</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>99Time</fullName>
                </value>
                <value>
                    <fullName>Overlap</fullName>
                </value>
                <value>
                    <fullName>Field Action</fullName>
                </value>
                <value>
                    <fullName>Field Action Access</fullName>
                </value>
                <value>
                    <fullName>BMS SRT</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isPerformed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPerformed</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS SRT</label>
    <nameField>
        <label>CSS SRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS SRTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSS_AutoAddAdminSRT_Test.cls
@istest
public class CSS_AutoAddAdminSRT_Test {
    static TestMethod void testautoaddAdminSRT() {
        CSS_Job_Order__c JO = new CSS_Job_Order__c();
        JO = CSS_TestData.createJobOrder(true);
        CSS_SRT__c SRT = new CSS_SRT__c();
					srt.Job_Order__c = JO.id;
                    srt.SRT_AccessiblityCheck__c=True;
                    srt.Access_Code_A__c = 65;
                    srt.name = 'TestClassName';
					srt.type__c = 'Admin';
           			srt.Assignment__c = 'PRIMARY';
           			srt.srt_time__c = 1;
           			srt.SRT_ID__c = '00-901-10';
		           	srt.isPerformed__c = true;
        insert srt;
        CSS_SRT__c SRT1 = new CSS_SRT__c();
                    srt1.Job_Order__c = JO.id;
                    srt1.SRT_AccessiblityCheck__c=True;
                    srt1.Access_Code_A__c = 65;
                    srt1.name = 'TestClassName';
					srt1.type__c = 'Admin';
           			srt1.Assignment__c = 'PRIMARY';
           			srt1.srt_time__c = 1;
           			srt1.SRT_ID__c = '00-902-10';
					srt1.isPerformed__c = true;
           insert srt1;
          
       
        
           Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
           Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
    Test.startTest();
        List<String> input = new List<String>();
        string str = 'test';
        string str1 = 'test1';
        input.add(str);
        input.add(str1);
         Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
           Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        css_AutoAddAdminSRT.getAdminSRTs(input);
        css_AutoAddAdminSRT.SRTCalloutAndInsert(JO.id,'In Shop','310 – Recreational Vehicle');
        //css_AutoAddAdminSRT.SRTCalloutAndInsert(JO.id,'Mobile','');
        css_AutoAddAdminSRT.SRTCalloutAndInsertInsiteAdminSRT(JO.id);
       
        
        Test.stopTest();
    }
    static TestMethod void testautoaddAdminSRT1() {
        
        
        CSS_Job_Order__c JO = new CSS_Job_Order__c();
        JO = CSS_TestData.createJobOrder(true);
        CSS_SRT__c SRT = new CSS_SRT__c();
          
                    srt.Job_Order__c = JO.id;
                    srt.SRT_AccessiblityCheck__c=True;
                    srt.Access_Code_A__c = 65;
                    srt.name = 'TestClassName';
					srt.type__c = 'Admin';
           			srt.Assignment__c = 'PRIMARY';
           srt.srt_time__c = 1;
           srt.SRT_ID__c = '00-901-10';
           //srt.Component_id__c = solcomp.id;
           srt.isPerformed__c = true;
           insert srt;
        CSS_SRT__c SRT1 = new CSS_SRT__c();
                            srt1.Job_Order__c = JO.id;
                    srt1.SRT_AccessiblityCheck__c=True;
                    srt1.Access_Code_A__c = 65;
                    srt1.name = 'TestClassName';
					srt1.type__c = 'Admin';
           			srt1.Assignment__c = 'PRIMARY';
           srt1.srt_time__c = 1;
           srt1.SRT_ID__c = '00-902-10';
           //srt.Component_id__c = solcomp.id;
           srt1.isPerformed__c = true;
           insert srt1;
       
       Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
           Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
       Test.startTest();
        List<String> input = new List<String>();
        //string str = 'test'+';;'+'test1';
        string str = 'test';
        string str1 = 'test1';
        input.add(str);
        input.add(str1);
         Test.setMock(HttpCalloutMock.class, new CSS_AccessToken_SRT_Test());
           Test.setMock(HttpCalloutMock.class, new CSS_getAllRepDiagSRTs_Test());
        
        css_AutoAddAdminSRT.getAdminSRTs(input);
        //css_AutoAddAdminSRT.SRTCalloutAndInsert(JO.id,'In Shop','310 – Recreational Vehicle');
        css_AutoAddAdminSRT.SRTCalloutAndInsert(JO.id,'Mobile','');
        css_AutoAddAdminSRT.SRTCalloutAndInsertInsiteAdminSRT(JO.id);

            
        
        Test.stopTest();
    }
}