objects/CSS_CampTsbTrp__c.object
<CustomObject>
    <fields>
        <fullName>Job_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Order</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_CampTsbTrp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Performed_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Required to Performed/Review</description>
        <inlineHelpText>Required to Performed/Review</inlineHelpText>
        <label>Performed Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Performed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Technicain Check if Performed</description>
        <inlineHelpText>Technicain Check if Performed</inlineHelpText>
        <label>Performed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAM</fullName>
                </value>
                <value>
                    <fullName>TSB</fullName>
                </value>
                <value>
                    <fullName>TRP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TSB</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TSBs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Work_Group_Name__c</fullName>
        <label>Work Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CSS_DsidClose_Test.cls
@isTest
public class CSS_DsidClose_Test {
    public static testMethod void testJobOrderData(){
        
        
        Test.startTest();
        CSS_Job_Order__c  servjob = new CSS_Job_Order__c ();
        //servjob.id = 'a093B000000xyjzQAA';
        servjob.CSS_Resolution__c = 'Solved';
        servjob.CSS_Feedback_Comments__c = 'Santosh';
        servjob.DSID__c = 'DBDT6931';
        insert servjob;
        
        CSS_CampTsbTrp__c camps = new CSS_CampTsbTrp__c(); 
        camps.Job_Order__c = servjob.id;
        camps.type__c = 'CAM';
        camps.performed_review__c = true;
        camps.performed__c = true;
        insert camps;
        user x = new user();
        x.Work_Group_Name__c = 'ORLANDO';
        
        ApexPages.CurrentPage().getParameters().put('Id',servjob.id);
        css_dsidclose controller = new css_dsidclose();
        
        Test.setMock(HttpCalloutMock.class, new CSS_GetdsidDetails_Test());
        controller.Wid = servjob.id;
        CSS_J2Adsidclose_EDS z = new CSS_J2Adsidclose_EDS();
        
        
        controller.solDetFailed = false;
        controller.campids = 'C1960';
        controller.solErrorMsg = 'invalid';
        
        controller.Closedsid(servjob.CSS_Resolution__c,servjob.CSS_Feedback_Comments__c,servjob.DSID__c);
        
        
        Test.stopTest();
        
        
        
        
        
        
        
    }
}