objects/CSS_Fault_Code__c.object
<CustomObject>
    <fields>
        <fullName>DSID__c</fullName>
        <formula>Job_Order__r.DSID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DSID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FaultCode__c</fullName>
        <description>Stores the value of the Fault code.</description>
        <formula>if(Fault_Code__r.Name != null,Fault_Code__r.Name,FaultCodeR2__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FaultCode</label>
        <type>Text</type>
    </fields>
    <label>CSS Fault Code</label>
    <nameField>
        <label>Fault Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Fault Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solution_Component__c.object
<CustomObject>
    <description>Captures All CSS Components for the Solution</description>
    <fields>
        <fullName>Action__c</fullName>
        <description>Action Selected by Technician during repair</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Replace</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charlength__c</fullName>
        <defaultValue>false</defaultValue>
        <description>turns true if the length of the component name is more than 80 characters</description>
        <label>Charlength</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component_Id__c</fullName>
        <description>Captures the Component or Failure ID for the Repair</description>
        <label>Component Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL_Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FSL Service Job</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Failures Added</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of Parts used in Repair</description>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected_Component__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected Component</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Job for this Component</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipLabel>CSS Solution Components</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solutions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Solutions linked to the Component</description>
        <label>CSS Solutions</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipLabel>Failure Selected By Technician</relationshipLabel>
        <relationshipName>CSS_Solution_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CSS Solution Component</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Solution Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSS_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>CSS_Nested_Solutions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Nested Solutions</label>
        <referenceTo>CSS_Solutions__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DSID__c</fullName>
        <formula>Service_Job__r.DSID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DSID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Notes__c</fullName>
        <label>Diagnostic Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Response__c</fullName>
        <description>Values for Verification</description>
        <label>Diagnostic Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not the solution</fullName>
                </value>
                <value>
                    <fullName>Most likely the solution</fullName>
                </value>
                <value>
                    <fullName>Could not perform the solution verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL_Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FSL Service Job</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Solutions History</relationshipLabel>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FaultCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Fault Code</label>
        <referenceTo>CSS_Fault_Code__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup for Service Job object that stores the  Job order number associated with it.</description>
        <label>Service Job</label>
        <referenceTo>CSS_Job_Order__c</referenceTo>
        <relationshipName>CSS_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Title__c</fullName>
        <description>It’s a solution Id obtained from EDS.</description>
        <label>Solution Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSL_Update_Cause.cls
/**********************************************************************
Name:FSL_Update_Cause
Copyright © 2011  Cummins
=======================================================================
=======================================================================
Purpose:                                                            
To perform all the Functionalties of Job Plan                                                          
=======================================================================
=======================================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE             DETAIL                                 
1.0 - Vinod Yellala      03/11/2019       INITIAL DEVELOPMENT
***********************************************************************/
public class FSL_Update_Cause {
    @InvocableMethod(label='FSLupdateCause' description='updateCause from Process Builder')
    public static void FSLupdateCause(List<Id> solId){
        
        List<WorkOrder> fslWOs=new List<WorkOrder>();
        WorkOrder fslWO;//=new WorkOrder();
        List<CSS_Solutions__c> lstSolutions;
        system.debug('solId: '+solId);
        //added FSL_Service_Job__c on SOQL by vinodo yellala FSL 4C's
        lstSolutions = [Select Id, Name,Solution_Title__c, Service_Job__c, Rank__c,DSID__c,FSL_Service_Job__c,
                        Diagnostic_notes__c, Diagnostic_Response__c, FaultCode__c,FaultCode__r.name,
                        (select Id,Name,Action__c,Component_Id__c, Solutions__c,Quantity__c,Selected_Component__c,Charlength__c, Service_Job__c 
                         from CSS_Solution_Components__r  where Selected_Component__c=TRUE)
                        from CSS_Solutions__c where Id = :solId ];//removed check and CSS_Nested_Solutions__c = null from 9/6 - by vinod
        if(!lstSolutions.isEmpty() && lstSolutions.size()>0)
        {
            //Starts added by vinod 6/3 for 4C's on FSL
            
            fslWOs=[Select Id,WorkOrderNumber,EditCause__c from Workorder where id= :lstSolutions[0].FSL_Service_Job__c];//added by vinod 6/3 for 4C's on FSL
            
            if(fslWOs.size()>0)
                fslWO=fslWOs[0];
            if(String.isBlank(fslWO.EditCause__c))
                fslWO.EditCause__c='';
            //Ends added by vinod 6/3 for 4C's on FSL
            List<CSS_Solutions__c> NestedSOls=[Select Id, Name,Solution_Title__c, Service_Job__c, Rank__c,DSID__c,
                                               Diagnostic_notes__c, Diagnostic_Response__c, FaultCode__c, FaultCode__r.name,(select Id,Name,Action__c,Component_Id__c, Solutions__c,Quantity__c,Selected_Component__c,Charlength__c, Service_Job__c from CSS_Solution_Components__r),CSS_Nested_Solutions__c
                                               from CSS_Solutions__c where CSS_Nested_Solutions__c IN :lstSolutions];            
            String SolCompToBMS='';
            String SolResponse='';
            String BMSFailureID='';
            String NestSolCompToBMS='';
            String NestSolResponse='';
            String NestBMSFailureID='';
            system.debug('fslWO>>'+fslWO);
            Map<Id,List<CSS_Solutions__c>> mapSolNested=new Map<Id,List<CSS_Solutions__c>>();        
            for(CSS_Solutions__c sol:NestedSOls){
                if(mapSolNested.containsKey(sol.CSS_Nested_Solutions__c)){
                    mapSolNested.get(sol.CSS_Nested_Solutions__c).add(sol);
                }else{
                    mapSolNested.put(sol.CSS_Nested_Solutions__c, new List<CSS_Solutions__c>{sol});
                }
            }
            system.debug('mapSolNested: '+mapSolNested);
            for(CSS_Solutions__c solutions : lstSolutions)
            {
                system.debug('solutions.Diagnostic_Response__c>>'+solutions.Diagnostic_Response__c);
                NestSolCompToBMS = ''; 
                NestSolResponse = '';
                BMSFailureID = '';
                //modified by vinod yellala 6-3 to add 2nd value check on diagnostic response
                if(solutions.Diagnostic_Response__c != null && 
                   (solutions.Diagnostic_Response__c.equalsIgnoreCase('Most likely the solution') ||
                    solutions.Diagnostic_Response__c.equalsIgnoreCase('Most likely the solution. Repair recommended.')))
                {
                    if(fslWO != null)
                    {
                        //SolResponse = '\n' + 'Solution Title' + '=' + solutions.Solution_Title__c + '\n' + 'Diagnostic Notes' + '=' + solutions.Diagnostic_notes__c;
                        SolResponse += '\n' + solutions.FaultCode__r.name +  '\nDiagnostic Notes' + ': ' + solutions.Diagnostic_notes__c +'\n' ;
                        if(solutions.CSS_Solution_Components__r != null){
                            system.debug('solutions.CSS_Solution_Components__r size:'+solutions.CSS_Solution_Components__r.size());
                            for(CSS_Solution_Component__c components : solutions.CSS_Solution_Components__r){
                                if(components.Selected_Component__c)
                                {
                                    SolResponse +='Root Cause:'+components.name+'\n';
                                    BMSFailureID = BMSFailureID;
                                }
                            }
                        }
                        if(mapSolNested.containsKey(solutions.Id)){
                            for(CSS_Solutions__c nestedSol : mapSolNested.get(solutions.Id)){
                                //modified by vinod yellala 6-3 to add 2nd value check on diagnostic response
                                if(nestedSol.Diagnostic_Response__c != null && 
                                   (nestedSol.Diagnostic_Response__c.equalsIgnoreCase('Most likely the solution') ||
                                    nestedSol.Diagnostic_Response__c.equalsIgnoreCase('Most likely the solution. Repair recommended.'))){
                                        NestSolResponse = '\n' + 'Diagnostic Notes' + ':' + nestedSol.Diagnostic_notes__c + 'Root Cause' + ':' + nestedSol.Solution_Title__c + '\n';
                                        if(nestedSol.CSS_Solution_Components__r != null){
                                            for(CSS_Solution_Component__c components : nestedSol.CSS_Solution_Components__r){
                                                NestBMSFailureID = NestBMSFailureID + '';
                                            }
                                        }
                                        NestSolCompToBMS = NestSolCompToBMS + '\n' + NestSolResponse + '\n' + NestBMSFailureID;
                                    }
                            }
                        }
                        SolCompToBMS = SolCompToBMS + '\n' + SolResponse + '\n' + NestSolCompToBMS + '\n' + BMSFailureID;
                    }
                }
            }
            
            String cause;
            if(fslWO != null)
            {
                //cause = (fslWO.EditCause__c == null)?'':fslWO.EditCause__c.replace('\n' + 'Service Order' + '=' + fslWO.WorkOrderNumber, '');//added by vinod 6/3 for 4C's on FSL
                fslWO.EditCause__c += SolCompToBMS + '\n' + '\n';//added by vinod 6/3 for 4C's on FSL
                system.debug('fslWO.EditCause__c>>'+fslWO.EditCause__c);
                update fslWO;//added by vinod 6/3 for 4C's on FSL
            }
        }
    }
}