objects/CSS_Accreditation__c.object
<CustomObject>
    <description>Object to capture information related to Technician and Account Accreditations</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSS Accreditations</relationshipLabel>
        <relationshipName>CSS_Accreditations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MARKET_APPLICATION__c</fullName>
        <label>MARKET_APPLICATION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRODUCT_RANGE__c</fullName>
        <label>PRODUCT_RANGE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Details__c</fullName>
        <label>Product Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SP_CODE__c</fullName>
        <label>SP_CODE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSS Accreditation</label>
    <nameField>
        <label>CSS_Accreditation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Accreditations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSM_AccreditationInsert_Batch.cls
global class OSM_AccreditationInsert_Batch implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        date d = system.today();
        String query = 'SELECT Id, SP_CODE__c, Account__c, Product_Details__c, PRODUCT_RANGE__c, MARKET_APPLICATION__c FROM CSS_Accreditation__c WHERE CreatedDate >=: d'; 
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<CSS_Accreditation__c> accredList)
    {
        try{
            system.debug('accredList '+accredList.size());
            Set<ID> accountIDSet = new Set<ID>();
            if(accredList.size() > 0 ){
                OSM_UpdateAccSerLevel_HelperDataloader.dobeforeinsertOpertions(accredList);
            }
        }catch(Exception e){
            system.debug('In exception block of OSM_AccreditationInsert_Batch '+e.getMessage()+'  '+e.getLineNumber());
        }
    }
    
    global void finish(Database.BatchableContext BC)
    {
    } 
}