objects/CSS_Claim_Submission__c.object
<CustomObject>
    <fields>
        <fullName>BMS_Claim_ReqJSON__c</fullName>
        <label>BMS Claim ReqJSON</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS Claim Submissions</relationshipLabel>
        <relationshipName>CSS_Claim_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ERP_Status__c</fullName>
        <description>To store send Claims to BMS webservice status</description>
        <label>ERP Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Appealed/Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Information Only</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Paid as Submitted</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Parts to Return</fullName>
                </value>
                <value>
                    <fullName>Pending Authorization</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>View All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSS Claim Submission</label>
    <nameField>
        <label>CSS Claim Submission  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Claim Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CG_SendClaimInfoBatch_BMS.cls
/**********************************************************************
Name: CG_SendClaimInfoBatch_BMS
Copyright © 2018  Cummins
=======================================================================
=======================================================================
Purpose:    This class is for fetching all the submitted claims and send it to bms.
=======================================================================
=======================================================================
History                                                            
-------                                                            
VERSION  AUTHOR            DATE                DETAIL                                 
1.0     Rajkumar BT      06/13/2018     INITIAL DEVELOPMENT                    
***********************************************************************/
global class CG_SendClaimInfoBatch_BMS implements Database.Batchable <sObject>, Database.allowscallouts{

    global Database.QueryLocator start(Database.BatchableContext BC){
        String status = 'In Review';
        String erpStatus = 'Error';
        //Datetime BatchRuntime =system.now();
        string query = 'SELECT id,CSS_Claims__r.name,BMS_Claim_ReqJSON__c FROM CSS_Claim_Submission__c WHERE Status__c =:status and (ERP_Status__c =: erpStatus or ERP_Status__c = \'\') limit 40';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<CSS_Claim_Submission__c> scope){
        //call bms
        system.debug('call BMS'+scope);
        CSS_WS_BMS.claimsInbound(scope);
        system.debug('call BMS');
    }

    global void finish(Database.BatchableContext BC){
        /*List<CronJobDetail> detailId = [SELECT Id FROM CronJobDetail WHERE Name='submissionBatchSchedule' limit 1];
        system.debug('apexJob'+detailId);
        if (detailId!=null && detailId.size()>0) {
            Id jobId = [SELECT Id from CronTrigger WHERE CronJobDetailId = :detailId][0].Id;
            System.abortJob(jobId);
        }*/
        try{
        CG_SendClaimInfoBatch_BMS  SchdBatch = new CG_SendClaimInfoBatch_BMS();
        System.scheduleBatch (SchdBatch,'submissionBatchScheduleBMS', 5 ); 
        }
        catch(exception e)
        {
             system.debug('message and line number>>'+e.getMessage()+'and '+e.getLineNumber());
        }

    }

}