objects/CSS_DataExchange_Parent__c.object
<CustomObject>
    <description>This is used for storing Request &amp; Response values from Triage mobile app or external data system</description>
    <fields>
        <fullName>CSS_Job_Number__c</fullName>
        <label>CSS Job Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Company_Name__c</fullName>
        <label>Customer/Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSS_DataExchange_Parent</label>
    <nameField>
        <displayFormat>IAS-{0000000000}</displayFormat>
        <label>IAS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSS_DataExchange_Parent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSS_IARecordsDelBatch_Test.cls
@isTest
private class CSS_IARecordsDelBatch_Test{

    static testmethod void testCSS_IARecordsDelBatch(){
      
 
     CSS_DataExchange_Parent__c DataXchange = NEW CSS_DataExchange_Parent__c();
       DataXchange.CSS_Job_Number__c = 'CSS-00066709';
       DataXchange.Customer_Company_Name__c = 'Test';
   
       insert (DataXchange);
       String  whereClause = ' Id = \'' + DataXchange.Id + '\' ';
       String query = 'SELECT Id,CSS_Job_Number__c FROM CSS_DataExchange_Parent__c WHERE' + whereClause;
 
       Test.startTest();
       CSS_IARecordsDelBatch data = new CSS_IARecordsDelBatch(query);
       Database.executeBatch(data); 
       Test.stopTest();

    }
}