objects/CSS_Parts_Options__c.object
<CustomObject>
    <description>To store Parts and Options. Created Record type</description>
    <fields>
        <fullName>Amount_Local_Currency__c</fullName>
        <description>To store amount in local currency as per story# GSSC-138</description>
        <label>Amount Local Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSS_Claims__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSS Claims</label>
        <referenceTo>CSS_Claims__c</referenceTo>
        <relationshipLabel>CSS Parts Options</relationshipLabel>
        <relationshipName>CSS_Parts_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency_Type__c</fullName>
        <description>To store logged in user&apos;s currency type as per story# GSSC-138</description>
        <label>Currency Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate_Version__c</fullName>
        <description>To store the Exchange rate version of part created date as per story# GSSC-138</description>
        <label>Exchange Rate Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <description>To store the Exchange rate of part created date as per story# GSSC-138</description>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpenseTotal__c</fullName>
        <label>ExpenseTotal</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell_Price__c</fullName>
        <label>Sell Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price_Local_Currency__c</fullName>
        <description>To store Unit Price in local currency as per story# GSSC-138</description>
        <label>Unit Price Local Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>CSS Parts Options</label>
    <nameField>
        <label>CSS Parts Options Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Parts Options</pluralLabel>
    <recordTypes>
        <fullName>OtherClaimables</fullName>
        <active>true</active>
        <label>OtherClaimables</label>
    </recordTypes>
    <recordTypes>
        <fullName>Parts</fullName>
        <active>true</active>
        <description>To store Parts</description>
        <label>Parts</label>
    </recordTypes>
    <recordTypes>
        <fullName>TTML</fullName>
        <active>true</active>
        <description>To identify Travel, Towing, Meals and Lodging related Parts</description>
        <label>TTML</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CG_PartsOptionsUpdateBatch_Test.cls
@isTest
public class CG_PartsOptionsUpdateBatch_Test{
    static testMethod void CSS_GetMakeModelBatch_Test() {
        List<CSS_Parts_Options__c> paList = new List<CSS_Parts_Options__c>();
        
          Id partrecordTypeId = Schema.SObjectType.CSS_Parts_Options__c.getRecordTypeInfosByName()
                  .get('Parts').getRecordTypeId();
        
          css_claims__c claims1= new css_claims__C();
            claims1.Customer_Code__c='123';
            claims1.Customer_Name__c='TestUser';
        insert claims1;
        
        CSS_Parts_Options__c paOne = new CSS_Parts_Options__c();
        //paOne.Exchange_Rate__c = 1;
        paOne.Unit_Price_Local_Currency__c = 23 ;
        paOne.Sell_Price__c = 2;
        paOne.Amount_Local_Currency__c = 21 ;
        paOne.Amount__c = 29;
        paOne.Exchange_Rate_Version__c = 6;
        paOne.Currency_Type__c = 'USD';
        paOne.Unit_Price__c = '2';
        paOne.ExpenseTotal__c = 5;
        paOne.RecordTypeId = partrecordTypeId;
        paOne.CSS_Claims__c = claims1.Id;
        
        paList.add(paOne);
        
           CSS_Parts_Options__c paThree = new CSS_Parts_Options__c();
        //paOne.Exchange_Rate__c = 1;
        paThree.Unit_Price_Local_Currency__c = 23 ;
        paThree.Sell_Price__c = 2;
        paThree.Amount_Local_Currency__c = 21 ;
        paThree.Amount__c = 29;
        paThree.Exchange_Rate_Version__c = 6;
        paThree.Currency_Type__c = 'USD';
        paThree.Unit_Price__c = '2';
        paThree.ExpenseTotal__c = 5;
        paThree.RecordTypeId = partrecordTypeId;
        //paOne.CSS_Claims__c = claims1.Id;
        paList.add(paThree);
        Id otherClaimsrecordTypeId = Schema.SObjectType.CSS_Parts_Options__c.getRecordTypeInfosByName()
                  .get('OtherClaimables').getRecordTypeId();
        
        CSS_Parts_Options__c paTwo = new CSS_Parts_Options__c();
        //paTwo.Exchange_Rate__c = 1;
        paTwo.Unit_Price_Local_Currency__c = 23 ;
        paTwo.Sell_Price__c = 2;
        paTwo.Amount_Local_Currency__c = 21 ;
        paTwo.Amount__c = 29;
        paTwo.Exchange_Rate_Version__c = 6;
        paTwo.Currency_Type__c = 'USD';
        paTwo.Unit_Price__c = '2';
        paTwo.ExpenseTotal__c = 5;
        paTwo.RecordTypeId = otherClaimsrecordTypeId;
         paTwo.CSS_Claims__c = claims1.Id;
        paList.add(paTwo);
        
        CSS_Parts_Options__c paFour = new CSS_Parts_Options__c();
        //paTwo.Exchange_Rate__c = 1;
        paFour.Unit_Price_Local_Currency__c = 23 ;
        paFour.Sell_Price__c = 2;
        paFour.Amount_Local_Currency__c = 21 ;
        paFour.Amount__c = 29;
        paFour.Exchange_Rate_Version__c = 6;
        paFour.Currency_Type__c = 'USD';
        paFour.Unit_Price__c = '2';
        paFour.ExpenseTotal__c = 5;
        paFour.RecordTypeId = otherClaimsrecordTypeId;
         //paTwo.CSS_Claims__c = claims1.Id;
        paList.add(paFour);
        
        Id ttMLrecordTypeId = Schema.SObjectType.CSS_Parts_Options__c.getRecordTypeInfosByName()
                  .get('TTML').getRecordTypeId();
                  
         CSS_Parts_Options__c paFive = new CSS_Parts_Options__c();
       // paThree.Exchange_Rate__c = 1;
        paFive.Unit_Price_Local_Currency__c = 23 ;
        paFive.Sell_Price__c = 2;
        paFive.Amount_Local_Currency__c = 21 ;
        paFive.Amount__c = 29;
        paFive.Exchange_Rate_Version__c = 6;
        paFive.Currency_Type__c = 'USD';
        paFive.Unit_Price__c = '2';
        paFive.ExpenseTotal__c = 5;
        paFive.RecordTypeId = ttMLrecordTypeId ;
        paFive.CSS_Claims__c  = claims1.Id;
        paList.add(paFive);  
        
        insert paList;
        
        Test.startTest();
        CG_PartsOptionsUpdateBatch obj = new CG_PartsOptionsUpdateBatch();
        Database.executeBatch(obj);
        Test.stopTest();       
                  
        
     }
 }