objects/dbu_FAQ__c.object
<CustomObject>
    <description>The FAQs displayed on CSSNA Homepage</description>
    <fields>
        <fullName>Answer__c</fullName>
        <inlineHelpText>Answer for FAQs</inlineHelpText>
        <label>Answer</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FAQCategory__c</fullName>
        <label>FAQCategory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cummins R2.8 Turbo Diesel</fullName>
                </value>
                <value>
                    <fullName>My Account</fullName>
                </value>
                <value>
                    <fullName>Orders</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>This Site</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>65536</length>
        <type>LongTextArea</type>
    </fields>
    <label>dbu FAQ</label>
    <nameField>
        <displayFormat>FAQ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>dbu FAQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dbu_footerFAQs_Test.cls
@isTest
public class dbu_footerFAQs_Test {
    static testMethod void testfetchFAQsName() {  
        
        dbu_FAQ__c objFAQ = new dbu_FAQ__c();
        //objFAQ.Name = 'Test FAQ';
        objFAQ.Question__c= 'Test Question';
        objFAQ.Answer__c= 'Test Answer';
         objFAQ.FAQCategory__c= 'Order';
        
        Insert objFAQ;
        
         dbu_FAQ__c objFAQ1 = new dbu_FAQ__c();
        //objFAQ.Name = 'Test FAQ';
        objFAQ1.Question__c= 'Test Question';
        objFAQ1.Answer__c= 'Test Answer';
         objFAQ1.FAQCategory__c= 'Order';
        
        Insert objFAQ1;
        
        Test.startTest();  
            dbu_footerFAQs.fetchFAQsName();   
        Test.stopTest();  
    } 
}