objects/disco__Form_Template__c.object
<CustomObject>
    <description>The core container object for Youreka. A collection of Sections and Questions to be saved and published, used by end users to create Forms</description>
    <fields>
        <fullName>FSL_Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Approved</fullName>
                    <default>true</default>
                    <label>Not Yet Approved</label>
                </value>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>disco__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Drafting</fullName>
                    <default>true</default>
                    <label>Drafting</label>
                </value>
                <value>
                    <fullName>In Use</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Template</label>
    <nameField>
        <label>Form Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/lookUpController.cls
public class lookUpController {
    @AuraEnabled
	public static List < disco__Form_Template__c > fetchLookUpValues(String searchKeyWord,string ObjectName) {
        String searchKey = searchKeyWord + '%';
        List < disco__Form_Template__c > returnList = new List < disco__Form_Template__c > ();
        returnList = [select id, Name from disco__Form_Template__c where Name LIKE: searchKey and FSL_Approval_Status__c='Approved' and disco__Status__c='In Use'];
        return returnList;
    }
}