objects/FSL_Integration_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Log_Captured_Time__c</fullName>
        <label>Log Captured Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SenderID__c</fullName>
        <label>SenderID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Version__c</fullName>
        <label>Service Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ToolID__c</fullName>
        <label>ToolID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FSL_Integration_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>FSL Integration Error Logs</relationshipLabel>
        <relationshipName>FSL_Integration_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>login_user_WWID__c</fullName>
        <label>login user WWID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>FSL Integration Error Log</label>
    <nameField>
        <displayFormat>IE-{00000}</displayFormat>
        <label>FSL Integration Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSL Integration Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSL_ApplicationLoggerQueueable.cls
/************************************************************************************************************************************************************
Name: FSL_ApplicationLoggerQueueable 
Description: This class is used to Capture the Request and Response log.
Author: Ravikanth Macherla
--------------- ------------------ ------------------------------
Date - 02/13/2020 
************************************************************************************************************************************************************/
public class FSL_ApplicationLoggerQueueable implements Queueable {
    
    RestRequest request;
    RestResponse response;
    HttpRequest req;
    HttpResponse res;
    String serviceName;
    String status;
    String serviceVersion;
    String toolId;
    String senderId;
    String ReqstBody;
    String RespBody;
    String Sourcesystem;
    String loginuserWWID;
    ID LoginUserName;
    String Timestamp;
    ID Workorderid;
    
    public FSL_ApplicationLoggerQueueable(String ReqBody, String ResBody, RestRequest request, RestResponse response, String serviceName, 
                                          String status, String serviceVersion, String toolId, String senderId, Id workorderid, String Sourcesystem) {
                                              
                                              this.ReqstBody=ReqBody;
                                              this.RespBody=ResBody;
                                              this.request = request;
                                              this.response  = response;
                                              this.serviceName = serviceName;
                                              this.status=status;
                                              this.serviceVersion = serviceVersion ;
                                              this.toolId=toolId;
                                              this.senderId=senderId;
                                              this.Workorderid = workorderid;
                                              this.loginuserWWID = FSL_Utility.UserInfo().FederationIdentifier;
                                              this.LoginUserName = FSL_Utility.UserInfo().Id;
                                              this.Timestamp = FSL_Utility.SetNow(); 
                                              this.Sourcesystem = Sourcesystem;
                                          }
    
    public void execute(QueueableContext context) {
        
        FSL_Integration_Error_Log__c objIntegrationErrorLog = new FSL_Integration_Error_Log__c();
        
        if(!String.isBlank(ReqstBody)){
            objIntegrationErrorLog.Request__c = ReqstBody.trim();
            objIntegrationErrorLog.Response__c = RespBody;
        }
        else{
            objIntegrationErrorLog.Request__c = ReqstBody;
            objIntegrationErrorLog.Response__c = RespBody;
        }
        if(request !=null){
            objIntegrationErrorLog.Request__c = request.requestBody.toString().trim();
        }
        if(response!=null){
            objIntegrationErrorLog.Response__c = response.responseBody.toString();
        }
        objIntegrationErrorLog.Service_Name__c = serviceName;
        objIntegrationErrorLog.Service_Version__c = serviceVersion;
        if(status == 'OK' || status == 'Success' ) {
            objIntegrationErrorLog.Status__c = 'Success';
        }
        else{
            objIntegrationErrorLog.Status__c = 'Error';
        }
        objIntegrationErrorLog.ToolID__c = toolId;
        objIntegrationErrorLog.SenderID__c = senderId;
        objIntegrationErrorLog.Work_Order__c = Workorderid;
        objIntegrationErrorLog.Source__c = Sourcesystem;
        objIntegrationErrorLog.login_user_WWID__c = loginuserWWID;
        objIntegrationErrorLog.Log_Captured_Time__c = Timestamp;
        objIntegrationErrorLog.User_Name__c = LoginUserName;
        
        try {
            insert objIntegrationErrorLog;
            system.debug('check id'+objIntegrationErrorLog);
        } catch(Exception ex) {
            ex.getStackTraceString(); 
        }                
    }    
}