objects/FSL_Integration_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Version__c</fullName>
        <label>Service Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FSL Integration Error Log</label>
    <nameField>
        <displayFormat>IE-{00000}</displayFormat>
        <label>FSL Integration Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSL Integration Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSL_DeleteSuccessErrorLogs_Test.cls
@istest
public class FSL_DeleteSuccessErrorLogs_Test {
    
    public static testMethod void DeleteSucessLogs()
    {
        FSL_Integration_Error_Log__c objIntegrationErrorLog = new FSL_Integration_Error_Log__c();
        //objIntegrationErrorLog.Request__c = 'tet';
        objIntegrationErrorLog.Response__c = 'test';
        objIntegrationErrorLog.Service_Name__c = 'testing';
        objIntegrationErrorLog.Service_Version__c = 'test';
        objIntegrationErrorLog.Status__c = 'Success';
        insert objIntegrationErrorLog;
        test.starttest();
        FSL_DeleteErrorlogscheduledBatchable  fslDeleteErrorlog = new FSL_DeleteErrorlogscheduledBatchable();
         String sch = '0 0 23 * * ?';
        System.schedule('check',sch ,fslDeleteErrorlog);
        test.stoptest();
    }
}