objects/IAM_Contact_Provisioning__c.object
<CustomObject>
    <fields>
        <fullName>IAM_Active_Contact_Provisioning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Provisioning</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Active Contact Provisionings</relationshipLabel>
        <relationshipName>Contact_Provisionings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IAM_Application_Name__c</fullName>
        <label>Application Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EDS</fullName>
                </value>
                <value>
                    <fullName>Cummins Service Training</fullName>
                </value>
                <value>
                    <fullName>QuickServe Online</fullName>
                </value>
                <value>
                    <fullName>India ABO</fullName>
                </value>
                <value>
                    <fullName>Repair logistics and Service</fullName>
                </value>
                <value>
                    <fullName>Connected Solutions</fullName>
                </value>
                <value>
                    <fullName>CUMPAS 2.0</fullName>
                </value>
                <value>
                    <fullName>Guidanz</fullName>
                </value>
                <value>
                    <fullName>Marketplace</fullName>
                </value>
                <value>
                    <fullName>Identity and Access Management</fullName>
                </value>
                <value>
                    <fullName>WWSPS</fullName>
                </value>
                <value>
                    <fullName>BOX External Partners</fullName>
                </value>
                <value>
                    <fullName>Guidanz Mobile</fullName>
                </value>
                <value>
                    <fullName>Fleetguard FIT</fullName>
                </value>
                <value>
                    <fullName>NextGen</fullName>
                </value>
                <value>
                    <fullName>Rapid Serve Web</fullName>
                </value>
                <value>
                    <fullName>Mexico Warranty</fullName>
                </value>
                <value>
                    <fullName>Archer</fullName>
                </value>
                <value>
                    <fullName>BOX</fullName>
                </value>
                <value>
                    <fullName>CARE</fullName>
                </value>
                <value>
                    <fullName>CSS</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Campaigns</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Free Registration</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - ImmediateAssessment</fullName>
                </value>
                <value>
                    <fullName>Guidanz™ - Service</fullName>
                </value>
                <value>
                    <fullName>INSITE</fullName>
                </value>
                <value>
                    <fullName>Product Connectivity</fullName>
                </value>
                <value>
                    <fullName>DBU India - Field Service Lightning</fullName>
                </value>
                <value>
                    <fullName>Electrified Powertrain Specification Tool</fullName>
                </value>
                <value>
                    <fullName>PowerSpec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User_Features_And_ Access (Contact)</relationshipLabel>
        <relationshipName>Contact_Provisionings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IAM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Account Level</fullName>
                </value>
                <value>
                    <fullName>Pending Account Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Contact Approval</fullName>
                </value>
                <value>
                    <fullName>Active-Indemnified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Provisionings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Feature &amp; Access</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Rec Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Features_And_ Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IAM_Contact_Prov_Helper.cls
Public Class IAM_Contact_Prov_Helper{

    //In this method we will call this method only for active users who has login access.
    
    Public Static Void UpdateToActive(Set<id> ids){
        List<IAM_Contact_Provisioning__c> ConProv=[Select id,IAM_Active_Contact_Provisioning__c,IAM_Contact__c,IAM_Status__c,IAM_Application_Name__c,IAM_User__c from IAM_Contact_Provisioning__c where id=:ids];
        Set<id> ConIds=new Set<id>();
        
        if(!ConProv.isEmpty()){
            for(IAM_Contact_Provisioning__c c:ConProv){
               
               ConIds.add(c.IAM_Contact__c);   
            }
            
            List<user> usr=[Select id,Name,username,contactId from user where ContactId=:ConIds and isActive=True];
            System.debug('Printing user list'+usr);
            Map<id,User> userMap=new Map<id,User>();
            
            if(!usr.isEmpty()){
                  for(user u:usr){
                      userMap.Put(u.ContactId,u);
                  }
            }
            List<IAM_Contact_Provisioning__c> nonRSWListconprov = new List<IAM_Contact_Provisioning__c>();
            for(IAM_Contact_Provisioning__c cn:ConProv){
                cn.IAM_Active_Contact_Provisioning__c=cn.IAM_Contact__c;
                system.debug('Printing is key Present or not'+userMap.ContainsKey(cn.IAM_Contact__c));
                if(!userMap.isEmpty()){
                if(userMap.ContainsKey(cn.IAM_Contact__c)){
                   cn.IAM_User__c= userMap.get(cn.IAM_Contact__c).id;
                }
              }
                if(cn.IAM_Application_Name__c !='Rapid Serve Web'){
                    nonRSWListconprov.add(cn);
                }
            }
            Update ConProv;
            IAM_contactHelperClass.updateApplicationContact(ConProv);
            if(!nonRSWListconprov.isempty())
            IAM_Assign_Application_Permissionset.AssignApplication(nonRSWListconprov);
        }
    }
    
    Public Static Void CreationOfUser(List<Contact> lstCont){
        
        System.debug('Printing Contact Ids'+lstCont.Size());
        Set<id> ConIds=new Set<id>();
        
        if(!lstCont.isEmpty()){
            String userCreation='';
            if(!Test.isRunningTest()){ 
           		userCreation= IAM_CreateUser.CreateUser(lstCont); 
            }else{
                userCreation='OK';
            }
           System.debug('USer creation is'+userCreation);
           if(userCreation=='OK') {
               for(Contact c:lstCont){
                   ConIds.add(c.id);
               }
               System.debug('Printing Contact Ids'+ConIds);
               List<IAM_Contact_Provisioning__c> ConProv=[Select id,IAM_Contact__c,IAM_User__c,IAM_Status__c from IAM_Contact_Provisioning__c where IAM_Contact__c=:ConIds];
               Set<id> ProvID= new Set<id>();
               /*System.debug('Printing Cont provisionings'+ConProv);
               List<User> usr=[Select id,ContactId from user where ContactId=:ConIds]; 
               System.debug('Printing User records'+usr);
               Map<id,User> userMap=new Map<id,User>();
               for(user u:usr){
                   userMap.put(u.ContactId,u);
               } 
               System.debug('user Map'+userMap);*/
               if(!ConProv.isEmpty()){
                   for(IAM_Contact_Provisioning__c c:ConProv){
                       
                      ProvId.add(c.id); 
                   }
                   
                 if(!ProvID.isEmpty()){
                       UpdateToActive(ProvId);  
                 }
                   
               }  
           }
        }
    }
    
}