objects/ServiceOrderContact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ServiceOrderContacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Inserted_Account_contact_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Inserted Account contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Select</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payer_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ServiceOrderContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payer_Contact_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payer Contact Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payer_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR 5) AND 3 AND 4</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Payer_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.IAM_Contact_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Contact.IAM_Contact_Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>ServiceOrderContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipName>ServiceOrderContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Communication Recipient</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Recipients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FSL_CreateSOContactForAcoountContact.cls
public class FSL_CreateSOContactForAcoountContact { 
    
    //Below methods is to insert records into Communication Object based on the service order Acoount Contact
    public static Boolean isSOCInsert=false;
    @InvocableMethod(label='CreateserviceOrderContactForAcoountContact' description='CreateserviceOrderContactForAcoountContact' category='WorkOrder')
    //public static void insertServiceOrderContactList(List<workOrder> newWOs){
   public static List<workOrder> insertServiceOrderContactList(List<workOrder> newWOs){
      /* for(ServiceOrderContact__c  LstSoc:[select id,Is_Inserted_Account_contact_del__c from ServiceOrderContact__c where Is_Inserted_Account_contact_del__c =true]){
                 ServiceOrderContact__c socObj = new ServiceOrderContact__c();
               
                update LstSoc;
            }*/
      
            
        Set<Id> payerConList = new Set<Id>();
        Set<Id> WOIds = new Set<Id>();
        
        List<ServiceOrderContact__c> insertSOCList = new List<ServiceOrderContact__c>();
        if(newWOs != null){
           for(workOrder wo:newWOs){
                WOIds.add(wo.Id);
            }
            for(ServiceOrderContact__c soc : [select id, name, Payer_Contact__c, Payer_Contact__r.Name from ServiceOrderContact__c where Service_Order__c IN: WOIds]){
                if(soc.Payer_Contact__c != null){
                    payerConList.add(soc.Payer_Contact__c);
                }           
            }
           
      
        
        
        if(newWOs != null && newWOs.size()>0){            
            for(WorkOrder wo : newWOs){
               // if(wo.Payer_ContactID__c != null){
                   // if(payerConList == null || (!payerConList.contains(wo.Payer_contactId__c))) {
                        
                        ServiceOrderContact__c socObj = new ServiceOrderContact__c();
                        
                        socObj.Payer_Account__c = wo.Payer__c;
                        socObj.Account__c = wo.AccountId; // As part of stroy CT4-98                       
                        socObj.Payer_Contact__c = wo.ContactID;
                        socObj.Service_Order__c = wo.Id;
                        socObj.Payer_Contact_Flag__c = true;
                        socObj.Opt_In__c= false;
                        socObj.Is_Inserted_Account_contact_del__c =true;
                        insertSOCList.add(socObj);
                   // }
                //}
            } 
            insert insertSOCList ;
           
             
        }
      /*  if(insertSOCList != null && insertSOCList.size()>0){
            if(!isSOCInsert){
                insert(insertSOCList);
                isSOCInsert=true;
            }               
        }*/
       
    } 
     return null;    
 }
 }